### ISSUE TITLE
awsubs.tv

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#100]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://awsubs.tv/

**Penjelasan Lebih Lanjut**
Banner

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
https://awsubs.co/tower-of-god-episode-2-subtitle-indonesia/
di video playernya gan close button overlay transparan

**Comment by realodix** [comment]
> 
> 
> https://awsubs.co/tower-of-god-episode-2-subtitle-indonesia/
> di video playernya gan close button overlay transparan

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix banner baru sama close button

**Comment by Recehan-Slayer** [comment]
@realodix banner sama close button gan https://awsubs.co/

**Comment by realodix** [comment]
> 
> 
> banner sama close button gan https://awsubs.co/

Thank you
