### ISSUE TITLE
dutafilm.live - Iklan Transparan Menutupi Halaman Download

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#102]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://dutafilm.live/film/nonton-6-underground-2019-qxvvap

**Penjelasan Lebih Lanjut**
Kurang lebih mirip seperti https://github.com/realodix/AdBlockID/issues/97

**Rule yang diusulkan**
- `dutafilm.live##a[target="_blank"][onclick="$(this).remove();"]`
- `dutafilm.live##body > a[href] > div[style^="position:absolute;"][style*="z-index:"]`

**Comment by Recehan-Slayer** [comment]
`https://dutafilm.cc/film/nonton-jumanji-the-next-level-2019-qdttxx`

overlay `bebasjudi88.com`

**Comment by realodix** [comment]
> `https://dutafilm.cc/film/nonton-jumanji-the-next-level-2019-qdttxx`
> 
> overlay `bebasjudi88.com`
> 
> buat adblockID+ nya mnding pke rule wildcards aja gan sgt tidak mungkin untuk maintenance semua situs yg hmpir tiap hari gnti domain.
> Ini di ABPindo aja jg pke https://github.com/ABPindo/indonesianadblockrules/commit/fafb6c3ebab1e2d4744b96fe7ea73ea806ec34f1

Thank you, sedang dicoba. Contoh dari ABPindo itu pemblokiran murni Gan, bukan `hide` atau blokir dengan opsi `$domain=`

**Comment by Recehan-Slayer** [comment]
Klo diuBO sepertinya mereka g akan langsung menambahkan rule wildcards domain. klo pada laporan yg pertama tp klo uda bnyak laporan situs dgn nama yg sama dan ganti domain yg berbeda psti mereka lngsung pakai uda bnyak contohnya kek nekopoi shrink dll dan mayoritas emg situs" illegal dan shorteners tpi klo adguard ntah ga prnah ngecek
