### ISSUE TITLE
mangaku.in - Load gambar tercegah jika mengaktifkan filtering

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#103]
**Sample URL**
https://mangaku.in/dr-stone-reboot-chapter-8/

Saya pengguna `extension adguard` di browser chrome, jika kuaktifkan adguard nya untuk mangaku.in tidak akan memunculkan halaman2 dari chapter manga yg ada. Akan tetapi ketika dimatikan justru memungkikan ke load halaman2nya.

Menyoba sendiri buat aturan filter , beberapanya  
```
||mangaku.in#%#//scriptlet("prevent-bab")
||mangaku.in#%#//scriptlet("prevent-fab")
@@||mangaku.in^$generichide
```
dan tentunya nggak ada yang berhasil. Entah disana buat sendiri script nya atau gimana, gak bisa meliat karena script nya keliatan seperti di encrypt.
dan lagi jika kumatikan javascript, juga dicegah oleh mangaku buat ngeload gambar ama memunculkan tulisan yg mewajibkan menyalakan javascriptnya jika mau melihat gambar.

Tetapi ada beberapa series komik nya yang berbeda dalam script yg dapat diliat dari URL. jika ada yang memiliki kata mirror3 di url atau yg bisa diliat dibawah ini 
https://mangaku.co/mirror3/manga/dead-life/chapter-61/

Justru ke load aja gambar2nya secara normal.

Agak kesal sih, tapi klo keadaan terdesak ya gpp lah bisa ku whitelist aja ini situs. 
Kalau ini issue gak berhasil juga, ya gpp juga gan.

Sekian

**Comment by realodix** [comment]
> https://mangaku.in/dr-stone-reboot-chapter-8/
> jika kuaktifkan adguard nya untuk mangaku.in tidak akan memunculkan halaman2 dari chapter manga yg ada. Akan tetapi ketika dimatikan justru memungkikan ke load halaman2nya.

Maksudnya halaman2 tuh apa ya? Gambar komiknya atau apa ya? Saya buka URL di atas dan beberapa URL di bawah ini, gambar komiknya muncul.

- https://mangaku.in/uq-holder-chapter-167/
- https://mangaku.in/one-punch-man-chapter-123/
- https://mangaku.in/one-piece-chapter-965/

> jika kumatikan javascript, juga dicegah oleh mangaku buat ngeload gambar ama memunculkan tulisan yg mewajibkan menyalakan javascriptnya jika mau melihat gambar.

Saya lihat mereka render gambar komiknya pakai javascript, lalu mereka taruh di

```html
<div class="ikDMceEMXM">
  ...
</div>
```

Makanya mereka cegah untuk metikan javascript.

**Comment by GrennKren** [comment]
oh kalau punya agan bisa kebuka berarti masalahnya cuman salah satu filter yg kupake aja toh.. sep2 makasih gan udah nyobain sendiri

**Comment by GrennKren** [comment]
Hahahahah.. fixed. pake rule ini, simple aja ternyata
`@@||mangaku.in^$extension`

Tadi menyoba memeriksa satu2 filter , yg kudapatkan bila dibagian kategori filter annoyance sama security di adguard yg menyebabkan ga ke load gambar2nya. Nggan bila dua kategori itu ku matiin.

Tapi tetep ga ngerti ama filter rules @@  (exception) , kan arti dari exception itu pengecualian tapi kenapa ada option generichide , exception, dll yg fungsi nya justru buat mencegah seperti filter rules biasa.

Btw asalan ku buka kembali ini issue minta tolong buat dimasukin ke dalam filter  adblockid. 

Makasih

**Comment by GrennKren** [comment]
Lupakan jir.. rupanya lupa mengaktifkan kembali filter annoyance sama security

**Comment by realodix** [comment]
> Hahahahah.. fixed. pake rule ini, simple aja ternyata
> `@@||mangaku.in^$extension`
> 
> Tadi menyoba memeriksa satu2 filter , yg kudapatkan bila dibagian kategori filter annoyance sama security di adguard yg menyebabkan ga ke load gambar2nya.

Wow, thank you untuk analisanya Gan. Masalahnya `@@$extension` merupakan exception rule khusus AdGuard, gak kompatibel dengan AdBlocker lainnya. Saya akan coba lakukan analisa lebih lanjut pada filter annoyance dan security.

> Tapi tetep ga ngerti ama filter rules @@ (exception) , kan arti dari exception itu pengecualian tapi kenapa ada option generichide , exception, dll yg fungsi nya justru buat mencegah seperti filter rules biasa.

Saya akan coba jelaskan tentang `@@$generichide`, exception rule paling banyak digunakan untuk mengatasi Anti-AdBlock.

Dalam beberapa kasus, ada script yang mendeteksi Ad Blocker dengan pola Ad Blocker menghilangkan element pada web tersebut. Katakanlah generic rule pada filter dapat menghilangkan class html `A B C D E F G H I J`, maka yg dilakukan script tersebut adalah "`Jika element html class A B C D hilang, maka munculkan peringatan untuk mematikan Ad Blocker`"

Biasanya mereka (admin situs) berganti-ganti dalam periode tertentu. 
1. Jika `A B C D` hilang, maka munculkan peringatan.
2. Jika `A C E F` hilang, maka munculkan peringatan.
3. Jika `G H I J` hilang, maka munculkan peringatan.

Akan sangat sulit mengikuti mereka untuk mengganti rule pada filter, makanya langsung pakai pakai `@@$generichide` untuk mematikan rule `A B C D E F G H I J`.

**Comment by realodix** [comment]
Saya curiga dengan Fanboy's Annoyances.

Coba pakai ini deh Gan, `@@/particles.$script,domain=mangaku.in`

**Comment by GrennKren** [comment]
Luar binasa banget gan! Beneran works!! 
kali ini dah ku cek dengan teliti filter2 yg aktif kek biasa aku pakai, dan masalah di mangaku udah ga ada lagi.
Makasih banyak gan!

**Comment by realodix** [comment]
Sip, sudah ditambahkan

**Comment by realodix** [comment]
Revisi, filter untuk issue ini Saya pindahkan ke [AdBlockID+](https://github.com/realodix/AdBlockID#cara-menggunakan)
