### ISSUE TITLE
drakorindo.us

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1032]
**Jenis**
- Iklan

**Sample URL**
https://drakorindo.us/drama-korea-inspector-koo-subtitle-indonesia/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Ini iklan di bagian mana Gan?

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot 2021-11-03 at 18-07-14 Drama Korea Inspector Koo Subtitle Indonesia drakorindo](https://user-images.githubusercontent.com/1314456/140049883-49959657-e97d-43c9-b21f-525e2aac172c.png)
</details>

**Comment by Recehan-Slayer** [comment]
![Screenshot 2021-11-03 at 18-10-52 Drama Korea Inspector Koo Subtitle Indonesia drakorindo](https://user-images.githubusercontent.com/9379770/140050392-0453f1d3-de82-4f98-8349-8bd0840c0d3b.png)

**Comment by realodix** [comment]
Thank you
