### ISSUE TITLE
[Anti-Adblock] infotekno.net

### ISSUE THREAD

**Issue by alvahn** [realodix/AdBlockID#104]
**Sample URL**
https://infotekno.net/vga?url=aHR0cHM6Ly9nby5pbmZvdGVrbm8ubmV0L0pySVhjeWkvd2luZG93cy0xMC1saXRlLWVkaXRpb24tMTloMi14NjQtaXNv

**Penjelasan Lebih Lanjut**
AA

**Comment by realodix** [comment]
Thank you

**Comment by WaferNabati** [comment]
@realodix https://go.infotekno.net/JrIXcyi/windows-10-lite-edition-19h2-x64-iso#dl
anti adblock

**Comment by realodix** [comment]
> @realodix https://go.infotekno.net/JrIXcyi/windows-10-lite-edition-19h2-x64-iso#dl
> anti adblock

Ada sample URL yang lain gak? Saya buka berkali-kali, gak ada peringatan anti adblock

**Comment by WaferNabati** [comment]
ntah ga tau tdinya aku nyoba safelink yg diatas itu trus smpai ketujuan link muncul anti adblock "block adblock"

**Comment by realodix** [comment]
> ntah ga tau tdinya aku nyoba safelink yg diatas itu trus smpai ketujuan link muncul anti adblock "block adblock" tp skrng ga muncul lg sepertinya filternya kmaren belum ku update

Sip, thank you untuk laporannya. Saya akan tetap buka issue ini untuk pantau dalam beberapa hari ke depan.

**Comment by realodix** [comment]
Saya rasa ini sudah aman, barusan buka linknya gak ada notif anti adblocker
