### ISSUE TITLE
mangalist.org

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1044]
**Jenis**
- Anti-Adblock

**Sample URL**
https://mangalist.org/url/go/UHBCeXVVUmc1YzhyVWVsamFodTBZUGhESW5NaVZtdjh0VGZtTHNKblBVZz0=&owner=manganime.in

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you
