### ISSUE TITLE
doujinpoi.club

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1045]
**Jenis**
- Anti-Adblock

**Sample URL**
https://doujinpoi.club/manga/the-delicious-club/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix ini yg  anti adblock adult site masuk ke adblocid apa adblockid adult bro

**Comment by realodix** [comment]
> ini yg anti adblock adult site masuk ke adblocid apa adblockid adult bro

Semua issue yang Saya mention, filter spesifiknya masuk ke dalam adult.

<details>
  <summary>Screenshot</summary>
  
  ![noname](https://user-images.githubusercontent.com/1314456/140519272-a0599b56-2421-4f20-9cdc-9fd3c66101a4.png)
</details>

**Rencana ke depan**
Website komik (adult) sepertinya memiliki kemungkinan untuk bentrok dengan filter generik khusus adult di AdBlockID sangat kecil. Saya akan memasukkan filter spesifiknya ke dalam AdBlockID. Saat ini sedang dikerjakan di #1061.
