### ISSUE TITLE
niihen.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1049]
**Jenis**
- Pop-up
- Terdapat safelink

**Sample URL**
https://www.niihen.com/2021/10/shuumatsu-no-harem.html

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
**Catatan**
Auto safelink berasal dari https://github.com/NiiHen/punya

Dibutuhkan inject CSS untuk menampilkan link, karena link download secara default `dispaly: block;`.

**Comment by realodix** [comment]
Popup tidak ditemukan Gan? Pemicunya pas lagi klik apa?

**Comment by Recehan-Slayer** [comment]
popup nya di dalam safelink

**Comment by realodix** [comment]
> popup nya di dalam safelink

Ok, I see

Sepertinya saat ini tidak perlu Gan
- Saat ini auto safelink nya sudah lumpuh
- Sepertinya halaman safelink khusus NiiHen, mereka sama2 memanggil kode dari https://github.com/NiiHen
