### ISSUE TITLE
sekaikomik.site

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1052]
**Jenis**
- Anti-Adblock

**Sample URL**
https://www.sekaikomik.site/manga/the-ladies-associate/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you

**Comment by realodix** [comment]
Anti-Adblock tidak ditemukan Gan, Saya sudah buka berbagai halaman.

**Comment by Recehan-Slayer** [comment]
apa anti adblocknya ada di filter adblockid adult soalnya saya  masi blom aktifkan

**Comment by realodix** [comment]
> apa anti adblocknya ada di filter adblockid adult soalnya saya masi blom aktifkan

Tenang Gan, kalau sudah masuk ke dalam AdBlockID (biasa atau khusus Adult), Saya akan bilang.

Terakhir kali buka [sekaikomik.site/the-la..ter-07/](https://www.sekaikomik.site/the-ladies-associate-chapter-07/) juga tidak ada 

Ini daftar filter yang Saya gunakan
- Semua uBlock filter
- EasyList
- EasyPrivacy

**Comment by Recehan-Slayer** [comment]
![Screenshot_2021-11-06-14-31-47-442_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/140601813-5d5607d3-1b4a-49a3-a971-e4783c80cf15.jpg)


kadang muncul kadang ga gan

**Comment by realodix** [comment]
Ok Gan thank you
