### ISSUE TITLE
ryuukoi.web.id

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#106]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://ryuukoi.web.id/

**Penjelasan Lebih Lanjut**
Banner judi

**Comment by realodix** [comment]
Thank you untuk laporannya.

Saya bingung di sebelah mananya ya? Saya buka2 halaman yang lain juga gak nemuin. Kalau boleh tahu filter apa saja yang digunakan, agar Saya bisa analisis lebih lanjut.

![screencapture-ryuukoi-web-id-2019-12-22-09_42_32](https://i.imgur.com/W8bAw8T.jpg)

**Comment by WaferNabati** [comment]
<details> 
![Annotation 2019-12-22 115105](https://user-images.githubusercontent.com/9379770/71317299-75a85980-24b1-11ea-9490-8f5fab51e80b.png)
yang filter ublock saya pakai semua kecuali experimental

**Comment by WaferNabati** [comment]
@realodix 
![Annotation 2019-12-22 115541](https://user-images.githubusercontent.com/9379770/71317367-231b6d00-24b2-11ea-9c81-0e49c1c887e7.png)

**Comment by realodix** [comment]
Seperti SS yang Saya kasih di atas, harusnya bersih. Penyebanya karena ABPindo dan uBlock filters menggunakan `@@$generichide`.

Untuk mattin rules tersebut, di My Filters bisa diisi dengan `@@||ryuukoi.web.id^$generichide,badfilter`.

Saya akan coba blokir sumber gambarnya.

![cats](https://user-images.githubusercontent.com/1314456/71322258-42d58400-24f8-11ea-9405-ec7f3c381e1f.jpg)
