### ISSUE TITLE
otakudesu.vip

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1060]
**Jenis**
- Iklan

**Sample URL**
https://otakudesu.vip/shman-king-episode-30-sub-indo/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
anti klik kanan anti copy gan

**Comment by realodix** [comment]
> 
> 
> anti klik kanan anti copy gan

Ok, thank you Gan
