### ISSUE TITLE
pahe.in - tidak bisa klik generate link

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#107]
**Sample URL**
https://pahe.in/?dd1fa7bc42=WWZKalZHdzYxSjNmUEJaUEFYRHBZeXl2aVBGV0xyenU2bEkwamhoU21DQUowZ0tGUmZ0bys5a1lvczVxemJGOEZ0aWowdmNpSTFOc3cxVW94SDNSZFE9PQ==

sumber link : pahe.in

**Penjelasan Lebih Lanjut**
bro ini kenapa ya klo ubo aktif ga bisa di klik generate linknya coba tolong dicek
didalam pahe.in safelink ada 3 domain intercelestial.com sweetlantern.com dan linegee.net
untuk filter yg saya pakai sama seperti di issue sebelumnya

**Comment by realodix** [comment]
Thank you untuk laporannya.

Menurut Saya ini karena wadah HTML untuk iklan yang belum dihilangkan. Harusnya dia ada di bawah halaman, namun karena iklannya diblokir, dia jadi numpuk ke atas dan menutup tombol download.

![cats](https://user-images.githubusercontent.com/1314456/71355236-fd28c200-25b0-11ea-9193-2ebe67feb952.jpg)

**Comment by WaferNabati** [comment]
sip gan tq
