### ISSUE TITLE
rysafe.blogspot.com - blocking generate link

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#108]
**Sample URL**
https://rysafe.blogspot.com/2018/11/why-you-need-travel-insurance.html?url=IyNvJTVEa1FKJTFGJTQwciU1RHpkJTE4TWZmaWclMUVnJTdEcU5OYSUxOSU3QiUwNSU3RiUxQSUxQkQlNUMlMTklMTVMQSUxN0ZNWEclMDdFR0slMDZNRE9HR08lMDZNJTVFQVpMJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj

**Source**
https://www.rymaru.id/enen-no-shouboutai/

**Penjelasan Lebih Lanjut**
blocking generate link

**Comment by realodix** [comment]
Saya menggunakan konfigurasi yang sama persis seperti yang Agan gunakan di https://github.com/realodix/AdBlockID/issues/106#issuecomment-568232658.

Saya menemukan ABPindo menggunakan rule `/safelink$3p,script` yang menyebabkan tombol `KLIK UNTUK GENERATE LINK` tidak dapat ditekan.

Solusinya Agan bisa menambahkan `/safelink$3p,script,badfilter` pada My Filters atau laporkan pada ABPindo.

![cats](https://user-images.githubusercontent.com/1314456/71354227-d9b04800-25ad-11ea-97a2-79c01c563d6d.jpg)

**Comment by WaferNabati** [comment]
skrng gw cmn pke filter adblockID doang gan untuk regional indo soalnya abp indo bnyak salah ngeblockir visit link disafelink"/shortlink
