### ISSUE TITLE
Tokopedia.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1081]
https://www.tokopedia.com/search?ob=5&q=ketapel

![Screenshot_20211130-175634862](https://user-images.githubusercontent.com/19517680/144034950-200fae0c-f6a5-4590-bf2b-6e6469aac33f.jpg)

**Comment by realodix** [comment]
Thank you

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/144084416-cee28f88-f641-48d1-837b-6a268bb51e96.png)

**Comment by realodix** [comment]
> <details>
>   <summary>Screenshot</summary>
>   
>   ![image](https://user-images.githubusercontent.com/19517680/144084416-cee28f88-f641-48d1-837b-6a268bb51e96.png)
> </details>
> 
> https://www.tokopedia.com/search?pmax=1800000&pmin=1300000&st=product&q=Xiaomi%20Redmi%20Note%208

Ini test di mana Gan, AdGuard atau uBO?

Versi AdBlockID saat ini v21.11.111 atau v2.0.9.35 di AdGuard

Login dan non-login harusnya sudah hilang

<details>
  <summary>Video</summary>
  
  https://user-images.githubusercontent.com/1314456/144089944-51b1faf7-5ef7-493d-90fa-7cc7769d4d5d.mp4
</details>

**Comment by 3xploiton3** [comment]
saya test di adguard desktop 7.7.2 belum hilang
https://www.tokopedia.com/search?ob=5&rf=true&st=product&q=Switch%208%20poe%2B

![image](https://user-images.githubusercontent.com/19517680/144372783-66c3ea9c-a461-4a37-a72b-2507f17ea5ae.png)

**Comment by realodix** [comment]
Halo Gan, Saya sudah bertanya ke AdGuard, dan mereka konfirmasi ini adalah bug. Saat ini Saya sudah ubah filternya untuk menghindari bug tersebut.

Jadi ternyata filter baru yg kmrn Saya tambahkan (untuk https://github.com/realodix/AdBlockID/issues/1081#issue-1067090922) memicu bug di AG. Hal ini membuat semua filter untuk tokped tidak berfungsi. Makanya di desktop ([#1081 (comment-982786021)](https://github.com/realodix/AdBlockID/issues/1081#issuecomment-982786021), [#1081 (comment-984342713)](https://github.com/realodix/AdBlockID/issues/1081#issuecomment-984342713)) yg harusnya sudah gak ada malah muncul lagi.

Thx sudah lapor
