### ISSUE TITLE
Buat filter khusus Ublock oringin

### ISSUE THREAD

**Issue by Gamefire238** [realodix/AdBlockID#1084]
Saya berharap Anda membuat filter yang khusus untuk uBO karena filter (##.example) tidak berfungsi di uBO dan hanya berfungsi jika filter di ubah menjadi (*##.example)
Contoh:
"##.box_item_ads_popup" di "otakudesu.vip"

Gambar Tinjauan
Sebelum
![IMG_20211206_113254](https://user-images.githubusercontent.com/78879425/144785619-8aa3fbff-8b8d-448a-8a9c-b96132e8a2ec.jpg)

Sesudah
![IMG_20211206_113351](https://user-images.githubusercontent.com/78879425/144785659-5df0832b-de7f-4b6c-8c5c-0bdb355161a5.jpg)

Saya berharap Anda membuat filter khusus uBO tanpa mengubah filter asli karena (*##.Example) hanya berlaku untuk uBO dan tidak untuk Vivaldi, dan yang lainnya saya tidak tahu :)

**Comment by realodix** [comment]
Halo Gan

> Saya berharap Anda membuat filter yang khusus untuk uBO

Seperti yang bisa Anda lihat di halaman depan (file readme), dari sekian banyak ad blocker, Saya hanya menyarankan untuk menggunakan AdBlockID di uBO atau AdGuard. Jadi memang AdBlockID dibuat khusus untuk uBO dan AdGuard.

> karena filter (##.example) tidak berfungsi di uBO dan hanya berfungsi jika filter di ubah menjadi (*##.example)

`*##.example` ini adalah filter spesifik dengan penggunaan `*` agar bisa di semua domain, jadi mirip seperti filter generic.

Dugaan Saya dalam issue ini filter generic berjalan, makanya Anda menyarankan untuk membuatnya jadi spesifik.

Apakah Anda sudah cek di halaman Filter lists, `Ignore generic cosmetic filters` tidak tercentang? Kurang lebih seperti screenshoot ini

<details>
  <summary>Screenshot</summary>
  
  ![unnamed](https://user-images.githubusercontent.com/1314456/144856688-afba2003-cd79-4722-93d6-62348d4af7ce.jpg)
</details>

Kalau sudah dipastikan tidak tercentang dan filter generic masih tidak bisa juga, Saya butuh info filter apa saja yang Anda gunakan

**Comment by Gamefire238** [comment]
Wah, terimakasih infonya  :+1:
