### ISSUE TITLE
reddit.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1085]
https://www.reddit.com/r/sharex/comments/oqwz48/sharex_breaks_windows_11/

tidak bisa klik kanan

windows 11

**Comment by realodix** [comment]
> https://www.reddit.com/r/sharex/comments/oqwz48/sharex_breaks_windows_11/
> 
> tidak bisa klik kanan
> 
> windows 11

Saya gagal paham ini maksudnya gimana?

- Pertama reddit itu situs internasional
- Kedua, Saya mau coba bantu buat scriptnya tapi reddit seperti biasa bisa klik kanan
