### ISSUE TITLE
[Anti-Adblock] go.softfull.me

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#109]
**Sample URL**
https://go.softfull.me/?id=eWFadXloSXBqS0lvYmo2NjJvUlJsRW5NbFB2MmlDQWp3Y3NVamxTbC92WT0=

**Penjelasan Lebih Lanjut**
AA

Source
https://animee.xyz/heavy-object-subtitle-indonesia-episode-01-24-end-batch/

dan disitus animee.xyz juga ada banner iklanya gan

**Comment by realodix** [comment]
Thank you, tolog dicek kembali :D

**Comment by WaferNabati** [comment]
@realodix bannernya masih ada bro

**Comment by realodix** [comment]
Sorry gak merhatiin, ternyata 2 request.
