### ISSUE TITLE
tokopedia.com - area kosong pada '/find' page

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1099]
https://www.tokopedia.com/find/pc-gaming

![image](https://user-images.githubusercontent.com/19517680/148866526-f76dd4eb-c43c-4d19-86b9-511a0a87749d.png)

pakai ublock origin, chrome dev
ada frame kosong

**Comment by realodix** [comment]
Saat ini Saya test di HP dengan tampilan desktop, hasilnya fine aja.

Tolong screenshot loggernya Gan, Saya mau lihat filter rules apa yang jalan

**Comment by realodix** [comment]
Saya tidak begitu ngerti apa yang terjadi? 
Ini terlihat seperti bug pada uBO, dimana uBO memperlihatkan perilaku yang berbeda antara Firefox dan browser berbasis Chromium.

Saat ini dengan AdBlockID v22.1.25 tampilan di browser berbasis Chromium sudah terlihat normal.
