### ISSUE TITLE
nusantararom.org

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1100]
https://nusantararom.org/vayu/

![Screenshot_20220111-162742848](https://user-images.githubusercontent.com/19517680/148917122-1034dbce-b416-47b7-916b-b131a9bc84ad.jpg)

**Comment by realodix** [comment]
Ini peringatan anti-adblocker?

**Comment by realodix** [comment]
Saya tidak dapat mereplikasinya

**Comment by What-Zit-Tooya** [comment]
> Saya tidak dapat mereplikasinya

![1](https://user-images.githubusercontent.com/9832875/149435412-53ba4787-758a-497c-a292-9c7732ee73ce.png)

I can reproduce this, Both on FF desktop & phone

**Comment by realodix** [comment]
Sekarang Saya melihatnya, tetapi ada yang aneh

- Turn off uBO or similar extension
- Clear all (Cookies, Site Data, Cache , etc)

<details>
  <summary>Screenshot</summary>
  
  ![noname-crop](https://user-images.githubusercontent.com/1314456/149464668-cf797996-371e-4693-85ff-4554e21309e8.png)
</details>

**Comment by What-Zit-Tooya** [comment]
> 

Need dig the code to see what happen on site :D

**Comment by What-Zit-Tooya** [comment]
@realodix @3xploiton3 fixed in uBO - uAssets https://github.com/uBlockOrigin/uAssets/commit/c63b722f1cf165f4d64d57acb389e35d9ff883d5

**Comment by realodix** [comment]
> fixed in uBO - uAssets [uBlockOrigin/uAssets@c63b722](https://github.com/uBlockOrigin/uAssets/commit/c63b722f1cf165f4d64d57acb389e35d9ff883d5)

Ok, thank you
