### ISSUE TITLE
Meowku (209.126.6.6)

### ISSUE THREAD

**Issue by Bug-Cache** [realodix/AdBlockID#1107]
http://209.126.6.6/oni-chichi-refresh%e2%99%a5-2015-episode-1-subtitle-indonesia/

Ads

![Screenshot_20220130-011245346 (1)](https://user-images.githubusercontent.com/98657967/151672513-15a0c248-5016-4459-9e32-a2f446340334.jpg)

**Comment by realodix** [comment]
Maaf ini pakai adblocker apa ya?

Karena untuk popup warna hijau di atas, versi terakhir AdBlockID (v22.1.132 atau v2.0.9.60 (khusus AdGuard)) sebelum #1105, seharusnya sudah tidak ada popup.

**Comment by Bug-Cache** [comment]
![Screenshot_20220131-132906548 (1)](https://user-images.githubusercontent.com/98657967/151748633-46ddb6e6-2e0b-416e-b503-1a97a4ccd5df.jpg)

Pakai adblock dari 1dm+
https://play.google.com/store/apps/details?id=idm.internet.download.manager

**Comment by realodix** [comment]
OK Saya sduah downlaod

Di 1DM Saya melihat ada uBlock filters yang disertakan, yang sepertinya sama seperti AdBlockID tidak 100% compatible juga dengan 1DM. Karena sebagian popup sudah dihilangkan oleh uBlock filters.

Seperti yang Saya sebutkan di [readme halaman depan](https://github.com/realodix/AdBlockID#desktop), Saya hanya menyarankan untuk menggunakan uBlock Origin atau AdGuard. Karena AdBlockID sangat bergantung pada teknologi penghilang iklan yang lebih canggih, sayangnya saat ini hanya ada di adblocker tersebut 😄 

Baik uBlock Origin dan AdGuard keduanya sama-sama bisa digunakan di Android. Detailnya ada di https://github.com/realodix/AdBlockID#mobile
