### ISSUE TITLE
ngelag.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1113]
https://ngelag.com/cara-menulis-huruf-arab-dan-berharakat-di-android-tanpa-root/

permasalahan website setelah masuk tidak bisa kembali ke google (atau halaman sebelumnya) 
mungkin ada sesuatu js yang menghalangi

![image](https://user-images.githubusercontent.com/19517680/152633281-7bc00e59-7e5c-42a1-9418-5cb23f7e8197.png)

**Comment by aszksbdje** [comment]
Gk paham @3xploiton3 lapor kesini bener apa enggak.
Cuman pingin komen kok bisa ya... tak coba back gk mau kembali. lucu situsnya.

**Comment by realodix** [comment]
Bisa, karena ada ini

```js
<script type='text/javascript'>
history.pushState(null, null, location.href);
window.onpopstate = function () {
    history.go(1);
};	
</script>
```

Bisa diakalin dengan `ngelag.com##+js(set, window.onpopstate, noopFunc)`

---

Saya tidak paham apa tujuannya mencegah user untuk tekan tombol back, ini terlihat seperti untuk lucu2an saja.

**Comment by aszksbdje** [comment]
> Bisa, karena ada ini
> 
> ```js
> <script type='text/javascript'>
> history.pushState(null, null, location.href);
> window.onpopstate = function () {
>     history.go(1);
> };	
> </script>
> ```
> 
> Bisa diakalin dengan `ngelag.com##+js(set, window.onpopstate, noopFunc)`
> 
> Saya tidak paham apa tujuannya mencegah user untuk tekan tombol back, ini terlihat seperti untuk lucu2an saja.

Itu di masukin my filter kalau di ublock ?

**Comment by aszksbdje** [comment]
> Bisa, karena ada ini
> 
> ```js
> <script type='text/javascript'>
> history.pushState(null, null, location.href);
> window.onpopstate = function () {
>     history.go(1);
> };	
> </script>
> ```
> 
> Bisa diakalin dengan `ngelag.com##+js(set, window.onpopstate, noopFunc)`
> 
> Saya tidak paham apa tujuannya mencegah user untuk tekan tombol back, ini terlihat seperti untuk lucu2an saja.

Sangar... Solved

**Comment by 3xploiton3** [comment]
bisa ditambahkan ke filter AdblockID Plus?
