### ISSUE TITLE
EMSPOSINDONESIA.COM (phising)

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1114]
Link phising (penipuan pos indonesia)
EMSPOSINDONESIA.COM
track-posindonesia-coid.com

![Screenshot_20220205-220253844](https://user-images.githubusercontent.com/19517680/152647268-c9d65667-a1cd-4c0a-a88d-392f7c6d6609.jpg)
![Screenshot_20220205-220511713 (1)](https://user-images.githubusercontent.com/19517680/152647353-fd0e8f14-29f1-4bcc-bcbc-41ae83a4be92.jpg)

**Comment by 3xploiton3** [comment]
![Uploading Screenshot_20220205-220759046 (1).jpg…]()

**Comment by 3xploiton3** [comment]
Isi email sebagai berikut:

![Screenshot_20220205-220759046 (1)](https://user-images.githubusercontent.com/19517680/152647461-98b7270c-13d6-4476-b5bb-670612ce68b7.jpg)

**Comment by realodix** [comment]
Ini benar-benar di luar scope AdBlockID Gan, maaf.

Sebaiknya langsung dilaporkan ke https://trustpositif.kominfo.go.id/
