### ISSUE TITLE
cnbcindonesia.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1115]
![image](https://user-images.githubusercontent.com/19517680/152651531-d3870f85-5ebe-4764-94d8-fc5acbf5d64c.png)

https://www.cnbcindonesia.com/market/20211022143903-17-285828/arto-hingga-gozali-keluarga-ini-tajir-gilak-jual-bank-mini

banner segede baliho partai

**Comment by realodix** [comment]
Di Saya gak ada. Ini kondisi tanpa ad blocker

<details>
  <summary>Screenshot</summary>
  
  ![noname](https://user-images.githubusercontent.com/1314456/152674279-88413912-a4e5-4cf8-9e3c-435e2ff504da.png)
</details>

**Comment by realodix** [comment]
Sudah 2 hari, Saya masih tidak menemukannya

**Comment by 3xploiton3** [comment]
saya cek kembali sudah hilang dengan sendirinya tanpa saya ubah settingan
