### ISSUE TITLE
moviegan.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#112]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://moviegan.com/

**Penjelasan Lebih Lanjut**
banner iklan judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
`https://moviegan.vip/movies/frozen-ii-2019/`
`https://jodklub.online/r15BhVwYmCAZ/17386`

**Comment by realodix** [comment]
> https://moviegan.vip/movies/frozen-ii-2019/
> https://jodklub.online/r15BhVwYmCAZ/17386

Thank you
