### ISSUE TITLE
galamedia.pikiran-rakyat.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1121]
https://galamedia.pikiran-rakyat.com/humaniora/pr-351158085/asmaul-husna-yuk-dzikir-pagi-dengan-al-ghani-al-mughni-dan-al-maani-hanya-allah-pemberi-rezeki?

![Screenshot_20220219-013238279 (1)](https://user-images.githubusercontent.com/19517680/154742087-84165e08-01bc-4f13-843c-4189bd189d22.jpg)

**Comment by realodix** [comment]
Saya tidak tahu apakah commit ini (https://github.com/realodix/AdBlockID/commit/ba8112db50cab150f407572c731c75904134a85c) dapat membantu? Karena Saya tidak menemukan area berwarna abu-abu seperti SS di atas.

![noname-crop](https://user-images.githubusercontent.com/1314456/154793107-57a9a2ad-78ff-4057-aa54-e5c58291e5b2.png)
