### ISSUE TITLE
[nsfw] manhwaid.org 

### ISSUE THREAD

**Issue by YellowStar11** [realodix/AdBlockID#1123]
- Iklan
- Pop-up
- Anti-Adblock

**Sample URL**
https://manhwaid.org/ [Nsfw] 

Iklan, pop up & adblock terdeteksi disitus tersebut. Saya menggunakan Browser Vivaldi dengan adblocker bawaan

**Comment by realodix** [comment]
Halo Gan

Saya sudah mencoba untuk install Vivaldi, install AdBlockID di adblocker bawaan dan membuka manhwaid.org. Hasilnya sesuai seperti yang dilaporkan.

Tapi sebenarnya ini adalah laporan yang invalid, karena tidak ada masalah dengan manhwaid.org seperti yang dilaporkan. Di [halaman depan](https://github.com/realodix/AdBlockID#desktop) Saya menyarankan untuk hanya pasang AdBlockID di uBlock Origin atau AdGuard.

Masalah utamanya adalah di beberapa situs, AdBlockID sangat membutuhkan teknologi pemblokir iklan yang lebih maju, sayangnya saat ini hanya ada di uBlock Origin dan AdGuard.
