### ISSUE TITLE
cnnindonesia.com

### ISSUE THREAD

**Issue by 3xploitzer0** [realodix/AdBlockID#1133]
https://www.cnnindonesia.com/gaya-hidup/20190717174155-255-413026/membangkitkan-energi-terbesar-dengan-meditasi-kundalini

![Screenshot_20220226-003446023](https://user-images.githubusercontent.com/56762704/155761113-60e95505-bbc6-40b4-a1a1-26dd8ece6356.jpg)

Ads

**Comment by realodix** [comment]
Halo Gan, sorry ini pakai apa ya? Saya tidak menemukannya. 

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2022-02-26-01-04-19-176_com kiwibrowser browser](https://user-images.githubusercontent.com/1314456/155765148-cdfdd7b5-cc1c-439d-907d-7b3195d2f099.jpg)
</details>

**Comment by realodix** [comment]
Sudah 2 hari, tetapi hingga saat ini Saya tidak menemukan seperti yang ada di screenshoot
