### ISSUE TITLE
suara.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1135]
![Screenshot_20220228-000304_Kiwi Browser](https://user-images.githubusercontent.com/19517680/155892000-e3f96bdf-e6b0-4b26-971f-4bb14771b8b7.png)

Banner bawah

https://bekaci.suara.com/read/2022/02/26/200500/ppatk-blokir-rekening-crazy-rich-yang-terlibat-binary-option-nilainya-fantastis

**Comment by realodix** [comment]
Ini pakai browser atau AdBlocker apa?

**Comment by realodix** [comment]
Gunakan uBlock Origin atau AdGuard.

**Comment by 3xploiton3** [comment]
Sudah tentunya saya cuma pakai ublock origin & adguard, setelah saya purge & force update, masih ada ads

https://www.suara.com/tekno/2022/02/27/180732/bocoran-desain-dan-spesifikasi-poco-m4-pro-dirilis-besok

![Screenshot_20220228-152842_Kiwi Browser](https://user-images.githubusercontent.com/19517680/155950083-e0d5c806-142a-47c5-8231-0384749b71e6.png)

**Comment by realodix** [comment]
[suara.com](https://www.suara.com/tekno/2022/02/27/180732/bocoran-desain-dan-spesifikasi-poco-m4-pro-dirilis-besok) sudah ada di dalam AdBlockID.

Untuk uBo harus dipastikan pengaturan ini tidak tercentang
- Settings > Default behavior > Disable cosmetic filtering
- Filter lists > Ignore generic cosmetic filters

**Comment by 3xploiton3** [comment]
> [suara.com](https://www.suara.com/tekno/2022/02/27/180732/bocoran-desain-dan-spesifikasi-poco-m4-pro-dirilis-besok) sudah ada di dalam AdBlockID.
> 
> Untuk uBo harus dipastikan pengaturan ini tidak tercentang
> 
> * Settings > Default behavior > Disable cosmetic filtering
> * Filter lists > Ignore generic cosmetic filters

Oke terimakasih,
