### ISSUE TITLE
tempo.co

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1136]
https://seleb.tempo.co/read/1565366/5-hal-yang-dilakukan-doni-salmanan-sebelum-disorot-soal-trading-binary-option

Banner atas

![Screenshot_20220228-151852_Kiwi Browser](https://user-images.githubusercontent.com/19517680/155948632-2db02a91-0615-4b80-bd88-cedbb77d376f.png)

**Comment by realodix** [comment]
Di sini yang dimaksud banner atas yang mana ya?

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/156017616-cc3a5ce9-e659-4986-a1b9-0b9a32df88e5.png)

**Comment by realodix** [comment]
Ini seharusnya sih tidak masalah Gan. Mereka menggunakannya untuk menampilkan banner berlangganan tempo.

<details>
  <summary>Screenshot</summary>
  
  ![noname-crop](https://user-images.githubusercontent.com/1314456/156187709-809160d2-e255-4b27-a583-9ae888471f45.png)
</details>
