### ISSUE TITLE
pikiran-rakyat.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1137]
https://zonajakarta.pikiran-rakyat.com/teknologi/pr-183842715/xiaomi-banting-harga-ratusan-ribu-hp-canggih-poco-x3-gt-baru-cuma-dijual-segini-per-februari-2022

Frame kosong d bawah

![Screenshot_20220228-153244_Kiwi Browser](https://user-images.githubusercontent.com/19517680/155950570-aa49ba1a-ab35-4621-b174-3929dbf3bf93.png)

**Comment by realodix** [comment]
> https://zonajakarta.pikiran-rakyat.com/teknologi/pr-183842715/xiaomi-banting-harga-ratusan-ribu-hp-canggih-poco-x3-gt-baru-cuma-dijual-segini-per-februari-2022
> 
> Frame kosong d bawah

Ini mirip seperti #1135

Frame kosong yang dimaksud sudah ditangani dengan baik oleh easylist. Agan bisa mengikuti cara ini https://github.com/realodix/AdBlockID/issues/1135#issuecomment-1054059170
