### ISSUE TITLE
bisnis.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1145]
https://m.bisnis.com/market/read/20220304/192/1506815/kebijakan-rusia-dan-efek-ke-surya-esa-perkasa-essa-serta-produsen-pupuk

![Screenshot_20220306-004408521](https://user-images.githubusercontent.com/19517680/156894356-6ed69ee3-8c0c-48cc-8678-31028b89a22b.jpg)

Banner di bawah

**Comment by realodix** [comment]
Ini sudah ditangani dengan baik oleh easylist.

<details>
  <summary>Screenshot</summary>
  
  ![noname](https://user-images.githubusercontent.com/1314456/156902035-40f7ba40-71f2-495f-951a-f34c61f84a7b.png)
</details>
