### ISSUE TITLE
big.go.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1146]
![image](https://user-images.githubusercontent.com/19517680/157466871-42ace23d-0c01-4162-9211-fb066e194da5.png)

http://inacors.big.go.id/sbc/Account/Index?returnUrl=%2Fsbc

cookies banner

**Comment by realodix** [comment]
Ini udah masuk kok Gan ke filter Annoyances umum seperti Fanboy’s Annoyance dan EasyList Cookie
