### ISSUE TITLE
pikiran-rakyat.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1149]
![Screenshot_20220314-203440980](https://user-images.githubusercontent.com/19517680/158182885-b130e077-8540-4ced-9fc2-79fb519a626c.jpg)

https://jurnalsoreang.pikiran-rakyat.com/ekonomi/amp/pr-1013964174/lebih-gila-dari-binary-option-bos-robot-trading-fahrenheit-jadi-buronan-menipu-hingga-rp-5-triliun

**Comment by realodix** [comment]
Ini alamatnya AMP ya?

Di filterbase easylist sudah ditangani dengan baik Gan. Kalau Saya tambahin ke AdBlockID akan jadi numpuk.

<details>
  <summary>Screenshot</summary>
  
  ![Image 4](https://user-images.githubusercontent.com/1314456/158192268-ecd39f2f-52b1-4234-8342-defcb22da82b.png)
</details>

**Comment by 3xploiton3** [comment]
![Screenshot_20220315-235408036](https://user-images.githubusercontent.com/19517680/158430518-cb789774-c30d-4164-b6fb-cf47b47e9301.jpg)

Filter easylist sudah saya aktifkan, ad masih terlihat, sudah saya coba force update,

**Comment by realodix** [comment]
Coba screenshot nya di naikin Gan ke halaman paling atas

**Comment by 3xploiton3** [comment]
![Screenshot_20220316-144313890](https://user-images.githubusercontent.com/19517680/158540780-fb3144f7-c640-4fcd-91bf-7f3cd00f978e.jpg)

**Comment by realodix** [comment]
Ini mirip seperti #1135 dan #1137

Frame kosong yang dimaksud sudah ditangani dengan baik oleh easylist. Agan bisa mencoba mengikuti cara ini terlebih dahulu https://github.com/realodix/AdBlockID/issues/1135#issuecomment-1054059170

Jika tidak bisa juga, untuk dapat membantu Agan, Saya butuh info lebih lanjut tentang settingan yang digunakan, agar Saya bisa menyamakannya. Hal paling mudah bisa ke menu Support -> Troubleshooting Information lalu paste di sini.

**Comment by 3xploiton3** [comment]
uBlock Origin: 1.41.8
Chromium Mobile: 99
filterset (summary): 
  network: 103295
  cosmetic: 156461
  scriptlet: 23416
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 6102-1, 17h.20m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 4938-14, 17h.20m
    IDN-0: 8881-243, 17h.20m
    adguard-annoyance: 50873-177, 17h.20m
    adguard-spyware: 26744-858, 17h.20m
    fanboy-annoyance: 63852-2889, 17h.20m
    ublock-annoyances: 4391-277, 17h.20m
  default: 
    user-filters: 6-0, never
    adguard-mobile: 7344-24, 17h.20m
    easylist: 64187-1498, 17h.20m
    easyprivacy: 26680-10366, 17h.20m
    ublock-abuse: 72-0, 17h.20m
    ublock-badware: 3972-83, 17h.20m
    ublock-filters: 30417-596, 17h.20m
    ublock-privacy: 200-38, 17h.20m
    ublock-unbreak: 1734-63, 17h.20m
filterset (user): [array of 6 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  ignoreGenericCosmeticFilters: false
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 1839 ms (selfie)
  maxAssetCacheWait: 1211 ms

**Comment by realodix** [comment]
Saya sudah menyamakannya sesuai parameter yang Anda berikan, dan semuanya masih bisa ditangani dengan baik oleh easylist.

**Comment by realodix** [comment]
Coba pengaturan filter ini
- Matikan semua filter (termasuk user filter), kecuali uBlock filter, easylist, easyprivacy dan AdBlockID.

Kurang lebih seperti di screenshot

<details>
  <summary>Screenshot</summary>
  
  ![Image 1](https://user-images.githubusercontent.com/1314456/160256289-3321e61d-2da1-43c1-b75e-4c71eb865a83.png)
</details>
