### ISSUE TITLE
animebukatsu.net

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#115]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://animebukatsu.net/2019/08/my-colorful-story-album.html 

**Penjelasan Lebih Lanjut**
popups

**Comment by realodix** [comment]
Thank you. Saya coba blokir ads servernya, harusnya sih sudah gak ada.
