### ISSUE TITLE
tempo.co

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1150]
https://bisnis.tempo.co/amp/1570749/terkini-bisnis-sicepat-ekspres-minta-maaf-korban-indra-kenz-rugi-rp-500-juta

![Screenshot_20220315-235108203](https://user-images.githubusercontent.com/19517680/158429954-ba00b7d6-a096-4b84-9cf2-c1d1b2c77e0b.jpg)

**Comment by realodix** [comment]
<details>
  <summary>Screenshot</summary>
  
  ![Image 11](https://user-images.githubusercontent.com/1314456/158560577-b4583481-55d0-4cd8-8bf1-9566082de996.png)
</details>

Saya malah tidak menemukan ada frame kosong setelah kalimat "media sosial Instagram." di paragraf pertama. Yang Saya temukan ada setelah kalimat "berita trending tersebut."

Kurang lebih ini mirip seperti #1135 dan #1137

Frame kosong yang dimaksud sudah ditangani dengan baik oleh easylist. Agan bisa mencoba mengikuti cara ini terlebih dahulu https://github.com/realodix/AdBlockID/issues/1135#issuecomment-1054059170

Jika tidak bisa juga, untuk dapat membantu Agan, Saya butuh info lebih lanjut tentang settingan yang digunakan, agar Saya bisa menyamakannya. Hal paling mudah bisa ke menu Support -> Troubleshooting Information lalu paste di sini.
