### ISSUE TITLE
IDLIX (193.178.172.113)

### ISSUE THREAD

**Issue by abala26** [realodix/AdBlockID#1151]
**Jenis**

- Iklan

**Sample URL**
https://193.178.172.113//

**Penjelasan Lebih Lanjut**

saya disuruh ke sini. bagaimana cara blok iklan jeniusplay atau jwplayer.
![Screenshot 2022-03-20 190954](https://user-images.githubusercontent.com/101976086/159818105-0122230e-3093-45c6-aacb-ca7a589a6ed1.png)
menggunakan adblocker adguard v.7.9.1 dengan filter AdGuard Base, AdGuard Tracking Protection, AdGuard Social Media, AdGuard Annoyances, AdBlockID. Sama tadi saya disuruh record file har
[193.178.172.113.zip](https://github.com/realodix/AdBlockID/files/8337484/193.178.172.113.zip)

**Comment by abala26** [comment]
gak ada respon?
aku nyoba memperbaiki sendiri, ini kodenya
||jeniusplay.com/cdn/video/QQnewfix.mp4$media,1p

**Comment by realodix** [comment]
Sorry baru online, iklan videonya sudah Saya halau.

> gak ada respon? 
> aku nyoba memperbaiki sendiri, ini kodenya 
> ||jeniusplay.com/cdn/video/QQnewfix.mp4$media,1p

Sebenarnya Anda bisa mengirimkan Pull Request dan jangan ragu :D

**Comment by abala26** [comment]
> Sorry baru online, iklan videonya sudah Saya halau.
> 
> > gak ada respon?
> > aku nyoba memperbaiki sendiri, ini kodenya
> > ||jeniusplay.com/cdn/video/QQnewfix.mp4$media,1p
> 
> Sebenarnya Anda bisa mengirimkan Pull Request dan jangan ragu :D

ya, takut kalau dah gak aktif 😊
saya pengguna baru dan cuman penikmat gak tau cara pull request
