### ISSUE TITLE
Tiktok.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1154]
https://www.tiktok.com/?lang=en&is_copy_url=1&is_from_webapp=1

![Screenshot_20220328-165638750](https://user-images.githubusercontent.com/19517680/160374194-75e8b6aa-1081-45db-99f4-491ef7ed2d65.jpg)

Pop up

**Comment by realodix** [comment]
Sorry Gan, walaupun ini popup, tetapi ini bukan iklan..

Lebih baik langsung dilaporkan ke AdGuard Annoyances dan Fanboy’s Annoyance, karena mereka filter khusus Annoyance.

Untuk pribadi, bisa coba ini `tiktok.com##.backdrop-1 .guide-container`
