### ISSUE TITLE
shrinkads.com (movienear.me) - Pop-Up

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#116]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
https://www.shrinkads.com/M2VcuRQa

**Penjelasan Lebih Lanjut**
Popups

**Comment by realodix** [comment]
Ini pop-up yang muncul di selain uBlock ya?

**Comment by WaferNabati** [comment]
tetap aja muncul walaupun pke ublock origin

**Comment by WaferNabati** [comment]
ada fake button barunya skrng
https://www.shrinkads.com/5nzL

**Comment by realodix** [comment]
> ada fake button barunya skrng

Thank you, fake button sudah saya commit di https://github.com/realodix/AdBlockID/commit/44db43e7230fe041ec8ac5e1f82384505f0104ca

> https://www.shrinkads.com/5nzL
> btw popupsnya muncul pas habis klik continue link yg pertama

Untuk popup Saya gak nemuin.

1. Isi captcha, klik `Click here to continue`.
2. Tunggu sekitar 5 detik, lalu klik `Get Link`.
3. Menuju https://www74.zippyshare.com/v/3Qh5JbIm/file.html

**Comment by WaferNabati** [comment]
@realodix kok punya gw ada popupsnya selalu muncul ke web https://www.miuiku.com/

**Comment by realodix** [comment]
> kok punya gw ada popupsnya selalu muncul ke web https://www.miuiku.com/

Gue juga gak ngerti deh kenapa? Harusnya di uBlock sudah tidak ada pop-up, karena di uBlock filter  juga sudah ditambahkan
`https://github.com/NanoMeow/QuickReports/issues/2150`

Pop-upnya sudah Gue cegah dengan cara manual di https://github.com/realodix/AdBlockID/commit/15b421f34839a316cfe1abcabfad7de282d7f4ee

Rasanya ini bisa dianggap selesai, thank you untuk laporannya :D
