### ISSUE TITLE
Gif dengan url diblok

### ISSUE THREAD

**Issue by w13d** [realodix/AdBlockID#1161]
**Sample HTML**

> ```
> <!DOCTYPE html>
> <html>
> <body>
> 
> <h2>Animated Images</h2>
> 
> <p>HTML allows moving images:</p>
> 
> <a href="http://samples.com" target="_blank">
> 
> <img src="https://www.w3schools.com/html/programming.gif" alt="Computer man" style="width:48px;height:48px;">
> 
> </a>
> 
> </body>
> </html>
> 
> ```

**Penjelasan Lebih Lanjut**

Halaman yang mengandung image GIF dan mempunyai hyperlink (a href url) diblok oleh filter AdBlockID.
Pada sample HTML di atas, image GIF tidak muncul jika browser menggunakan AdGuard dengan AdBlockID aktif.

Filter yang menimbulkan masalah ada di [SINI](https://github.com/realodix/AdBlockID/blob/master/output/adblockid.txt).
Yaitu pada baris 1155 :  `##a[target="_blank"] > img[src*=".gif"]`

Filter tersebut membuat image GIF dengan hyperlink tidak bisa muncul di halaman web.

**Comment by realodix** [comment]
Saat ini memang didesain seperti itu, gambar gif dengan link open new tab akan dihilangkan.. 

Adakah link nyata, agar Saya masukkan ke dalam whitelist?
