### ISSUE TITLE
detik.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1167]
![Screenshot_20220421-170422_Kiwi Browser](https://user-images.githubusercontent.com/19517680/164431846-b0c27b9a-093a-4baf-8057-cedd96bd4e28.png)

Banner bawah

https://news.detik.com/berita/d-6043507/konvoi-bus-massa-buruh-bergerak-menuju-kawasan-dpr-polisi-siaga

**Comment by realodix** [comment]
dMentor harusnya sih gak ada masalah, karena bagian dari program detik itu sendiri

https://20.detik.com/program/200625563/dmentor
