### ISSUE TITLE
exe.io 

### ISSUE THREAD

**Issue by RaveN0X87** [realodix/AdBlockID#117]
https://anitoki.com/?p=6930

https://exe.io/js/full-page-script.js

**Comment by realodix** [comment]
Thank you :D

**Comment by WaferNabati** [comment]
@realodix ini kemungkinan blocking script filternya jg sama gan sumber `psarips.eu`
<details>
https://earnload.com/full/?api=9e215342d130cd952872648af56e6247ab403c10&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv

http://shrinkme.io/full/?api=6a4e9296859080eb5c9c8d797358d9069754edbc&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv

https://links4earn.com/full/?api=23f0ca5680d15a3a33311f2fd0220324d004a38c&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv

https://shorten.sh/full/?api=4cad1dae3630a2d2d580570ec5c75f8be5011a6f&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv

https://cutpaid.com/full/?api=5e028c40b1b4d3e70c504929e780acc4a701fd98&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv

https://ilinkshort.com/full/?api=507454267fef0dbc50f6dd90769cb9c468458a5d&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv

https://urle.io/full/?api=726f220bb154f22e398a30e130fc7531b019ee14&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv

https://gpmojo.com/full/?api=180ffb45ee1d5bed5c471a6e1c11adf29b994376&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv

https://boomx5.com/full/?api=c8212e5bd65ce2675d9a5913462be404&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv

https://gplinks.in/full/?api=a34e4c05ef8afa7330c7dc7da6cf9fd84623e91b&url=aHR0cHM6Ly9nZXQtdG8ubGluay90aGUtd2l0Y2hlci1zMDFlMDgtbXVjaC1tb3JlLTcyMHAtMTBiaXQtd2VicmlwLTJjaC14MjY1LWhldmMtcHNhNjc0NTQv
