### ISSUE TITLE
The filter blocking embedded GIF on Disqus

### ISSUE THREAD

**Issue by heywolf15** [realodix/AdBlockID#1172]
![firefox_I6bfcw3jUo](https://user-images.githubusercontent.com/34807171/166116946-d02ad54a-7b9b-4a39-9d8a-44b5c31a0d6b.png)

Can't see embedded GIF on Disqus

**Comment by realodix** [comment]
Give Me an example URL

**Comment by heywolf15** [comment]
https://disqus.com/embed/comments/?base=default&f=dsogaming&t_i=162997%20https%3A%2F%2Fwww.dsogaming.com%2F%3Fp%3D162997&t_u=https%3A%2F%2Fwww.dsogaming.com%2Fnews%2Fnazralath-the-fallen-world-is-brand-new-dark-souls-inspired-dark-fantasy-action-adventure-game%2F&t_e=Nazralath%3A%20The%20Fallen%20World%20is%20a%20new%20Dark%20Souls-inspired%20dark%20fantasy%20action-adventure%20game&t_d=Nazralath%3A%20The%20Fallen%20World%20is%20a%20new%20Dark%20Souls-inspired%20dark%20fantasy%20action-adventure%20game&t_t=Nazralath%3A%20The%20Fallen%20World%20is%20a%20new%20Dark%20Souls-inspired%20dark%20fantasy%20action-adventure%20game&s_o=popular#version=48980166e0153f33375a5a0d60b5e441

Sorry for a long link, because this is embedded Disqus link

This is how it looks when it gets filtered
![firefox_rJ5BHIzGxp](https://user-images.githubusercontent.com/34807171/166124461-7dd597d8-2b56-4490-acda-de6f7cbe0038.png)

This is how it supposes to look
![firefox_wyOhPWaWPR](https://user-images.githubusercontent.com/34807171/166124468-871fd2db-f3cc-4a50-882f-c6931caa3015.png)
