### ISSUE TITLE
otakudrive.net

### ISSUE THREAD

**Issue by RaveN0X87** [realodix/AdBlockID#118]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://otakudrive.net/?id=ME5ReE1mbmZ3TDNadlI0bjZqVFh4WWxKTGJCakRWbUlIRE0xVEJuLzJDdHZwckQ4dDdFU1pzdTlUME9qY0hTWEZMUzUreEtCV3BVbmd4WWdjZUVpZHc9PQ==

**Penjelasan Lebih Lanjut**
Banner iklan

**Comment by realodix** [comment]
Thank you :D
