### ISSUE TITLE
cekresi.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1181]
![image](https://user-images.githubusercontent.com/19517680/168100263-ae451a7c-5856-4e83-ad4e-023b6e26bf1a.png)

https://cekresi.com/ongkir/2087-2724-cengkareng-ceper-klaten/?w=1&courier=jne

ads

**Comment by realodix** [comment]
Sudah ditangani dengan baik oleh easylist.

<details>
  <summary>Screenshot</summary>
  
  ![Image 1](https://user-images.githubusercontent.com/1314456/168129101-174b5387-c359-42bb-a440-7e2131069f58.png)
</details>
