### ISSUE TITLE
kompas.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1186]
![Screenshot_20220513-180732_Kiwi Browser](https://user-images.githubusercontent.com/19517680/168271224-0e52778e-ecf9-4270-9473-d7b2e6c1865b.png)

https://money.kompas.com/read/2022/05/12/200704526/dipakai-gratis-lalu-dari-mana-google-dapat-untung-dari-google-maps?page=all

**Comment by realodix** [comment]
Ini seharusnya sudah ditangani dengan baik oleh easylist.

![Image 2](https://user-images.githubusercontent.com/1314456/168375300-3913844c-1dc9-4932-9655-40691a9eff72.png)

**Comment by 3xploiton3** [comment]
network: 86796


Masih muncul itu filter list saya, easylist sudah termasuk

**Comment by realodix** [comment]
Saya juga gak ngerti apa yang terjadi di Agan. Hal ini mirip seperti issue2 sebelumnya yang saya tag invalid, terlihat seperti filter `generic hide` tidak berfungsi.

Agan pakai browser apa? Saya dari kemarin gak ketemu ada browser dengan ciri terdapat logo 5 jari di samping jumlah tab.

**Comment by 3xploiton3** [comment]
pakai kiwi browser, hanya browser itu yang support ublock-origin mobile
