### ISSUE TITLE
animenine.fun

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1188]
![image](https://user-images.githubusercontent.com/19517680/168567932-5bf8e026-a35c-430c-b9ac-ab737f2b6f93.png)

https://animenine.fun/nonton-one-piece-episode-1013-sub-indo

ada sesuatu yang menghalangi

**Comment by realodix** [comment]
Sepertinya ini tentang perbedaan perilaku adblocker antara firefox dan chrome.

Saya mencoba di browser dengan konfigurasi (Semua filter uBlock + EasyList + AdBlockID)

Hasilnya di Firefox tidak bermasalah.

<details>
  <summary>Screenshot</summary>
  
  ![Image 3](https://user-images.githubusercontent.com/1314456/168588089-3d1185b5-856e-4477-91ee-dde64dcdbedd.png)
</details>

**Comment by 3xploiton3** [comment]
betul, saya coba di chrome dev hasilnya ada notice, di firefox dev tidak ada notice
