### ISSUE TITLE
idntimes.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1190]
https://www.idntimes.com/tech/trend/izza-namira-1/aplikasi-android-paling-mahal-di-play-store/4

![Screenshot_20220521-063757_Kiwi Browser](https://user-images.githubusercontent.com/19517680/169624933-b1705c3d-3e73-42f0-91cc-d2c683925ce2.png)

Pop up menganggu

**Comment by realodix** [comment]
Tidak muncul peringatannya
