### ISSUE TITLE
indojavstream.com

### ISSUE THREAD

**Issue by Bug-Cache** [realodix/AdBlockID#1193]
**Jenis**

Klik double play

**Sample URL**
https://indojavstream.com/watch/pppd00974.html?key=o5bralxobpyv

**Penjelasan Lebih Lanjut**
![image](https://user-images.githubusercontent.com/98657967/170099220-118c6ded-4b84-4a93-b22e-c2f67833ddc1.png)
play di Server FE, harus klik play berulang-ulang

**Comment by realodix** [comment]
Ini gak masuk ruang lingkup, coba ini

`komikhentai.eu.org##div:matches-css(position:fixed):matches-css(width:1140px):matches-css(height:671px)`
