### ISSUE TITLE
sindonews.com

### ISSUE THREAD

**Issue by BanijaDev** [realodix/AdBlockID#1196]
**Sample URL**
https://international.sindonews.com/read/747597/40/negara-negara-yang-tidak-punya-hubungan-diplomatik-dengan-indonesia-1650351890?showpage=all

**Penjelasan Lebih Lanjut**

![Screenshot_20220528-160850_Kiwi Browser](https://user-images.githubusercontent.com/97141433/170818954-47f7ebbf-5e41-4b87-84fd-b06e528b297e.png)

**Comment by realodix** [comment]
Pakai adblocker apa? uBlock atau AdGuard?

**Comment by BanijaDev** [comment]
Adguard extension
![Screenshot_20220531-010421_Kiwi Browser](https://user-images.githubusercontent.com/97141433/171042370-d1dfbba6-c6e3-4de7-a60a-4d134888117d.png)

**Comment by realodix** [comment]
Ini karena AdGuard gagal mengkonversi ke aturan mereka. Di uBlock Origin tidak ada masalah.

[AdguardTeam/FiltersRegistry/d4446d0/filters/ThirdParty/filter_120_AdBlockID/diff.txt#L405](https://github.com/AdguardTeam/FiltersRegistry/blob/d4446d05bf1f48189d8335819c5fa8c4a753a76d/filters/ThirdParty/filter_120_AdBlockID/diff.txt#L405)

Kode sudah Saya improve, berharap mereka dapat mengkonversinya.
