### ISSUE TITLE
xbokep.bond

### ISSUE THREAD

**Issue by Bug-Cache** [realodix/AdBlockID#1198]
**Jenis**

Iklan

**Sample URL**
https://xbokep.bond/bokep-indo-mahasiswi-tete/

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Di mananya ya?
Bisa kasih SS buat lebih perjelas?

**Comment by realodix** [comment]
Iklan masih tidak ditemukan selain tempat iklan kosong. Saya rasa ini bisa ditutup.
