### ISSUE TITLE
rancah.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1199]
**Jenis**
- Boost timer

**Sample URL**
https://bit.rancah.com/mVJEJLlV

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Iklannya di bagian mana?

**Comment by realodix** [comment]
Note
- Anti-adblock https://bit.rancah.com/mVJEJLlV/QCRoZW5kcmFicmlkZ2UkQA==

**Comment by realodix** [comment]
Sudah hari ke 2

Saya rasa ini bisa ditutup

**Comment by Recehan-Slayer** [comment]
countdownya bro bukan iklan

**Comment by realodix** [comment]
> countdownya bro bukan iklan

Sayangnya ini Saya tidak ketemu angka yang pas. Saya coba cepetin 2x lipat hasilnya bad request, mereka seperti memvalidasinya di sisi server. Terakhir ada di angka 20% lebih cepat, bener2 tidak berasa.

Bisa coba ini `rancah.com##+js(nano-sib, , ,0.8)`
