### ISSUE TITLE
cermati.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1205]
**Jenis**
- Iklan

**Sample URL**
https://www.cermati.com/artikel/fenomena-exposure-menguntungkan-atau-merugikan?

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Di bagian mana?

**Comment by Recehan-Slayer** [comment]
banner

**Comment by realodix** [comment]
Bisa berikan screenshot?

**Comment by Recehan-Slayer** [comment]
![Screenshot_2022-06-11-18-08-30-240_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/173185366-ae1cbdd0-f61b-4413-8c47-785185ebd1e0.jpg)
![Screenshot_2022-06-11-18-08-36-262_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/173185384-0ee120a1-9fd9-414c-bd99-3f050c5d0048.jpg)

**Comment by realodix** [comment]
Saya lihat ini banner, tapi mengarah ke produk/layanan mereka sendiri. Ini seharusnya tidak boleh dihilangkan dengan sengaja.

`cermati.com##.post-content a.btn-track > picture`
