### ISSUE TITLE
logitech.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1206]
![image](https://user-images.githubusercontent.com/19517680/173227112-be1ac1db-fc0b-4c57-82a8-1ea316b48b5c.png)

https://www.logitech.com/en-us/products/keyboards/k375s-multidevice-stand-combo.html

website rusak (tidak berfungsi normal) ada filter yang perlu diperbaiki

**Comment by realodix** [comment]
Filter rules apa yang perlu diperbaiki? Saya butuh info lebih lanjut, seperti filter apa saja yang digunakan dan info lainnya yg bsia diberikan.

Saya test di Edge dan Firefox, hasilnya normal.

<details>
  <summary>Screenshot</summary>
  
  ![Image 1](https://user-images.githubusercontent.com/1314456/173227296-8ea63d88-c3f8-49f4-9293-709e542e2f1a.png)
</details>

**Comment by 3xploiton3** [comment]
maaf sudah diperbaiki fanboy filter
