### ISSUE TITLE
[Anti-Adblock] spiin.xyz (exe.io)

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#121]
**Sample URL**
Sebelumnya dimukan pada https://anitoki.com/?p=6930 (#117)

[https://exe.io/full/?api=e66b884a...J&type=2](https://exe.io/full/?api=e66b884a7f6cb0cf4f147cf1121d391dd5de3d9c&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MTN6bkRmb18xUDA1WS1kemxYb2tMb2x5a2xPSV9QTE5J&type=2)
Redirect to https://spiin.xyz/zl9r

[https://exe.io/full/?api=e66b884a...0&type=2](https://exe.io/full/?api=e66b884a7f6cb0cf4f147cf1121d391dd5de3d9c&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MUlJamEwdlJSQ3YtM0pVcTBsY2dZanliSGNjRmI1TUQ0&type=2)
Redirect to https://spiin.xyz/wcS7qHI

[https://exe.io/full/?api=e66b884a...S&type=2](https://exe.io/full/?api=e66b884a7f6cb0cf4f147cf1121d391dd5de3d9c&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MWN2cHRZRk5pOVZjOXNIM2tiOGZKVFNRYVJGemhUWXRS&type=2)
Redirect to https://spiin.xyz/ZNuf7tof

[https://exe.io/full/?api=e66b884a...t&type=2](https://exe.io/full/?api=e66b884a7f6cb0cf4f147cf1121d391dd5de3d9c&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MWhIT0ZjVlBYdnFhQ1Z1MUtXQm51MmVQZTNNcGlLSWZt&type=2)
Redirect to https://spiin.xyz/lz29YMc

**Comment by WaferNabati** [comment]
klo dari exe.io domainya selalu ganti" hampir tiap hari

**Comment by realodix** [comment]
**History**
Sekarang jadi redirect ke memoo.xyz
