### ISSUE TITLE
helmiau.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1210]
**Jenis**
- Anti-Adblock

**Sample URL**
https://www.helmiau.com/

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Anti-Adblock dimana? Bisa kasih Screenshoot?

**Comment by Recehan-Slayer** [comment]
![Screenshot_2022-06-18-03-07-06-020_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/174394502-bfa0357a-8e0c-4a26-a32f-85f2765406d1.jpg)

https://helmiau.github.io/blog/helmiwrt-os
