### ISSUE TITLE
oploverz.asia

### ISSUE THREAD

**Issue by aszksbdje** [realodix/AdBlockID#1219]
**Jenis**

**Sample URL**
https://oploverz.asia/
https://65.108.132.145/

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
>Terdapat iklan di halaman ...

Sorry di halaman yang mana ya ada iklan?

**Comment by aszksbdje** [comment]
Maaf, lupa tadi belum kasih gambar. 😅

Iklan di semua tempat.

https://ibb.co/t4JyQxP
https://ibb.co/5s56m22

**Comment by realodix** [comment]
Ok Saya mengerti


Sorry, Saya tidak menyatukan AdBlockID ke dalam AdBlockID Plus.

Saat ini oploverz sudah ada di AdBlockID, mohon subscribe AdBlockID-nya juga.

**Comment by aszksbdje** [comment]
Oh. jadi "plus" dan "tidak" itu beda ... 
saya pikir plus berarti versi lebih lengkapnya ... 
🙈🙈🙈
