### ISSUE TITLE
rancah.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1229]
**Sample URL**
https://bit.rancah.com/pYSMi
https://bit.rancah.com/E61swwi

**Penjelasan Lebih Lanjut**
macet pas hitungan mundur ke 0 tidak mau lanjut ke web filehosting

**Comment by realodix** [comment]
Saya coba https://bit.rancah.com/pYSMi

Edge 103.0.1264.49, uBO 1.43.0

https://user-images.githubusercontent.com/1314456/178443388-42d4cc99-2a29-47a0-9113-6cf8dfb128e3.mp4

**Comment by Recehan-Slayer** [comment]
gw coba pke chrome tombol continue nya g muncul

**Comment by realodix** [comment]
Coba ke Support -> Troubleshooting Information, paste di sini..

Saya cona samakan setingannya

**Comment by Recehan-Slayer** [comment]
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 120829
  cosmetic: 130972
  scriptlet: 36578
  html: 0
listset (total-discarded, last updated): 
  removed: 
    IDN-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 9859-19, 3d.16h.33m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 2855-6, 3d.16h.32m
    adguard-annoyance: 54996-446, 3d.16h.40m
    adguard-generic: 65568-786, 3d.16h.39m
    adguard-spyware: 26315-804, 3d.16h.37m
    ublock-annoyances: 4479-192, 3d.20h.40m
  default: 
    user-filters: 0-0, never
    easylist: 68494-874, 3d.16h.35m
    easyprivacy: 27362-10272, 3d.16h.34m
    plowe-0: 3646-866, 3d.20h.41m
    ublock-abuse: 75-0, 3d.20h.40m
    ublock-badware: 4212-314, 3d.20h.40m
    ublock-filters: 32096-3833, 3d.20h.40m
    ublock-privacy: 225-41, 3d.20h.40m
    ublock-quick-fixes: 207-18, 6h.59m
    ublock-unbreak: 1831-101, 3d.20h.40m
    urlhaus-1: 4945-0, 6h.58m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 16210 ms (selfie)
  maxAssetCacheWait: 4540 ms
