### ISSUE TITLE
Gomunime (185.231.223.76) 

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1231]
**Jenis**
- Iklan
- Pop-up

**Sample URL**
https://185.231.223.76/iya-na-kao-sare-nagara-opantsu-misete-moraitai-episode-3-sub-indo/

**Penjelasan Lebih Lanjut**
- pas putar video muncul popup ke situs judi

**Comment by realodix** [comment]
Popup tidak ditemukan. Ketika sedang apa ya?

https://user-images.githubusercontent.com/1314456/179075217-0fa85468-2d72-4e57-ae9b-08a658142006.mp4

**Comment by Recehan-Slayer** [comment]
kadang suka muncul tp ga selalu ya itu pas play ada tulisan the ad will end in  pas itu kadang muncul popup ke situs judi

**Comment by realodix** [comment]
Ketika nanganin Gomunime, Saya lihat mereka mengharuskan user melewati step ini

1. Klik video yang ingin user tonton.
2. Putar video iklan hingga selesai (ditandai tulisan `This ad will end in`)
   2.1. Jika user klik video iklan tersebut, maka akan munncul jendela baru.
4. Putar video sesungguhnya.

Proses ini benar-benar tidak bisa dirubah.

---

Cara ngakalinnya, Saya mengalihkan video iklan (nomor 2) ke video kosong yang disediakan oleh uBO dan AdGuard.

`||konveti.onicdn.xyz/adam/*.mp4$redirect-rule=noopmp4-1s`

Tentu saja, user masih bisa terkena popup jika pas proses peralihan video user klik video tersebut (nomor 2.1), karena ini seperti klik url biasa.
