### ISSUE TITLE
carapedi.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1235]
**Jenis**
- Iklan
- Pop-up

**Sample URL**
https://cararegistrasi.com/Iyr0IaidU2

**Penjelasan Lebih Lanjut**
![Capture](https://user-images.githubusercontent.com/9379770/179786934-feb4655f-24eb-4ae7-a604-92d141ce8eec.PNG)

**Comment by realodix** [comment]
https://carapedi.id/Iyr0IaidU2
