### ISSUE TITLE
cnnindonesia.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1237]
**Jenis**
- Iklan

**Sample URL**
https://www.cnnindonesia.com/nasional/20210226153619-12-611379/dikira-maling-intel-polres-jakut-ditangkap-warga-tanah-abang

**Penjelasan Lebih Lanjut**
![Uploading Screenshot_2022-07-22-12-48-39-067_com.kiwibrowser.browser.jpg…]()

**Comment by realodix** [comment]
Sorry screenshotsnya gak keluar

**Comment by Recehan-Slayer** [comment]
![Screenshot_2022-07-22-12-48-39-067_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/180387068-38b4179b-3968-4978-89cf-564148f9db43.jpg)

**Comment by realodix** [comment]
@HazakuraID 

Bisa tolong paste **Troubleshooting Information** di sini?

Ada di halaman Support - > Troubleshooting Information

**Comment by realodix** [comment]
@HazakuraID Pakai uBlock Origin atau AdGuard di Kiwi Browser?

**Comment by realodix** [comment]
Di halaman Filter list, Ignore generic cosmetic filters sudah dipastikan tidak tercentang?
