### ISSUE TITLE
animekompi.web.id

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1240]
**Jenis**
- Terdapat safelink

**Sample URL**
http://animekompi.web.id/overlord-season-4-episode-4-subtitle-indonesia/

**Comment by realodix** [comment]
Safelinknya yang OneDrive bukan?

https://smkn1stg-my.sharepoint.com/:v:/g/personal/mslasvildz_smkn1sintang_sch_id/ESZHGLmYavxHrDAdTuroqHMBzRit2GvDyBZsEyxvmy06Mg?e=oiMUbl

**Comment by GrennKren** [comment]
Oh iya bener, works filter nya!

**Comment by realodix** [comment]
Thank you, sekarang Saya masukkan ke AdBlockID
