### ISSUE TITLE
neonime.org

### ISSUE THREAD

**Issue by KagaKouko99** [realodix/AdBlockID#125]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Lainnya

**Sample URL**
https://neonime.org/

**Penjelasan Lebih Lanjut**
Banner iklan haram

**Comment by KagaKouko99** [comment]
dibagian dalam jg ada
https://neonime.org/episode/beastars-1x12/

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
`https://neonime.org/episode/boku-no-hero-academia-season-4-4x22/`

banner judi

**Comment by realodix** [comment]
> https://neonime.org/episode/boku-no-hero-academia-season-4-4x22/
> 
> banner judi

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix iklan judi bro. gnti domain https://neonime.moe/

**Comment by realodix** [comment]
> 
> 
> iklan judi bro. gnti domain https://neonime.moe/

**Comment by Recehan-Slayer** [comment]
masi ada bro `https://bit.ly/2PFGKYv`

**Comment by realodix** [comment]
> 
> 
> masi ada bro `https://bit.ly/2PFGKYv` sama yg diatasnya chatango

Thank you
