### ISSUE TITLE
cnbcindonesia.com

### ISSUE THREAD

**Issue by YellowStar11** [realodix/AdBlockID#1250]
**Jenis*
- Anti-Adblock

**Sample URL**
https://cnbcindonesia.com/

**Penjelasan Lebih Lanjut**
- Video autoplay selalu muncul, apakah ini bisa dihapus?
![IMG_20220815_132246](https://user-images.githubusercontent.com/98148960/184586449-33d8c724-1f69-4833-9c7d-4597a9f0c084.jpg)

**Comment by realodix** [comment]
Link fullnya mana? Yang sesuai dengan screeshoot?

**Comment by YellowStar11** [comment]
> Link fullnya mana? Yang sesuai dengan screeshoot?
> 
> AdBlocker yang digunakan hanya bawaan dari Brave ya atau ada yang lain?

Saya menggunakan adblock default Brave browser

Link: https://www.cnbcindonesia.com/market/20220815091813-17-363707/kasus-pencuri-cokelat-hotman-paris-pastikan-bela-alfamart 

Hampir semua berita yg saya buka di CNBC Indonesia ada video autoplay di bawah

**Comment by realodix** [comment]
OK sekarang Saya paham

cnbcindonesia.com untuk menghapus video sudah ada di AdBlockID. Testing di uBlock Origin dan AdGuard, semua masih OK.

https://github.com/realodix/AdBlockID/blob/bacf3e8c5b87f6dd7ecf9fdccb9314f9af77f2dd/src/modules/annoyance.adfl#L97
https://github.com/realodix/AdBlockID/blob/bacf3e8c5b87f6dd7ecf9fdccb9314f9af77f2dd/src/modules/annoyance.adfl#L102

**Comment by YellowStar11** [comment]
> OK sekarang Saya paham
> 
> cnbcindonesia.com untuk menghapus video sudah ada di AdBlockID. Testing di uBlock Origin dan AdGuard, semua masih OK.
> 
> Sepertinya Brave belum mendukung syntax `:remove()`, dimana ini untuk benar2 mengahapus video dari halaman.
> 
> https://github.com/realodix/AdBlockID/blob/bacf3e8c5b87f6dd7ecf9fdccb9314f9af77f2dd/src/modules/annoyance.adfl#L97
> 
> 
> https://github.com/realodix/AdBlockID/blob/bacf3e8c5b87f6dd7ecf9fdccb9314f9af77f2dd/src/modules/annoyance.adfl#L102

saya kira bekerja di Brave browser, karena brave juga menggunakan filter uBO

**Comment by realodix** [comment]
> saya pikir juga bekerja di Brave browser, karena brave juga menggunakan filter uBO sbg filter default

Anda bisa melaporkannya langsung ke Brave
