### ISSUE TITLE
teknosimple.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1252]
**Jenis**
- Iklan
- Pop-up

**Sample URL**
https://teknosimple.com/dslC

**Penjelasan Lebih Lanjut**
fake download

**Comment by Recehan-Slayer** [comment]
ada popupnya bro pas click here to continue

**Comment by Recehan-Slayer** [comment]
countdown yg di halaman pertama bisa dipercepat ga bro?

**Comment by realodix** [comment]
> countdown yg di halaman pertama bisa dipercepat ga bro?

Bisa, sudah Saya masukkan
