### ISSUE TITLE
Make a version for Adguard Home / Pihole

### ISSUE THREAD

**Issue by xenstar** [realodix/AdBlockID#1253]
You should make a version, which can work with AdguardHome.

**Comment by realodix** [comment]
Until now, this has been very difficult to implement. I don't have enough knowledge and time to do it.

**Comment by xenstar** [comment]
That's okay. Your blocklist is already added with Hagezi - https://github.com/hagezi/dns-blocklists

So once you update your list, it will be automatically added with hagezi pro+ list, and we can add it in adguardhome.
