### ISSUE TITLE
huntersekai.download

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1254]
**Sample URL**
http://www.huntersekai.download/

**Penjelasan Lebih Lanjut**
chatango nya ga muncul

**Comment by Recehan-Slayer** [comment]
uBlock Origin: 1.44.0
Chromium: 104
filterset (summary): 
  network: 124895
  cosmetic: 131937
  scriptlet: 37384
  html: 0
listset (total-discarded, last updated): 
  removed: 
    IDN-0: null
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 9966-4, 22h.21m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 2855-6, 22h.21m
    adguard-annoyance: 56919-427, 22h.22m
    adguard-generic: 67248-796, 22h.22m
    adguard-spyware: 26679-1030, 22h.22m
    ublock-annoyances: 4553-196, 22h.21m
  default: 
    user-filters: 0-0, never
    easylist: 67008-1027, 22h.21m
    easyprivacy: 27444-9271, 22h.21m
    plowe-0: 3634-865, 22h.21m
    ublock-abuse: 76-0, 22h.21m
    ublock-badware: 4177-326, 22h.21m
    ublock-filters: 32457-3972, 22h.21m
    ublock-privacy: 241-36, 22h.21m
    ublock-quick-fixes: 403-16, 22h.21m
    ublock-unbreak: 1845-100, 22h.21m
    urlhaus-1: 6984-0, 22h.21m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 28246 ms (selfie)
  maxAssetCacheWait: 4644 ms

**Comment by realodix** [comment]
Saya coba menyamakan filter listnya, hasilnya kolom chatt tetap muncul

<details>
  <summary>Filter List</summary>
  
  ![Image 002](https://user-images.githubusercontent.com/1314456/187762384-a98adfa5-6629-4d3a-a94d-6a0e93cfd828.png)
</details>

<details>
  <summary>huntersekai.download</summary>
  
  ![Image 003](https://user-images.githubusercontent.com/1314456/187762438-7f016fe9-e71c-4c92-a202-f2408755596b.png)
</details>

**Comment by Recehan-Slayer** [comment]
iya keknya dr adblock openwrt pke filter ini bro adaway, adguard, oisd_full, reg_id
