### ISSUE TITLE
idntimes.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1255]
**Jenis**
- Iklan

**Sample URL**
https://www.idntimes.com/tech/gadget/agung-prasetya/power-supply-full-modular-untuk-para-gamers-c1c2?

**Penjelasan Lebih Lanjut**
![Screenshot_2022-09-01-04-59-57-178_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/187792857-2d995720-7e75-4a42-99d9-ac1173c47b6d.jpg)

**Comment by realodix** [comment]
> ![IMG_20220901_211339](https://user-images.githubusercontent.com/105591857/187936266-67895f7b-3288-45e3-af44-fe8ff6b4c7a7.jpg)
> 
> Hmm😏bug masih sama browser uBlock juga Saya digunakan pakai webShuttle code inspect element rules copy baru saja

Di uBlock Origin, tolong ke halaman Support -> Troubleshooting Information

Paste di sini, agar Saya bisa samakan

**Comment by realodix** [comment]
@HazakuraID Apakah di halaman Filter list, `Ignore generic cosmetic filters` sudah dipastikan tidak tercentang? Seperti screenshot di bawah.

<details>
  <summary>Screenshot</summary>
  
  ![Image 004](https://user-images.githubusercontent.com/1314456/187991311-67306c83-79d4-4c3a-aaf5-8dcb702738d9.png)
</details>
