### ISSUE TITLE
pintunow.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1256]
**Jenis**
- Terdapat safelink

**Sample URL**
https://bit.rancah.com/BeqDbgw

**Penjelasan Lebih Lanjut**
Percepat hitungan mundur

**Comment by Recehan-Slayer** [comment]
@realodix jadi bad request bro yg di halaman terakhir yg countdown pertama lancar

**Comment by realodix** [comment]
Waduh algoritmanya berubah, terpakasa Saya hapus.

Coba pakai ini `pintunow.com##+js(nano-sib, , ,0.8)`, mentok di angka `0.8` (lebih kecil lebih cepat), tapi kadang mereka naik ke angka `0.9`.

**Comment by Recehan-Slayer** [comment]
yg dihalaman terakhir di whitelist bisa g . boost nya yg dihalaman countdown pertama aja

**Comment by realodix** [comment]
> yg dihalaman terakhir di whitelist bisa g . boost nya yg dihalaman countdown pertama aja

Bisa, pakai ini

```
pintunow.com##+js(nano-sib)
go.pintunow.com#@#+js(nano-sib)
```
