### ISSUE TITLE
orami.co.id

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1262]
**Jenis**

**Sample URL**
https://www.google.com/amp/s/www.orami.co.id/magazine/amp/bahan-alami-mengatasi-ejakulasi-dini

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ... 
Terdapat iklan gambar yang tak bisa di blok

**Comment by realodix** [comment]
https://www.orami.co.id/magazine/amp/bahan-alami-mengatasi-ejakulasi-dini
