### ISSUE TITLE
LebahMovie (45.67.231.215)

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1263]
http://45.67.231.215/waktu21/

**Penjelasan Lebih Lanjut**
Video pada situs ini tidak dapat di putar
http://45.67.231.215/waktu21/

**Comment by realodix** [comment]
Halaman yang mana ya? Saya coba, video tetap dapat diputar dengan baik

http://45.67.231.215/thor-love-thunder-2022/

<details>
  <summary>Screenshot</summary>
  
  ![Image 005](https://user-images.githubusercontent.com/1314456/192045692-098f1745-45bf-4c86-86fa-2c5b73f9e55a.png)
</details>

**Comment by realodix** [comment]
Tidak ada tanggapan, Saya akan menutupnya.

Terima kasih sudah melapor
