### ISSUE TITLE
Anikor (62.182.85.146)

### ISSUE THREAD

**Issue by Lotlofia** [realodix/AdBlockID#1267]
https://62.182.85.146/series/house-of-the-dragon-2022/

**Comment by realodix** [comment]
Di Saya lancar saja kok, website bisa dibuka.

Sesuai dengan halaman depan AdBlockID, Saya tidak pernah mendeskripsikan AdBlockID dapat membuka website yang terblokir aksesnya.

**Comment by 3xploiton3** [comment]
banyak ads

![image](https://user-images.githubusercontent.com/19517680/197223151-bd4c977e-a11f-4537-82b8-2c64b37c7ed6.png)

**Comment by fgt7** [comment]
Gabisa Diplay 
 - pas adblocknyala
![image](https://user-images.githubusercontent.com/104822944/197369535-e78e1920-87d8-4543-8b44-808cf2451640.png)

 - Adblock Mati
![image](https://user-images.githubusercontent.com/104822944/197369564-4e370370-9cd8-431c-bb30-70e4cd3a4340.png)

![image](https://user-images.githubusercontent.com/104822944/197369639-36e74baa-082d-4557-9353-e29e5d33bf18.png)
