### ISSUE TITLE
thebabelianchannel.site

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1271]
**Jenis**
- Iklan

**Sample URL**
https://thebabelianchannel.site/2022/10/announcement/pendant-event/super-dimension-sky-island-release-event/
https://id.modoomarblecodex.site/codex/pendant/sudim-sky-island

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by Recehan-Slayer** [comment]
anti select anti copy anti klik kanan

**Comment by realodix** [comment]
> anti select anti copy anti klik kanan

Sudah
