### ISSUE TITLE
Optimized filter request 

### ISSUE THREAD

**Issue by YellowStar11** [realodix/AdBlockID#1276]
Hallo,Bisakah filter AdBlockID dilakukan pengoptimalan? Filter AdblockID sangat bagus karena Sudah menjangkau website Indonesia tapi sayangnya tidak bisa di tambahkan ke filter regional di Brave Browser & Sudah dilakukan Review oleh FanboyNZ author Easylist & Brave engineer, untuk selengkapnya silahkan membaca-nya di forum ini mengapa AdblockID tidak bisa di tambahkan ke filter regional default Brave browser https://community.brave.com/t/request-add-new-regional-list-filter/428329/2

**Comment by realodix** [comment]
Saya coba tinjau dan optimalkan di https://github.com/realodix/AdBlockID/pull/1277

**Comment by realodix** [comment]
Update, Saya sudah mengoptimalkan dan membersihkan AdBlockID, tetapi masih belum Saya satukan ke dalam branch utama. Saya masih terus memantau apakah masih bisa optimalkan lagi atau tidak.

> Saya harap setelah filter ini dilakukan perbaikan bisa di tambahkan sebagai filter regional pengganti ABPIndo

Masalah utama selanjutnya adalah apakah AdBlockID cocok digunakan di adblock bawaan Brave Browser atau tidak? Saat ini AdBlockID hanya 100% compatible di uBlock Origin dan AdGuard. Saya akan mempelajari adblock bawaan Brave Browser.

----

Selanjutnya Saya akan menjawab beberapa point yang ada di https://community.brave.com/t/request-add-new-regional-list-filter/428329 dan memberikan jawaban apakah AdBlocID cocok digunakan di adblock bawaan Brave Browser.

**Comment by YellowStar11** [comment]
> Update, Saya sudah mengoptimalkan dan membersihkan AdBlockID, tetapi masih belum Saya satukan ke dalam branch utama. Saya masih terus memantau apakah masih bisa optimalkan lagi atau tidak.
> 
> > Saya harap setelah filter ini dilakukan perbaikan bisa di tambahkan sebagai filter regional pengganti ABPIndo
> 
> Masalah utama selanjutnya adalah apakah AdBlockID cocok digunakan di adblock bawaan Brave Browser atau tidak? Saat ini AdBlockID hanya 100% compatible di uBlock Origin dan AdGuard. Saya akan mempelajari adblock bawaan Brave Browser.
> 
> Selanjutnya Saya akan menjawab beberapa point yang ada di https://community.brave.com/t/request-add-new-regional-list-filter/428329 dan memberikan jawaban apakah AdBlocID cocok digunakan di adblock bawaan Brave Browser.

Saya rasa AdblockID cocok di Brave Browser karena Brave juga menggunakan filter Ublock sebagai filter Default https://github.com/brave/adblock-resources Bahkan filter regional Adguard juga tersedia default di Brave Browser

**Comment by realodix** [comment]
Saya sudah mempelajari Brave Shields, kesimpulannya Saya lebih menyarankan untuk hanya menggunakan AdBlockID di extensi uBlock Origin dan AdGuard.

Dari hasil uji coba, ada beberapa filter yang tidak mengeluarkan efek apapun di Brave Shields.


```AdBlock
kompas.com##div:matches-css-before(content: /Adv/)
kompas.com##.js-read-article .video-box-wrap:remove()
kompas.com##.js-read-article .rVideo-player:remove()
jurnalisindonesia.id##div:has(> .adsbygoogle)
onlinemetro.id##.code-block:has(.adsbygoogle)
```

- https://nasional.kompas.com/read/2022/10/12/18432021/minta-ktt-g20-lebih-digaungkan-jokowi-sehingga-geregetnya-betul-ada
- https://onlinemetro.id/medsos/cara-menonaktifkan-mode-terbatas-di-tiktok-matikan-pembatasan-konten-tiktok-dengan-ini/
- https://www.jurnalisindonesia.id/

Hasilnya seperti yang dijelaskan di screenshot

<details>
  <summary>Screenshot</summary>

![img](https://i.imgur.com/oA6zbPT.png)
![img](https://i.imgur.com/NwN2aA7.png)
![img](https://i.imgur.com/iACHiw7.png)
</details>

**Comment by realodix** [comment]
Saat ini AdBlockID sudah dioptimalkan dan dibersihkan.

> Remove as many generic filters as possible, and target just the regional sites. This would avoid redundancy with Easylist.

Setiap bulannya, Saya selalu membandingkan generic filter yang ada di AdBlockID ([/src/general-block.adfl](https://github.com/realodix/AdBlockID/blob/master/src/general-block.adfl), [/src/general-hide.adfl](https://github.com/realodix/AdBlockID/blob/master/src/general-hide.adfl)) dengan yang ada di easylist ([/easylist/easylist_general_block.txt](https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_block.txt), [/easylist/easylist_general_block_dimensions.txt](https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_block_dimensions.txt), [/easylist/easylist_general_hide.txt](https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_general_hide.txt)) di https://adblockplus.org/redundancy_check

Jika ditemukan ada yang sama, maka akan dihapus
