### ISSUE TITLE
manhwaindo.me

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#1279]
> **Jenis**
> - Iklan
> 
> **Sample URL**
> https://komikdewasa.me/ & https://manhwaindo.me
> 
> 
> **Penjelasan Lebih Lanjut**
> - Terdapat iklan judi CNN Slot di dua website tersebut

_Originally posted by @YellowStar11 in https://github.com/realodix/AdBlockID/issues/1278#issue-1404014034_

**Comment by 3xploitzer0** [comment]
> > **Jenis**
> > 
> > * Iklan
> > 
> > **Sample URL**
> > https://komikdewasa.me/ & https://manhwaindo.me
> > **Penjelasan Lebih Lanjut**
> > 
> > * Terdapat iklan judi CNN Slot di dua website tersebut
> 
> _Originally posted by @YellowStar11 in [#1278 (comment)](https://github.com/realodix/AdBlockID/issues/1278#issue-1404014034)_

https://manhwaindo.me/komik-manhwa-fathers-lust-chapter-83/

muncul pop up
