### ISSUE TITLE
noyads.net [Pop-up ads]

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#128]
**Jenis iklan** (hapus yang tidak perlu)

- Pop-up

**Sample URL**
https://noyads.net/RkiflI

**Penjelasan Lebih Lanjut**
Popups

**Comment by realodix** [comment]
Saya buka https://noyads.net/RkiflI, mereka langsung mengarahkan ke https://higud.com/RkiflI.

Sebenarnya untuk higud.com pada uBlock tidak ada masalah, baru saja gue hapus scripletnya di https://github.com/realodix/AdBlockID/commit/e3a7a9d0f47210b5e456a188cb1da46a79e859a5 karena sudah ada di uBlock Filter.

```js
<script>
  $(document).on("click", ".btn", function(){
      window.open("https://apeka.me/download.php")
  })
  $(document).on("click", ".klikdisini", function(){
      window.open("https://yim3eyv5.top/i6d40dp6?key=f5db31bbebc2e21d6f4158644aa755a3")
  })
</script>
```



Karena mereka menggunakan JS yg ditulis dengan inline script, maka untuk selain uBlock gue cegah secara manual.
