### ISSUE TITLE
komikcast.site

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1281]
**Jenis**
- Pop-up

**Sample URL**
https://komikcast.site/

**Penjelasan Lebih Lanjut**
Memang berupa domain baru dari dari **komikcast.com** ataupun **komikcast.me** . Tapi kurasa popup nya ini baru scriptnya.

**Comment by GrennKren** [comment]
Msh ada popup ke `https://ultima7.移动`

**Comment by realodix** [comment]
> Msh ada popup ke `https://ultima7.移动`

Sudah hari ke-2, Saya masih tidak menemukan pop-up
