### ISSUE TITLE
mojok.co

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1287]
![image](https://user-images.githubusercontent.com/19517680/199646593-4e14d3ea-4b90-4fb7-8a1c-e4399ac503ed.png)

https://mojok.co/susul/goyanglidah/soto-pak-paiman-kulon-progo-laris-setelah-pindah-ke-pinggiran-kota/2/

**Comment by realodix** [comment]
Ini bukan bug, tapi memang mereka menetapkan tingginya seperti itu. Saya juga telah mencoba dengan mematikan AdBlockID.

<details>
  <summary>Screenshot</summary>
  
  ![Image 007](https://user-images.githubusercontent.com/1314456/199812213-c494e4ff-4c58-477d-a0e8-1d1c088cb4f5.png)
</details>
