### ISSUE TITLE
icutlink.com - annoying notification

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#129]
**Jenis iklan** (hapus yang tidak perlu)
- Annoying notification

**Sample URL**
- https://icutlink.com/etxQ4MWywp
- https://icutlink.com/stmauX8nnp

**Penjelasan Lebih Lanjut**
Lanjutan dari issue yang dibuat oleh @WaferNabati pada https://github.com/realodix/AdBlockID/issues/65

**Comment by realodix** [comment]
Harusnya sih sudah selesai ya di sini

**uBlock**
`https://github.com/uBlockOrigin/uAssets/issues/3979`

**AdGuard**
`https://github.com/AdguardTeam/AdguardFilters/issues/42158`

**Comment by WaferNabati** [comment]
@realodix  masih ada tetep
![z4](https://user-images.githubusercontent.com/9379770/71612774-2363e880-2bd5-11ea-82d7-d061755440cd.png)

**Comment by realodix** [comment]
@okiehsch annoying notification always appear when we refresh the page
