### ISSUE TITLE
animekompi.net

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1290]
**Jenis**
- Terdapat safelink

**Sample URL**
https://animekompi.net/fuufu-ijou-koibito-miman-episode-05-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
- Terdapat safelink di tiap download ... 
- `go.menjelajahi.com`

**Comment by realodix** [comment]
Saya sudah mematikan JavaScript dan hasilnya tetap mengarah ke https://go.menjelajahi.com.

Jika seperti ini, maka tidak ada yang dapat dilakukan
