### ISSUE TITLE
Kompas.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1294]
https://otomotif.kompas.com/read/2022/11/11/062200115/pengemudi-bus-jelaskan-betapa-lihai-para-pencopet-di-kabin

![Screenshot_20221113-071251_Kiwi Browser](https://user-images.githubusercontent.com/19517680/201499626-1c565f3b-66f7-48fb-a1cd-0b5cb0f10daf.png)

**Comment by realodix** [comment]
Saya tidak menemukannya

![Image 003](https://user-images.githubusercontent.com/1314456/201542003-3dbf635c-f4b5-4dbb-a964-78259a1f5f50.png)
