### ISSUE TITLE
sangetods.net

### ISSUE THREAD

**Issue by fgt7** [realodix/AdBlockID#1295]
**Jenis**

- Anti-Adblock

**Sample URL**
sangetods.net

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ... 

![image](https://user-images.githubusercontent.com/104822944/202345982-f4a3ffb0-156e-43cf-8c84-b1570ae8c79b.png)

**Comment by realodix** [comment]
Sudah 4 hari, di saya aman aja..

<details>
  <summary>Screenshot</summary>
  
  ![Image 001](https://user-images.githubusercontent.com/1314456/202922132-cbd6f657-a80c-49b6-924c-e0c4d8a5924a.png)
</details>

**Comment by fgt7** [comment]
hmm sepertinya karna extensi `DuckDuckGo Privacy Essentials` mungkin karna bentrok atau apalah 



<details>
  <summary>Screenshot</summary>
 
![firefox_XzHKADzN1j](https://user-images.githubusercontent.com/104822944/203308845-41d3f95b-7fc2-4e0b-85ee-0b01e7f42eb7.gif)
  
</details>
