### ISSUE TITLE
dramamu.net

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#130]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
- https://dramamu.net/

**Penjelasan Lebih Lanjut**
- Empty overlay ads
- Extract dari issue https://github.com/realodix/AdBlockID/issues/127

**Comment by realodix** [comment]
Thank you @WaferNabati

**Comment by WaferNabati** [comment]
@realodix http://lk21.onl/
itu jg ada ads placeholdernya yg tersisa ga gan soalnya jg transparan
