### ISSUE TITLE
cnnindonesia.com

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1301]
**Jenis**
 Iklan

**Sample URL**
https://www.cnnindonesia.com/teknologi

**Penjelasan Lebih Lanjut**
- Terdapat Placeholder iklan di halaman cnnindonesia.com (kanan warna abu abu)
![Screenshot from 2022-11-27 22-10-32](https://user-images.githubusercontent.com/68702583/204142875-e2768d1a-02cd-4368-b91a-87941c29654b.png)

**Comment by realodix** [comment]
Di Saya aman, tidak ada masalah.

Bisa lebih spesifik?

<details>
  <summary>Screenshot</summary>
  
  ![Image 003](https://user-images.githubusercontent.com/1314456/204150247-f9b0a5e4-3e6d-4c37-931f-9de3c9f3cbc5.png)
</details>

**Comment by Reno-Sifana** [comment]
Ooh. Tadi saya lihat seperti ada kotak abu abu di kanan kirain iklan. Ya sudah. Ntar kalau saya nemu iklan di website lain saya akan kasih info. 😁

**Comment by realodix** [comment]
> Ooh. Tadi saya lihat seperti ada kotak abu abu di kanan kirain iklan.

Kotak abu-abu yang ada di kanan itu kita menyebutnya dengan empty ads placeholder, wadah iklan yang masih muncul ketika iklannya dihilangkan. Kita juga menghapus itu, tapi sayangnya pada issue ini Saya tidak menemukannya.
