### ISSUE TITLE
nooblasto.com

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1306]
**Jenis**
 Iklan

**Sample URL**
https://www.nooblasto.com/merk-speaker-bluetooth/ & https://www.nooblasto.com/rekomendasi-speaker-logitech-rgb/
![Screenshot from 2022-12-05 11-09-53](https://user-images.githubusercontent.com/68702583/205548258-0adc9f6f-083b-4e23-b9fb-5b1f7d41bc25.png)

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Ini sudah pernah ditangani di https://github.com/realodix/AdBlockID/issues/1298, hasilnya filternya masih bekerja dengan baik

<details>
  <summary>Screenshot</summary>
  
  ![Image 003](https://user-images.githubusercontent.com/1314456/205620507-a702a2cf-ef9a-4053-a999-dbb0b35edfbf.png)
</details>

**Comment by realodix** [comment]
Di sisi Anda, terlihat seperti filter cosmetic yang tidak berfungsi

**Comment by Reno-Sifana** [comment]
nggak saya centang **"Ignore Generic Cosmetic Filter"** masih bawaan setelan UBlock Origin 
![Screenshot from 2022-12-05 18-14-10](https://user-images.githubusercontent.com/68702583/205624585-35bea141-d4a5-4ec8-b685-1513ea35a74f.png)

**Comment by realodix** [comment]
`Ignore generic cosmetic filters` memang jangan dicentang, jika dicentang maka filter `generic cosmetic` tidak akan bekerja.

Sebagai info, ada 2 jenis filter cosmetic
1. Generic, contoh `##.iklan` semua situs kena
2. Spesifik, contoh `domain.com##.iklan` hanya domain.com yang kena

**Comment by realodix** [comment]
Untuk nooblasto.com, seperti yang bisa Anda lihat di screenshot Saya menggunakan spesifik, maka Saya simpulkan filter cosmetic (generic dan spesifik) tidak bekerja.

Pastikan filter cosmetic tidak ter-disable, kurang lebih seperti ini

![Image 004](https://user-images.githubusercontent.com/1314456/205643360-3ff24e34-4fb2-4884-b57f-90134bc0f485.png)

![Image 005](https://user-images.githubusercontent.com/1314456/205643398-73da99c5-03cd-4a23-a08c-3704b397e9a5.png)
