### ISSUE TITLE
OPLOVERZ.asia 

### ISSUE THREAD

**Issue by aszksbdje** [realodix/AdBlockID#1307]
Lapor penemuan iklan. 
Oploverz.asia tapi redirect ke https://15.235.11.45/
![2022-12-11_083454](https://user-images.githubusercontent.com/16359705/206882411-94b0d74a-fa53-44aa-8220-20c49ccd3994.png)

**Comment by realodix** [comment]
Mohon update AdBlockID, kemarin https://15.235.11.45/ sudah dimasukkan di https://github.com/realodix/AdBlockID/commit/9a0cf99647a0776bc1c053c918f1369936fc9de9#diff-0b4d08fe1d5c3887fece741abb1ba0802ec8a807b28584114424463ce0803c0a

**Info**
Interval update otomatis sekitar 4 hari sekali, tetapi Anda dapat melakukan force update dengan menekan tombol jam, lalu tekan update now.

![Image 002](https://user-images.githubusercontent.com/1314456/206887381-9c624bc9-fc50-478b-bb8e-0583dfda3582.png)

**Comment by aszksbdje** [comment]
Terima kasih infonya...

Hanya penasaran, jadi sistem adblok blokir alamat ya (bukan iklan). Jadi kalau alamat ganti, realodix harus submit lagi alamat yang baru gitu ya ? ..

**Comment by realodix** [comment]
Pada dasarnya dapat melakukan 4 cara, tergantung kebutuhannya.

1. Generic block - Blokir iklan disemua website, contoh [src/general-block.adfl](https://github.com/realodix/AdBlockID/blob/master/src/general-block.adfl)
2. Generic hide - Sembunyikan iklan di semua website, contoh [src/general-hide.adfl](https://github.com/realodix/AdBlockID/blob/master/src/general-hide.adfl)
3. Specific block - Blokir iklan hanya di website yang dicantumkan saja, contoh [src/specific-block.adfl](https://github.com/realodix/AdBlockID/blob/master/src/specific-block.adfl)
4. Specific hide - Sembunyikan iklan hanya di website yang dicantumkan saja, contoh [src/specific-hide.adfl](https://github.com/realodix/AdBlockID/blob/master/src/specific-hide.adfl)

List di atas Saya urutkan berdasarkan prioritasnya, jadi untuk pertama akan ditambahkan filter point 1, jika point 1 masih muncul iklan, maka akan ditambahkan filter point 2 dan seterusnya hingga iklan benar2 hilang.

Sebagai contoh untuk Oploverz, ketika Saya pertama kali membukanya Saya melihat filter generic block (point 1) sudah ada (dan tidak ada yang bisa ditambahkan lagi), lalu Saya menambahkan filter generic hide (point 2) dan ternyata masih belum bersih juga, maka Saya menambahkan filter specific.

Jika ada pertanyaan lain, jangan sungkan..
