### ISSUE TITLE
avtub.re

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1308]
**Sample URL**
https://example.com/

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ... di ublock origin 
Tidak dapat memblokir iklan gambar animasi ,seperti di bawah ini![20221212_102344_rmscr.jpg](https://user-images.githubusercontent.com/114223791/206954291-a02e3c7d-20e2-4cdb-adc5-6cb1eb64a911.jpg)

**Comment by realodix** [comment]
Di Saya aman saja, tidak ada iklan.

Di Halaman filterlist, `Ignore generic cosmetic filters` sudah dipastikan tidak tercentang?
