### ISSUE TITLE
jalantikus.com

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1309]
**Jenis**
 iklan

**Sample URL**
https://jalantikus.com/tips/kelebihan-browser-firefox-focus/

**Penjelasan Lebih Lanjut**
- Terdapat iklan higgs domino RP di halaman jalantikus.com 
![Screenshot from 2022-12-15 10-09-21](https://user-images.githubusercontent.com/68702583/207770816-12a58d97-1f73-42f3-b5ff-31d73616991c.png)

**Comment by realodix** [comment]
Di Saya bersih

Config: Pengaturan standart uBlock Origin + AdBlockID

![Image 003](https://user-images.githubusercontent.com/1314456/207776848-7b7516ee-1d32-4dd6-b21f-d70961846230.png)

**Comment by Reno-Sifana** [comment]
walah pantesan. setelah saya coba reset pengaturan UBlock Origin dan coba add 2 filter ternyata bisa
![Screenshot from 2022-12-15 14-30-04](https://user-images.githubusercontent.com/68702583/207799847-1deec5a9-64cb-4bf6-8e16-9d684c102164.png)
(sebelumnya cuma AdBlockID Plus saja) pantesan tembus iklannya wkwkwk
