### ISSUE TITLE
Maxmovie21 (45.129.230.103)

### ISSUE THREAD

**Issue by fgt7** [realodix/AdBlockID#1313]
**Jenis**
- Iklan

**Sample URL**
45.129.230.103

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Ini apa ya, di Saya bersih.. Bisa tambahkan screenshot iklannya di bagian mana?

<details>
  <summary>Screenshot</summary>
  
  ![noname-crop](https://user-images.githubusercontent.com/1314456/208358333-c42f44b6-bda5-417b-bbe5-cb11fcd53fe2.png)
</details>

<details>
  <summary>Screenshot 2</summary>
  
  ![noname-crop-2](https://user-images.githubusercontent.com/1314456/208358350-afe8dd40-2ea4-4189-9708-8e5e7a68ba7c.png)
</details>

**Comment by fgt7** [comment]
disaya masih ada
<details>
  <summary>Screenshot</summary>

![firefox_uEELQBaKu5](https://user-images.githubusercontent.com/104822944/208392657-102047b4-c1c8-48b8-8749-0d1d86253312.png)


</details>

**Comment by realodix** [comment]
Saya lihat iklan yg ditampilkan seperti AdBlockID tidak memberikan efek apapun..

Ini pakai AdBlockID atau AdBlockID Plus?
Filter apa saja yg digunakan? Saya akan menyamakan settingan Anda dan menyelidikinya

**Comment by fgt7** [comment]
<details>
  <summary>Screenshot</summary>

![firefox_nhqp4teJuc](https://user-images.githubusercontent.com/104822944/208568693-fc4950bb-518a-4337-9d4f-ba0541da4854.gif)


</details>

```
uBlock Origin: 1.45.2
Firefox: 108
filterset (summary): 
  network: 122303
  cosmetic: 0
  scriptlet: 23821
  html: 888
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 684-8, 17h.2m
    https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2046-74, 17h.2m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7745-3958, 17h.2m
    adguard-spyware-url: 862-152, 16h.53m
    curben-phishing: 22558-1, 17h.2m
    curben-pup: 190-0, 17h.2m
    adguard-annoyance: 62279-54823, 17h.2m
    ublock-annoyances: 4821-1332, 17h.2m
    IDN-0: 5396-1596, 16h.54m
    KOR-1: 3946-2802, 17h.2m
  default: 
    user-filters: 2-0, never
    ublock-filters: 32321-8613, 17h.3m
    ublock-badware: 4211-648, 17h.2m
    ublock-privacy: 301-12, 17h.2m
    ublock-abuse: 77-1, 17h.2m
    ublock-unbreak: 1931-255, 17h.2m
    ublock-quick-fixes: 492-176, 17h.2m
    easylist: 61519-30197, 17h.2m
    easyprivacy: 31006-1750, 17h.2m
    urlhaus-1: 7524-0, 17h.2m
    plowe-0: 3671-3, 17h.2m
filterset (user): [array of 2 redacted]
trustedset: 
  added: [array of 18 redacted]
modifiedUserSettings: 
  parseAllABPHideFilters: false
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3048 ms (selfie)
  maxAssetCacheWait: 2384 ms

```

**Comment by realodix** [comment]
Mohon centang `Parse and enforce cosmetic filters`

**Comment by fgt7** [comment]
Oke done. trimakasih
