### ISSUE TITLE
htmlgames.com

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [realodix/AdBlockID#1316]
**Jenis**
Adblock Detected, Game Jadi Lambat Loading

**Sample URL**
Iframe: https://cdn.htmlgames.com/SealifePuzzle/index.html
Sumber: https://www.roundgames.net/match-3-games/sealife-puzzle/

**Penjelasan Lebih Lanjut**
Nemu Di Iframe
![image](https://user-images.githubusercontent.com/78845241/210077190-95d5af46-bb36-4ae7-adce-b1ba24b63e41.png)

Filter List: 
![image](https://user-images.githubusercontent.com/78845241/210077108-4dd692ce-093c-4c53-8967-8713e2b439c2.png)

**Comment by realodix** [comment]
Maaf ini situs internasional atau tidak berbahasa indonesia
