### ISSUE TITLE
avtub.io

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1320]
**Jenis**
<!--
- Iklan
- Pop-up
- 
-
-
-

**Sample URL**
Avtub.io

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ... 
Terdapat pop up banner yang menutupi layar setelah salah satu vidio di putar beberapa menit
Bisa di blok dengan adblockid dan abpindo
Di adguard tapi layar jadi hitam
Karena banner ada 2 yang terblokir cuma satu
![20230111_101343_rmscr](https://user-images.githubusercontent.com/114223791/211711936-09e2c024-53e2-4a62-ad94-a6c775de7a3a.jpg)

**Comment by Jokopentil** [comment]
Maaf bang sepertinya masih tetap hitam layarnya![20230111_102730_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212080716-ba0d274c-2115-4360-9127-12004b4114b8.jpg)
Tapi menggunakan brave browser bisa
Tapi vidio erorr code

**Comment by Jokopentil** [comment]
Maaf bang sepertinya masih tetap hitam layarnya![20230111_102730_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212080716-ba0d274c-2115-4360-9127-12004b4114b8.jpg)
Tapi menggunakan brave browser bisa
Tapi vidio erorr code![20230112_202919_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212081731-ca9f923c-da63-4d27-9ae5-909f25d105ee.jpg)

**Comment by Jokopentil** [comment]
![20230112_185851_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212081849-330c1d9e-6233-48fc-9c81-84c9385c1693.jpg)

**Comment by Jokopentil** [comment]
![20230112_204733_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212083490-ff0bc41d-6db5-4746-ba8a-c77d73578c36.jpg)

**Comment by Jokopentil** [comment]
![20230112_204733_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212083695-a811c13f-8d9f-4047-8125-d0113310ce7a.jpg)

**Comment by realodix** [comment]
Di Saya tidak ada masalah, seperti di screenshot yang Saya berikan

<details>
  <summary>Screenshot - uBlock Origin - Kiwi Browser</summary>
  
  ![Screenshot 2023-01-13 at 03-43-57 AVTub - Video BOKEPXXI Terbaru](https://user-images.githubusercontent.com/1314456/212179201-169557a1-4356-4a92-8b3b-a47240df5e81.png)
</details>

**Comment by realodix** [comment]
> Maaf bang sepertinya masih tetap hitam layarnya
><details>
>  <summary>Screenshot</summary>
> 
>  ![20230111_102730_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212080716-ba0d274c-2115-4360-9127-12004b4114b8.jpg)
> </details>

Ini pakai browser dan adblocker apa ya? Tanda shield di samping kiri alamat web terlihat seperti bukan uBlock Origin atau AdGuard..

---

> Tapi menggunakan brave browser bisa
> Tapi vidio erorr code

Brave browser Saya sudah coba, AdBlocKID **tidak berfungsi secara utuh** dan video dapat diputar.

Btw seperti yang telah Saya sampaikan di halaman depan, Saya hanya menyarankan pemasangan AdBlockID di uBlock Origin dan AdGuard. Produk ad blocker lainnya seperti adblock plus, brave browser shields, dan produk lainnya tidak Saya dukung

terima kasih 😄

**Comment by Jokopentil** [comment]
Pakai  ubloc aja pakai blok elemen
Browser yandex android
Nanti tetap muncul layar hitam tapi bisa di klik tanda x dan vidio tetap bisa di putar

**Comment by realodix** [comment]
> Pakai ubloc aja pakai blok elemen 
> Browser yandex android
> Nanti tetap muncul layar hitam tapi bisa di klik tanda x dan vidio tetap bisa di putar

Yandex Browser Android? Bagaimana cara menambahkan extensi uBlock Origin / AdGuard ke Yandex Browser Android?

**Comment by Jokopentil** [comment]
Pakai ublock origin developer build
Ada di chrome store
Dan saya telah menemukan solusi untuk
Situs ini
Pakai adguard versi apk vpn mod![20230113_165320_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212290938-ff5bd1ad-167e-4e3b-a7a0-71a4a27eff51.jpg)

**Comment by Jokopentil** [comment]
Untuk adguard di yandex bisa pakai
Adguard beta chrome
Ad chrome store

**Comment by Jokopentil** [comment]
![20230113_170737_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212293988-4b767346-3a7e-42e4-bd96-4874b0397441.jpg)
Disitu linknya klo pengen download
Link tulisan biru

**Comment by Jokopentil** [comment]
![20230113_170724_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212294234-4aec1354-f50a-4b93-903e-b9a553caf0e4.jpg)

**Comment by realodix** [comment]
Saya sudah mencobanya di Yandex dan uBlockOrigin Development Build, hasilnya aman seperti di SS yang Saya sertakan 

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2023-01-14-00-29-12-059_com yandex browser](https://user-images.githubusercontent.com/1314456/212381965-ce736812-4bfb-4bb3-89ee-093c937bce64.jpg)
</details>

**Comment by Jokopentil** [comment]
Mmungkin di refresh dulu kali ya filternya baru di coba lagi
Tapi klo tetep tak bisa ya pa boleh buat
Saya jadi tertantang untuk bisa mengatasi
Sebab saya paling benci dengan iklan judi
Apa mungkin ya pengaruh dari filter abpindo
Yg katanya blokir iklan judi😏😏😏

**Comment by Jokopentil** [comment]
Bisa kirim ulang ss nya
Apakah harus di tambahka ke daftar filter saya?🙏

**Comment by realodix** [comment]
https://user-images.githubusercontent.com/1314456/212468727-26c045cc-708a-4cf5-a598-517e91e17f38.mp4

**Comment by Jokopentil** [comment]
Bisa kirim ulang ss nya
Apakah harus di tambahka ke daftar filter saya?🙏
![20230114_173327_rmscr.jpg](https://user-images.githubusercontent.com/114223791/212469987-ea9d81d5-9989-49dd-b678-9d598bb4b593.jpg)
Cara blok tanda x hitam
Itu klo gk di klik gk hilang layar hitamnya
Ya saya coba dulu ya cara agan
Nanti klo gk berhasil , ya gk pa2 klik manual saja
Oya itu yandex versi yg lama ya?
Kok tanda gembok yang di bawah bisa terbuka
Trimakasi atas tanggapan dan responnya
Dari saya client
Mohon maaf jika agak merepotkan

**Comment by Jokopentil** [comment]
Kayaknya udah ketemu penyebabnya
Klo yg saya buka itu avtub.se itu memang banyak pop up nya
Sedangkan yg agan buka itu mungkin avtub.re memang klo di buka situsnya sama
Tapi memang pop upnya susah di ilangi
🙏

**Comment by realodix** [comment]
AVTub sudah Saya update, mohon force update AdBlockID di sisi Anda 

> Kayaknya udah ketemu penyebabnya
> Klo yg saya buka itu avtub.se itu memang banyak pop up nya
> Sedangkan yg agan buka itu mungkin avtub.re memang klo di buka situsnya sama

Saya baru sadar, Anda melaporkan avtub.io, tapi yang Anda buka avtub.se, jadi ini inti permasalahannya. Kabar baiknya AdBlockID sudah saya update.

**Comment by realodix** [comment]
> Oya itu yandex versi yg lama ya?
> Kok tanda gembok yang di bawah bisa terbuka

Saya baru download Yandex, jadi seharunya versi terbaru. Tentang tanda gembok, Saya juga tidak paham, karena Saya bukan pengguna Yandex. Yandex Saya download khusus untuk menyamakan browser yang Anda gunakan, jadi Saya bisa melihatnya langsung.
