### ISSUE TITLE
bokepsin.me

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1322]
**Jenis**

**Sample URL**
https://bokepsin.me/bokep-indo-viral-4-bocah-gabut-di-kosan/

**Penjelasan Lebih Lanjut**
- Terdapat anti adblock saat vidio di putar / di klik
- menggunakan adguard dan ublock origin
![20230111_112038_rmscr](https://user-images.githubusercontent.com/114223791/211731186-6dfc4324-1048-4b3a-a135-980d4754e0c7.jpg)

**Comment by realodix** [comment]
Saya sudah mencoba server SF, SB dan GD, hasilnya fine saja..

Saya coba di 2 browser
- Kiwi browser + uBO
- Chrome + AdGuard Mobile

Itu server yang mana ya? Di gambar, browser dan adblock apa yang digunakan?

**Comment by Jokopentil** [comment]
Pakai kiwi
 Sudah pakai adguard dan ublock kok begitu

**Comment by Jokopentil** [comment]
server SF, SB dan GD, 
Itu maksudnya server apa itu ya

**Comment by Jokopentil** [comment]
Itu coba link yang diatas
Tidak semua vidio yang ada di situs itu ada anti adblock
Yang ada contohnya yg ada di link di atas

**Comment by realodix** [comment]
> Pakai kiwi 
> Sudah pakai adguard dan ublock kok begitu
> Itu coba link yang diatas 
> Tidak semua vidio yang ada di situs itu ada anti adblock
> Yang ada contohnya yg ada di link di atas

Saya tidak mengerti, Saya coba hasilnya fine saja

Ping @3xploiton3, Mohon bantuannya, apakah di Anda juga muncul peringatan anti-adblock?

> server SF, SB dan GD, 
> Itu maksudnya server apa itu ya

Di SS yang Anda berikan, itukan ada 3 server untuk play video
Server (SF), Server (SB) dan Server (GD)

**Comment by 3xploiton3** [comment]
Ya ada anti adblock seperti di ss

**Comment by realodix** [comment]
Popup saya berhasil menemukannya dan sudah diatasi..

Untuk peringatan anti adblocker, Sayangnya walaupun Saya sudah mencoba di berbagai browser termasuk di HP, Saya tidak berhasil menemukannya.
