### ISSUE TITLE
gramedia.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1324]
![image](https://user-images.githubusercontent.com/19517680/213249952-aeb4579d-195f-4573-bf7d-0ff92199eee2.png)

https://www.gramedia.com/best-seller/penyedia-hosting-vps/

**Comment by realodix** [comment]
Self ads, ini seharusnya tidak boleh dihilangkan dan jika tidak sengaja hilang harus dikembalikan.

Jika Anda mau, bisa gunakan ini

```
gramedia.com##.entry-content .grame-pickofthemonth
gramedia.com##.entry-content .grame-bukuterbaru
```
