### ISSUE TITLE
mangaip.com - Mengapa ada di AdBlockID

### ISSUE THREAD

**Issue by mangaip** [realodix/AdBlockID#1326]
Bagaimana menghapus url web/blog dari list adblock, soalnya ada blog saya yang masuk list adblock.

**Comment by fgt7** [comment]
mungkin langsung taruh linknya, supaya dihapus dari list / bisa Fork repoini trs nanti tinggal diPr

**Comment by realodix** [comment]
> Bagaimana menghapus url web/blog dari list adblock, soalnya ada blog saya yang masuk list adblock.

Apa URLnya yang tidak sengaja masuk ke AdBlockID, agar segera bisa Saya tindak lanjuti

**Comment by mangaip** [comment]
wah saya kurang tau siapa yang masukan ke list adblock.

Ini kak url-nya: mangaip.com

**Comment by realodix** [comment]
Halaman yang mana ya yg rusak karena AdBlockID? Saya sudah coba buka berbagai halaman, sepertinya tidak ada yang rusak

**Comment by mangaip** [comment]
Tidak ada yang rusak seh kak, cuma kok bisa url saya masuk ke list adblock? Padahal saya belum pernah memasukan url tersebut ke AdBlockID.

Ya kalau tidak ada imbasnya bagi blog saya, tidak apa² kak, tidak dihapus juga.

**Comment by realodix** [comment]
> Tidak ada yang rusak seh kak, cuma kok bisa url saya masuk ke list adblock? Padahal saya belum pernah memasukan url tersebut ke AdBlockID.

Saya yang memasukkannya kak, atas rekomendasi dari kontributor sekitar 15 bulan yang lalu. Jika terjadi kerusakan tampilan karena AdBlockID atau ada rekomendasi situs yang ingin dimasukkan ke AdBlockID, mohon laporkan ya kak

![noname](https://user-images.githubusercontent.com/1314456/215299000-6e56b11c-e0b1-472a-9276-69e015382998.png)
