### ISSUE TITLE
mkvking.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#133]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://mkvking.com/?c17421bdaf=RnBaUkQwM09hVE5nSUswc3I4TGtKS1lqcHduUGlzeTBLV2ZCb1VwQ3FTbzYrZ3BraXdqYWhzZDYvckN6S1lCSWExNEJkWExWSFV3OE9uakhUNHNYdVlKSC9GbWVHaXBXU0JPYzErcm9FVVE9

**Source link**
https://mkvking.com/knives-out-2019/

**Penjelasan Lebih Lanjut**
Tempat iklan menutupi generate link

**Comment by realodix** [comment]
> **Sample URL**
> https://mkvking.com/?c17421bdaf=RnBaUkQwM09hVE5nSUswc3I4TGtKS1lqcHduUGlzeTBLV2ZCb1VwQ3FTbzYrZ3BraXdqYWhzZDYvckN6S1lCSWExNEJkWExWSFV3OE9uakhUNHNYdVlKSC9GbWVHaXBXU0JPYzErcm9FVVE9

Ini mengarah ke [https://space.tribuntekno.com/?id=OFN...1llT3c9](https://space.tribuntekno.com/?id=OFNJVTFWcjZDa2M3dzZ4VkI3U2FMKzZmVzhlellLcVlPeE9aVHBTUHJGbjRITG5idXhsQmxpLzJETlhObGQ1WjdtQnZhM2xFdW1JdXppZ0gweFFlb1hFYmI5LzVxRWlYYXp0ZklvQ1llT3c9), jadi untuk tribuntekno.com Saya buat issue baru.

Untuk issue ini sendiri Saya fokus ngilangin iklan yang ada di mkvking.com, ada adserver yang Saya temukan.
