### ISSUE TITLE
enfa.co.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1335]
https://www.enfa.co.id/

rusak

![image](https://user-images.githubusercontent.com/19517680/218325489-f567fb63-a96e-4585-a316-f0dfd4eceb13.png)

my filter
> uBlock Origin: 1.46.0
Chromium: 111
filterset (summary): 
  network: 132148
  cosmetic: 141291
  scriptlet: 25118
  html: 0
listset (total-discarded, last-updated): 
  removed: 
    plowe-0: null
  added: 
    https://filters.adtidy.org/extension/ublock/filters/3.txt: 36116-3076, 2d.9h.58m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7824-2, 2d.9h.58m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 59-4, 2d.9h.58m
    IDN-0: 5435-357, 2d.9h.58m
    RUS-0: 39298-205, 4h
    fanboy-annoyance: 84102-411, 2d.9h.58m
    fanboy-cookiemonster: 45451-45451, 2d.9h.58m
    ublock-annoyances: 4821-81, 2d.9h.58m
  default: 
    user-filters: 25-2, never
    easylist: 61412-105, 2d.9h.58m
    easyprivacy: 30943-12004, 2d.9h.58m
    ublock-abuse: 77-1, 2d.9h.58m
    ublock-badware: 4313-119, 2d.9h.58m
    ublock-filters: 32427-503, 2d.9h.58m
    ublock-privacy: 268-59, 2d.9h.58m
    ublock-quick-fixes: 442-118, 3h.59m
    ublock-unbreak: 1874-72, 2d.9h.58m
    urlhaus-1: 6351-0, 3h.58m
filterset (user): [array of 25 redacted]
trustedset: 
  added: [array of 34 redacted]
modifiedUserSettings: 
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 3379 ms (selfie)
  maxAssetCacheWait: 491 ms

**Comment by realodix** [comment]
Ini apa yang rusak ya? Karena tulisan ini tidak ada atau ada yang lainnya?

![Screenshot 2023-02-13 at 01-18-22 Home Enfa A Indonesia](https://user-images.githubusercontent.com/1314456/218329353-845f88aa-2a89-4ef1-8fe2-cee266f8ac7f.png)

**Comment by 3xploiton3** [comment]
> Ini apa yang rusak ya? Karena tulisan ini tidak ada atau ada yang lainnya?
> 
> ![Screenshot 2023-02-13 at 01-18-22 Home Enfa A Indonesia](https://user-images.githubusercontent.com/1314456/218329353-845f88aa-2a89-4ef1-8fe2-cee266f8ac7f.png)

ini klo ublock di disable muncul cookies, klo ublock di enable, website gak bisa berfungsi, atau tidak bisa di klik apa2

**Comment by realodix** [comment]
Dari list di atas, Saya lihat setidaknya ada 2 filter yang menyebabkan issue ini terjadi
- fanboy-annoyance
- fanboy-cookiemonster (di halaman filter list namanya EasyList Cookie)

**Comment by realodix** [comment]
Ini bisa diakali dengan menambahkan `enfa.co.id##.legal-alert-popup-overlay`

Saya bisa memasukkanya ke AdBlockID Plus, tapi sepertinya sayang juga karena enfa.co.id lebih ke situs perusahaan yang sepertinya jarang juga ada yang buka.

**Comment by 3xploiton3** [comment]
@ryanbr
