### ISSUE TITLE
movies21.co - Empty ads placeholders

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#134]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://movies21.co/
https://terbit21.online/
http://dunia21s.fun/
https://filmapik.bid/
https://movieon21.vip/
http://cinemaxx1.id/
https://dramamu.net/

**Penjelasan Lebih Lanjut**
close banner/overlay yg tersisa. sekalian bikinin general filter buat close banner/overlay bisa ga brow msh bnyak biasanya diweb" download streaming movies tombol close banner/overlay yg tersisa biar bersih ga mengganggu

**Comment by WaferNabati** [comment]
https://dramafilm21.com/
popups + close banner

**Comment by realodix** [comment]
> close banner/overlay yg tersisa. sekalian bikinin general filter buat close banner/overlay bisa ga brow msh bnyak biasanya diweb" download streaming movies tombol close banner/overlay yg tersisa biar bersih ga mengganggu

Bisa banget kalau namanya kurang lebih sama kaya di [/src/general_hide.adbl](https://github.com/realodix/AdBlockID/blob/master/src/general_hide.adbl) atau pada commit ini https://github.com/realodix/AdBlockID/commit/b2620f7702879256ed8bd1f1144e54775a8d169e
