### ISSUE TITLE
Movieku.cc / Oploverz.asia

### ISSUE THREAD

**Issue by acgl** [realodix/AdBlockID#1357]
**Jenis**

**Sample URL**
https://movieku.cc/
https://oploverz.asia/

**Penjelasan Lebih Lanjut**
- Waktu klik halaman muncul popup tap baru yang mengganggu seperti mengarahkan halaman ke playstore/web web shop ( Shopee/Lazada )

**Comment by realodix** [comment]
Movieku dan Oploverz sudah Saya buka, hasilnya:
- Link https://movieku.cc/ mengarah ke https://107.152.37.223/
- Link https://oploverz.asia/ mengarah ke https://oploverz.tv/

Semuanya sudah ada di AdBlockID, test dengan uBlock Origin di desktop hasilnya Saya tidak menemukan popup.

Saya butuh info lebih lanjut:
- Adblocker apa yang digunakan?
- Browser apa yang digunakan?
- HP atau Desktop?

Saya akan coba menyamakannya..

**Comment by acgl** [comment]
Kiwi Browser Extension uBO origin & 

Browser 1DM+
• EasyList, privacy , cookie
• uBo filter , privacy, Annoyance
• AdblockID, AdblockID Plus

2 browser itu kalo klik halaman website terutama movieku.cc otomastis ngebuka web baru

Contoh pada saat di halaman https://107.152.37.223/
Pada saat klik gambar di website/ movie yang ada. Yang harusnya mengarah ke https://107.152.37.223/series/chilling-adventures-of-sabrina-season-1/
Malah muncul tab baru yang mengarah ke https://anahitagirted.uno/ed/F3yDBDF1UsyAoJba*yMPDPhy1KIOg*7cOUqT49iA5KssdCKwBS3Z0eU5Ew8vjx6MSIrtPrZYdRLHxyTKykdlvT0sCx7necDusDVX4Fd0D*lOXDQsPOUnbGRWrVeZ4_Nw8AAy3TBVjF8V*EBqvEvl4zyzLdiPcIWm07ekfYm74yK*sSiwFqfqRTFsjeUCiovNgt6_VnajyjJup4TvwKLF4hHCVU6CnPEC0X01xnjAUaD6YvxUjG*53EzghW_8YK6zYFyV_kyPREFlE2xTauduSPI6_nm6L8aH3YteYLWkMaD9aAxraYIMiERheXeoUYwe9TlLjyoLBKn54Nx1fM6tpIZZ*Qp0w8ln4000_kCzWpEJwxpyNt0OMeh3LxUeBiauAKeP3Rzy_7R3xy2mWN5WFDjqd3CCYlp9mO2X_hZ0QwK3RSqVIKfMta4GGYcLgzvYVMxykWpCumDyvcgX9afexuXgmkchO2ta5mCed6318u62*9TwMM3urj3JIkfsTsqZlKF13Y*DAhkMf8BdAuigGyfaFiD0UsZEFYaTbW9nI27pnLo7qDGHV6vyawrZyL*m6rEhMZtpzPVawnArW4D8X0Q7zcJrrXRD3rIlsGRoGWgUL9Qa5fb_dduVGHfH76G0bc2G2xin3CnFi66riaxURLRKResEcjlt9xHBFZN9tHUeOZndPxIQWpRGIC9JyJOrH4SjtY8NJP7UxzpjPm0*4kF9rTt_nY6Nar6LjHUYN30?md=7JibioTMsICduJiOiEkIsICc0JiOiQXYiVHciwiIjJiO1MjNsICZioTLxwiIhJiOzYTN5wiIzJiOiMjMwgXN3AjIsIiYiojIzIDM4RTN4ICLiInI6ICa0RHczpzLvEDM34SM1IjLzcjLyIzMvICLiEnI6ICa0RHczpzLvEDM34SM1IjLzcjLyIzMv8zc9MVYiJXauFmIsICaiojM2gzNsICbiojIpRmIsICdioTL0IDMsIieiozNxEjMsIyaioTMsISdiojIiwiImJiOmFGbzVGLiUmI6ISbpVzdzs2Z0FXdywWMwJnIsIybiojZhx2clxiItJiOxYzN4cjN5QDO3kzNywiI3JiOiUyNCViMyQXa0xWZlIjMlMTQlIjMZ9WdlIDMzVWYyNGalRWJyAjZvJXJyAzUhJmcp5WYlIDMlczQlIDMN9mdpV2a1ViMyUiMDViMysWZ5d3byR2clIjMlMTQlUjQlUDRlIzQlIjM09Gc39mckNXJyITJzEUJ1IUJyIDd1RXdwVyMBRTJyITJyMUJyITarxWYuVyMBRTJyITJyMUJyIDZvdnbs9WYkVyMBJTJyITJyMUJyIzclFmcjhWJzEkMlIjMlIzQlIjMmlGb0VmclMTQyUiMyUiMDViMyIDMxgTLxATLyYTJzEkMlIjMlIzQlIjMj9mb0F2Y0VyMBJTJyITJyMUJyIDav1WZlMTQxUiMyUiMDViMyMXZylWZzVyMBFTJyITJyMUJyIDbpNHdlMTQxUiMyUiMDViMy8mbn9WaudWJzEUMlIjMlIzQlIjMhRmdh52YlRWJzEUMlIjMlIzQlIjMi92br1WYytWJzEUMlIjMlIzQlIjMslmbrVyMBFTJyITJyMUJyIjc1NXYrVyMBFTJyITJyMUJyITbvZXaltWdilmelMTQxUiMyUiMDViMyMWYyFWJzEUMlIjMlIzQlIjMiF2dhhWJzEUMlIjMlIzQlIjMlUzQlIjMzFmYylmbhVSNDViMyUyMBFTJyITJyMUJyITbvZXalNXJzEUMlIjMlIzQlIjMyAjMwUyMBFTJyITJyMUJyIjMwEDOlMTQxUiMyUiMDViMyIWYu5WZyVyMBVyMBFTJyITJyMUJyIDZtNWYlMTQxUiMyUiMDViMyYWYuNHchdWZlMTQxUiMyUiMDViMyM2bwlncpdGa0VyMBFTJyITJyMUJyITbvZXaltWdlMTQxUiMyUiMDViMyIXanhGdzVyMBFTJyITJyMUJyIjclNXZyZXZkVyMBFTJyITJyMUJyITYkZXZyRXazVmclMTQxUiMyUSNEVyNEJCLiAncioTMuUDLig2YioDNsIiYsJiOw4yN5wiI2ZnI6ISQS1kIsIidyJiOi0UYslWLUdjMwICLiE2YiojMsIyY0JiOiMWZsxWdsFmciwiIjVGdiojI0cmIsIyYkxWbio

**Comment by acgl** [comment]
Saya make kedua browser itu di Mobile

**Comment by realodix** [comment]
Saya tidak menemukan popup seperti yang Anda laporkan

Kiwi Browser, uBlock Origin (pengaturan default + AdBlockID)

https://user-images.githubusercontent.com/1314456/224905246-5e9c83dc-d5f6-4aa7-ae12-fcf0a0cba26c.mp4

**Comment by acgl** [comment]
Okedeh ntar coba saya update filternya, makasi udh bantu jawab, btw gimana cara Block link anahitagirted.com/Uno/dll

**Comment by realodix** [comment]
OK, Saya tutup ya issue ini, thank you

> btw gimana cara Block link anahitagirted.com/Uno/dll

Ada berbagai macam teknik:
- `||anahitagirted.com^$popup` untuk mecegah popup yang mengarah ke anahitagirted.com di situs apapun
- atau `107.152.37.223##+js(window.open-defuser)` untuk mecegah semua popup yang ada di https://107.152.37.223/

---

Saya mencoba buka https://107.152.37.223/ dengan kondisi adblocker dimatikan, hasilnya juga tidak ada popup


https://user-images.githubusercontent.com/1314456/224911971-f4d77b1a-f919-4e3c-b5eb-5c03696b1823.mp4

**Comment by acgl** [comment]
Makasi banyak yaa min? Info + ilmunya.
Ada solusi buat hilangin notif kayak gini ga ya

You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page.

**Comment by realodix** [comment]
> Ada solusi buat hilangin notif kayak gini ga ya
> 
> You are seeing this message because ad or script blocking software is interfering with this page. Disable any ad or script blocking software, then reload this page.

Waduh, Saya tidak bisa menjawabnya jika tidak membuka situsnya langsung. Karena ada berbagai macam solusi, dimana solusi tersebut mengikuti teknik yang mereka (situs target) gunakan. Ini seperti memilih obat, tergantung penyakitnya 😆 

Ini seperti pesan anti adblocker, bisa minta linknya gak? Nanti akan coba Saya buka

**Comment by acgl** [comment]
Apkmirror.com
Mediafire.com

2 doang sih sejauh ini
Saya make browsee 1DM/1DM+ Yang di playstore
Soalnya kalo di mobile gede banget notifnya

**Comment by realodix** [comment]
> Apkmirror.com
> Mediafire.com
> 
> 2 doang sih sejauh ini

Di Apkmirror.com Saya hanya menemukan tulisan ini "_No ads, dark mode, and more with APKMirror Premium_"

Ini bisa dengan `apkmirror.com##div > :has-text(/no ads/i)`

---

> Saya make browsee 1DM/1DM+ Yang di playstore
> Soalnya kalo di mobile gede banget notifnya

Saya sudah coba download 1DM, lalu di menu pojok kanan atas, Saya klik `Manage adblock host & filters`. Saya tidak bisa mengetahui mereka pakai engine adblock apa?

AdBlockID sendiri dioptimalkan untuk uBlock Origin dan AdGuard, produk adblocker lainnya AdBlocID tidak akan bisa bekerja secara optimal.

**Comment by acgl** [comment]
Kalo pake engine saya kuramg tau, yaudalah makasi udh bantu jawab
Have a nice day
