### ISSUE TITLE
kusonime.com

### ISSUE THREAD

**Issue by acgl** [realodix/AdBlockID#1358]
**Jenis**
<!-
- Terdapat safelink
-->

**Sample URL**
https://kusonime.com/mou-ippon-batch-subtitle-indonesia/
https://tempel.in/view/84a4af3d
https://carapedi.id/zuAy69
https://tempel.in/view/21db62dd
https://semawur.com/fpQtHDOvhs

**Penjelasan Lebih Lanjut**
- Terdapat safelink, shortlink
Browser yang digunakan : Kiwi Browser
Adblock : Ekstensi uBlock Origin

Thank you ~

**Comment by realodix** [comment]
Safelink yang dapat dihilangkan kurang lebih seperti yang ada di nimegami.id, Anda dapat mebandingkannya dengan mematikan AdBlockID

https://nimegami.id/one-piece-film-red-sub-indo/
