### ISSUE TITLE
yuksinau.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1359]
![image](https://user-images.githubusercontent.com/19517680/225495957-d778dae2-d8f7-4b1c-9ec0-89359d54d187.png)

https://www.yuksinau.id/pengertian-dan-contoh-seni-rupa-murni/

**Comment by realodix** [comment]
yuksinau.id sudah ada di AdBlockID

![noname-crop](https://user-images.githubusercontent.com/1314456/225596828-14fa5351-0cbe-4e54-8cbc-235825f87bef.png)

Filter `||yuksinau.id/html/hades.js` yang ada di AdBlockID masih efektif, jadi Saya tidak menemukan popup tersebut.

Bisa di jelaskan lebih rinci?

**Comment by 3xploiton3** [comment]
aneh di saya rule tsb tidak terdeteksi, sudah saya update filter & purge all caches

> uBlock Origin: 1.47.4
Chromium: 113
filterset (summary): 
  network: 111640
  cosmetic: 109148
  scriptlet: 24781
  html: 0
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7575-2, 4m
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid_plus.txt: 62-4, 4m
    IDN-0: 5459-346, 3d.23h.29m
    RUS-0: 39489-52, 1d.21h.20m
    fanboy-cookiemonster: 46124-214, 3d.23h.29m
    ublock-annoyances: 4853-59, 3d.23h.29m
  default: 
    user-filters: 29-0, never
    easylist: 63833-69, 3d.23h.29m
    easyprivacy: 31047-1283, 3d.23h.29m
    plowe-0: 3757-937, 3d.23h.28m
    ublock-abuse: 78-1, 3d.23h.29m
    ublock-badware: 4720-114, 3d.23h.29m
    ublock-filters: 32887-429, 3d.23h.29m
    ublock-privacy: 292-1, 3d.23h.29m
    ublock-quick-fixes: 378-16, 14h.12m
    ublock-unbreak: 1923-42, 3d.23h.29m
    urlhaus-1: 6820-0, 14h.11m
filterset (user): [array of 29 redacted]
trustedset: 
  added: [array of 36 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  cloudStorageEnabled: true
  suspendUntilListsAreLoaded: true
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 7547 ms (selfie)
  maxAssetCacheWait: 561 ms

**Comment by 3xploiton3** [comment]
fixed, sudah normal kembali, setelah saya clear cache & cookies
