### ISSUE TITLE
pinloker.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1362]
**Jenis**
- Pop-up

**Sample URL**
https://apk.miuiku.com/QzJkCAZd4S

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Ini mirip seperti di https://github.com/realodix/AdBlockID/issues/1260, alamatnya gonta ganti..

Hanya dapat 1x ke pinloker, sisanya diarahkan ke https://app.vebma.com/bayar-500rb-per-hari--11-apk-dan-website-penghasil-uang-tercepat

---

Pernah dilaporkan ke sini juga https://github.com/uBlockOrigin/uAssets/issues/16373, sepertinya filter yang ada sudah tidak berfungsi

**Comment by Recehan-Slayer** [comment]
![Screenshot 2023-03-20 033826](https://user-images.githubusercontent.com/9379770/226207679-a11c7cc9-7f0f-42d5-ad56-486d389847ba.png)

masi ada bro anti adblocknya

**Comment by realodix** [comment]
peringatan anti adblock harusnya sudah hilang sejak di https://github.com/realodix/AdBlockID/commit/d3f2c5eaa05aa3a70d608ce19f0bed57a2cea038

Di Saya sudah gak ada, filter yang digunakan ini `@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$xhr,from=vebma.com`

**Comment by realodix** [comment]
Tolong diperiksa lagi, sekarang pakai Saya ganti ke `##+js(no-fetch-if, adsbygoogle.js)`

**Comment by Recehan-Slayer** [comment]
masi ada ntah apanya uda gw update pdhal

**Comment by Recehan-Slayer** [comment]
uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 112910
  cosmetic: 153294
  scriptlet: 37520
  html: 1070
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7611-2, 1m
    adguard-generic: 68942-5235, 2m
    adguard-spyware-url: 949-4, 2m
    adguard-annoyance: 65207-1705, 1m
    adguard-social: 20036-31, 1m
    ublock-annoyances: 4836-9, 1m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33840-318, 2m
    ublock-badware: 4752-0, 2m
    ublock-privacy: 342-0, 2m
    ublock-abuse: 78-0, 2m
    ublock-unbreak: 1948-1, 2m
    ublock-quick-fixes: 421-0, 2m
    easylist: 64319-595, 2m
    easyprivacy: 31065-1767, 1m
    urlhaus-1: 6712-0, 1m
    plowe-0: 3755-2, 1m
filterset (user): [empty]
trustedset: 
  added: [array of 1 redacted]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 466 ms (selfie)
  maxAssetCacheWait: 355 ms

**Comment by Recehan-Slayer** [comment]
eh uda bro cuma fake button dibagian atas masi ada yg venma

**Comment by Recehan-Slayer** [comment]
![Screenshot 2023-03-21 153049](https://user-images.githubusercontent.com/9379770/226552948-a0a9ccd2-56dd-427d-a6d6-d5fe70d84170.png)

ama getlinknya hilang bro

uBlock Origin: 1.47.4
Firefox: 111
filterset (summary): 
  network: 112910
  cosmetic: 153294
  scriptlet: 37520
  html: 1070
listset (total-discarded, last-updated): 
  added: 
    https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt: 7611-2, 5m
    adguard-generic: 68942-5235, 6m
    adguard-spyware-url: 949-4, 6m
    adguard-annoyance: 65207-1705, 6m
    adguard-social: 20036-31, 6m
    ublock-annoyances: 4836-9, 6m
  default: 
    user-filters: 0-0, never
    ublock-filters: 33840-318, 6m
    ublock-badware: 4752-0, 6m
    ublock-privacy: 342-0, 6m
    ublock-abuse: 78-0, 6m
    ublock-unbreak: 1948-1, 6m
    ublock-quick-fixes: 421-0, 6m
    easylist: 64319-595, 6m
    easyprivacy: 31065-1767, 6m
    urlhaus-1: 6712-0, 6m
    plowe-0: 3755-2, 5m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 466 ms (selfie)
  maxAssetCacheWait: 355 ms

**Comment by realodix** [comment]
> ama getlinknya hilang bro

Sekarang berubah lagi ya.. Nah kalau ini Saya juga bingung deh mau diapain. Di bawah ini kondisi dimana adblock dimatikan, hasilnya juga hilang

https://user-images.githubusercontent.com/1314456/226576127-3cc41bf9-2ba4-4b45-b146-fdc7354b8ad2.mp4
