### ISSUE TITLE
klikpajak.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1365]
![image](https://user-images.githubusercontent.com/19517680/226584437-0e1ede48-9b94-4f97-b12a-1e6af030c8ef.png)

https://klikpajak.id/blog/formulir-spt-masa-pph-pasal-23-excel-terbaru/

**Comment by realodix** [comment]
klikpajak memasang banner yang mengiklankan produk mereka sendiri di situs mereka sendiri

Aduh sorry ini tidak masuk dalam kategori yang harus dihilangkan, karena:
- Ini masuk ke dalam kategori banner yang tidak boleh dihilangkan secara sengaja
- Berpotensi merugikan user, karena berisi info penting untuk konsumen
