### ISSUE TITLE
isekaisubs.web.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1374]
**Jenis**
- Iklan

**Sample URL**
https://isekaisubs.web.id/anime/kono-subarashii-sekai-ni-bakuen-wo/

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by Recehan-Slayer** [comment]
https://isekaisubs.web.id/
ada iklan judi nya bro

**Comment by realodix** [comment]
> https://isekaisubs.web.id/ ada iklan judi nya bro

Thank you
