### ISSUE TITLE
megaup.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1376]
**Jenis**
- Anti-Adblock

**Sample URL**
https://megaup.net/1dksd

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Ini mirip seperti di https://github.com/AdguardTeam/AdguardFilters/issues/147780

Ada filter di uBlock filters – Quick fixes yang menyebabkannya

![noname-crop](https://user-images.githubusercontent.com/1314456/232239975-d2dfb11c-5986-4daa-8b1c-6d9afbbce71c.png)

Solusi sementara `megaup.net#@#body .metaRedirectWrapperBottomAds:style(pointer-events: none !important; padding-left: 10000px !important;)`

**Comment by Recehan-Slayer** [comment]
> 

ttep muncul bro pke yg diatas

**Comment by realodix** [comment]
Ternyata efeknya beda-beda

1. Firefox (jika uBlock filters – Quick fixes aktif)
 
`megaup.net#@#body .metaRedirectWrapperBottomAds:style(pointer-events: none !important; padding-left: 10000px !important;)`

Tidak perlu dilakukan  - Jika uBlock filters – Quick fixes tidak aktif atau tidak ada filter `megaup.net##body .metaRedirectWrapperBottomAds:style(pointer-events: none !important; padding-left: 10000px !important;)`

2. Chrome

`@@/imageads/*$domain=megaup.net`
