### ISSUE TITLE
app.wapka.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1378]
https://lendrive.web.id/isekai-maou-to-shoukan-shoujo-no-dorei-majutsu-bd-x265-hevc-subtitle-indonesia/

example link:
https://www.wts.pw/full/?api=c459ca2d2ff7da18fec24ab01fb49d529ca0dc99&url=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvNTY5NDUxNjIvbGVuZHJpdmVfcml0dWFsX2RpYWJsb19iZF8wNy0xMl83MjBwX2hldmMtcmFy&type=2

redirect to:
https://app.wapka.id/iphone-vs-android-which-one-reigns-supreme

muncul pop up terabox

**Comment by realodix** [comment]
Ini terlihat seperti link yang disamarkan

---

![noname](https://user-images.githubusercontent.com/1314456/235444395-b637fbdd-9041-4223-a8ed-d272ca32f743.png)

Info, jika AdBlockID muncul seperti gambar di atas, segera hapus lalu subscribe ulang

Mohon untuk confimr ulang apakah linknya masih tersamarkan atau tidak

**Comment by 3xploiton3** [comment]
> Ini terlihat seperti link yang disamarkan
> 
> ![noname](https://user-images.githubusercontent.com/1314456/235444395-b637fbdd-9041-4223-a8ed-d272ca32f743.png)
> 
> Info, jika AdBlockID muncul seperti gambar di atas, segera hapus lalu subscribe ulang
> 
> Mohon untuk confimr ulang apakah linknya masih tersamarkan atau tidak

![image](https://user-images.githubusercontent.com/19517680/235461745-de96a60e-e41b-477b-ac4a-9c6de675a6be.png)

iya kok bisa jadi 0

**Comment by Reno-Sifana** [comment]
> > Ini terlihat seperti link yang disamarkan
> > ![noname](https://user-images.githubusercontent.com/1314456/235444395-b637fbdd-9041-4223-a8ed-d272ca32f743.png)
> > Info, jika AdBlockID muncul seperti gambar di atas, segera hapus lalu subscribe ulang
> > Mohon untuk confimr ulang apakah linknya masih tersamarkan atau tidak
> 
> ![image](https://user-images.githubusercontent.com/19517680/235461745-de96a60e-e41b-477b-ac4a-9c6de675a6be.png)
> 
> iya kok bisa jadi 0 ?
> 
> sudah saya subscribe ulang, popup masih muncul

@3xploiton3 punyaku barusan bisa kok habis Subscribe ulang filternya
### Filter
- AdBlockID 8,841 used out of 8,847
- AdBlockID Plus 77 used out of 77
![Screenshot from 2023-05-01 21-00-37](https://user-images.githubusercontent.com/68702583/235464225-0ec34c9c-b243-4e5f-a5af-65157835a097.png)
