### ISSUE TITLE
tafsirweb.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1379]
https://tafsirweb.com/9012-surat-fussilat-ayat-30.html

setiap copy arab atau kata muncul link sumber, agak mengganggu buat yang sering copy harus menghapus link

 bisa tolong dihilangkan?

**Comment by 3xploiton3** [comment]
masih ada linknya, kadang hilang, kadang muncul lagi, tolong di cek ulang

**Comment by realodix** [comment]
Di Saya fine aja..

versi AdBlockID untuk issue ini v23.5.9, jika versinya sama atau lebih tinggi harusnya sih sudah
