### ISSUE TITLE
nekopoi.care

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1380]
**Jenis**
- Iklan

**Sample URL**
https://nekopoi.care/

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Di Saya fine saja..

---

![noname](https://user-images.githubusercontent.com/1314456/235509542-180b3f87-7d40-4035-a886-96874b30450d.png)

Jika melihat fenomena seperti gambar di atas, mohon untuk subscribe ulang dan confirm apakah masih ada masalah terkait dengan issue ini

**Comment by Recehan-Slayer** [comment]
g pke yg plus sih brarti ada di yg plus?

**Comment by Recehan-Slayer** [comment]
iya uda bisa subscribe ulang
