### ISSUE TITLE
Request: Filtering by image size results in false blocks quite often

### ISSUE THREAD

**Issue by fa0311** [realodix/AdBlockID#1382]
These frequently block incorrectly, so we request that they be removed or made into a separate filter file.

https://github.com/realodix/AdBlockID/blob/57f962c2aec0f16c25ea4ac76ef47000cdcbbda7/dist/adblockid.adfl.txt#L2181-L2463

#### Related Issues
#1331

**Comment by realodix** [comment]
I need the url address, I'll whitelist it

**Comment by fa0311** [comment]
This problem occurred with self-hostable open source.
Is it possible to use a blacklist method instead of a whitelist method for filter URLs?
Or suggest moving them to AdBlockID Plus.
If you do not accept this suggestion, you may close this issue.

**Comment by realodix** [comment]
I don't understand, what do you mean "self-hostable open source"?

**Comment by fa0311** [comment]
Server-side software that provides the WebUI (in my case WordPress, but not exclusively).
These are hosted by different users on different domains, so it is impossible to include them all.
There is a solution to change them so that they are not filtered by AdBlockID, but this is only a temporary solution and will confuse other users who are facing this problem.

**Comment by Alex-302** [comment]
728*90 is very popular banner size

**Comment by realodix** [comment]
> Or suggest moving them to AdBlockID Plus.

I chose this solution by moving them to AdBlockID Plus

Thank You
