### ISSUE TITLE
e-bpom.pom.go.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1386]
Tidak bisa select copy

https://e-bpom.pom.go.id/

**Comment by realodix** [comment]
Waduh, ini situs pemerintah

Sry Gan gak berani kalau untuk umum, bypass anti copy paste termasuk pelanggaran keamanan (walaupun kecil). Kalau situs bukan pemerintah masih berani Saya.

```adblock
pom.go.id##+js(aopr, document.oncontextmenu)
```

**Comment by 3xploiton3** [comment]
oke sip tdk apa, saya masukkan ke personal filter, terimakasih
