### ISSUE TITLE
layarkeren.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#139]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://layarkeren.com/
https://layarkeren.com/tv/joy-of-life-bahasa-indonesia-2019/

**Penjelasan Lebih Lanjut**
iklan yg tersisa transparan sama dibagian dalam post ada banner iklan judi

**Comment by realodix** [comment]
1. Overlay tidak terlalu mengganggu. Mengingat maintain domain movie yang sulit karena gonta-ganti terus, jadi Saya rasa biarkan saja.
2. Banner iklan judi tidak ada, sepertinya sudah bersih dari issue sebelumnya.

<details>
  <summary>Screenshoot 1</summary>
  
  ![screencapture-layarkeren-2019-12-29-10_55_30](https://user-images.githubusercontent.com/1314456/71552161-e6a7be00-2a29-11ea-9311-93cad46fda53.png)
</details>

<details>
  <summary>Screenshoot 2</summary>
  
  ![screencapture-layarkeren-tv-joy-of-life-bahasa-indonesia-2019-2019-12-29-10_55_59](https://user-images.githubusercontent.com/1314456/71552162-ead3db80-2a29-11ea-8fed-608b3021c1fb.png)
</details>

Thank you

**Comment by WaferNabati** [comment]
@realodix masih ada gan disebelah kiri transparan klo ke klik menuju ke situs judi

**Comment by realodix** [comment]
Ah, I missed that. Jadi terpaksa masukin domain untuk specific hide karena saat ini gak ada jalan lain buat ngilangin iklan di sebelah kiri haha

Thank you

**Comment by realodix** [comment]
Domain berubah jadi layarkeren.org
