### ISSUE TITLE
obengplus.com

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1391]
**Sample URL**
https://obengplus.com/

**Penjelasan Lebih Lanjut**
 Halaman obengplus.com menjadi rusak ketika Ublock Origin diaktifkan
Screenshot tampilan https://obengplus.com ketika Ublock Origin diaktifkan 
![Screenshot from 2023-05-16 20-06-49](https://github.com/realodix/AdBlockID/assets/68702583/eedec41e-c14c-4e07-8527-1c6ec72b6eb7)
Screenshot tampilan https://obengplus.com ketika Ublock Origin dinonaktifkan 
![Screenshot from 2023-05-16 20-07-47](https://github.com/realodix/AdBlockID/assets/68702583/15c650c8-86ca-4227-bde6-6f6471028d71)
Filter yang aktif: Bawaan Ublock Origin sama AdBlockID 
![Screenshot from 2023-05-16 20-12-30](https://github.com/realodix/AdBlockID/assets/68702583/43e16f7b-b6b7-4b0a-bd07-313979716558)

**Comment by 3xploiton3** [comment]
> **Sample URL** https://obengplus.com/
> 
> **Penjelasan Lebih Lanjut**
> 
> Halaman obengplus.com menjadi rusak ketika Ublock Origin diaktifkan
> Screenshot tampilan https://obengplus.com ketika Ublock Origin diaktifkan ![Screenshot from 2023-05-16 20-06-49](https://user-images.githubusercontent.com/68702583/238655120-eedec41e-c14c-4e07-8527-1c6ec72b6eb7.png) Screenshot tampilan https://obengplus.com ketika Ublock Origin dinonaktifkan ![Screenshot from 2023-05-16 20-07-47](https://user-images.githubusercontent.com/68702583/238655399-15c650c8-86ca-4227-bde6-6f6471028d71.png) Filter yang aktif: Bawaan Ublock Origin sama AdBlockID ![Screenshot from 2023-05-16 20-12-30](https://user-images.githubusercontent.com/68702583/238655853-43e16f7b-b6b7-4b0a-bd07-313979716558.png)

ini website private ya? langsung diminta login
websitenya terlihat gak pakai ssl
![image](https://github.com/realodix/AdBlockID/assets/19517680/d8380d28-9a0a-4fa1-8aaa-6a4f28370c0b)

**Comment by Reno-Sifana** [comment]
> > **Sample URL** https://obengplus.com/
> > **Penjelasan Lebih Lanjut**
> > Halaman obengplus.com menjadi rusak ketika Ublock Origin diaktifkan
> > Screenshot tampilan https://obengplus.com ketika Ublock Origin diaktifkan ![Screenshot from 2023-05-16 20-06-49](https://user-images.githubusercontent.com/68702583/238655120-eedec41e-c14c-4e07-8527-1c6ec72b6eb7.png) Screenshot tampilan https://obengplus.com ketika Ublock Origin dinonaktifkan ![Screenshot from 2023-05-16 20-07-47](https://user-images.githubusercontent.com/68702583/238655399-15c650c8-86ca-4227-bde6-6f6471028d71.png) Filter yang aktif: Bawaan Ublock Origin sama AdBlockID ![Screenshot from 2023-05-16 20-12-30](https://user-images.githubusercontent.com/68702583/238655853-43e16f7b-b6b7-4b0a-bd07-313979716558.png)
> 
> ini website private ya? langsung diminta login websitenya terlihat gak pakai ssl ![image](https://user-images.githubusercontent.com/19517680/238657597-d8380d28-9a0a-4fa1-8aaa-6a4f28370c0b.png)

iya. di Firefox juga gembok merah di Address Bar nya. Kalau diminta login saya kurang tahu. (segera saya tutup tab nya soalnya)

**Comment by realodix** [comment]
Ini adalah anti adblock, jika di situs pada umumnya menapilkan peringatan, obengplus memillih untuk menghancurkan tampilannya.
