### ISSUE TITLE
AdBlockID Subscription URL Change

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#1394]
<p align="center"><img src="https://github.com/realodix/AdBlockID/assets/1314456/32ec7a6e-0f18-4915-8946-f64c4aec3ee4" /></p>

Hello Guys,

Jika kalian menerima pesan ini, selamat Anda merupakan salah satu orang yang menurut Saya penting untuk segera dikabari :D

Sejak beberapa minggu yang lalu, ada sedikit perubahan nih di AdBlockID yang menyebabkan subscription Url berubah. Jadi, Anda perlu mengganti subscription Url-nya dengan yang baru.

> Beberapa dari kalian mungkin sudah pernah Saya arahkan untuk mengganti `@main` ke `@latest`, jika sudah, kalian bisa mengabaikan pesan ini.

### AdBlockID
- AdGuard: Tidak perlu melalukan apa-apa, Saya sudah mengurusnya langsung ke AdGuard.
- uBlock Origin & AdNauseam: Anda perlu mengganti subscription Url-nya dengan yang baru.

### AdBlockID Plus
- Anda perlu mengganti subscription Url-nya dengan yang baru.

Jika kalian memiliki pertanyaan (terkain issue ini, apapun itu), jangan malu untuk bertanya.

Terima kasih

Btw, jika Kalian ada di sekitar Jakarta, ayo kita nongkrong di Starbucks

---

Hello Guys,

If you received this message, congratulations you are one of the people who I think it is important to inform about the subscription url change :D

There was a slight change in AdBlockID that caused the subscription Url to change. So, you need to replace the subscription Url with a new one.

### AdBlockID
- AdGuard: No need to do anything.
- uBlock Origin & AdNauseam: You need to replace the subscription Url with a new one.

### AdBlockID Plus
- You need to replace the subscription Url with a new one.

If you have any questions (about this issue, whatever it is), leave a comment.

Thank you

@Recehan-Slayer, @3xploiton3, @3xploitzer0, @abidjauhar17 ,@abala26, @acgl, @ardilazm, @arfshl, @arsindyfm, @aszksbdje, @BanijaDev, @Bug-Cache, @butaw45, @chigarow, @e-budianto, @fgt7, @Gamefire238, @GrennKren, @Gyputra, @HDark15, @Jokopentil, @KagaKouko99, @krisanto29, @lcqlcq5, @Lotlofia, @Manssizz, @Nirajgoythale, @PT-Aweh-KangTravel, @RaveN0X87, @Reno-Sifana, @RidhoAW, @sandycorzeta, @scripthunter7, @SuperMarioMakerII, @Taufik-Rahman, @TheBSODAndWSODFan, @What-Zit-Tooya, @wout-codes, @xenstar, @YellowStar11

**Comment by realodix** [comment]
**QA**
- **Mengapa Anda Saya mention?** Karena menurut Saya, Anda cukup penting untuk Saya kabari. Anda pernah memberikan kontribusi di AdBlockID (membuat issue, pull request, atau sekedar ikut berdiskusi).
- **Apakah harus segera Saya ubah?** Ya, tentu saja. Tetapi walau bagaimanapun pilihan ada di tangan Anda.

**Comment by 3xploiton3** [comment]
Pemberitahuannya telat bang, ✌️
sudah diganti ke subscribe terbaru gara2 banyak iklan yg muncul,

terimakasih juga utk bang @realodix yg sudah aktif memberikan filter2 hebat, membuat berselancar di internet menjadi  lebih aman dan nyaman minim gangguan

**Comment by aszksbdje** [comment]
Terima Kasih telah menyempatkan waktu untuk membuat pemberitahuan.
Kami sangat mengapresiasi developer yang peduli dengan masukan dari pengguna.

Sehat sehat terus ngab... kami padamu.... 😁😁😁

**Comment by Reno-Sifana** [comment]
> Pemberitahuannya telat bang, v sudah diganti ke subscribe terbaru gara2 banyak iklan yg muncul,
> 
> terimakasih juga utk bang @realodix yg sudah aktif memberikan filter2 hebat, membuat berselancar di internet menjadi lebih aman dan nyaman minim gangguan

sama. sejak post kapan hari di discussion ini https://github.com/realodix/AdBlockID/issues/1378#issuecomment-1529596178 dah ku ganti

**Comment by Jokopentil** [comment]
Sekedar tanya nih bang?
Admind di adblockid ada berapa sih kok
Selalu ownernya yg handle
Nah klo owner lagi berhalangan siapa yg menangani dan merawat adblockid, secara filter ini dipakai seterusnya🙏🙏

**Comment by realodix** [comment]
> Sekedar tanya nih bang? 
> Admind di adblockid ada berapa sih kok 
> Selalu ownernya yg handle
> Nah klo owner lagi berhalangan siapa yg menangani dan merawat adblockid, secara filter ini dipakai seterusnya🙏🙏

GitHub merupakan sarana yang bagus untuk kolaborasi. Dengan berkontribusi, dapat ikut menjaga suatu project terus berjalan. Siapapun dapat berkontribusi dengan membuat [pull requests](https://github.com/realodix/AdBlockID/pulls).
