### ISSUE TITLE
itemku.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1396]
![image](https://github.com/realodix/AdBlockID/assets/19517680/beecedfc-a7e0-488e-9d1c-e55a0766c65b)

https://itemku.com/g/scribd/akun?sort=1&region=id

ads

**Comment by realodix** [comment]
Related:
- https://github.com/realodix/AdBlockID/issues/1370

**Comment by realodix** [comment]
Sepertinya ini sudah tidak relevan, rules untuk itemku.com akan dihapus
- https://github.com/uBlockOrigin/uAssets/issues/24278#issuecomment-2196311200
