### ISSUE TITLE
terabox.fun

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1398]
**Jenis**
- Iklan
- Pop-up
- Anti-Adblock
- Terdapat safelink

**Sample URL**
https://terabox.fun/sl/2nkSF4ZbsZ

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Sepertinya ini situs internasional, langsung laporkan Saja ke:
- AdGuard (sudah pernah dilaporkan) `https://github.com/AdguardTeam/AdguardFilters/issues/152232`
- uBlock Origin https://github.com/uBlockOrigin/uAssets/issues
