### ISSUE TITLE
sukamovie.club

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#140]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
http://sukamovie.club/

**Penjelasan Lebih Lanjut**
Overlay iklan judi

**Comment by realodix** [comment]
1. Yang di bawah sudah saya hilangkan.
2. Bagian tengah ini tidak terlalu mengganggu. Mengingat maintain domain movie yang sulit karena gonta-ganti terus, jadi Saya rasa biarkan saja.

**Comment by WaferNabati** [comment]
justru yg ditengah itu malah yg paling mengganggu brow -_-
