### ISSUE TITLE
oploverz.love

### ISSUE THREAD

**Issue by aszksbdje** [realodix/AdBlockID#1404]
Pakai Adguard 4.0 106
Situs Oploverz
![Screenshot_2023-06-04-10-23-26-267_com android chrome](https://github.com/realodix/AdBlockID/assets/16359705/29139146-9060-4f09-ba8e-63857208bc93)

**Comment by realodix** [comment]
Untuk AdGuard, tunggu AdBlockID diperbarui di https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_120_AdBlockID
