### ISSUE TITLE
Title Suggestion

### ISSUE THREAD

**Issue by ChowMein47** [realodix/AdBlockID#1408]
Saya ingin memberikan saran untuk menambahkan bendera Indonesia & Malaysia di filter AdblockID sebagai tanda filter regional. Thx

**Comment by realodix** [comment]
Ini tidak umum, karena Saya belum pernah menemukan yang menaruh bendera di namanya. Paling hanya pengelompokkan saja, itu juga yang mengelompokkan adalah aplikasi ad blocker itu sendiri.

Saya rasa, sebaiknya buat polling di https://github.com/realodix/AdBlockID/discussions/new?category=polls

Terima kasih
