### ISSUE TITLE
dutasex.info

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1409]
http://dutasex.info/bokep-indo-video-viral-pelajar-smp-pekanbaru-bergoyang/
Banner yang mengganggu (gambar bibir) dan fiter anti social media
![20230613_133451_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/b6e9a69b-1b75-4967-abf6-a4704856befd)

**Comment by realodix** [comment]
Domainnya berubah jadi `dutasex.icu`

Untuk annoyance yang sifatnya umum, bisa gunain filter khusus Annoyance
- AdGuard – Annoyances
- EasyList – Annoyances

atau kalau belum ada di mereka bisa gunain ini
```adblock
dutasex.icu###promoapk
dutasex.icu##.chaty
```

Ruang lingkup AdBlockID hanya sebatas yang tertera di https://github.com/realodix/AdBlockID#manfaat-yang-anda-dapatkan saja

**Comment by Jokopentil** [comment]
Ya kemarin sudah saya laporkan pihak adguadr sudah fix
