### ISSUE TITLE
vpnjantit.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1411]
![image](https://github.com/realodix/AdBlockID/assets/19517680/07813b26-7846-4fae-babe-d0bfde4051cc)

https://www.vpnjantit.com/who-is-domain-or-ip?host=38.54.76.161&ping=Show+Info#result

**Comment by realodix** [comment]
Maaf ini akan Saya tutup dan menandainya sebagai invalid

**Comment by 3xploiton3** [comment]
ya  sebaiknya dihilangkan

dan juga kotak merah yang saya tandai dihilangkan

![image](https://github.com/realodix/AdBlockID/assets/19517680/086f9a5a-8778-4b89-b7e4-3d9e84b21751)

**Comment by realodix** [comment]
Done, karena ini situs luar, jadi ada di AdBlockID Plus
