### ISSUE TITLE
komikcast.io

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1414]
**Jenis**
- Iklan
- Pop-up

**Sample URL**
https://komikcast.io

**Penjelasan Lebih Lanjut**
Domain baru dari komikcast.site

**Comment by GrennKren** [comment]
Hapus cache sama cookies buat memastikan.. ada popup mengarah ke `bkqk.bljyynzmlmazz.top` .

**Comment by realodix** [comment]
Ini pakai adblocker apa ya dan di browser dan device (pc / hp) apa?

**Comment by GrennKren** [comment]
PC, Chrome Browser, Adguard Windows (Bukan yang Extension Chrome).

Tapi di ponsel dengan adguard android gak berpengaruh sih
<img width="700" src="https://github.com/realodix/AdBlockID/assets/34759917/2d229250-1c5a-4558-8096-01c344901cf2">

**Comment by realodix** [comment]
Sepertinya ada perbedaan perilaku ya

- AdGuard for Windows, ada popup seperti yang Anda laporkan
- AdGuard Browser extension, tidak ada popup
- AdGuard for Android, tidak ada popup

Pada titik ini, tidak ada yang dapat Saya lakukan

**Comment by GrennKren** [comment]
ok deh.. berarti cukup di ignore aja itu pesan popup nya.
