### ISSUE TITLE
komikcast.io

### ISSUE THREAD

**Issue by YellowStar11** [realodix/AdBlockID#1415]
**Jenis**
- Iklan judi

**Sample URL**
https://komikcast.io/

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman 
![Screenshot_2023-06-17-09-32-37-92_d0ef7a9810af20f7b394f4f927b723b0](https://github.com/realodix/AdBlockID/assets/98148960/e2c9d865-8e8e-4e51-9d16-d286fdc396bb)

**Comment by realodix** [comment]
Duplicate of #1414

**Comment by realodix** [comment]
Mohon untuk update AdBlockID, saat ini versinya ada di v23.6.20 atau jika di AdGuard ada di v2.0.15.8
