### ISSUE TITLE
gudangmovies21.skin

### ISSUE THREAD

**Issue by richie3011** [realodix/AdBlockID#1416]
**Jenis**
- Pop-up tombol close iklan

**Sample URL**
https://gudangmovies21.skin/

**Penjelasan Lebih Lanjut**
- Terdapat tombol close iklan di halaman . 
![Screenshot_2023-06-19-09-13-14-35_d0ef7a9810af20f7b394f4f927b723b0](https://github.com/realodix/AdBlockID/assets/98148960/2298d2b0-13ad-4a85-bd8b-46407b3a3f56)

**Comment by realodix** [comment]
Ini pakai Ad blocker apa ya? gudangmovies21.skin sduah ada di AdBlockID, jadi di Saya gak ada masalah

**Comment by Jokopentil** [comment]
Dari tampilann itu firefox kak
Pasti ada 3 adblock pilihan di browser itu
Yg mendukung adblockid
Ublock origin ,adguard dan adnawsim
Kalo pakai ghostery gak mendukung ad list regional
Mohon di koreksi jika salah🙏

**Comment by Jokopentil** [comment]
![20230619_211753_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/a864fc2b-8dd1-42f8-95ca-c2a9a0fd7be4)

![20230619_211641_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/0a704cb0-b0d7-4126-b5f0-770b7f5523b4)

Di punyaku juga lancar

**Comment by Jokopentil** [comment]
Mungkin itu pakai adblok dns sepert nextdns rethink dns dll memang bisa di block tapi gk sempurna hasilnya
Atau bsaa jadi kakaknya ini gak subscrib ulang jika pakai ublock
Klo pakai dns itu pakai energized regional
Emang begitu biasanya terkadang gk sempurna

**Comment by realodix** [comment]
OK, Saya tutup issue ini
