### ISSUE TITLE
movindo21.com - banner pemasangan iklan

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#142]
**Jenis iklan** (hapus yang tidak perlu)
- Tempat Banner
- Pop-up
- Lainnya

**Sample URL**
https://movindo21.com/
https://movindo21.com/f/jack-irish-bad-debts-2012.htm
https://galaxyxxi.com/

**Penjelasan Lebih Lanjut**
Tempat banner iklan/Space ads

**Comment by realodix** [comment]
Banner pemasangan iklan, ini gak apa-apa. Mereka mengiklankan diri mereka di situs mereka sendiri.
