### ISSUE TITLE
liputan6.com - AdBlockID breaks the automatic page load

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1420]
https://github.com/reforget-id/AutoAllPage/issues/12#issuecomment-1608945673

**Comment by realodix** [comment]
> https://github.com/reforget-id/AutoAllPage/issues/12#issuecomment-1608945673

Meurut halaman ini https://github.com/reforget-id/AutoAllPage/issues/12#issuecomment-1608945673, penyebabnya adalah 

```adblock
liputan6.com##+js(aeld, scroll)
```

Jika melihat historynya, filter tersebut digunakan untuk issue berikut ini:
- https://github.com/realodix/AdBlockID/issues/1120
- https://github.com/AdguardTeam/AdguardFilters/issues/111220

Perlu dicatat, ini adalah masalah yang cukup kecil karena yang macet hanya ekstensi AutoAllPage, bukan liputan6.com.

Tapi walau bagaimananpun Saya akan coba memantau `liputan6.com##+js(aeld, scroll)` hingga besok pagi apakah fiilter tersebut masih relevan atau tidak.
- Jika sudah tidak relevan, Saya akan menghapusnya
- Jika masih relevan, Saya akan coba lihat apakah ada filter pengganti yg setara atau tidak

**Comment by reforget-id** [comment]
Buat memperjelas saja, filter `liputan6.com##+js(aeld, scroll)` tidak merusak fungsi AutoAllPage, tapi merusak fitur bawaan liputan6.com. AutoAllPage tidak melakukan apa-apa terhadap situs liputan6.com. 
Fitur bawaan liputan6.com yang dimaksud adalah halaman loading otomatis saat discroll. Jika filter tersebut aktif, maka kita harus mengklik tombol 'selanjutnya' secara manual.

**Comment by realodix** [comment]
Filter sudah dihapus, thank you
