### ISSUE TITLE
isekaipalace.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1422]
**Jenis**
- Anti-Adblock

**Sample URL**
https://www.isekaipalace.com/2022/10/cour-kedua-danmachi-iv-tayang-musim.html#?o=49be70e3dbee5190bcb7d87335ad8d7bc06e1bfa56e843527cb908bb3ca9541c2c1f562d299fbfb344e4752dcbe956b10f1db6ebd0315546d8ac41532657a9e4de489a807d0b47dad1611e8be82f12d58b74b58986ef0c574b1c593a8b21e0b7ae3d6c99cd801ed1

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by luminiatus2** [comment]
wow
