### ISSUE TITLE
NontonFilmDrama (45.141.56.28)

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1423]
https://45.141.56.28/800-bullets-2002-jf/
Pop up banner muncul setelah beberap menit setelah vidio di putar
![20230702_165456_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/ef6911d9-976c-43be-bc00-1898a4628561)

**Comment by realodix** [comment]
Ini setelah menit ke berapa ya?

Saya sudah menit ke 5 belum muncul juga

**Comment by Jokopentil** [comment]
![20230702_181307_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/c43c275e-0d07-46db-b454-2fbf5775083d)

Maaf kak itu udah fix masalahnya ada di fittur hide annoying
Itu ada iklan vidio saat pertama klik play
Karena itu pop up link vidio
Untuk iklan vidio gk bisa di blok di firefox
Untuk kiwi browser udah fix
Untuk banner itu sekitar di menit kira2 ke 5

**Comment by Jokopentil** [comment]
Coba kakak pakai firefox dan putar film 5 menit atau lebih

**Comment by Jokopentil** [comment]
Lupa menghidupkan hide annoying ads

**Comment by Jokopentil** [comment]
Antara menit 4sampei 7

**Comment by realodix** [comment]
Waduh, ini sulit dilakukan, karena terdapat perbedaan perilaku haha

Yang perlu digaris bawahi adalah:
- AdBlockID hanya bekerja dengan baik di AdGuard dan uBlock Origin
- Mereka menjamin selama pengaturannya sama, akan menghasilkan perilaku yang sama dimanapun itu, ntah di dekstop, di HP atau browser manapun

### Berikut laporam untuk NontonFilmDrama

Saja coba di Firefox desktop + uBlock Origin (default) + AdBlockID
- Iklan video seharusnya tidak ada, saya lihat di logger iklannya berhasil dihilangkan oleh easylist. Untuk memastikannya, Saya matikan semua filter, lalu hanya mengaktifkan easylist, hasilnya tidak ada iklan video saat pertama kali diputar.
- Iklan video datang dari JuraganFilm, untuk lebih memastikannya lagi agar iklan video tidak muncul, Saya blokir videonya di https://github.com/realodix/AdBlockID/commit/eb160761932b24210aed086fe2b8a3daaf0d23b1
- Banner di dalam video datang dari JuraganFilm, ini juga sudah Saya hilangkan di https://github.com/realodix/AdBlockID/commit/7bef262c7324f03188e8b8644081dccfb3f7e526
- Banner2 yang ada di NontonFilmDrama semuanya sudah hilang di https://github.com/realodix/AdBlockID/commit/ea64881dff3f2517f229db46518b6e647e7d35da dan https://github.com/realodix/AdBlockID/commit/2ff31b105f385b8e45358f82f376a58bcc619538

Saat ini benar-benar sudah bersih, terima kasih untuk laporannya

**Comment by Jokopentil** [comment]
Trimakasih responnya👍
