### ISSUE TITLE
NontonFilmDrama (45.141.56.28)

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1427]
https://45.141.56.28/series/nonton-scent-of-love-2022-sub-indo/
![20230706_015211_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/2bab6d61-d604-4b3e-acae-45479eea8d87)

![20230706_015159_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/9c4c0429-f97b-4db1-a751-6f49c7c5be53)

Iklan banner versi kiwi gk hilang 
Yg di paling atas dan bawah layar vidio
Pakai ublock origin

**Comment by Jokopentil** [comment]
Pakai ublock origin

**Comment by realodix** [comment]
Saya tidak menemukan ini

![251250404-9c4c0429-f97b-4db1-a751-6f49c7c5be53](https://github.com/realodix/AdBlockID/assets/1314456/828cc62d-2f62-4533-bf69-11ae1d588e45)

Mohon untuk tidak mencentang Filter lists -> Ignore generic cosmetic filters

![noname-crop](https://github.com/realodix/AdBlockID/assets/1314456/b5a14ffd-f75a-4a3c-9e59-3fceda254fc8)
