### ISSUE TITLE
id.quora.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1435]
![image](https://github.com/realodix/AdBlockID/assets/19517680/de2ced65-de23-4aac-be72-5dd35175191e)

https://id.quora.com/Dari-mana-seorang-wartawan-mendapatkan-penghasilan

**Comment by realodix** [comment]
Thank you

Btw sekarang terdapat beberapa pilihan subscription link

https://github.com/realodix/AdBlockID#subscription

**Comment by 3xploiton3** [comment]
> 

bedanya dengan yg lama apa? bukannya setiap ada update commit, user juga bisa melakukan update manual utk dpt filter update ?

sepertinya fungsinya kurang berguna, malah bagusan bila ada fitur seperti annoyance (filter block element yang dirasa mengganggu dari sisi user[subjektif])

**Comment by realodix** [comment]
> bedanya dengan yg lama apa?

Tidak ada bedanya, karena hanya miror saja.

> sepertinya fungsinya kurang berguna

Iya kelihatan tidak berguna, tapi sangat krusial. Masalah utama yang sedang AdBlockID hadapi adalah tentang beban distribusi AdBlockID yang cukup tinggi beberapa bulan terakhir ini.

Bulan lalu hampir terkena teguran penyalahgunaan pemakaian GitHub, makanya Saya buru2 langsung mematikan link yang lama dan menggantinya dengan server mirror, jsdelivr.

> bukannya setiap ada update commit, user juga bisa melakukan update manual utk dpt filter update ?

Awalnya jsdelivr maks 12 jam sekali update, belakangan dengan semakin meningkatnya trafik malah bisa 7 hari.

Jika versi AdBlockID anda masih nyangkut di v23.7.35 (09 Jul 2023 18:58 UTC), Saya sudah memperbarui linknya di halaman depan, saat ini AdBlockID ada di versi 23.7.43 (12 Jul 2023 16:42 UTC) atau lebih tinggi.

Server mirror baru sudah Saya tambahkan juga dari pages.dev, saat ini cukup menjanjikan, sekali commit langsung update, tapi gak tahu deh akhir bulan ini seperti apa.

**Comment by realodix** [comment]
> bedanya dengan yg lama apa?

Tidak ada bedanya, karena hanya miror saja.

> sepertinya fungsinya kurang berguna

Iya kelihatan tidak berguna, tapi sangat krusial. Masalah utama yang sedang AdBlockID hadapi adalah tentang beban distribusi AdBlockID yang cukup tinggi beberapa bulan terakhir ini.

> bukannya setiap ada update commit, user juga bisa melakukan update manual utk dpt filter update ?

Awalnya AdBlockID didistribusikan langsung dari repo utama, ini yang jadi masalah, karena GitHub tidak dirancang untuk distribusi konten. Bulan lalu hampir terkena teguran penyalahgunaan pemakaian GitHub, makanya Saya buru2 langsung mematikan link yang lama dan menggantinya dengan server mirror, jsdelivr.

Di awal pindah ke jsdelivr bulan lalu, awalnya jsdelivr maks 12 jam sekali update, belakangan dengan semakin meningkatnya trafik malah bisa 7 hari.

Jika versi AdBlockID anda masih nyangkut di v23.7.35 (09 Jul 2023 18:58 UTC), Saya sudah memperbarui linknya di halaman depan, saat ini AdBlockID ada di versi 23.7.43 (12 Jul 2023 16:42 UTC) atau lebih tinggi.

Server mirror baru sudah Saya tambahkan juga dari pages.dev, saat ini cukup menjanjikan, sekali commit langsung update, tapi gak tahu deh akhir bulan ini seperti apa.

Untuk AdGuard aman, karena mereka mirroring ke server mereka sendiri.

**Comment by realodix** [comment]
> bedanya dengan yg lama apa?

Tidak ada bedanya, karena hanya miror saja.

> sepertinya fungsinya kurang berguna

Iya kelihatan tidak berguna, tapi sangat krusial. Masalah utama yang sedang AdBlockID hadapi adalah tentang beban distribusi AdBlockID yang cukup tinggi beberapa bulan terakhir ini.

> bukannya setiap ada update commit, user juga bisa melakukan update manual utk dpt filter update ?

Awalnya AdBlockID didistribusikan langsung dari repo utama, makanya sekali commit update langsung tersedia. Tapi ini yang jadi masalah, karena GitHub tidak dirancang untuk distribusi konten. Bulan lalu hampir terkena teguran penyalahgunaan pemakaian GitHub, makanya Saya buru2 langsung mematikan link yang lama dan menggantinya dengan server mirror, jsdelivr.

Di awal pindah ke jsdelivr bulan lalu, awalnya jsdelivr maks 12 jam sekali update, belakangan dengan semakin meningkatnya trafik malah bisa 7 hari.

Jika versi AdBlockID anda masih nyangkut di v23.7.35 (09 Jul 2023 18:58 UTC), Saya sudah memperbarui linknya di halaman depan, saat ini AdBlockID ada di versi 23.7.43 (12 Jul 2023 16:42 UTC) atau lebih tinggi.

Server mirror baru sudah Saya tambahkan juga dari pages.dev, saat ini cukup menjanjikan, sekali commit langsung tersedia update, tapi gak tahu deh akhir bulan ini seperti apa.

Untuk AdGuard aman, karena mereka mirroring ke server mereka sendiri.

**Comment by realodix** [comment]
> bedanya dengan yg lama apa? 

Secara konten, isinya sama persis dan tidak ada bedanya. Yang membedakan hanyalah fungsinya saja.

> malah bagusan bila ada fitur seperti annoyance (filter block element yang dirasa mengganggu dari sisi user[subjektif])

Terima kasih atas permintaan fitur filter annoyance. Ini adalah fitur yang sangat bermanfaat bagi masyarakat luas dan harus segera dibuat.

Sayangnya Saya harus menunda fitur tersebut untuk saat ini. Untuk menjaga kemampuan dalam memelihara kualitas AdBlockID secara memadai, Saya harus sangat berhati-hati dalam menyertakan filter.

Jika memungkinkan, harap pertimbangkan untuk menjadi maintainer aktif filter annoyance, dengan cara ini maka filter annoyance bisa segera dibuat dan masyarakat luas bisa segera menikmati manfaatnya.
