### ISSUE TITLE
karyawan.co.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1438]
![image](https://github.com/realodix/AdBlockID/assets/19517680/418188de-0917-47af-a10b-0f57dcbfd04e)

https://karyawan.co.id/

**Comment by realodix** [comment]
Ini mereka menetapkan secara manual, ada iklan atau tidak ada iklan, tingginya diatur ke 214.4px

Pakai ini saja

```adblock
karyawan.co.id##.site-content:style(margin-top: 100px!important;)
```

![noname](https://github.com/realodix/AdBlockID/assets/1314456/a2acaf0d-bea1-4e2e-a1ea-ed2e69533ef7)

**Comment by 3xploiton3** [comment]
kenapa tidak dimasukkan ke filter list?

![image](https://github.com/realodix/AdBlockID/assets/19517680/646944f8-e511-4831-ba69-62b3e14609dd)

baikknya masukkan ke annoyance/adblockid plus

**Comment by realodix** [comment]
Hmmm maaf, sepertinya penjelasan Saya kurang jelas ya..

Karena ini bukan termasuk annoyance atau ads placeholder, tetapi memang mereka mendesain webnya seperti itu. Jadi kita tidak perlu melakukan tweaking tampilan.

Saat ini angkanya sudah mereka ganti jadi `118.4px`, mendekati angka yang Saya kasih `100px`.

![noname](https://github.com/realodix/AdBlockID/assets/1314456/58362624-776a-4eaf-a092-d1721acdae35)

---

Kecuali memang terpaksa banget, contohnya seperti https://uzone.id/ yang terpaksa Saya tweaking untuk mencegah tampilannya hancur saat iklan dihilangkan.

<details>
  <summary>Screenshot sebelum</summary>
  
  ![noname](https://github.com/realodix/AdBlockID/assets/1314456/bc3814b5-082b-480b-baac-2016c819611c)
</details>

<details>
  <summary>Screenshot sesudah</summary>
  
  ![noname-crop](https://github.com/realodix/AdBlockID/assets/1314456/83d5b3e9-2ee6-4cde-a1f8-e97bd04c6e5d)
</details>

**Comment by realodix** [comment]
> ![image](https://user-images.githubusercontent.com/19517680/253594789-646944f8-e511-4831-ba69-62b3e14609dd.png)
> 
> baikknya masukkan ke annoyance/adblockid plus

Saat ini AdBlockID belum ada kebijakan minimal jumlah pengunjung, karena jika dibandingkan oleh top 10 filter regional, rata2 ada di angka belasan ribu filter, AdBlockID sendiri masih di bawah 10k. Jadi saat ini mau situs tidak terkenal pun bisa dimasukkan.

<details>
  <summary>Screenshot</summary>
  
  ![noname-crop](https://github.com/realodix/AdBlockID/assets/1314456/85783f00-76ff-4d85-b44a-eda711d728cc)
</details>

**Comment by 3xploiton3** [comment]
baik terimakasih penjelasannya, saya mengerti,
