### ISSUE TITLE
miteblog.com

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1442]
**Jenis**
- Pop-up
- Redirect

**Sample URL**
`https://miteblog.com/?id1=7.NoNiN_NnNiNL7oj8NV7r7~ND7uNO7S717I7vN9NANqNW7fNjjgN_72NnNKjPjCNFNUNxNANK7RN.NqNKN.NK7-N~N07lNpNiNw7o717ZNTNGNTNAjANV7yNWNpNrN9Nn7Z64b00616dc9e8a7298e6f012a39c4f79a0117a630eb3f63461263dd2658b57117~NnNkjEjAN9`

**Penjelasan Lebih Lanjut**
- android; firefox; ubo
- pas mau generate link download langsung dialihkan ke shopee. saya kasih screenshot di bawah

**Informasi link tambahan**
- original link `https://www.yurasu.xyz/2023/07/santa-cecilia-dan-romo-lawrence-episode.html` [1080p MiteDrive]
- shortlink awal `https://blog.yurasu.xyz/2023/01/manga-sasayaku-you-ni-koi-wo-utau-karya_13.html?m=1`

**Screenshot**

![IMG_20230715_072835](https://github.com/realodix/AdBlockID/assets/79722529/6489c87d-89a6-4747-8703-097235669f19)
![IMG_20230715_072844](https://github.com/realodix/AdBlockID/assets/79722529/ef43ac52-1977-4b45-b56d-dc72d1a152c8)

**Comment by realodix** [comment]
Thank you, update tersedia pada AdBlockID v23.7.52

Mohon ditest dan laporkan kembali jika masih terjadi masalah
