### ISSUE TITLE
kiryuu.id

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1444]
**Jenis**
- Iklan

**Sample URL**
`https://kiryuu.id/`

**Penjelasan Lebih Lanjut**
- Banner
![Screenshot_2023-07-16-06-28-41-21](https://github.com/realodix/AdBlockID/assets/79722529/47bd5508-897e-428b-9ce5-168870bb34db)

**Comment by realodix** [comment]
Thank you

- AdGuard: Tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.60, bisa langsung force update.
