### ISSUE TITLE
pojokmanga.net

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1445]
**Jenis**
- Iklan

**Sample URL**
`https://pojokmanga.net/`

**Penjelasan Lebih Lanjut**
- Banner

![Screenshot_2023-07-16-08-03-26-11](https://github.com/realodix/AdBlockID/assets/79722529/70d67ae8-5424-437f-a2d2-df85bf92a0cc)

![Screenshot_2023-07-16-08-04-21-63](https://github.com/realodix/AdBlockID/assets/79722529/ceaa4d4d-74cc-4c5c-b8b2-65db8d2a7d6f)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.61, silahkan force update.
