### ISSUE TITLE
mangakita.net

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1446]
**Jenis**
- Iklan
- Pop-up

**Sample URL**
`https://mangakita.net/`

**Penjelasan Lebih Lanjut**
- floating close teaser
- modal popup overlay

![Screenshot_2023-07-16-08-10-22-05](https://github.com/realodix/AdBlockID/assets/79722529/855bab33-574c-4ff2-adab-12797e330f73)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.61, silahkan force update.
