### ISSUE TITLE
ometlit.com

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1447]
**Jenis**
- Pop-up
- Redirect

**Sample URL**
`https://ometlit.com/`

**Penjelasan Lebih Lanjut**
- ketuk/klik dimanapun dialihkan ke shopee. pas saya klik 'open' langsung ke mobile appnya

![IMG_20230716_083023](https://github.com/realodix/AdBlockID/assets/79722529/98e1ef10-6158-4872-a2e5-652fc21feb50)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.61, silahkan force update.
