### ISSUE TITLE
hellosehat.com

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1449]
<details>
  <summary>Screenshot</summary>
  
  ![20230716_134508_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/2cf47fe9-bfb1-4e3b-a904-8a3b740b1e41)
</details>

<details>
  <summary>Screenshot 2</summary>
  
  ![20230716_133246_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/23062f6f-fbaa-41f1-99e7-c1412d5e3755)
</details>

https://hellosehat.com/seks/tips-seks/cara-merangsang-g-spot/
Banner pop up

**Comment by Jokopentil** [comment]
Muncul setelah beberapa menit

**Comment by Jokopentil** [comment]
![20230716_201912_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/04a6b1b2-91c1-4d70-b714-5292a6a58771)

Hanya menambahkan muncul notifikasi di bawah

**Comment by realodix** [comment]
Kak maaf, setelah Saya lihat, ini di luar jangkauan AdBlockID.

1. Websites’ own ads: Banner yang mengiklankan layanan di situs sendiri tidak boleh dengan sengaja dihilangkan.
2. Walaupun ini masuk ke dalam `annoyance`, namun ini berdasarkan preferensi pribadi, artinya sebagian orang bisa merasa terganggu dan sebagian orang juga bisa merasa bermanfaat. Ini harus dimasukkan ke dalam `optional filter`, jadi user bisa bebas untuk menggunakannya atau tidak. AdBlockID sendiri belum memiliki optional filter khusus menangani annoyance.

Kakak bisa langsung menggunakan filter ini AdGuard – Annoyances, EasyList – Annoyances dan uBlock filters – Annoyances.

---

Saat ini, Saya fokus menghilangkan area seperti ini

![noname](https://github.com/realodix/AdBlockID/assets/1314456/b6bb6122-1269-4113-bb2b-ea50cbd4ba40)
