### ISSUE TITLE
hops.id

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1450]
![20230716_163022_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/c7900855-ccf5-4f24-b2b8-973e5487dac3)

![20230716_163013_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/58c0df95-8495-4fed-b415-566b0283ebd9)

Banner dan vidio iklan
https://www.hops.id/hot/pr-2946971509/usai-bercerai-iyeth-bustami-dituding-jadi-perusak-rumah-tangga-mantan-suami-hingga-dilaporkan-ke-polisi

**Comment by Jokopentil** [comment]
Tunggu beberapa detik baru muncul

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.62, silahkan force update.
