### ISSUE TITLE
niagahoster.co.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1451]
![image](https://github.com/realodix/AdBlockID/assets/19517680/88cbc84a-0b45-41c7-9a69-de5c4fcc9a4d)

https://www.niagahoster.co.id/blog/mengurangi-ttfb/

**Comment by realodix** [comment]
Ini mirip seperti https://github.com/realodix/AdBlockID/issues/1438, memang desainnya seperti itu

Kelas CSS untuk `site-content` mereka tetapkan `margin-top: 256px;`.


![noname](https://github.com/realodix/AdBlockID/assets/1314456/98d280c7-dbff-4b30-8a14-b2410fb920dc)
