### ISSUE TITLE
mirrorkomik.net

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1452]
**Jenis**
- Iklan

**Sample URL**
https://mirrorkomik.net/Anime

**Penjelasan Lebih Lanjut**
![image](https://github.com/realodix/AdBlockID/assets/19517680/6b6fc055-b230-4d18-925e-14e8fb654f78)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.64, silahkan force update.
