### ISSUE TITLE
info.gambar.pro

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1455]
**Jenis**
- Iklan
- Anti-Adblock

**Sumber URL**
`https://apk.miuiku.com/F3SYxVHZ`

**Penjelasan Lebih Lanjut**
- adblock detection
- fake download button

<details><summary>Screenshot</summary>
<p>

![Screenshot_2023-07-20-08-44-14-52](https://github.com/realodix/AdBlockID/assets/79722529/5d2f4648-887a-40cb-987b-112d7a7e16f6)

</p>
</details>

**Comment by realodix** [comment]
Thank you, ini outputnya


https://github.com/realodix/AdBlockID/assets/1314456/15d4391e-2e67-443f-9468-6bb8caabacfb

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.73, silahkan force update.

**Comment by T-Baniza** [comment]
> Thank you, ini outputnya

Wah terima kasih!
