### ISSUE TITLE
indofilm.sbs 

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1456]
https://www.juraganfilm.sbs/
![20230720_170329_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/fcef43e5-7c7e-49e6-be59-b34c4d4f5266)

![20230720_165743_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/5d05ebd7-d800-46d3-84ff-365f8f1349d1)

Layar jadi hitam 
Sepertinya pop up banner / annoyance yg kurang terblokir sempurna

**Comment by Jokopentil** [comment]
Tunggu beberapa detik

**Comment by realodix** [comment]
Ini karena perubahan domain dari indofilm.buzz ke indofilm.sbs 

Sudah direvisi di https://github.com/realodix/AdBlockID/commit/fbcf2796b6e7ae0e180d1472b167181b8b0e5ce1 sekitar 1 jam yang lalu

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.76, silahkan force update.
