### ISSUE TITLE
tonanmedia.my.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1457]
**Jenis**
- Anti-Adblock

**Sample URL**
https://www.tonanmedia.my.id/2023/06/genshin-impact-mendapatkan-adaptasi.html#?o=4d82cdfa1ec2ea1d45f468b6c3cf4db3bf3a263726f89a280ac1ece0bc115ec41d26002276838e5d

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Saya gak yakin ini perlu dilakukan penanganan, karena ini bener2 berjalan normal

https://github.com/realodix/AdBlockID/assets/1314456/250dbdf8-2702-4988-847c-fe8c8f06d3cd
