### ISSUE TITLE
thejakartapost.com

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1459]
**Jenis**
- Iklan
- Annoyances

**Sample URL**
`https://www.thejakartapost.com/`

**Penjelasan Lebih Lanjut**
- sticky bottom

<details><summary>Details</summary>
<p>

![IMG_20230721_035832](https://github.com/realodix/AdBlockID/assets/79722529/418dc22b-17fd-4a73-a4f2-edb54a63b93c)

![IMG_20230721_035825](https://github.com/realodix/AdBlockID/assets/79722529/6bf3d7a8-0218-4fd0-9dd4-860561e051b1)

</p>
</details>

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.79, silahkan force update.
