### ISSUE TITLE
beritasatu.com

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1460]
**Jenis**
- Iklan
- Annoyances

**Sample URL**
`https://www.beritasatu.com/`

**Penjelasan Lebih Lanjut**
- blank space
- top ads

<details><summary>Details</summary>
<p>

![IMG_20230721_041708](https://github.com/realodix/AdBlockID/assets/79722529/db31510e-1471-4bcd-aa30-2a8bcd4f6c7d)

</p>
</details>

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.79, silahkan force update.
