### ISSUE TITLE
samehadaku.skin

### ISSUE THREAD

**Issue by cyberboh** [realodix/AdBlockID#1463]
**Jenis**
popup gamble site
![image](https://github.com/realodix/AdBlockID/assets/99109969/a0a8a4a4-c74e-46fd-95a8-4af6901162c2)

**Sample URL**
`https://samehadaku.skin/bleach-sennen-kessen-hen-ketsubetsu-tan-episode-3/`

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman video player

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.91, silahkan force update.
