### ISSUE TITLE
mangakyo.org

### ISSUE THREAD

**Issue by ChowMein47** [realodix/AdBlockID#1464]
**Jenis**
- Iklan judi 

**Sample URL**
https://mangakyo.org/

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman 
- 
![Screenshot_2023-07-23-18-45-51-99_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/98148960/da3c61ec-f0d7-4ac7-b324-77260ba283f0)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.93, silahkan force update.
