### ISSUE TITLE
shinigami.id

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1465]
**Jenis**
- Iklan
- Pop-up

**Sample URL**
`https://shinigami.id/`

**Penjelasan Lebih Lanjut**
- popup muncul setelah 1-2 detik

<details><summary>Screenshot_2023-07-24-07-44-13-03.jpg</summary>
<p>

![Screenshot_2023-07-24-07-44-13-03](https://github.com/realodix/AdBlockID/assets/79722529/e656034d-6d87-47e2-bd08-ddaa2cb058b2)

</p>
</details>

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.94, silahkan force update.
