### ISSUE TITLE
tirto.id

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1466]
**Jenis**
- Iklan

**Sample URL**
`https://tirto.id/`

**Penjelasan Lebih Lanjut**
- banner di halaman depan dan di dalam artikel

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.94, silahkan force update.
