### ISSUE TITLE
katadata.co.id

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1467]
**Jenis**
- Iklan
- Anti-Adblock

**Sample URL**
`https://katadata.co.id/`

**Penjelasan Lebih Lanjut**
- muncul blank white space di atas (muncul cuma 1 detik), kayaknya anti-adblock ya? Soalnya pas scroll ke bawah otomatis langsung ke atas lagi. Versi desktop bisa scroll ke bawah tapi kadang muncul white space di atas lagi, sedangkan mobile cuma muncul beberapa detik tapi ga bisa scroll ke bawah

<details><summary>IMG_20230724_103057.jpg</summary>
<p>

![IMG_20230724_103057](https://github.com/realodix/AdBlockID/assets/79722529/1783d7d7-7ced-4cdf-8096-a1d22152985c)

</p>
</details>

**Comment by realodix** [comment]
Di Saya aman, HP (AdGuard) dan PC (uBlock Origin).

Kemungkinan nge-glitch aja, karena prosesnya ada 3 tahap

1. Tahap pertama easylist coba nge-blokir jaringan iklannya.

<details>
  <summary>Screenshot 1</summary>
  
  ![noname-crop](https://github.com/realodix/AdBlockID/assets/1314456/9adb5c06-d75d-454b-b4da-1bcc2de60e69)
</details>

2. Tahap kedua easylist coba membuang objectnya

<details>
  <summary>Screenshot 2</summary>
  
  ![noname-crop2](https://github.com/realodix/AdBlockID/assets/1314456/c93a4f5a-a7b1-43c2-916b-afb40347a189)
</details>

3. Tahap 3, AdBlockID coba membuang object yang tersisa

<details>
  <summary>Screenshot 3</summary>
  
  ![noname-crop3](https://github.com/realodix/AdBlockID/assets/1314456/0104f427-7d5d-4257-8c95-2adf314dd90b)
</details>

---

> ga bisa scroll ke bawah

Di Saya aman gak ada masalah, skenario yang bisa Saya jalankan untuk gak bisa scroll ke bawah adalah harusnya ada popup, nah itu popup kalau dipaksa dihilangkan akan muncul efek susah scroll hingga popupnya bner2 hilang

<details>
  <summary>Screenshot</summary>
  
  
   ![noname-crop](https://github.com/realodix/AdBlockID/assets/1314456/43e7f92e-e59f-45ab-a128-9d490206e3c2)
</details>


Apakah ada filter khusus yang mencoba menghilangkan popupnya?

**Comment by T-Baniza** [comment]
> Apakah ada filter khusus yang mencoba menghilangkan popupnya

Ngga ada Gan, popup muncul secara normal.
Saya coba reset ulang uBo; default filter lists, AdBlockID, ABPindo. Ga ada ekstensi tambahan, kejadian serupa terulang.

> Kemungkinan nge-glitch aja

Kayaknya untuk uBo firefox mobile betul nge-glitch Gan, atau mungkin di hp saya aja begini.
Setelah saya coba pakai brave browser (nightly) dengan tambahan filter AdBlockID ga ada kejadian serupa. Empty space atas ilang, scrolling berjalan normal.

**Comment by realodix** [comment]
Jika seperti itu, kemungkinan besar hanya nge-glitch saja.

Saya akan tutup issue ini, thank you
