### ISSUE TITLE
mangakyo.org

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1470]
**Jenis**
- Iklan

**Sample URL**
`https://mangakyo.org/my-civil-servant-life-reborn-in-the-strange-world-chapter-00/`

<details><summary>Screenshot_2023-07-27-09-51-36-08.jpg</summary>
<p>

![Screenshot_2023-07-27-09-51-36-08](https://github.com/realodix/AdBlockID/assets/79722529/3d91dad4-3afe-4066-b8e3-f4a9f3c5b83e)

</p>
</details>

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.119, silahkan force update.
