### ISSUE TITLE
livebasah.eu.org

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1474]
https://livebasah.eu.org/category/mango-live/page/9/

**Comment by Jokopentil** [comment]
![20230729_214454_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/a3b999e9-bc2d-4892-a2fd-4bdf78d2bf00)

Semua link vidio mengandung pop up
Saat di putar juga membuka banyak tab
Saya coba lapor ke adguard eror saat kirim
Jadi tolong laporkan

**Comment by Jokopentil** [comment]
Kiwi browser

**Comment by realodix** [comment]
Thank you, popup untuk livebasah.eu.org sudah ditangani

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.127, silahkan force update.

---

> Semua link vidio mengandung pop up
> Saat di putar juga membuka banyak tab
> Saya coba lapor ke adguard eror saat kirim
> Jadi tolong laporkan

Kemungkinan ada di server tempat mereka upload video. Ini bisa langsung ke AdGuard.

Saya coba buka 3 link di atas
- https://livebasah.eu.org/hana-tiktok-aka-lisachan-mango-live/
- https://livebasah.eu.org/joget-seksi-dj-vika/
- https://livebasah.eu.org/streamer-tobrut-uting-pink/

Semuanya gak ada popup, link videonya yang mana ya?

**Comment by Jokopentil** [comment]
Oke

**Comment by realodix** [comment]
> di situs ini juga terdeteksi adblock

@ChowMein47

Contoh linknya yang mana ya? 3 link contoh yang Saya bagikan di sini gak ada terdeteksi adblocker

**Comment by Jokopentil** [comment]
Untuk pop up itu sudah di tangani team adguar
https://livebasah.eu.org/baby-cewek-oppai-gede/
Link diatas ini ada banner timer delay
Jika di klik muncul pop up
![20230730_094201_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/8f20d871-7584-4c9a-a5f6-208acfeeb9f4)

Lihat pojok atas ada timer

**Comment by Jokopentil** [comment]
https://livebasah.eu.org/vale-mango-live-perah-asi/ adblock detect nya ada di sini
Gk semua ad

**Comment by realodix** [comment]
> https://livebasah.eu.org/vale-mango-live-perah-asi/ adblock detect nya ada di sini 
> Gk semua ad

Ini juga gak ada, ada link aktual yang lain gak?

**Comment by Jokopentil** [comment]
Itu adblock detect it
Di adguard terbaca

**Comment by Jokopentil** [comment]
Khusus yg initimer banner link pop up
![20230730_124334_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/10847b15-5fec-4bed-a925-88c5dd811345)

https://livebasah.eu.org/baby-cewek-oppai-gede/

**Comment by Jokopentil** [comment]
Apakah bisa timernya di ilangkan

**Comment by realodix** [comment]
Ini sudah masuk ke filter utama

- https://github.com/uBlockOrigin/uAssets/commit/7a4d5f5135baab5d94ce9b690765d785d8d0ff30
- https://github.com/easylist/easylist/commit/545a9b411b2393a1526082753ec19fa3fd7954b6
- https://github.com/AdguardTeam/AdguardFilters/commit/4e7ce59132dbf36c80ea85707318f67c26268c19

---

> Itu adblock detect it
> Di adguard terbaca

https://github.com/realodix/AdBlockID/issues/1474#issuecomment-1657049034

Gak ada yang dapat dilakukan jika Saya tidak melihatnya. Saya lihat di `https://github.com/AdguardTeam/AdguardFilters/issues/157701#issuecomment-1657111452` mengatakan `I can't reproduce` yang menandakan mereka juga tidak melihatnya, mungkin ada step yang kita lewatkan?
