### ISSUE TITLE
livebasah.eu.org

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1475]
https://livebasah.eu.org/baby-cewek-oppai-gede/
Pop up timer delay jika di klik pop up window
![20230730_011738_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/ccfd6986-7d52-40af-a37f-b35be3c37dd4)
Bisa di handle besok saja sudah malam🙏🙏 maaf sudah menggangu

**Comment by Jokopentil** [comment]
![20230730_011738_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/4752405f-4e3e-41ed-bce3-7b40f6449cb9)

**Comment by realodix** [comment]
Ini sudah masuk ke filter utama

- https://github.com/uBlockOrigin/uAssets/commit/7a4d5f5135baab5d94ce9b690765d785d8d0ff30
- https://github.com/easylist/easylist/commit/545a9b411b2393a1526082753ec19fa3fd7954b6
- https://github.com/AdguardTeam/AdguardFilters/commit/4e7ce59132dbf36c80ea85707318f67c26268c19
