### ISSUE TITLE
`yasir252.com`

### ISSUE THREAD

**Issue by cyberboh** [realodix/AdBlockID#1476]
**Jenis**
- reveal unlock download link w/o ads

**Sample URL**
`https://www.yasir252.com/software/vuescan-pro-full-version-win-mac/`

**Penjelasan Lebih Lanjut**
![image](https://github.com/realodix/AdBlockID/assets/99109969/9df19d01-d4a6-4faf-8999-fc2f7d068b11)

**Comment by partingscientist** [comment]
Not sure what the maintainer thinks, but revealing the no-ads download button might be out of scope.

The with-ads download button is probably within scope though. Can you test the following?
```adblock
jenismac.com##+js(noeval-if, /chp_?ad/)
jenismac.com##+js(nano-sib)
jenismac.com###hello
```

**Comment by realodix** [comment]
Maaf, tidak ada yang dapat Saya lakukan, karena itu terjadi di sisi server mereka.

Thank you
