### ISSUE TITLE
`www.jenismac.com`

### ISSUE THREAD

**Issue by cyberboh** [realodix/AdBlockID#1477]
**Jenis**
anti adblock

**Sample URL**
`https://www.jenismac.com/top-10-cloud-service-providers-globally-in-2023/`
the url above came from `https://www.yasir252.com/software/vuescan-pro-full-version-win-mac/`

**Penjelasan Lebih Lanjut**
![image](https://github.com/realodix/AdBlockID/assets/99109969/e1edace8-21b1-4e9f-892b-dac28b4bca14)

**Comment by partingscientist** [comment]
Can you test the following?
```adblock
jenismac.com##+js(noeval-if, /chp_?ad/)
jenismac.com##+js(nano-sib)
jenismac.com###hello
```

**Comment by realodix** [comment]
> Can you test the following?
> 
> ```
> jenismac.com##+js(noeval-if, /chp_?ad/)
> jenismac.com##+js(nano-sib)
> jenismac.com###hello
> ```

@partingscientist Thank you

---

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.7.129, silahkan force update.
