### ISSUE TITLE
paylaterin.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1485]
https://www.paylaterin.com/bni-mobile-banking-error-304/

**Comment by 3xploiton3** [comment]
ketika back malah redirect ke shopee

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.6, silahkan force update.
