### ISSUE TITLE
erocafe.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1486]
**Jenis**
- Anti-Adblock

**Sample URL**
https://erocafe.net/

**Penjelasan Lebih Lanjut**
- Terdapat iklan di halaman ...

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.7, silahkan force update.

**Comment by Recehan-Slayer** [comment]
masi ada bro

**Comment by Recehan-Slayer** [comment]
uBlock Origin: 1.51.0
Chromium Mobile: 116
filterset (summary):
 network: 167708
 cosmetic: 169121
 scriptlet: 37822
 html: 0
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 10358-5, 1m
  adguard-cookies: 26525-29, 1m
  adguard-generic: 72944-554, now
  adguard-mobile-app-banners: 4474-14, 1m
  adguard-other-annoyances: 13201-42, 1m
  adguard-popup-overlays: 23214-69, 1m
  adguard-social: 21083-905, 1m
  adguard-spyware: 62188-1325, 1m
  adguard-widgets: 2249-7, 1m
  ublock-cookies-adguard: 286-4, now
 default:
  user-filters: 5-0, never
  adguard-mobile: 8472-48, now
  easylist: 68211-1634, never
  easyprivacy: 33319-16852, 1m
  plowe-0: 3717-874, 1m
  ublock-badware: 7673-255, 1m
  ublock-filters: 34442-4216, 1m
  ublock-privacy: 447-61, 1m
  ublock-quick-fixes: 262-28, 1m
  ublock-unbreak: 2111-130, 1m
  urlhaus-1: 6843-0, 1m
filterset (user): [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1589 ms (selfie)
 maxAssetCacheWait: 315 ms

masi muncul

**Comment by Recehan-Slayer** [comment]
uBlock Origin: 1.51.0
Chromium Mobile: 116
filterset (summary):
 network: 167708
 cosmetic: 169121
 scriptlet: 37822
 html: 0
listset (total-discarded, last-updated):
 removed:
  IDN-0: null
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 10358-5, 1m
  adguard-cookies: 26525-29, 1m
  adguard-generic: 72944-554, now
  adguard-mobile-app-banners: 4474-14, 1m
  adguard-other-annoyances: 13201-42, 1m
  adguard-popup-overlays: 23214-69, 1m
  adguard-social: 21083-905, 1m
  adguard-spyware: 62188-1325, 1m
  adguard-widgets: 2249-7, 1m
  ublock-cookies-adguard: 286-4, now
 default:
  user-filters: 5-0, never
  adguard-mobile: 8472-48, now
  easylist: 68211-1634, never
  easyprivacy: 33319-16852, 1m
  plowe-0: 3717-874, 1m
  ublock-badware: 7673-255, 1m
  ublock-filters: 34442-4216, 1m
  ublock-privacy: 447-61, 1m
  ublock-quick-fixes: 262-28, 1m
  ublock-unbreak: 2111-130, 1m
  urlhaus-1: 6843-0, 1m
filterset (user): [array of 5 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 ignoreGenericCosmeticFilters: false
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1589 ms (selfie)
 maxAssetCacheWait: 315 ms

masi muncul

**Comment by realodix** [comment]
<details>
  <summary>Screenshot</summary>
  
  ![unnamed](https://github.com/realodix/AdBlockID/assets/1314456/8db620ec-0f97-4973-8175-b32365fb0483)
</details>

Saya coba buka di Kiwi dengan konfigurasi uBO yang sama, hasilnya aman kok. Kecuali jika menu "Block ads" pada kiwi dicentang, maka akan muncul peringatan.

**Comment by Recehan-Slayer** [comment]
block ads kaga di centang tp aneh kadang suka muncul

**Comment by realodix** [comment]
Klo dilihat dari kodenya, mereka pakai `https://wordpress.org/plugins/chp-ads-block-detector/`

CHP akan aktif jika 
- `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` terblokir. 
- Berapa element terhidden.

Untuk mengatasinya, Saya membiarkan `/adsbygoogle.js` untuk direquest dan membuka semua geniric hide untuk menghindari CHP terpicu aktif.

Kemungkinan ada plugin lain atau apapun itu di sisi Anda yang tidak sengaja memblokir.
