### ISSUE TITLE
juraganfilm.icu

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1487]
https://www.juraganfilm.icu/
Juraganfilm.sbs
![20230801_224217_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/e3d0fb2c-694d-495d-ad90-de43425bda99)

Layar jadi hitam

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.8, silahkan force update.
