### ISSUE TITLE
merdeka.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1488]
https://www.merdeka.com/jateng/6-ciri-ciri-orang-beriman-dalam-islam-perlu-diketahui-kln.html

![image](https://github.com/realodix/AdBlockID/assets/19517680/07c9043c-6460-4a81-954d-7879ee322970)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.22, silahkan force update.
