### ISSUE TITLE
pecintabokep.club

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1490]
https://pecintabokep.club/bokep-indo/bokep-indo-masih-smp-ngentod-di-kamar-mandi-bokepsin-com/
Iklan
![20230803_203342_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/c3ff7e8e-1dce-4405-af0c-0b27703d3022)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.23, silahkan force update.
