### ISSUE TITLE
sekaikomik.bio

### ISSUE THREAD

**Issue by ChowMein47** [realodix/AdBlockID#1492]
**Jenis**
- Pop-up
- redirect

**Sample URL**
https://sekaikomik.bio/

**Penjelasan Lebih Lanjut**
- Pop up/redirect mengarah ke situs lain

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.27, silahkan force update.
