### ISSUE TITLE
kiryuu.id

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1493]
**Sample URL**

`https://kiryuu.id/`

**Penjelasan Lebih Lanjut**

clicking anywhere will trigger a popunder to `kaya303.us`

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.31, silahkan force update.
