### ISSUE TITLE
mangaindo.me

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1494]
**Sample URL**

`https://mangaindo.me/`

**Penjelasan Lebih Lanjut**

close teaser

<details><summary>Screenshot.jpg</summary>
<p>

![Screenshot_2023-08-06-13-28-28-43](https://github.com/realodix/AdBlockID/assets/79722529/6bfd79fa-a28b-4de6-85b0-efec357adbde)

</p>
</details>

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.31, silahkan force update.
