### ISSUE TITLE
mgkomik.com

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1495]
**Sample URL**

`https://mgkomik.com/`

**Penjelasan Lebih Lanjut**

close teaser

<details><summary>Screenshot.jpg</summary>
<p>

![IMG_20230806_133504](https://github.com/realodix/AdBlockID/assets/79722529/89c38f29-59d2-4d64-97b1-c3caabfe5f1f)

</p>
</details>

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.32, silahkan force update.
