### ISSUE TITLE
isekaipalace.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1496]
**Sample URL**
https://www.isekaipalace.com/2022/11/author-mushoku-tensei-merayakan-ulang.html#?o=58c427da7b708d8fc1aec32a3a604ce9302e1977a0f07f5e5b866027b470e312b21a78b38968d0e23e8307a1f6ac468284292c1f2184cb7088efe69d875942d365db1f77c27c3514e0e6c7c2489e2bc3535ace51a1ddbaac77795d618644fe2bae5a7a96793a26e8

**Penjelasan Lebih Lanjut**
ga bisa di klik 
...

**Comment by Recehan-Slayer** [comment]
di klik menuju linknya

**Comment by Recehan-Slayer** [comment]
![Screenshot 2023-08-08 013202](https://github.com/realodix/AdBlockID/assets/9379770/1e6d3a9e-c69b-405b-b3b9-e70a0e746cd8)
![Screenshot 2023-08-08 013208](https://github.com/realodix/AdBlockID/assets/9379770/f3c5dd1c-68eb-4281-ae20-9c02bd2fd327)

**Comment by Recehan-Slayer** [comment]
`https://drive.google.com/file/d/1EXYgxuc-KCGEkPKaycARnTpFWVmDNODS/view?usp=sharing`

**Comment by Recehan-Slayer** [comment]
klo yang ini bisa di klik templatenya sepertinya sama
`https://www.tonanmedia.my.id/2023/05/oda-mengatakan-bahwa-live-action.html#?o=63a018231a879bd8f6727675a7fa85d1b92396d574bff28a71ca239e6a8e09ec1f1555f6cd412a1020e9005fede7fb30e397c386267d094aa7458183e05343764634f4e681065d64435b4364be9916ed76f16251a4eeb82fae4f85848b9e871128dd7447f1e7b7da4a880435bc2c4f7ec92406b1cb12e46c3f5197b11e2973a7006af74bead71381`

**Comment by realodix** [comment]
Saat ini di Saya juga tidak dapat diklik. Saya coba mematikan ad blocker di isekaipalace.com untuk melihat aslinya seperti apa? Hasilnya gak bisa diklik juga. Jika seperti ini, tidak ada yang dapat Saya lakukan.




https://github.com/realodix/AdBlockID/assets/1314456/e7fd0bc4-fadc-4ed3-af55-38143dd36133

**Comment by T-Baniza** [comment]
coba pakai mobile Gan? Di saya bisa

<details><summary>Details</summary>
<p>

![Screenshot_2023-08-08-02-01-47-97](https://github.com/realodix/AdBlockID/assets/79722529/3a01d2e2-57a9-4e92-bc0d-f0073d96032e)
![Screenshot_2023-08-08-02-01-56-07](https://github.com/realodix/AdBlockID/assets/79722529/f1d677fb-fb18-4841-ba4b-72e5d62b13d7)
![Screenshot_2023-08-08-02-02-11-02](https://github.com/realodix/AdBlockID/assets/79722529/0cc3c45e-4ea1-49dd-b0f1-d6197fd80170)


</p>
</details>

**Comment by realodix** [comment]
Sekarang sudah bisa kembali. Saya gak ngerti kenapa.

https://github.com/realodix/AdBlockID/assets/1314456/af21216a-ec41-4c34-a1f2-c2a68dbaab16

**Comment by Recehan-Slayer** [comment]
gw coba clear cookies dan site data bisa bro tp kadang suka gitu lg di link yg laen. kadang bisa di klik kadang ngga ntah knp

**Comment by realodix** [comment]
Saya tutup dulu ya

Dalam issue ini, gak ada perubahan yang Saya lakukan, hanya menghilangkan sisa2 banner saja dan menambah filter untuk AdGuard user.

Terima kasih

**Comment by Recehan-Slayer** [comment]
@realodix https://www.isekaipalace.com/2022/11/author-mushoku-tensei-merayakan-ulang.html#?o=3f784329d67d6af33c451db7696d19df026c6f779ec892afe9caef0b490b8ddf8a51018940c631d801b6a90cc7e8e58c7281f509d732f017a2d0bc351fb845e40841fb48ec6fe6b628aa0dde60d61bb8e2105003c39a8472710b37e7f96c7f634326ed8b0fe1b540
muncul lg bro

**Comment by Jokopentil** [comment]
Anti adblock gak terdeteksi oleh ublock origin
Tapi ada annoyances di paling bawah
![Screenshot_2023-10-14-07-32-48-20_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/25922da3-f352-4807-a718-92e418bc8775)

Di adguard memang sepertinya ada

**Comment by Jokopentil** [comment]
Anti adblock gak terdeteksi oleh ublock origin
Tapi ada annoyances di paling bawah
![Screenshot_2023-10-14-07-32-48-20_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/25922da3-f352-4807-a718-92e418bc8775)

Di adguard memang sepertinya ada
![Screenshot_2023-10-14-07-38-20-93_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/75b3901e-3691-4806-ab44-13b9248403ac)

Pakai ublock origin hp bisa di putar
GK tau kalau di windows

**Comment by Jokopentil** [comment]
Tolong di cek pakai adguard di hp saya juga mengalami kendala saat menuju link yg di maksud setelah klik lemot loading erorr

**Comment by Jokopentil** [comment]
Untuk menuju link emang suka eror kak
Kadang kena kadang tidak
Seperti safe link
Coba minta bantuan tim adguard

**Comment by realodix** [comment]
Changelog
- ads placeholder tampilan mobile paling bawah.
- Peringatan anti-adblock gak disentuh, sejauh ini hillang dengan sendirinya setelah beberapa detik.
---

> Tapi ada annoyances di paling bawah
Peringatan cookies gak disentuh, ini harus dimasukkan ke filter annoyances terpisah.

> Tolong di cek pakai adguard di hp saya juga mengalami kendala saat menuju link yg di maksud setelah klik lemot loading erorr
Testing tanpa adblock sepenuhnya juga sama, lemot dan loadingnya lama
