### ISSUE TITLE
kompas.tv

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1498]
https://www.kompas.tv/lifestyle/430396/rawon-posisi-pertama-ini-10-sup-terenak-di-dunia-2023-versi-taste-atlas
![20230808_141308_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/a6c13842-7092-4b39-a1ae-79f3ee3882cc)

Memaksa untuk login ,di tekan tanda x
Tak mau hilang
Tak bisa buka halaman show all

...

**Comment by realodix** [comment]
Pada issue ini, yang Saya kerjakan
- Menghilangkan video autoplay yang tidak berhubungan dengan artikel

Thank you
- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.43, silahkan force update.

---

Untuk masalah dipaksa login, memang itu sistem keamanannya dia, seharusnya tidak boleh diganggu gugat, paling jauh hanya menghilangkan popup login saja.

Saja coba membuka halamannya
- Saya tidak menemukan popup login.
- Tombol show all berfungsi normal, bisa diklik dan halamannya terbuka.

https://github.com/realodix/AdBlockID/assets/1314456/66acb7cf-7984-4def-9efe-a674b41a04de
