### ISSUE TITLE
brouhahastudio.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1499]
![image](https://github.com/realodix/AdBlockID/assets/19517680/830a3749-1a7f-4671-943d-8d24a8595ed0)

https://www.brouhahastudio.com/portfolio/

right-click disable

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.43, silahkan force update.
