### ISSUE TITLE
komikcast.vip

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1502]
**Sample URL**
https://komikcast.vip/

**Penjelasan Lebih Lanjut**
Domain baru dari komikcast.io
...

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.52, silahkan force update.
