### ISSUE TITLE
lendrive.web.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1504]
![image](https://github.com/realodix/AdBlockID/assets/19517680/ac1e2ec0-cde5-42c4-924f-26f3bcbe4f5b)

https://lendrive.web.id/

**Comment by realodix** [comment]
Saya tidak menemukannya. Ini harus menunggu setelah beberapa detik ya atau mungkin ada yang harus diklik?

**Comment by Jokopentil** [comment]
![20230814_120402_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/6ef7a630-673a-43f6-986d-d0ddf6593508)


Itu terindikasi malware setelah di buka

**Comment by 3xploiton3** [comment]
> Saya tidak menemukannya. Ini harus menunggu setelah beberapa detik ya atau mungkin ada yang harus diklik?

tidak ada itu tampilan awal di beranda website, sementara saya cek ulang sudah hilang
