### ISSUE TITLE
tutsnode.net

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1505]
https://github.com/uBlockOrigin/uAssets/issues/19336

**Comment by realodix** [comment]
Saya cukup bingung untuk menanggapi issue ini.

Singkatnya, ini bukan bug, tapi anti-adblock. 

1. Jika kita melihat https://github.com/AdguardTeam/AdguardFilters/issues/120116 dan https://github.com/AdguardTeam/AdguardFilters/issues/140173, tutsnode.net sudah 2x dilaporkan untuk kategori anti-adblock dan semuanya tidak ada AdBlockID.
2. Kebeneran salah satu filter di AdBlockID terkena perangkapnya dan memicu anti-adblock di tutsnode.net. Saat ini filter tersebut sudah Saya hapus. Tetapi ini tidak menyelesaikan sumber masalah utamanya, dimana anti-adblocknya tidak dilumpuhkan, jadi mereka dapat dengan mudah mengganti pengaturan perangkap mereka untuk menangkap filter lainnya dan memicu anti-adblock kembali.
3. Saya dapat dengan mudah melumpuhkan anti-adblock tutsnode.net dengan meminjam kode dari AdGuard, agar tidak terjadi lagi di uBO, tetapi karena ini situs internasional, ini harus ditangani di fillter uBO. Maka ketika mereka mengganti pengaturan perangkap mereka, tidak akan memicu anti-adblock seperti di AdGuard.

Terima kasih
