### ISSUE TITLE
vpnjantit.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1506]
![image](https://github.com/realodix/AdBlockID/assets/19517680/eb36113b-7ebd-4ba1-9be5-8b843ff9ba48)

https://www.vpnjantit.com/free-wireguard-indonesia

**Comment by realodix** [comment]
Ini bisa Saya masukkan ke dalam AdBlockID+, tapi sayangnya Saya tidak menemukannya

**Comment by Jokopentil** [comment]
Di saya juga tidak ada kiwi adguard
Mungkin itu terpengaruh extension yg lain? Coba cek extensi apa aja yg di instal

**Comment by 3xploiton3** [comment]
untuk sementara sudah hilang anti-adblock, setting tidak ada yg diubah, hanya force update ublock-origin,
