### ISSUE TITLE
globalssh.net

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1507]
https://globalssh.net/member/create/free/shadowsocks

![image](https://github.com/realodix/AdBlockID/assets/19517680/db5891f8-0fb5-49ba-b47d-5a3a918c8f58)
![image](https://github.com/realodix/AdBlockID/assets/19517680/6f402a33-198f-484b-b862-517465459cb9)

**Comment by realodix** [comment]
Jika Saya berhasil menanganinya, Saya bisa memasukkanya ke AdBlockID+. Sayangnya ini butuh login, sehingga Saya tidak dapat melihat kode mereka.
