### ISSUE TITLE
kurakura21 (170.64.254.40)

### ISSUE THREAD

**Issue by ChowMein47** [realodix/AdBlockID#1508]
**Sample URL**

http://170.64.254.40/

**Penjelasan Lebih Lanjut**
Anti adblock terdeteksi saat membuka link download
![Screenshot_2023-08-14-11-46-30-06_3aea4af51f236e4932235fdada7d1643](https://github.com/realodix/AdBlockID/assets/98148960/fbae76a4-6464-4fc6-8c2a-9587a505e497)

**Comment by Jokopentil** [comment]
![20230814_121457_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/755b180d-c359-4999-8332-1107c92e6276)


Di punyaku malah tak bisa di buka

**Comment by Jokopentil** [comment]
Aku buka semua terkait kurakura21 gak ada adblock detec
Itu situs dewasa bukan
Pake ke kiwi adguard

**Comment by Jokopentil** [comment]
Itu mungkin dark reader penyebabnya
Itu browser firefox bukan

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.66, silahkan force update.
