### ISSUE TITLE
Iklan inject dr Provider XL

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#151]
**Sample URL**
`http://ibn.adreach.co/ads-request?j=9&i=169523231&t=2&s=I04060157763197487093&a=https://yukisubs.com/`  
 
**Penjelasan Lebih Lanjut**
klo misal mau ngakses situs terkadang diarahkan dulu ke `http://ibn.adreach.co/ads-request?j=9&i=169523231&t=2&s=I04060157763197487093&a=domain situs yang di akses`

kira" apakah bisa diblock brow pke adblocker

**Comment by realodix** [comment]
> **Sample URL**
> `http://ibn.adreach.co/ads-request?j=9&i=169523231&t=2&s=I04060157763197487093&a=https://yukisubs.com/`
> 
> kira" apakah bisa diblock brow pke adblocker

Pas buka yuki

XL tumben inject iklan Gan. Kalau pakai AdGuard di HP, coba blokir alamatnya aja pakai user rules, dilihat di log keblokir gak alamatnya.

Kayaknya bisa deh, seperti yg dilakukan oleh @sentabi untuk blokir iklan indihome. 

https://github.com/sentabi/telkom

**Comment by WaferNabati** [comment]
ga cuman buka yuki aja pokoknya setiap berapa kali buka website entah puluhan atau ratusan psti ada inject iklan dr XL ntah axis kyknya jg sama atau opsel lainya

**Comment by WaferNabati** [comment]
@realodix `https://github.com/ABPindo/indonesianadblockrules/issues/113` di ABPindo sudah ditambahkan

**Comment by realodix** [comment]
Dan ternyata di AdBlockID juga sudah ada [0f63b3f#diff-1d08ead](https://github.com/realodix/AdBlockID/commit/0f63b3fd29306d37796f6819d5e1bed8d62e9504#diff-1d08ead25c2a0fcd65d245dbd44d0c2bR7) 😄 , mirip seperti di https://github.com/ABPindo/indonesianadblockrules/commit/7bd7a94766ca88a118c45a62a73c5209f26017f0 blockir `$third-party`.

Dari https://www.umimarfa.web.id/2016/03/cara-mengatasi-ibn-ads-xl.html, saya ketemu domain baru, `http://ibnads.xl.co.id/`. Mungkin karena `ibnads.xl.co.id`, jadi masih muncul (mungkin).

Saya tutup dulu, mohon dipantau Gan.

**Comment by WaferNabati** [comment]
@realodix iya skrng keknya uda ga muncul lg

**Comment by PenghancurRecehan** [comment]
@realodix yg XL udah ke block gan yg telkomsel blom
https://ads.telkomsel.com & http://ads.telkomsel.com

**Comment by realodix** [comment]
> @realodix yg XL udah ke block gan yg telkomsel blom
> https://ads.telkomsel.com & http://ads.telkomsel.com

@PenghancurRecehan Sudah ditambahkan, mohon dicheck kembali

**Comment by Recehan-Slayer** [comment]
@realodix  bangsat ini gan opsel indo emng, pkoknya klo ngakses situs yg bukan https ,ssl psti ada iklanya di inject klo bisa cari smua domain adservernya gan opsel indo
![Untitled](https://user-images.githubusercontent.com/9379770/72170746-01077180-3404-11ea-9ab5-b750dae74121.jpg)

**Comment by 3xploiton3** [comment]
Saya pakai dns dot.tiar.app dgn filter dr adblockid

Masih redirect ke sini
http://ibn.adreach.co/ads-request?j=9&i=174163715&t=2&s=I04120157979636880501&a=http://www.apps2sd.info/contact

**Comment by realodix** [comment]
@3xploiton3 Memangnya bisa ya dot.tiar.app? Setahu Saya kalau dns syntaxnya pakai ip biasa, gak bisa syntax filter. Gak tahu juga sih, Saya belum pernah pakai dot.tiar.app

**Comment by 3xploiton3** [comment]
@realodix hanya block di dns, annoying banget adsnya xl

**Comment by realodix** [comment]
@3xploiton3 Masalahnya pihak operator merasa tidak melanggar undang-undang yang berlalaku. Biasanya buka situs yang tidak menggunakan `https://` yang kena.

https://www.indotelko.com/read/1410401700/brti-iklan-sisipan-tak-melanggar-uu-ite

---

Terkdang ISP internet menyisipkan iklan pada sisi server, nah kalau kayak gini mau diblokir kayak apa juga gak bisa, hanya bisa di hidden aja di sisi client dengan manipulasi HTML oleh ad blocker.

**Comment by 3xploiton3** [comment]
@realodix bagaimana klo menggunakan jaringan full enkripsi seperti vpn?
Apakah msh bs di inject dr provider?

**Comment by realodix** [comment]
Kurang tau juga deh Bro, belum pernah bner2 nyoba. Mungkin bisa kali, situs terblokir aja bisa.

**Comment by realodix** [comment]
> http://rbt.xl.co.id/rbtapp/www/page/result_page.jsp?header=wap.level.0.header.nonsub.3&mcode=16470612&aotype=AOC2&crypt=NjI4NzgyNzM3MTI4MXwyMDIwMDIxODE2MTQ1Mnw2NGU4Yjg5Yzc3MTFiZmY4ODAzZmM0MGYzY2Q3NWM3NzQ1M2IyYjky
> 
> Ga sempat nangkap situs sebelumnya krn redirect ke situ
_https://github.com/realodix/AdBlockID/issues/435#issue-566751017 by @3xploiton3_

**Comment by Recehan-Slayer** [comment]
@realodix ibn.adreach.co masi tembus gan di hp klo yg diblock 3pnya. Ini gw pke opsel axis
ibn.adreach.co/interstitial?orgUrl=http%3A%2F%2Fanimekompi.web.id%2F&adsTransactionId=D0486689241255630&interstitialTimeout=18&width=320&height=480&i=169032909&clickUrl=http%3A%2F%2Fibn.adreach.co%3A80%2Fads-click%3F%26adsTransactionId%3DD0486689241255630%26targetUrl%3Dhttps%253A%252F%252Fprioritas.xl.co.id%252Fnews-promo%252Fpromo%252Fapr20%252Fbooster-online-partner%26orgUrl%3Dhttp%253A%252F%252Fanimekompi.web.id%252F%26i%3D169032909&beaconUrl=

![Screenshot_2020-04-12-18-01-27-20](https://user-images.githubusercontent.com/9379770/79067224-63933680-7cad-11ea-93cc-9b45adf8f8aa.png)

![Screenshot_2020-04-12-18-01-16-83](https://user-images.githubusercontent.com/9379770/79067236-76a60680-7cad-11ea-978d-80c082572e68.png)
