### ISSUE TITLE
gramedia.com

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1510]
**Sample URL**

`https://www.gramedia.com/best-seller/cara-menulis-daftar-pustaka/`

**Penjelasan Lebih Lanjut**

pas mau back redirect ke shopee

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.67, silahkan force update.
