### ISSUE TITLE
info.mapsadress.com

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1513]
**Sample URL**

`https://wts.pw/zSuA1nPq`

**Penjelasan Lebih Lanjut**

Popup
Fake dl button

https://github.com/realodix/AdBlockID/assets/79722529/62a93c73-a9ea-44d0-a964-f88b3469c830

**Comment by realodix** [comment]
Minta website sumbernya dong

**Comment by T-Baniza** [comment]
`https://blog.kopajasubs.info/2023/08/yu-gi-oh-go-rush-069.html`

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.78, silahkan force update.

----

### Catatan

Popup ketika tekan tombol "Click To Verify" pada info.mapsaddress.com dengan sangat terpaksa tidak bisa diterapkan

![noname-crop](https://github.com/realodix/AdBlockID/assets/1314456/ff2cc247-62aa-4c9d-b3a8-4a1370bd131f)

Saat ini jika diterapkan dengan `info.mapsaddress.com##+js(window.open-defuser)` hasilnya akan berhenti di "Redirecting"

![noname-cropiii](https://github.com/realodix/AdBlockID/assets/1314456/4a0026e1-1511-49fc-9f4e-570c862ca25a)
