### ISSUE TITLE
teknisitv.com

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1514]
**Sample URL**

https://www.teknisitv.com/cara-update-firmware-fiberhome/

**Penjelasan Lebih Lanjut**

Terdapat Pop-Up Banner "Advertisement" di tengah tengah halaman.
![Screenshot from 2023-08-16 18-12-52](https://github.com/realodix/AdBlockID/assets/68702583/6ad82c26-ee5f-4460-8671-c80bd353ce94)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.79, silahkan force update.
