### ISSUE TITLE
jendelakaba.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1518]
https://jendelakaba.com/

![image](https://github.com/realodix/AdBlockID/assets/19517680/b12ae5e8-718f-4024-84c6-b50092c8d6e1)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.87, silahkan force update.
