### ISSUE TITLE
[SafelinkScript] adikanime.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#152]
**Jenis iklan** (hapus yang tidak perlu)

- Safelink script

**Sample URL**
https://adikanime.com/tv/karakai-jouzu-no-takagi-san-season-2-2019/

**Penjelasan Lebih Lanjut**
blocking safelink script 
`https://rawcdn.githack.com/andrianadi888/safeevolution/3a87387a83e2031ae0627ccadee7cf430503a11a/Auto.js
`

**Comment by realodix** [comment]
Thank you
