### ISSUE TITLE
tooncubus.top

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1521]
**Sample URL**

`https://www.tooncubus.top/`

**Penjelasan Lebih Lanjut**

Right click block

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.8.96, silahkan force update.
