### ISSUE TITLE
tokosatu.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1522]
![image](https://github.com/realodix/AdBlockID/assets/19517680/e4e6a920-04c8-4dee-90da-ea53292dca57)

tokosatu.com

popup

**Comment by realodix** [comment]
Popup, maksudnya yang ini bukan?

![noname-crop](https://github.com/realodix/AdBlockID/assets/1314456/0fc4c225-4220-4595-a06e-ac9f72d1f5af)

**Comment by 3xploiton3** [comment]
kok kena block ya

> uBlock Origin: 1.51.0
Chromium: 116
filterset (summary):
 network: 130430
 cosmetic: 143373
 scriptlet: 27235
 html: 0
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 10660-13, 12h.46m
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 524-4, 16h.23m
  DEU-0: 7039-0, 12h.48m
  IDN-0: 9667-381, 16h.24m
  RUS-0: 39727-50, 16h.22m
  ara-0: 2324-6, 12h.47m
  easylist-annoyances: 3900-47, 4d.17h.29m
  easylist-chat: 132-0, 4d.17h.29m
  easylist-notifications: 2643-103, 4d.17h.29m
  fanboy-cookiemonster: 48151-234, 4d.17h.29m
  fanboy-social: 16144-10, 4d.17h.29m
  ublock-annoyances: 5369-79, 4d.17h.29m
  [1 lists not shown]: [too many]
 default:
  user-filters: 20-0, never
  easylist: 69943-60, 4d.17h.29m
  easyprivacy: 33292-247, 4d.17h.29m
  plowe-0: 3720-1069, 4d.17h.29m
  ublock-badware: 7716-148, 4d.17h.29m
  ublock-filters: 34266-394, 4d.17h.29m
  ublock-privacy: 463-10, 4d.17h.29m
  ublock-quick-fixes: 280-19, 10h.44m
  ublock-unbreak: 2112-41, 4d.17h.29m
  urlhaus-1: 6026-0, 12h.45m
filterset (user): [array of 20 redacted]
trustedset:
 added: [array of 20 redacted]
switchRuleset:
 added: [array of 4 redacted]
hostRuleset:
 added: [array of 6 redacted]
userSettings:
 advancedUserEnabled: true
 cloudStorageEnabled: true
 suspendUntilListsAreLoaded: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1195 ms (selfie)
 maxAssetCacheWait: 781 ms

**Comment by realodix** [comment]
> kok kena block ya

@3xploiton3 Dari ABPIndo, tapi sudah difix sama kontributor mereka.

<details>
  <summary>Screenshot</summary>
  
  ![noname-crop](https://github.com/realodix/AdBlockID/assets/1314456/57de2984-ff7e-4888-af4e-cc798766560c)
</details>

Ini adalah self-promotion, jadi Saya tidak bisa menghilangkannya. Jika ingin menghilangkannya, bisa pakai ini

```adblock
tokosatu.com##+js(aopr, popup_custom_data)
```

Terima kasih
