### ISSUE TITLE
doujindesu.tv

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1524]
**Sample URL**

`https://doujindesu.tv/kyouyama-kazusa-no-amai-himitsu/`

**Penjelasan Lebih Lanjut**

- Right click block

Ga bisa klik kanan di setiap halaman baca. Kalo di home page masih bisa

**Comment by realodix** [comment]
Tolong dicek kembali. Saya menemukan, terkadang di uBO gagal menghalau popup di Firefox.

**Comment by GrennKren** [comment]
> Tolong dicek kembali. Saya menemukan, terkadang di uBO gagal menghalau popup di Firefox.

masih gan.. mencoba di chrome windows dengan adguard extension.
aku mencoba sendiri, seperti nya filter ini bisa.
```
doujindesu.tv##+js(acis, /_0x5209|_0x5697/)
doujindesu.tv##+js(aopr, zfgloadedpopup)
```

**Comment by GrennKren** [comment]
> aku mencoba sendiri, seperti nya filter ini bisa.

Eh gak ternyata.. sama aja ada popup

**Comment by realodix** [comment]
> > Tolong dicek kembali. Saya menemukan, terkadang di uBO gagal menghalau popup di Firefox.
> 
> masih gan.. mencoba di chrome windows dengan adguard extension. aku mencoba sendiri, seperti nya filter ini bisa.
> 
> ```
> doujindesu.tv##+js(aopr, zfgloadedpopup)
> doujindesu.tv##+js(aopr, _0x5209)
> doujindesu.tv##+js(aopr, _0x5697)
> ```
> 
> bila `doujindesu.tv##+js(aopr, zfgloadedpopup)` sendiri aja sudah bisa sebenarnya , akan tetapi ketika dicoba diperangkat lain dengan Adguard Android tidak bisa. Jadinya menambahkan 2 filters tambahan untuk memblokir variable _0x5209 dan _0x5697

Terima kasih untuk sarannya. Saat ini di Saya cukup aman menggunakan `doujindesu.tv##+js(nowoif)` untuk menghalau [`window.open()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open).

Saya cukup kesulitan untuk mereproduksinya, karena Saya tidak menemukan popup tersebut.
