### ISSUE TITLE
tutwuri.id

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1527]
**Sample URL**

`https://ayobelajarbareng.com/66JMc7uup`

**Penjelasan Lebih Lanjut**
- Countdown timer
<details><summary>Screenshot.jpg</summary>
<p>

![IMG_20230828_165822](https://github.com/realodix/AdBlockID/assets/79722529/f98bfd18-204b-4c7f-9f1f-84da3c36c7ec)

</p>
</details>

**Comment by realodix** [comment]
Mohon untuk disertakan link sumbernya dong

**Comment by T-Baniza** [comment]
`https://www.yurasu.xyz/2023/08/perkumpulan-gelap-episode-07-sub-indo_28.html`

**Comment by T-Baniza** [comment]
> Kemungkinan dari sini ya
- `https://www.yurasu.xyz/2023/08/perkumpulan-gelap-episode-07-sub-indo_28.html`

Iya
