### ISSUE TITLE
shinigami.id

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1528]
**Sample URL**

`https://shinigami.id/series/demonic-emperor/chapter-427/`

**Penjelasan Lebih Lanjut**

- Banner judi di halaman baca

<details><summary>Screenshot.jpg</summary>
<p>

![IMG_20230829_035705](https://github.com/realodix/AdBlockID/assets/79722529/b37790d0-9079-4032-9929-77ae6120f694)

</p>
</details>

**Comment by realodix** [comment]
Terkait:
- https://github.com/realodix/AdBlockID/issues/1465
