### ISSUE TITLE
TeraBox (1024tera.com)

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1529]
https://bdlhksamarinda.id/yandex-browser-jepang/
![20230829_135305_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/6268663f-b932-4b70-8a29-57afda6ca7f5)

![20230829_135233_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/9774cbd7-beb7-4d7d-9f56-9fdcf4a9e171)

Download palsu mengarah ke play store
Aplikasi fake

...

**Comment by realodix** [comment]
Saya masih bingung, tombol download palsunya yang mana ya?

Saya coba buka halaman yang lain https://bdlhksamarinda.id/simcity-buildit-mod-apk/, lalu tekan tombol "Download Disini" yang warna biru, hasilnya benar kok mengarah ke https://www.1024tera.com/sharing/link?surl=O8BCocP04ijAQgxZK5HQSg

**Comment by Jokopentil** [comment]
![20230829_184837_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/3d851b38-546e-4738-9421-817663e0baf4)


![20230829_184732_rmscr.jpg](https://github.com/realodix/AdBlockID/assets/114223791/cbb910ad-69e5-4a43-a0e4-40c13c39d299)

Harusnya itu langsung download ke aplikasi browser yg di maksud kakak
Tapi di direct ke halaman screenshot
Secara tidak sadar kita di bawa ke pop up 
Iklan berupa halaman tersebut
Bukankah itu termasuk annoyance atau
Daftar kejengkelan

**Comment by realodix** [comment]
> Harusnya itu langsung download ke aplikasi browser yg di maksud kakak
> Tapi di direct ke halaman screenshot
> Secara tidak sadar kita di bawa ke pop up
> Iklan berupa halaman tersebut
> Bukankah itu termasuk annoyance atau
> Daftar kejengkelan

Jika memang seperti itu, harusnya memang termasuk fake button dan dimasukkan ke filter annoyance

Ini langkah yang Saya lakukan

### Desktop
1. Buka sample URL https://bdlhksamarinda.id/simcity-buildit-mod-apk/
2. Klik tombol "DOWNLOAD DISINI" yang warna biru
3. Lalu diarahkan ke situs berbagi file TeraBox https://www.1024tera.com/sharing/link?surl=O8BCocP04ijAQgxZK5HQSg
4. Pilih filenya dan tekan download
5. Lalu diarahkan untuk men-download aplikasi "Desktop-nya TeraBox" untuk melanjutkan proses download file yang ingin kita download.

### Mobile
- Langkah 1 - 3 sama kayak di dekstop.
- Lalu langkah selanjutnya Kita diarahkan untuk men-download aplikasi "Mobile-nya TeraBox" untuk melanjutkan proses download file yang ingin kita download.

---

Di tahap ini Saya melihatnya ini normal, dugaan Saya Kita diharuskan download aplikasi client TeraBox untuk men-download file yang dihosting di TeraBox.

**Comment by realodix** [comment]
> Harusnya itu langsung download ke aplikasi browser yg di maksud kakak
> Tapi di direct ke halaman screenshot

Bagaimana caranya? Apakah ada langkah yang Saya lewati?

**Comment by Jokopentil** [comment]
https://bdlhksamarinda.id/simcity-buildit-mod-apk/
Link yg kakak buka tidak sama yang saya laporkan
https://bdlhksamarinda.id/yandex-browser-jepang/
Awal buka juga muncul halaman itu juga
Intinya yg jadi penyebab itu tombol download itu
Mengenai aplikasi tera kota itu hanya
Aplikasi penyimpan data sudah saya instal dan itu berisi link dowload game
Yg kakak buka
Yg mau saya mau download itu browser
Bukan game🙏🙏🙏
