### ISSUE TITLE
sakuraost.com - Safelink script

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#153]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://www.sakuraost.com/2019/11/hello-happy-world-sekai-nobbinobi.html

**Penjelasan Lebih Lanjut**
`https://raw.githack.com/arlinadsign/saflink/master/Safelink21.js`

**Comment by realodix** [comment]
Thank you
