### ISSUE TITLE
apabeda.com

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1536]
**Sample URL**

https://apabeda.com/perbedaan-lenovo-ideapad-slim-1-dan-3/

**Penjelasan Lebih Lanjut**

Saya tidak dapat memastikan, apakah itu Pop Up iklan apa bukan. 
![Screenshot from 2023-09-02 10-30-31](https://github.com/realodix/AdBlockID/assets/68702583/bfcd152e-0489-4caf-bb8e-0d2b2cc08e78)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.9.4, silahkan force update.
