### ISSUE TITLE
[problem] sogafime.net

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#154]
**Sample URL**
https://sogafime.net/rumput-tetangga-2019/

**Penjelasan Lebih Lanjut**
klo adblockernya hidup tombol download nya hilang
sama block 3dp scriptnya bro 
`https://raw.githack.com/rizkiramdandi/Dev/master/autoconvretlink.js`
<details>

![Annotation 2019-12-29 230024](https://user-images.githubusercontent.com/9379770/71559304-0fae6a00-2a8f-11ea-987a-801df1db6417.png)

**Comment by WaferNabati** [comment]
@realodix ini jg bro https://www.lk21id.com/supernova-the-knight-the-princess-shooting-star-2014/
tombol downloadnya keblock

**Comment by realodix** [comment]
Thank you
