### ISSUE TITLE
detik.com

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1544]
**Sample URL**

https://news.detik.com/berita/d-6920277/manajer-wo-tersangka-kebakaran-gunung-bromo-terancam-5-tahun-bui?utm_source=copy_url&utm_campaign=detikcomsocmed&utm_medium=btn&utm_content=news

**Penjelasan Lebih Lanjut**

Ada objek kosong tak kasat mata. sepertinya ditempati oleh Banner "Iklan" 
![Screenshot from 2023-09-09 10-39-05](https://github.com/realodix/AdBlockID/assets/68702583/3acf9961-a24f-412a-81e4-37fe69162746)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.9.38, silahkan force update.
