### ISSUE TITLE
filmblurayku.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#155]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://www.filmblurayku.com/ip-man-4-the-finale-2019/

**Penjelasan Lebih Lanjut**
Banner iklan judi

**Comment by realodix** [comment]
Sorry Gan, Saya gak tau ada di mana  iklan judinya

<details>
  <summary>Screencapture</summary>
  
  ![screencapture-filmblurayku-ip-man-4-the-finale-2019-2019-12-30-18_27_19](https://user-images.githubusercontent.com/1314456/71580154-1b06a180-2b32-11ea-8ead-e35f9ed15c30.png)
</details>

**Comment by WaferNabati** [comment]
@realodix 
![z2](https://user-images.githubusercontent.com/9379770/71581530-34aae780-2b38-11ea-90c9-1da1cb07aa06.png)

**Comment by realodix** [comment]
Dilihat dari cosmetic filter yang disarankan oleh uBlock, iklannya mengarah ke `qqjoker5.com`. Filter untuk menghilangkan iklan yang mengarah ke `qqjoker5.com` sudah ada sebelumnya.

![cats](https://user-images.githubusercontent.com/1314456/71587855-fb7f7100-2b51-11ea-903d-a9e44f81e367.jpg)

**Comment by realodix** [comment]
Maaf Gan saya tag invalid, karena sebelumnya filternya sudah ada dan seperti di screenshot di Saya juga bersih. Saya coba bantu dengan blokir gambarnya.

**Comment by WaferNabati** [comment]
nah skrng udah ga ada. sebenarnya bisa diblock manual tpi ntar klo ada kasus orang lain yg pakai filter ini sama seperti gw biar fix aja.
