### ISSUE TITLE
komikdewasa.biz

### ISSUE THREAD

**Issue by ChowMein47** [realodix/AdBlockID#1550]
**Sample URL**
https://komikdewasa.biz/

**Penjelasan Lebih Lanjut**
Iklan & banner (seperti yang terlihat di screenshot)
![Screenshot_2023-09-15-08-29-37-74_d0ef7a9810af20f7b394f4f927b723b0](https://github.com/realodix/AdBlockID/assets/98148960/58e031bf-0eb9-444d-8e29-5856f8c8ad1d)

**Comment by realodix** [comment]
Thank you

- AdGuard: Menunggu AdGuard, biasanya akan tersedia sekitar 1-2 jam kemudian.
- uBO: Tersedia pada AdBlockID v23.9.59, silahkan force update.
