### ISSUE TITLE
thegamer.com

### ISSUE THREAD

**Issue by aszksbdje** [realodix/AdBlockID#1551]
**Sample URL**

https://thegamer.com/

**Penjelasan Lebih Lanjut**

Mereka menggunakan "Admiral" dan beberapa situs lain sepertinya yang pakai Admiral lolos semua.

pakai HP. AdblockID Masuk di custom karena language spesifik tidak update.

![Screenshot_2023-09-16-12-05-56-250_com android chrome](https://github.com/realodix/AdBlockID/assets/16359705/1dbbd193-1a6c-458a-9c29-26aefdf1c94a)
![Screenshot_2023-09-16-12-06-00-423_com android chrome](https://github.com/realodix/AdBlockID/assets/16359705/8597ceaf-01fe-4169-b0e6-32bd002ecf1f)

...

**Comment by realodix** [comment]
Ini situs internasional, seharusnya masuk ke
- https://github.com/easylist/easylist
- https://github.com/AdguardTeam/AdguardFilters
- https://github.com/uBlockOrigin/uAssets

Btw Saya tdiak menemukan adanya peringatan anti-adblock, Saya test di:
- uBlock Origin, pengaturan standar + AdBlockID
- AdGuard Android, pengaturan standar + AdBlockID

**Comment by aszksbdje** [comment]
Eh... maaf om... hehehe... wajib situs indo aja ya... 🙈🙈🙈

Sy pake adguard sm adblock id muncul ... kok bisa beda ya... 🙈🙈🙈

Terima Kasih banget puollllll bantuannya Om. 😁
