### ISSUE TITLE
xbokepfb.co

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1556]
https://xbokepfb.co/bokep-live-bigo-memek-tanpa-bulu/
![Screenshot_2023-09-18-07-25-48-90_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/43b63ccb-e572-470e-9043-d9e405a56662)

Klik reload page
Muncul pop up
![Screenshot_2023-09-18-07-26-27-74_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/85d8ae80-c9b1-47b5-914b-92f63a1265bd)

**Comment by realodix** [comment]
Terkait
- #1555

**Comment by realodix** [comment]
Video berasal dari `jandaqu.xyz`, sudah ada filternya di AdBlockID, jadi Saya tidak melihat masalah seperti yang dilaporkan.
