### ISSUE TITLE
[SafelinkScript] bioskopkaca21.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#156]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://bioskopkaca21.com/the-informer-2019/

**Penjelasan Lebih Lanjut**

`https://cdn.jsdelivr.net/gh/Indzign/theme@master/autosafelink.js`

**Comment by realodix** [comment]
Thank you
