### ISSUE TITLE
cnnindonesia.com

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1564]
**Sample URL**

https://www.cnnindonesia.com/teknologi/20180924193847-185-332821/5-momen-penting-sejarah-perjalanan-android

**Penjelasan Lebih Lanjut**

Terdapat banner bertuliskan "Advertisement" 
![Screenshot from 2023-09-24 10-15-04](https://github.com/realodix/AdBlockID/assets/68702583/0b9edd09-21d2-4c9a-9058-dd2bf17f5dfe)

**Comment by Jokopentil** [comment]
![Screenshot_2023-09-24-12-28-08-04_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/9dbc9cde-75ef-4a22-91a6-29b39221e63b)

Scrol ke bawah juga ada itu banner kosong memakan ruang

**Comment by Reno-Sifana** [comment]
> ![Screenshot_2023-09-24-12-28-08-04_4d38fce200f96aeac5e860e739312e76.jpg](https://user-images.githubusercontent.com/114223791/270146505-9dbc9cde-75ef-4a22-91a6-29b39221e63b.jpg)
> 
> Scrol ke bawah juga ada itu banner kosong memakan ruang

iya. tadi juga gitu di laptop.
