### ISSUE TITLE
tribunnews.com

### ISSUE THREAD

**Issue by cyberboh** [realodix/AdBlockID#1567]
**Sample URL**

`https://jakarta.tribunnews.com/2023/09/28/pegawai-pabrik-arang-di-lubang-buaya-yang-ditutup-karena-polusi-udara-ditawari-ikut-pelatihan-kerja`

This issue could be happened onto another `tribunnews network`

**Penjelasan Lebih Lanjut**

Full of ads and annoying sh*ts

![adss](https://github.com/realodix/AdBlockID/assets/99109969/51aafa98-2fea-435a-b348-27828cf8ab01)

**Comment by realodix** [comment]
> Penuh dengan iklan dan hal-hal yang mengganggu

Yang disebut dengan iklan tuh yang mana ya? Dari screenshot atau buka langsung ke halamannya, Saya tidak melihat iklan

**Comment by cyberboh** [comment]
> > Penuh dengan iklan dan hal-hal yang mengganggu
> 
> Yang disebut dengan iklan tuh yang mana ya? Dari screenshot atau buka langsung ke halamannya, Saya tidak melihat iklan

scroll down and see shopping lists, actuallt i already add number on screenshot above

**Comment by realodix** [comment]
> scroll down and see shopping lists, actuallt i already add number on screenshot above

Saya tidak melihatnya sebagai sebuah iklan. Itu lebih cocok masuk ke dalam kategori Annoyance, tetapi subjektif. AdBlockID tidak memiliki filter khusus Annoyance.

Anda bisa menambahkan filter ini di personal filter Anda:

```adblock
# 1
tribunnews.com##.side-article .widgettshop

# 2
tribunnews.com###boxright #jualbeli2022
```
