### ISSUE TITLE
Youtube Anti Adblock

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [realodix/AdBlockID#1571]
**Sample URL**

https://www.youtube.com/watch?v=fH4AJH8m2bs

**Penjelasan Lebih Lanjut**
Anti adblock
![bwiz3txsvyrb1](https://github.com/realodix/AdBlockID/assets/78845241/2db01765-3adc-41ea-9622-fdadb8afb84e)
Setelah nonton beberapa video tiba-tiba:
![2023-10-07_08-57_1](https://github.com/realodix/AdBlockID/assets/78845241/69834e52-8bf2-46b5-87ea-282992981111)

**Comment by realodix** [comment]
Pakai ad blocker apa?

**Comment by TheBSODAndWSODFan** [comment]
```
uBlock Origin: 1.52.2
Chromium: 110
filterset (summary):
 network: 198518
 cosmetic: 108846
 scriptlet: 36858
 html: 0
listset (total-discarded, last-updated):
 added:
  https://github.com/realodix/AdBlockID/raw/main/dist/adblockid.adfl.txt: 11228-0, 17m
  https://github.com/realodix/AdBlockID/raw/main/dist/adblockid_plus.adfl.txt: 81-5, 17m
  CHN-0: 24987-134, 17m
  IDN-0: 9658-400, 17m
  adguard-generic: 78319-641, 17m
  adguard-mobile: 8680-69, 17m
  adguard-spyware: 61395-1202, 17m
  adguard-spyware-url: 1250-4, 17m
  dpollock-0: 11577-257, 17m
 default:
  user-filters: 17-0, never
  easylist: 71567-1421, 17m
  easyprivacy: 33214-16666, 17m
  plowe-0: 3717-1564, 17m
  ublock-badware: 7186-323, 17m
  ublock-filters: 34975-4048, 17m
  ublock-privacy: 557-138, 17m
  ublock-quick-fixes: 178-34, 17m
  ublock-unbreak: 2132-144, 17m
  urlhaus-1: 10870-0, 17m
filterset (user): [array of 17 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3437 ms (selfie)
 maxAssetCacheWait: 680 ms
popupPanel:
 blocked: 46
 network:
  youtube.com: 18
  doubleclick.net: 4
  google.co.id: 1
  google.com: 22
  scriptcdn.net: 1
 extended:
  ###player-ads
  ##ytd-video-description-infocards-section-renderer.ytd-structure…
  ###clarify-box
  ###offer-module
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, google_ad_status, 1)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?true.*?\…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?true.*?\}\]\}…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?true.*?\}\}…
```

**Comment by realodix** [comment]
Untuk uBlock Origin, Anda bisa mengikutinya di https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by dragonfixed** [comment]
Can you provide the wole part of this


  ###player-ads
  ##ytd-video-description-infocards-section-renderer.ytd-structure…
  ###clarify-box
  ###offer-module
  ###merch-shelf
  ##.ytp-ad-progress-list
  ##[target-id="engagement-panel-ads"]
  ###player [class*="suggested-action-badge-icon"]:upward(.ytp-sug…
  ##+js(set-constant, google_ad_status, 1)
  ##+js(set-constant, ytInitialPlayerResponse.adPlacements, undefi…
  ##+js(set-constant, ytInitialPlayerResponse.adSlots, undefined)
  ##+js(set-constant, ytInitialPlayerResponse.playerAds, undefined…
  ##+js(set-constant, playerResponse.adPlacements, undefined)
  ##+js(json-prune-xhr-response, [].playerResponse.adPlacements []…
  ##+js(trusted-replace-fetch-response, /\"adPlacements.*?true.*?\…
  ##+js(trusted-replace-fetch-response, /\"adSlots.*?true.*?\}\]\}…
  ##+js(trusted-replace-fetch-response, /\"playerAds.*?true.*?\}\}…

**Comment by realodix** [comment]
Please follow https://github.com/uBlockOrigin/uAssets/issues/19976 or You can either add a rule to user rules temporary
