### ISSUE TITLE
anikor.cyou

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1575]
**Sample URL**

https://anikor.cyou/

**Penjelasan Lebih Lanjut**

iklan mengganggu dimana-mana
![image](https://github.com/realodix/AdBlockID/assets/37255346/fc0b22a0-c378-47ed-884d-fc96e96f536c)

**Comment by abidjauhar17** [comment]
@realodix tolong, sekarang alamat situsnya sudah berganti ke http://193.27.90.67
![image](https://github.com/realodix/AdBlockID/assets/37255346/65b6e020-e9af-457d-a908-555a22c3fb4e)

**Comment by realodix** [comment]
Done

**Comment by abidjauhar17** [comment]
@realodix alamat website sudah berganti ke https://ani-kor.online/

![image](https://github.com/realodix/AdBlockID/assets/37255346/23ffd450-3659-4172-abb6-5008b99d0723)

**Comment by realodix** [comment]
> @realodix alamat website sudah berganti ke https://ani-kor.online/

Thank you

**Comment by abidjauhar17** [comment]
> > @realodix alamat website sudah berganti ke https://ani-kor.online/
> 
> Thank you

sedikit saran dari saya, mungkin bisa dihapus saja alamat alamat yang lama agar tidak menambah size dari filter adblockid nya dan mungkin bisa sedikit mempercepat kinerja adblocker nya

**Comment by realodix** [comment]
> sedikit saran dari saya, mungkin bisa dihapus saja alamat alamat yang lama agar tidak menambah size dari filter adblockid nya dan mungkin bisa sedikit mempercepat kinerja adblocker nya

Dahulu saya juga berfikir seperti itu. Tapi ternyata kebanyakan dari mereka bisa balik lagi ke alamat yang lama. Satu2nya jaminan mereka tidak menggunakan kembali alamatnya adalah ketika alamatnya sudah mendekati expire atau sudah masuk ke database blacklist pemerintah. Saya lihat anikor sendiri yang paling tua alamatnya expire di Agutus 2024 dan saat ini belum ada satupun yang terblokir. Jadi biarkan saja ada di AdBlockID hingga mesin mendeteksi alamatnya sudah expire atau sudah di-blacklist oleh pemerintah.

> oh ya, saya memang tidak paham dengan python atau apapun itu yang berkaitan dengan tutorial menambahkan rule karena itu rumit bagi saya, tetapi saya tertarik untuk sekedar membantu mengecek dan melapor situs apa saja yang sudah mati alias sudah tidak bisa dibuka dan tidak diperlukan lagi agar bisa di clean dari filter AdBlockID
> 
> bagaimana cara saya bisa membantunya?

Terima kasih sudah memiliki niat untuk membantu.

Untuk memulai pencarian, Anda dapat memeriksa daftar alamat di [/dist/test_adblockid.txt](https://github.com/realodix/AdBlockID/blob/main/dist/test_adblockid.txt). Anda bisa memperkecil pencarian dengan masuk ke folder [/src](https://github.com/realodix/AdBlockID/tree/main/src). Saat ini [/src/modules/movie.adfl](https://github.com/realodix/AdBlockID/blob/main/src/modules/movie.adfl) dan [/src/modules/adult.adfl](https://github.com/realodix/AdBlockID/blob/main/src/modules/adult.adfl) merupakan kategori yang sering banget ganti domain.

Setelah itu,
- Jika Anda mengerti tentang cara pembuatan pull request, Anda dapat menambahkan rules dimana saja. Nanti sisanya Saya yang akan merapihkan.
- Atau Anda dapat membuat issue dan melaporkan daftar alamat yang perlu ditangani.

**Comment by abidjauhar17** [comment]
> > sedikit saran dari saya, mungkin bisa dihapus saja alamat alamat yang lama agar tidak menambah size dari filter adblockid nya dan mungkin bisa sedikit mempercepat kinerja adblocker nya
> 
> Dahulu saya juga berfikir seperti itu. Tapi ternyata kebanyakan dari mereka bisa balik lagi ke alamat yang lama. Satu2nya jaminan mereka tidak menggunakan kembali alamatnya adalah ketika alamatnya sudah mendekati expire atau sudah masuk ke database blacklist pemerintah. Saya lihat anikor sendiri yang paling tua alamatnya expire di Agutus 2024 dan saat ini belum ada satupun yang terblokir. Jadi biarkan saja ada di AdBlockID hingga mesin mendeteksi alamatnya sudah expire atau sudah di-blacklist oleh pemerintah.
> 
> > oh ya, saya memang tidak paham dengan python atau apapun itu yang berkaitan dengan tutorial menambahkan rule karena itu rumit bagi saya, tetapi saya tertarik untuk sekedar membantu mengecek dan melapor situs apa saja yang sudah mati alias sudah tidak bisa dibuka dan tidak diperlukan lagi agar bisa di clean dari filter AdBlockID
> > bagaimana cara saya bisa membantunya?
> 
> Terima kasih sudah memiliki niat untuk membantu.
> 
> Untuk memulai pencarian, Anda dapat memeriksa daftar alamat di [/dist/test_adblockid.txt](https://github.com/realodix/AdBlockID/blob/main/dist/test_adblockid.txt). Anda bisa memperkecil pencarian dengan masuk ke folder [/src](https://github.com/realodix/AdBlockID/tree/main/src). Saat ini [/src/modules/movie.adfl](https://github.com/realodix/AdBlockID/blob/main/src/modules/movie.adfl) dan [/src/modules/adult.adfl](https://github.com/realodix/AdBlockID/blob/main/src/modules/adult.adfl) merupakan kategori yang sering banget ganti domain.
> 
> Setelah itu,
> 
> * Jika Anda mengerti tentang cara pembuatan pull request, Anda dapat menambahkan rules dimana saja. Nanti sisanya Saya yang akan merapihkan.
> * Atau Anda dapat membuat issue dan melaporkan daftar alamat yang perlu ditangani.

bisakah saya membuat list seperti ini, kemudian melaporkannya nanti pada issues?

![image](https://github.com/realodix/AdBlockID/assets/37255346/1f2e6985-850b-4262-a9f2-b01a4d6f27b2)
