### ISSUE TITLE
OppaDrama (185.217.95.30)

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1576]
**Sample URL**

http://185.217.95.30/

**Penjelasan Lebih Lanjut**

ada sisa dari iklan popup yang sudah diblokir tetapi masih menyisakan tombol X dengan ukuran yang kecil
![image](https://github.com/realodix/AdBlockID/assets/37255346/d621ee52-1a7b-4f33-ad61-f5fc38cefd38)

**Comment by realodix** [comment]
Pakai Ad Blocker apa?

Filter sudah ada di AdBlockID, testing di AdGuard dan uBlock Origin gak ada masalah.

**Comment by abidjauhar17** [comment]
> Pakai Ad Blocker apa?
> 
> Filter sudah ada di AdBlockID, testing di AdGuard dan uBlock Origin gak ada popup seperti yang dilaporkan.

saya pake Adguard
terkadang tombol itu muncul.. tetapi mungkin rule berikut berguna dan bisa ditambah untuk menghilangkan secara total sisa iklannya
![image](https://github.com/realodix/AdBlockID/assets/37255346/4e0339b7-dee5-4e9e-9428-1629961944af)

**Comment by realodix** [comment]
@alex-302 

Please take a look

I can't reproduce it on my side

**Comment by realodix** [comment]
@abidjauhar17 
OppaDrama (185.217.95.30) sudah ada di AdBlockID. Saya uji di AdGuard Browser extension v4.2.189 (default setting) dan uBO v1.52.2 (default setting), hasilnya tidak ada masalah seperti yang Anda laporkan.

Masalahnya di sini adalah terlihat seperti terdapat perbedaan perilaku pada AdGuard, di Saya filter bekerja dengan baik sementara dii Anda filter sama sekali tidak bekerja.

---

@3xploiton3 @Jokopentil 
Permisi, apakah kalian menemukan popup juga?

**Comment by Jokopentil** [comment]
![Screenshot_2023-10-12-14-25-09-96_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/b4940b43-2a93-4fc8-9de5-91a9c86b1b5d)

Maaf di saya malah gak bisa
Yang menggunakan adblockid
Itu bisa dari adblocker ultimate dan total adblock kakak
Di kedua adblock itu memang sering bug
Atau bisa jadi dia menggunakan adblock ✋ dan abp
Dengan subscribe adblock adblockid

**Comment by Jokopentil** [comment]
Saya pakai ublock origin

**Comment by Jokopentil** [comment]
Apakah adguard punya versi windows?terkadang hasil tiap produk dari adguard gak sama kakak
Saya dulu pakai versi android, hasilnya GK sama dengan versi extension
Itu kelemahan adguard

**Comment by abidjauhar17** [comment]
> Coba tanya apakah mengaktifkan extension lainnya atau adblock lain bersamaan Semoga membantu

saya memiliki extension ini
![image](https://github.com/realodix/AdBlockID/assets/37255346/02df5626-28df-4792-9124-fbc1fcad0294)

**Comment by abidjauhar17** [comment]
saya rasa cukup dengan menambahkan rule ini pada filter adguard ataupun adblockid dapat membantu mengatasi masalah ini
`185.217.95.30###ouibounce-modal`
setidaknya itu yang saya dapat ketika mencoba menggunakan fitur blokir iklan pada adguard

![image](https://github.com/realodix/AdBlockID/assets/37255346/6d345543-ce54-41f2-9d4b-64e6dab1c744)

**Comment by Jokopentil** [comment]
Adguard sudah ada adblockid di pengaturan
Pilih penyaring
Pilih bahasa tertentu dan aktifkan adblockid
Saran matikan extension sponsor block
Dulu

**Comment by Jokopentil** [comment]
Matikan chapta block dan tolong cek Java script apakah terblokir
Karena Java script sangat mempengaruhi bahkan merusak situs itu sendiri
Situs itu sepertinya mengandung spam
 Sebaiknya cari situs lain
Lihat screenshot di atas spam 404

**Comment by Jokopentil** [comment]
Klo boleh tau pakai browser apa 
?

**Comment by abidjauhar17** [comment]
> Klo boleh tau pakai browser apa ?

opera browser

**Comment by Jokopentil** [comment]
Opera punya browser bawaan atau default coba matikan extension yg saya maksud
Jg matikan adblock ORI dari Opera
Dan cek Java script
Adblock cukup satu
Kebanyakan malah lemot

**Comment by Jokopentil** [comment]
Adblock bawaan maksud saya

**Comment by Alex-302** [comment]
@realodix I can't reproduce even if enabled only AdBlockID. But I see mentions of `ouibounce-modal` in the code.

**Comment by abidjauhar17** [comment]
> @realodix I can't reproduce even if enabled only AdBlockID. But I see mentions of `ouibounce-modal` in the code.

This is what I mean, maybe this rule can help solve the problem when added to the filter
`185.217.95.30###ouibounce-modal`

**Comment by 3xploiton3** [comment]
disable 1-1 extension, sampai hanya adguard yang terpakai

![image](https://github.com/realodix/AdBlockID/assets/19517680/ec10d553-7704-436a-b6f6-0d06ecd6013c)

sudah saya  coba pakai adguard & chrome latest version, gak ada ads yang dimaksud
bisa pakai settingan adguard saya, 
[20231012_174115_adg_ext_settings_4.2.189.json](https://github.com/realodix/AdBlockID/files/12880463/20231012_174115_adg_ext_settings_4.2.189.json)

**Comment by Jokopentil** [comment]
Coba itu mungkin mode siluman adguard aktif sebaiknya matikan karena itu juga pengaruh
Ya benar sekali sebaiknya anda ganti browser saja
Karena pengaturan adblock default Opera GK mendukung adblockid
Mungkin itu sja sekian terimakasih

**Comment by realodix** [comment]
> saya rasa cukup dengan menambahkan rule ini pada filter adguard ataupun adblockid dapat membantu mengatasi masalah ini
> 185.217.95.30###ouibounce-modal
> setidaknya itu yang saya dapat ketika mencoba menggunakan fitur blokir iklan pada adguard

@abidjauhar17 Saya tidak bermaksud membuat hal ini jadi bertele-tele dan rumit. Filter untuk menangani popup ouibounce pada OppaDrama (185.217.95.30) sudah ada di AdBlockID dan hingga saat ini masih berfungsi dengan baik.

Sepertinya di sisi Anda ada hal yang membuat filter rule yang sudah ada jadi tidak bekerja. Anda dapat mencobanya di browser lain apakah masih menemukan hal yang sama?

---

@3xploiton3 @Jokopentil Terima kasih sudah membantu

**Comment by abidjauhar17** [comment]
> > saya rasa cukup dengan menambahkan rule ini pada filter adguard ataupun adblockid dapat membantu mengatasi masalah ini
> > 185.217.95.30###ouibounce-modal
> > setidaknya itu yang saya dapat ketika mencoba menggunakan fitur blokir iklan pada adguard
> 
> @abidjauhar17 Saya tidak bermaksud membuat hal ini jadi bertele-tele dan rumit. Filter untuk menangani popup ouibounce pada OppaDrama (185.217.95.30) sudah ada di AdBlockID dan hingga saat ini masih berfungsi dengan baik.
> 
> Sepertinya di sisi Anda ada hal yang membuat filter rule yang sudah ada jadi tidak bekerja. Anda dapat mencobanya di browser lain apakah masih menemukan hal yang sama?
> 
> @3xploiton3 @Jokopentil Terima kasih sudah membantu

Ya. Di browser chrome juga mengalami hal yang sama
![IMG_20231013_141429](https://github.com/realodix/AdBlockID/assets/37255346/2dedb9bb-fcfe-484c-8bc1-f5875bf3f974)

**Comment by Jokopentil** [comment]
Saya sudah mencobanya di adguard itu memang gagal
Tapi setelah saya coba di ublock origin berhasil
Pakai saja ublock origin dan subscribe adblockid

Pada tanggal Jum, 13 Okt 2023 13.15, abidjauhar17 ***@***.***>
menulis:

**Comment by realodix** [comment]
Di https://github.com/realodix/AdBlockID/issues/1580 @Jokopentil melaporkan bahwa ia menemukan hal sama dengan yang dilaporkan oleh @abidjauhar17 

Testing di AdGuard Windows dan AdGuard Android, hingga saat ini Saya masih tidak menemukannya.

Saya coba blokir plugin sepenuhnya

**Comment by abidjauhar17** [comment]
@realodix alamatnya ganti ke https://oppadrama.site/
![image](https://github.com/realodix/AdBlockID/assets/37255346/4143c957-5eea-43ec-992c-1fd216174184)

**Comment by Jokopentil** [comment]
![Screenshot_2023-10-22-22-12-01-59_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/6934c0fe-710b-4250-84d2-22c40d076faa)

**Comment by realodix** [comment]
> alamatnya ganti ke https://oppadrama.site/

Done

**Comment by abidjauhar17** [comment]
@realodix alamatnya diganti ke http://185.217.95.44/

![image](https://github.com/realodix/AdBlockID/assets/37255346/a39380f3-c245-475a-808c-c040f3c26a7a)
