### ISSUE TITLE
jawapos.com

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1579]
Ruang kosong https://riaupos.jawapos.com/internasional/11/10/2023/312678/anies-jadi-pembicara-di-universitas-malaysia-ini-poin-pemaparannya.html

![Screenshot_2023-10-12-15-04-46-05_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/000d67ab-9fca-49ea-a18b-3cf70b29b912)

**Comment by realodix** [comment]
Saya masih tidak yakin, apakah ini berfungsi?

```adblock
jawapos.com##.isiberita > div:matches-css(display:block):has(> center)
```

**Comment by Jokopentil** [comment]
Masih tidak hilang,tapi menggunakan blokir elemen ublock origin berhasil di hilangkan
Saya belum tau apakah anda sudah memperbarui filternya?

**Comment by Jokopentil** [comment]
![Screenshot_2023-10-13-10-13-19-87_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/adb3050f-12ba-4279-adfe-419efff572cc)

**Comment by Jokopentil** [comment]
Saya sudah update filter tapi tetap tak hilang
