### ISSUE TITLE
kawanfilm21.online - Anti right click, selection & hotkey

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#158]
**Jenis iklan** (hapus yang tidak perlu)
- Anti right click anti selection anti hotkey

**Sample URL**
https://kawanfilm21.online/

**Penjelasan Lebih Lanjut**
anti klik kanan dll

**Comment by realodix** [comment]
> Anti right click anti selection anti hotkey

@okiehsch @Alex-302

**Comment by zloyden** [comment]
Added to our filters.

**Comment by xtubeidstudio** [comment]
https://kawan21.com 
Can anti Click for Layarkaca21

**Comment by zloyden** [comment]
> https://kawan21.com
> Can anti Click for Layarkaca21

It works fine on my end with our extension.
