### ISSUE TITLE
OppaDrama (185.217.95.30) - (Bug on AdGuard)

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1580]
![Screenshot_2023-10-13-13-49-08-36_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/67d11d49-8160-48ff-a721-a062c30e635f)

Tanda silang hilang di ublock origin tapi
Bug untuk adguard

**Comment by Jokopentil** [comment]
http://185.217.95.30/the-glory-episode-16-end/

**Comment by realodix** [comment]
Duplicate of #1576
