### ISSUE TITLE
Favicon Terblokir

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1582]
**Sample URL**

https://bitly.com/

**Penjelasan Lebih Lanjut**

bisakah anda menambah rule ini `@@favicon.ico|` pada filter adblockid?
karena itu memblokir icon favicon di beberapa website sehingga icon tidak tampak pada menu tab bar, salah satunya terdampak pada Bitly (anda bisa lihat pada gambar pertama)

oh ya saya mendapatkan rule itu pada filter indianlist ketika saya aktifkan pada adguard
![image](https://github.com/realodix/AdBlockID/assets/37255346/4f37837b-4068-4964-8fa1-fee0b25af544)

![image](https://github.com/realodix/AdBlockID/assets/37255346/54af91e1-a53a-4c5f-9dd1-be7622ad51b0)

**Comment by realodix** [comment]
Saya coba mereproduksi issue ini:
- Saya subscribe langsung dari https://github.com/mediumkreation/IndianList
- Buka https://bitly.com/

Hasilnya gak ada masalah.. Mau bantuin lapor tapi bingung juga mau ngomong apa, karena Saya sendiri tidak menemukannya.

Langsung laporkan saja ke yang bersangkutan atau disable filternya

![noname-crop](https://github.com/realodix/AdBlockID/assets/1314456/92bf4b9f-2d73-46c0-a03a-1f494f25b126)

**Comment by abidjauhar17** [comment]
> Saya coba mereproduksi issue ini:
> 
> * Saya subscribe langsung dari https://github.com/mediumkreation/IndianList
> * Buka https://bitly.com/
> 
> Hasilnya gak ada masalah.. Mau bantuin lapor tapi bingung juga mau ngomong apa, karena Saya sendiri tidak menemukannya.
> 
> Langsung laporkan saja ke yang bersangkutan atau disable filternya
> 
> ![noname-crop](https://user-images.githubusercontent.com/1314456/275262511-92bf4b9f-2d73-46c0-a03a-1f494f25b126.png)

ya karena saya aktifkan filter indianlist nya, makanya favicon tidak terblokir.
beda dengan pada saat di disable filternya, justru favicon nya terblokir
![image](https://github.com/realodix/AdBlockID/assets/37255346/49ff6ffd-74f6-41e1-bb1f-0f446884da44)
![image](https://github.com/realodix/AdBlockID/assets/37255346/82914755-61bf-4b65-9eab-f43853909c72)

**Comment by abidjauhar17** [comment]
dan saya pikir kalo rule yang sudah saya sebutkan diatas diterapkan pada filter adblockid, menurut saya itu bagus karena saya tidak perlu mengaktifkan filter indianlist tersebut, karena saya jarang membuka website dalam bahasa india (adguard mengaktifkan filternya secara otomatis) dan hal itu hanya akan menambah beban pada loading karena adguard butuh waktu untuk load filternya

**Comment by realodix** [comment]
> ya karena saya aktifkan filter indianlist nya, makanya favicon tidak terblokir.
> beda dengan pada saat di disable filternya, justru favicon nya terblokir

Sorry Saya salah paham di sini. Saya kira penyebabnya IndianList, ternyata bukan.

> dan saya pikir kalo rule yang sudah saya sebutkan diatas diterapkan pada filter adblockid, menurut saya itu bagus karena saya tidak perlu mengaktifkan filter indianlist tersebut, karena saya jarang membuka website dalam bahasa india (adguard mengaktifkan filternya secara otomatis) dan hal itu hanya akan menambah beban pada loading karena adguard butuh waktu untuk load filternya

Mohon untuk dipahami
- Saya tidak bisa serta merta menambahkan suatu filter rule ke AdBlockID sebelum Saya bisa mengkonfirmasinya secara langsung. Saya butuh mereproduksi ulang masalah tersebut agar Saya dapat mengkonfirmasinya.
-

**Comment by abidjauhar17** [comment]
> > ya karena saya aktifkan filter indianlist nya, makanya favicon tidak terblokir.
> > beda dengan pada saat di disable filternya, justru favicon nya terblokir
> 
> Sorry Saya salah paham di sini. Saya kira penyebabnya IndianList, ternyata bukan.
> 
> > dan saya pikir kalo rule yang sudah saya sebutkan diatas diterapkan pada filter adblockid, menurut saya itu bagus karena saya tidak perlu mengaktifkan filter indianlist tersebut, karena saya jarang membuka website dalam bahasa india (adguard mengaktifkan filternya secara otomatis) dan hal itu hanya akan menambah beban pada loading karena adguard butuh waktu untuk load filternya
> 
> Mohon untuk dipahami
> 
> * Saya tidak bisa serta merta menambahkan suatu filter rule ke AdBlockID sebelum Saya bisa mengkonfirmasinya secara langsung. Saya butuh mereproduksi ulang masalah tersebut agar Saya dapat mengkonfirmasinya.
> 
> Langkah apa yang perlu Saya lakukan agar Saya dapat menemukan kondisi favicon terblokir?

sebagai contoh, saya mendapati favicon tidak terblokir ketika mengaktifkan filter berikut pada adguard (itu karena filter indianlist dinyalakan)
![image](https://github.com/realodix/AdBlockID/assets/37255346/fb6e7935-74c4-40e2-a86c-b8b19311c14d)

tapi ketika saya hanya menggunakan filter berikut tanpa ada filter indianlist, maka anehnya favicon langsung terblokir, alias tanpa favicon pada menu tab bar
![image](https://github.com/realodix/AdBlockID/assets/37255346/1222c780-f946-4293-b480-ee2e54448def)

sepertinya filter indianlist sangat pintar disini karena menambahkan rule `@@favicon.ico|` pada allowed rule, sehingga tidak memblokir favicon
![image](https://github.com/realodix/AdBlockID/assets/37255346/777698e1-a186-4d7d-9975-409c0078a0f3)

**Comment by realodix** [comment]
![noname](https://github.com/realodix/AdBlockID/assets/1314456/fc9fdec9-8653-44ba-9aff-7625a752f78d)

Saya sudah menemukan penyebabnya

---

> sepertinya filter indianlist sangat pintar disini karena menambahkan rule `@@favicon.ico|` pada allowed rule, sehingga tidak memblokir favicon

Haha so funny, tapi menurut Saya candaanya terlihat cukup kasar sih. Saya tidak memiliki kewajiban apapun untuk membantu menyelesaikan masalah yang terjadi di Anda, apalagi dalam hal ini bukan disebabkan oleh AdBlockID :D

Solusinya
- Sepertinya memang filter indianlist cocok untuk Anda gunakan. Ini solusi paling sederhana yang bisa Anda lakukan sendiri :D
- atau Anda bisa melaporkannya langsung ke yang membuat filter rule `/favicon.ico$image,third-party` untuk merevisi filter rule-nya. Tujuannya sebenarnya bagus itu filter, karena memang bisa disalah gunakan, makanya mereka blokir sepenuhnya. Mereka hanya perlu merevisi sedikit saja dan masalah Anda pun kelar.

Sekian, terima kasih

**Comment by abidjauhar17** [comment]
> ![noname](https://user-images.githubusercontent.com/1314456/275275606-fc9fdec9-8653-44ba-9aff-7625a752f78d.png)
> 
> Saya sudah menemukan penyebabnya
> 
> > sepertinya filter indianlist sangat pintar disini karena menambahkan rule `@@favicon.ico|` pada allowed rule, sehingga tidak memblokir favicon
> 
> Haha so funny, tapi menurut Saya candaanya terlihat cukup kasar sih. Saya tidak memiliki kewajiban apapun untuk membantu menyelesaikan masalah yang terjadi di Anda, apalagi dalam hal ini bukan disebabkan oleh AdBlockID dan bukan juga disebabkan oleh settingan default.
> 
> Solusinya
> 
> * Sepertinya memang filter indianlist cocok untuk Anda gunakan. Ini solusi paling sederhana yang bisa Anda lakukan sendiri :D
> * atau Anda bisa melaporkannya langsung ke yang membuat filter rule `/favicon.ico$image,third-party` untuk merevisi filter rule-nya. Tujuannya sebenarnya bagus itu filter, karena memang bisa disalah gunakan, makanya mereka blokir sepenuhnya. Mereka hanya perlu merevisi sedikit saja dan masalah Anda pun kelar.
> 
> Sekian, terima kasih

anda tidak bisa bantu report pada mereka?
saya tidak tau harus report kemana

**Comment by Jokopentil** [comment]
Laporkan saja ke tim adguard
Paling nanti di sarankan mengaktifkan
Indian list
Bisa minta request untuk untuk merubah
Filter Indian list lewat tim adguard
