### ISSUE TITLE
juara.net

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1583]
![Screenshot_2023-10-14-19-46-46-14_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/57960d22-a72c-4a2d-9d7d-eff9d216f4ad)

![IMG_20231014_195216.jpg](https://github.com/realodix/AdBlockID/assets/114223791/5dfe9376-01c0-4045-9386-43d333b0fe87)

![IMG_20231014_195135.jpg](https://github.com/realodix/AdBlockID/assets/114223791/7e77d4a1-d434-4b1d-b3c0-27bc91e094af)

![Screenshot_2023-10-14-19-47-45-87_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/b8293d57-70dc-4839-ba37-c2b1b98a79bf)

Banyaknya ruang kosong bertuliskan advertisement
Masih dalam satu halaman 
Mohon scrol sampai ke bawah

**Comment by realodix** [comment]
Sample linknya mana yang sesuai di screenshoot?

**Comment by Jokopentil** [comment]
Maaf kelupaan 
https://www.juara.net/read/323917152/hasil-kualifikasi-motogp-indonesia-2023-adik-valentino-rossi-amankan-pole-position-jorge-martin-hingga-marc-marquez-ketiban-apes

**Comment by Jokopentil** [comment]
Maaf saya tambahkan ![Screenshot_2023-10-14-21-33-28-93_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/23b4340c-07a6-4ac3-95e7-72c7c8015028)

Apakah tampilan video auto play ini bisa di hilangkan
Mengganggu karena ngikut Mulu saat scroll 🤔
