### ISSUE TITLE
FilmLokal (5.45.95.74)

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1585]
**Sample URL**

https://5.45.95.74/

**Penjelasan Lebih Lanjut**

ada iklan GIF
![image](https://github.com/realodix/AdBlockID/assets/37255346/2e041c39-d299-47c6-939f-f83bad514a1d)

**Comment by abidjauhar17** [comment]
> Saya tidak menemukannya.
> 
> Ini tampilan ad blocker yang Saya matikan sepenuhnya.
> 
> Screenshot
> ![image](https://user-images.githubusercontent.com/1314456/275547064-f66b9828-69b0-450e-8f9f-c81e5822a7aa.png)
> 
> Coba masuk ke developer tools (Ctrl + Shift + I), lalu select iklannya agar Saya bisa lihat kodenya

apakah seperti ini?
![image](https://github.com/realodix/AdBlockID/assets/37255346/b180e2e9-61eb-4218-9ade-b4f1c1786c4e)

**Comment by realodix** [comment]
Terlihat seperti iframe. Nama class-nya aneh banget huruf acak gitu, klo kita klik element yang lain kan hurufnya bahasa inggris biasa.

Saya masih kurang jelas, coba klik kanan, klik view page source.. Select semua kodenya, lalu paste di https://pastebin.com/

**Comment by realodix** [comment]
> apakah seperti ini? ![image](https://user-images.githubusercontent.com/37255346/275550145-b180e2e9-61eb-4218-9ade-b4f1c1786c4e.png)

Saya tidak menemukan kode yang Saya cari. Coba Anda buka link zerobin yang Anda berikan, lalu klik `Teks mentah`, setelah itu `ctrl + f`

Di gambar kan kelihatan, sumber gambar dari `vickykilled.cfd` dengan nama class `Eub30 es3ai`, coba Anda cari deh

**Comment by abidjauhar17** [comment]
> > apakah seperti ini? ![image](https://user-images.githubusercontent.com/37255346/275550145-b180e2e9-61eb-4218-9ade-b4f1c1786c4e.png)
> 
> Saya tidak menemukan kode yang Saya cari. Coba Anda buka link zerobin yang Anda berikan, lalu klik `Teks mentah`, setelah itu `ctrl + f`
> 
> Terlihat pada screenshot, sumber gambar dari `vickykilled.cfd` dengan nama class `Eub30 es3ai`, coba Anda cari deh

ya anda benar, tetapi ketika saya mencoba memanfaatkan fitur blokir elemen iklan pada adguard, saya mendapati rule ini `5.45.95.74##html > iframe:nth-child(6)` dan ketika saya coba memasukkannya pada user rules, lalu saya refresh page nya
pop up itu pun menghilang, bahkan sudah saya refresh beberapa kali tetap berhasil menghilang

![image](https://github.com/realodix/AdBlockID/assets/37255346/bb571631-8887-4298-a456-6c98738101b0)
![image](https://github.com/realodix/AdBlockID/assets/37255346/71ca9a5e-944a-40aa-9732-f94c6cd77c60)

**Comment by realodix** [comment]
> saya gak bisa paste lewat pastebin, sebagai gantinya saya coba pakai zerobin https://zerobin.org/?3a94b8a927a3881f#HMN41qjrB6Wo9oLGTvBDxGB2Wa7S4bZExAyUgcHz1t5T

> > Saya tidak menemukan kode yang Saya cari. Coba Anda buka link zerobin yang Anda berikan, lalu klik `Teks mentah`, setelah itu `ctrl + f`
> > Terlihat pada screenshot, sumber gambar dari `vickykilled.cfd` dengan nama class `Eub30 es3ai`, coba Anda cari deh
> 
> ya anda benar, tetapi ketika saya mencoba memanfaatkan fitur blokir elemen iklan pada adguard, saya mendapati rule ini `5.45.95.74##html > iframe:nth-child(6)` dan ketika saya coba memasukkannya pada user rules, lalu saya refresh page nya pop up itu pun menghilang, bahkan sudah saya refresh beberapa kali tetap berhasil menghilang

Ternyata benar itu iframe. Sekarang sudah sangat jelas untuk Saya. 

Secara singkat:

- Dari awal Saya curiga itu iframe
- Ketika tadi saya minta untuk mengirimkan semua kode yang Anda kirim lewat zerobin, Saya ingin memastikan apakah iklan yang Anda laporkan berasal dari FilmLokal (5.45.95.74).
- Ternyata hasilnya FilmLokal (5.45.95.74) tidak pernah menampilkan iklan tersebut dengan bukti dari kode yang Anda kirimkan dan Anda sendiri juga tidak bisa mencarinya.

Kesimpulan saat ini
- Karena FilmLokal (5.45.95.74) tidak pernah menampilkan iklan tersebut, tetapi di Anda muncul iklan, maka kemungkinan besar hanya terjadi di sisi Anda saja.
- Oleh karena itu saat ini Saya tidak bisa menambahkan filter rules yang Anda sarankan.

Salam, terima kasih

**Comment by abidjauhar17** [comment]
> > saya gak bisa paste lewat pastebin, sebagai gantinya saya coba pakai zerobin https://zerobin.org/?3a94b8a927a3881f#HMN41qjrB6Wo9oLGTvBDxGB2Wa7S4bZExAyUgcHz1t5T
> 
> > > Saya tidak menemukan kode yang Saya cari. Coba Anda buka link zerobin yang Anda berikan, lalu klik `Teks mentah`, setelah itu `ctrl + f`
> > > Terlihat pada screenshot, sumber gambar dari `vickykilled.cfd` dengan nama class `Eub30 es3ai`, coba Anda cari deh
> > 
> > 
> > ya anda benar, tetapi ketika saya mencoba memanfaatkan fitur blokir elemen iklan pada adguard, saya mendapati rule ini `5.45.95.74##html > iframe:nth-child(6)` dan ketika saya coba memasukkannya pada user rules, lalu saya refresh page nya pop up itu pun menghilang, bahkan sudah saya refresh beberapa kali tetap berhasil menghilang
> 
> Ternyata benar itu iframe. Sekarang sudah sangat jelas untuk Saya.
> 
> Secara singkat:
> 
> * Dari awal Saya curiga itu iframe
> * Ketika tadi saya minta untuk mengirimkan semua kode yang Anda kirim lewat zerobin, Saya ingin memastikan apakah iklan yang Anda laporkan berasal dari FilmLokal (5.45.95.74).
> * Ternyata hasilnya FilmLokal (5.45.95.74) tidak pernah menampilkan iklan tersebut dengan bukti dari kode yang Anda kirimkan dan Anda sendiri juga tidak bisa mencarinya.
> 
> Kesimpulan saat ini
> 
> * Karena FilmLokal (5.45.95.74) tidak pernah menampilkan iklan tersebut, tetapi di Anda muncul iklan, maka kemungkinan besar hanya terjadi di sisi Anda saja.
> * Oleh karena itu saat ini Saya tidak bisa menambahkan filter rules yang Anda sarankan.
> 
> Salam, terima kasih

hah? How can it be that I'm the only one experiencing this annoying pop up, sementara orang lain tidak mengalaminya :D

**Comment by realodix** [comment]
> hah? How can it be that I'm the only one experiencing this annoying pop up, sementara orang lain tidak mengalaminya :D

Saya juga tidak tahu bagaimana itu bisa terjadi di Anda, Saya harus benar2 memegangnya secara langsung.

Tetapi mungkin dari video ini Anda bisa memahaminya.

Saya coba buka popup AdGuard, di sebelah kanan terlihat kode iframe AdGuard dengan id `adguard-assistant-dialog`.

Untuk membuktikan apakah memang popup tersebut berasal dari FilmLokal (5.45.95.74) atau hanya terjadi di sisi Saya, Saya buka kodenya lalu mencari id `adguard-assistant-dialog` tersebut. Hasilnya tidak ada, karena popup AdGuard hanya terjadi di sisi saya saja, sementara FilmLokal (5.45.95.74) tidak pernah menampilkan popup tersebut

https://github.com/realodix/AdBlockID/assets/1314456/41c4dc0c-11d0-4978-aad0-7d2d77c2e143

**Comment by Jokopentil** [comment]
Saya jg menemukan di android menggunakan adguard
Tapi menggunakan ublock origin aman GK terlihat
![Screenshot_2023-10-17-05-47-22-96_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/243ec441-a609-4c63-a84b-989ca47bf952)

**Comment by realodix** [comment]
Saya tidak tahu apa yang sebenarnya terjadi. Hingga saat ini masih tidak bisa menemukannya.

**Comment by realodix** [comment]
Saya tidak tahu apa yang sebenarnya terjadi. Hingga saat ini masih tidak bisa menemukannya. 

Berikut tampilan saat ini saat ad blocker sepenuhnya dimatikan 

![image](https://github.com/realodix/AdBlockID/assets/1314456/5c640b02-df7f-4bb8-8b53-d6d6f5e6dddc)
