### ISSUE TITLE
rockmods.net

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1589]
**Sample URL**

https://www.rockmods.net/2023/10/SDMaidSE.html

**Penjelasan Lebih Lanjut**

apakah bisa bypass shortlink di situs ini agar langsung sampai ke link tujuan?

![image](https://github.com/realodix/AdBlockID/assets/37255346/879c77f9-30ba-448f-bcc6-0b79f9305c61)
![image](https://github.com/realodix/AdBlockID/assets/37255346/aa4b2f64-2053-4d31-b0f2-3c161e3c75e0)

**Comment by realodix** [comment]
Sayangnya di situs tersebut tidak dimungkinkan
