### ISSUE TITLE
MovieKu (107.152.37.223)

### ISSUE THREAD

**Issue by acgl** [realodix/AdBlockID#1592]
**Sample URL**

https://107.152.37.223/

**Penjelasan Lebih Lanjut**

Hallo AdblockId, Ada Tombol tutup iklan di web https://107.152.37.223/ yang menggangu, bisa tolong di fix ga yah... 

Browser yang di gunakan itu Pake Mozila Android
Extension uBlock Origin pake filter mirror https://adblockid.pages.dev/adblockid.adfl.txt. Oiya mau nanya,sebenernya source filter AdblockId yang asli itu mana?

https://cdn.jsdelivr.net/gh/realodix/AdBlockID@latest/dist/adblockid.adfl.txt

https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt

https://adblockid.pages.dev/adblockid.adfl.txt

Bedanya @master sama @latest apa? Bingung saya

Terimakasih

![IMG_20231017_205951](https://github.com/realodix/AdBlockID/assets/148239408/3c80d391-74ee-4acf-b909-3f98abfbe341)
![IMG_20231017_205940](https://github.com/realodix/AdBlockID/assets/148239408/1a08d634-320e-4ed9-9033-1f4f8ddf025b)

**Comment by acgl** [comment]
Bedanya @latest sama @master apaan

**Comment by acgl** [comment]
Oiya mau nanya nih, saya buat github cuma buat nyari info di adblockid, nah temen saya juga buat akun baru awalnya mau laporin masalah ini tapi issue ga cuma dia aja yang bisa liat, tapi pake akun ku bisa. Kira kira apa tuh yang salah, btw saya itu masih awam di github.

**Comment by realodix** [comment]
> Oiya mau nanya,sebenernya source filter AdblockId yang asli itu mana?

Semua link yang Anda dapatkan dari https://github.com/realodix/AdBlockID, semuanya adalah asli.

> Bedanya `@master` sama `@latest` apa? Bingung saya

jsdelivr.net menyediakan 2 channel, `@master` sama `@latest`, dan itu sama persis. Tetapi saat ini `@latest` sudah ditinggalkan. Anda bisa buka masing2 linknya, lalu melihat tanggal yang tertera.

> Oiya mau nanya nih, saya buat github cuma buat nyari info di adblockid, nah temen saya juga buat akun baru awalnya mau laporin masalah ini tapi issue ga cuma dia aja yang bisa liat, tapi pake akun ku bisa. Kira kira apa tuh yang salah, btw saya itu masih awam di github.

"_tapi issue ga cuma dia aja yang bisa liat, tapi pake akun ku bisa_" Maksudnya bagaimana ya? Semua issue yang dibuat, ntah itu dalam keadaan masih terbuka atau sudah ditutup, bisa diakses oleh siapa saja kok.

---

### Pertanya Umum

Apa bedanya `jsdelivr.net` dan `pages.dev`?

**`jsdelivr.net`**
- Versi stabil
- Update tersedia ketika Saya benar-benar yakin filter yang dikeluarkan cukup efektif dan aman. Verifikasi berlangsung dari beberapa jam hingga hitungan hari.
- Sangat cocok jika Anda mau hanya ingin bersenang-senang menikmati browsing tanpa adanya iklan.

**`pages.dev`**
- Versi uji coba, kestabilannya masih dalam pemantauan.
- Update langsung tersedia ketika Saya menutup issue. Tetapi Saya belum yakin apakah ada tampilan halaman yang rusak atau tidak, yang mungkin terjadi karena ada bug yang Saya lewati.
- Sangat cocok jika Anda mau membantu memantau apakah website yang baru saja dimasukkan ke dalam filter, ada tampilan yang  rusak atau tidak.
