### ISSUE TITLE
jurnalfaktual.id

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#1596]
### Discussed in https://github.com/realodix/AdBlockID/discussions/1595

<div type='discussions-op-text'>

<sup>Originally posted by **@Jokopentil** October 19, 2023</sup>

Tak bisa di scroll kebawah sampai mentok
Kembali ke atas saat di scroll sampai bawah

![Screenshot_2023-10-18-20-12-34-49_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/1e4e8028-caaa-4fb0-9f88-80b90fd9cf3f)

https://jurnalfaktual.id/rupa-rupa/sosmed-an/nonton-film-jepang-tanpa-vpn-begini-caranya-dengan-yandex-browser-di-safari/</div>

**Comment by realodix** [comment]
@Jokopentil Ini pakai browser Kiwi dan uBO ya?

**Comment by Jokopentil** [comment]
Ubo dan adguard
Pakai kiwi dan Firefox hasilnya sama
GK bisa di scrol

**Comment by Jokopentil** [comment]
Maksudnya udah di coba masing2
Pertama ubo janggal
Ubo di matikan ganti adguard tetap seperti itu
Sampai ganti browser
Ganti adblock seperti di awal
Ternyata masih bermasalah

**Comment by Jokopentil** [comment]
Udah fix itu eror di kiwi saja
Memang loading dua kali untuk memblokir anti adblock tapi setelah itu lancar
Sudah saya coba berulang kali
Pake brave +adblockid

**Comment by realodix** [comment]
Di Kiwi ad blocker dimatikan sepenuhnya, muncul peringatan anti adblock.

> Udah fix itu eror di kiwi saja
> Memang loading dua kali untuk memblokir anti adblock tapi setelah itu lancar
> Sudah saya coba berulang kali
> Pake brave +adblockid

OK klo gitu Saya tutup ya issue ini

**Comment by realodix** [comment]
- Di AdGuard bisa berpotensi anti-adblock
- uBO aman
