### ISSUE TITLE
pediashare.net - Safelink script

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#160]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://www.pediashare.net/2019/07/download-film-wedding-agreement-full-movie.html

**Penjelasan Lebih Lanjut**
`https://cdn.statically.io/gh/hubgit21/club/64951dd4/club.js`

**Comment by realodix** [comment]
Thank you
