### ISSUE TITLE
biolazap.com

### ISSUE THREAD

**Issue by ikhoeyZX** [realodix/AdBlockID#1605]
### Sample URL

https://biolazap.com

### Ad Blocker

uBlock Origin

### Keterangan

muncul karna popup

**Comment by realodix** [comment]
Ini maksudnya di https://biolazap.com/ terdapat popup?

Atau Anda dari situs lain lalu mental ke https://biolazap.com/

**Comment by realodix** [comment]
Sudah hari ke 2 dan tidak ada jawaban lebih lanjut. Saya akan menutupnya, Anda dapat berkomentar untuk lebih lanjut.

Terima kasih

**Comment by ikhoeyZX** [comment]
> Ini maksudnya di https://biolazap.com/ terdapat popup?
> 
> Atau Anda dari situs lain lalu mental ke https://biolazap.com/

mental kesana gan
dari otakudesu.wiki

**Comment by realodix** [comment]
> ### Sample URL
> 
> https://biolazap.com
> ### Ad Blocker
> 
> uBlock Origin
> ### Keterangan
> 
> muncul karna popup

Waduh Gan, itu sample URL yang Anda kasih menyesatkan dan keterangan yang Anda berikan juga amat sangat minim.

Saya baru ketemu popupnya di halaman per episode di setiap film, samplenya https://otakudesu.wiki/episode/wpoiec-episode-1081-sub-indo/

Popup sudah ditangani, silahkan update filter AdBlockID

Terim kasih
