### ISSUE TITLE
minioppai.org

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1608]
### Sample URL

https://minioppai.org/

### Ad Blocker

AdGuard

### Keterangan

terdapat script anti adblock

![image](https://github.com/realodix/AdBlockID/assets/37255346/ae3727ed-fe30-4577-8ed3-60815d949c73)

**Comment by Jokopentil** [comment]
![Screenshot_2023-10-26-11-39-33-56_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/9ac1ee48-e75c-47c6-8f26-15bf6436b66b)

![Screenshot_2023-10-26-11-39-22-31_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/2d3bb06e-689b-4e5e-8103-c1f9fc00dfce)

**Comment by Jokopentil** [comment]
Tolong dua gambar itu

**Comment by realodix** [comment]
**Changelog**
- Menghilangkan ad placeholder seperti yang ada di SS dari @abidjauhar17 

**Catatan**
- Peringatan anti-adblock ditangani dengan baik di uBO dan AG Android. Terdeteksi di AG windows dan AG Browser extension. Compatibility issue, mirip seperti di https://github.com/realodix/AdBlockID/issues/1576. Bisa ditangani dengan rule khusus, tapi karena minioppai.org tidak seperti detik, kompas dan situs lainnya yang memilki trafik sangat tinggi, jadi Saya tidak dapat melakukannya lebih jauh.
- Saya tidak menemukan banner seperti yang dilaporkan oleh @Jokopentil. Tampilan di Saya mirip seperti yang ada di SS dari @abidjauhar17.

**Comment by Jokopentil** [comment]
![Screenshot_2023-10-26-16-58-16-44_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/9fb2dad5-9f8b-44a5-a003-4c59b09b5a19)

Yg di atas menggunakan kiwi/kromium

Yg di bawah ini pakai Firefox ![Screenshot_2023-10-26-16-59-40-57_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/realodix/AdBlockID/assets/114223791/991f0ebd-55e9-48a2-aeb0-5e9a4530b28c)

Keduanya pakai ublock origin
