### ISSUE TITLE
etiqueta.me (youshort.me) - fake button

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#161]
**Jenis iklan** (hapus yang tidak perlu)
- Fake button

**Sample URL**
http://etiqueta.me/HxLLCy

**Penjelasan Lebih Lanjut**
Fake button and possibly popunder

**Comment by realodix** [comment]
Thank you

**Comment by realodix** [comment]
**History**
Ganti ke oceantech.xyz
