### ISSUE TITLE
pahe.li

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1611]
### Sample URL

https://pahe.li/saw-x-2023-web-dl-480p-720p-1080p/

### Ad Blocker

AdGuard

### Keterangan

saya ingin bertanya apakah sampai saat ini sudah ada cara untuk bypass script shortlink/safelink yang ditanamkan pada situs https://pahe.li/ ?
karena bahkan script "Bypass Semua Shortlink" dari https://greasyfork.org/id/scripts/431691-bypass-all-shortlinks masih belum mampu mem-bypass shortlink/safelink dari https://pahe.li/ dan masih harus di skip secara manual

![image](https://github.com/realodix/AdBlockID/assets/37255346/3a947c50-64b2-4b5e-9939-b002efa56df3)

**Comment by realodix** [comment]
Mungkin ada di luar sana, tapi karena dalam keseharian Saya tidak memiliki kebutuhan untuk melewati setiap shortlink yang ada, jadi Saya tidak berusaha mencarinya.

**Comment by abidjauhar17** [comment]
> Mungkin ada di luar sana, tapi karena dalam keseharian Saya tidak memiliki kebutuhan untuk melewati setiap shortlink yang ada, jadi Saya tidak berusaha mencarinya.

jadi anda tidak bisa membantu mengatasi safelink ini?

**Comment by realodix** [comment]
Hmm maksud Saya mungkin ada alat yang lebih canggih dari alat yang Anda sebutkan (https://greasyfork.org/id/scripts/431691-bypass-all-shortlinks). Anda dapat langsung membuat permintaan ke sana, atau memodifikasi scriptnya sesuai kebutuhan.

**Comment by abidjauhar17** [comment]
> Hmm maksud Saya mungkin ada alat yang lebih canggih dari alat yang Anda sebutkan (https://greasyfork.org/id/scripts/431691-bypass-all-shortlinks). Anda dapat langsung membuat permintaan ke sana, atau memodifikasi scriptnya sesuai kebutuhan.

oh
yaa saya kira kalau anda bisa mem-bypass dan menambahkan rulenya pada filter adblockid, maka itu akan lebih bagus lagi karena saya lihat script bypass yang saya sebut tadi jarang mendapatkan update baru dari si pembuatnya
