### ISSUE TITLE
linkpoi.me

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1612]
### Sample URL

https://linkpoi.me/QNT1Mq

### Ad Blocker

AdGuard

### Keterangan

anti adblock script pada situs safelink buatan https://nekopoi.care/ 

contoh link anime: https://nekopoi.care/pv-mihitsu-no-koi-episode-1-subtitle-indonesia/

![image](https://github.com/realodix/AdBlockID/assets/37255346/6c5db3a6-71b3-45cf-8df7-a0bd36fdba4e)
![image](https://github.com/realodix/AdBlockID/assets/37255346/7d9ff340-c824-4a43-889b-8ad9760d5168)
![image](https://github.com/realodix/AdBlockID/assets/37255346/b242c06f-89e9-43d5-bf21-c2c13d216482)

**Comment by realodix** [comment]
Saya tidak dapat mendeteksinya di uBO, kemungkinan compatibility issue mirip seperti di https://github.com/realodix/AdBlockID/issues/1608.

Filter dari AdGuard mampu menanganinya dengan baik.

![image](https://github.com/realodix/AdBlockID/assets/1314456/de60bd14-f5c1-46b6-a38c-c326e2046586)

**Comment by abidjauhar17** [comment]
> Saya tidak dapat mendeteksinya di uBO, kemungkinan compatibility issue mirip seperti di #1608.
> 
> Filter dari AdGuard mampu menanganinya dengan baik.
> 
> ![image](https://user-images.githubusercontent.com/1314456/278292143-de60bd14-f5c1-46b6-a38c-c326e2046586.png)

saya menggunakan adguard extension pada opera windows
dan ini yang saya dapatkan dari filtering log adguard
![image](https://github.com/realodix/AdBlockID/assets/37255346/125c2585-b8df-4b8f-a0e3-2fe349196275)

sampai sekarang masih belum teratasi anti adblock nya
![image](https://github.com/realodix/AdBlockID/assets/37255346/c575e579-9f2e-4c1f-ae66-41269d69adcb)
