### ISSUE TITLE
ef.co.id

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1614]
### Sample URL

https://www.ef.co.id/englishfirst/kids/blog/perbedaan-english-british-dan-english-american/

### Ad Blocker

AdGuard

### Keterangan

cookie banner

![image](https://github.com/realodix/AdBlockID/assets/37255346/31dc80f2-c7d8-4f66-bb31-38be795434b3)

**Comment by realodix** [comment]
@zloyden Please take a look

**Comment by zloyden** [comment]
Fixed in AdGuard Annoyances, the update should be available in 2-3 hours.
