### ISSUE TITLE
uzone.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1615]
### Sample URL

https://uzone.id/usai-dicecer-pro-israel-grab-donasi-rp3-5-m-buat-palestina?utm_source=wifiid&utm_medium=article

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/19517680/af50141c-88c4-4b2e-ab9b-2b59c5d7e495)

**Comment by Jokopentil** [comment]
![Screenshot_2023-11-06-22-24-24-09_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/49818d5d-4bd0-4fa6-8d9d-a0c1ddc513fe)

https://uzone.id/aplikasi-dompet-kripto-novi-dari-meta-ditutup
Masih satu situs
Tolong yg ini mohon di ikut sertakan agar tidak tertinggal
