### ISSUE TITLE
megaup.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1616]
### Sample URL

https://megaup.net/1Zln3

### Ad Blocker

uBlock Origin

### Keterangan

Anti adblock

**Comment by realodix** [comment]
FIlter default uBO + AdBlockID, Saya tidak menemukan peringatan anti-adblock

**Comment by Jokopentil** [comment]
Coba min di cek apakah filter nya sudah di tambahkan
Kok aneh di adguard lancar
Jika memang bug bisa lapor ke ublock origin

**Comment by Jokopentil** [comment]
Pakai ublock origin masih ada gambar yg tertinggal
Sedangkan adguard bersih
![Screenshot_2023-11-07-23-14-28-17_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/db63e841-9db2-4ffe-8260-7b5643309fed)

**Comment by realodix** [comment]
> Pakai ublock origin masih ada gambar yg tertinggal Sedangkan adguard bersih

@Jokopentil  

- Gambar di uBO sama mereka dibuka blokirnya, lalu mereka hidden. Mungkin ada di beberapa platform yang filter rules untuk hiddennya gak berfungsi.
- Gambar di AdGuard tetap terblokir + hidden.

<details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/realodix/AdBlockID/assets/1314456/b5598b97-d41d-4feb-a97c-92596be32f5a)

  ![image](https://github.com/realodix/AdBlockID/assets/1314456/d313c2a3-2f4f-43b5-946b-e7a89dff0546)

</details>

**Comment by Jokopentil** [comment]
Apa bisa kasus seperti itu pakai bantuan  
Blokir elemen
Sekarang lapor adblockid pake aplikasi susah harus muter2lewat browser 🤦

**Comment by realodix** [comment]
> Apa bisa kasus seperti itu pakai bantuan
> Blokir elemen
> Sekarang lapor adblockid pake aplikasi susah harus muter2lewat browser 🤦

Bisa dengan dengan menambahkan `$badfilter` jadinya seperti ini `@@||megaup.net/imageads/$image,1p,badfilter`

Tapi Saya yakin ada alasan kuat kenapa mereka membuka blokir gambar iklan tersebut.

> Sekarang lapor adblockid pake aplikasi susah harus muter2lewat browser 🤦

GitHub mobile ya? Ini sedikit lucu sebenarnya, GitHub mobile belum mendukung fitur mereka sendiri. Semoga cepat mereka update.

**Comment by realodix** [comment]
Saya masih tidak dapat menemukan peringatan anti adblock. Harusnya ini sudah selesai dengan filter bawaan uBO.

**Comment by Jokopentil** [comment]
Ya berarti tinggal lapor bug lewat Firefox mobile
