### ISSUE TITLE
Rebahin (179.43.163.53)

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1618]
### Sample URL

http://179.43.163.53/

### Ad Blocker

AdGuard

### Keterangan

tolong dong di website ini gak bisa klik kanan pakai mouse

![image](https://github.com/realodix/AdBlockID/assets/37255346/bb5808fb-8084-41b5-89ea-dde913350236)

**Comment by realodix** [comment]
Thank you, tunggu update dari AdGuard
