### ISSUE TITLE
terbit21.online - Anti right click

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#162]
**Jenis iklan** (hapus yang tidak perlu)
- Anti copy paste

**Sample URL**
https://terbit21.online/download/?movie=it-chapter-two-2019&ref=186561

**Penjelasan Lebih Lanjut**
Anti right click etc dan banner iklan gan

**Comment by realodix** [comment]
@okiehsch @zloyden

**Comment by zloyden** [comment]
Added to our filters.
