### ISSUE TITLE
inwepo.co

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1621]
### Sample URL

https://inwepo.co/

### Ad Blocker

uBlock Origin

### Keterangan

ada banner kecil bertuliskan AD (Iklan) di tengah tengah halaman.
![Screenshot from 2023-11-16 21-09-35](https://github.com/realodix/AdBlockID/assets/68702583/86b3193b-afeb-4bfe-a9f3-9e140e13615a)
(Screenshot sudah saya upload, tapi gak nampil di Preview).

**Comment by realodix** [comment]
Terima kasih

Ini seharusnya sudah sekitar 2 hari yang lalu di https://github.com/realodix/AdBlockID/commit/804833c55944e7f1264209fc648a11106a0ef889

Tolong update dan laporkan kemabali

**Comment by Reno-Sifana** [comment]
> Terima kasih
> 
> Ini seharusnya sudah sekitar 2 hari yang lalu di [804833c](https://github.com/realodix/AdBlockID/commit/804833c55944e7f1264209fc648a11106a0ef889)
> 
> Tolong update dan laporkan kemabali

Problem Solved. Saya coba tekan "Purge All Caches" kemudian Update Now baru hilang bannernya. 
![Screenshot from 2023-11-17 10-11-33](https://github.com/realodix/AdBlockID/assets/68702583/c0f84d93-05e1-4400-8969-2993331b31f0)
