### ISSUE TITLE
alqanime.net

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1622]
### Sample URL

https://alqanime.net/dr-stone-new-world-part-2/

### Ad Blocker

AdGuard

### Keterangan

- Safelink pada beberapa tombol download

Seperti tombol mediafire dan Archivd

**Comment by Jokopentil** [comment]
![Screenshot_2023-11-17-15-18-13-30_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/db14a4b3-6a5c-4b0e-87c0-5964e64d2cea)

Pilih acefile

**Comment by Jokopentil** [comment]
![Screenshot_2023-11-17-15-18-35-35_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/344850ad-1169-482b-ba8b-9b44f31031f0)

Klik stream

**Comment by GrennKren** [comment]
Udh gak ada lagi safelink. keliatannya salah satu filter bawaan lain sudah memperbaikinya

**Comment by realodix** [comment]
> Udh gak ada lagi safelink. keliatannya salah satu filter bawaan lain sudah memperbaikinya

@GrennKren  Saya mengonfirmasi bahwa saat ini sudah diselesaikan oleh filter utama (easylist dan AdGuard Base)

> Tulisan close menghalangi tombol klik play

@Jokopentil Saya lihat di SS (https://github.com/realodix/AdBlockID/issues/1622#issuecomment-1815923308) itu mengarah ke https://acefile.co/f/101198923/alqanime_drstns3p2_01_360p-mp4 dan ada di mirror 2

Saya tidak menemukannya, hanya ada mirror 4 dan tidak dapat di-play

![image](https://github.com/realodix/AdBlockID/assets/1314456/be23e91b-186a-4bc6-82b3-6ff523ee04f9)

**Comment by GrennKren** [comment]
@realodix  safelink kembali muncul pada mediafire dan Archivd
https://alqanime.net/mashle-shinkakusha-kouho-senbatsu-shiken-hen/
