### ISSUE TITLE
simontokx.quest

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1623]
### Sample URL

https://simontokx.quest/watch/65182945.html

### Ad Blocker

uBlock Origin

### Keterangan

Iklan video saat di putar 
![Screenshot_2023-11-19-17-23-41-56_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/48c5e195-d2a5-4194-afcc-283e818488c2)

**Comment by realodix** [comment]
uBlock Origin (default settings) + AdBlockID

Saya tidak menemukan iklan tersebut

**Comment by Jokopentil** [comment]
Itu memang browsernya
Saya coba di brave dan Firefox gak ada iklan

**Comment by realodix** [comment]
Maksudnya bagaimana? Memang muncul di browser apa?

Brave berbasis Chromium sama seperti Chrome. Saya cek di Firefox dan Chrome, hasilnya tidak ada, sudah diblokir oleh filter bawaan.

**Comment by realodix** [comment]
Sumber video iklan sudah Saya blokir sepenuhnya, apakah masih ada?

**Comment by Jokopentil** [comment]
Iklannya hanya muncul di kiwi saja
Ini sama kasusnya dengan jurnalfaktual.id yg gak bisa da scroll
Iklan video sudah terblokir
