### ISSUE TITLE
OppaDrama (185.217.95.48) 

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1624]
### Sample URL

http://185.217.95.48/movie-ganjil-genap-2023-webdl/

### Ad Blocker

AdGuard

### Keterangan

banner iklan GIF

![image](https://github.com/realodix/AdBlockID/assets/37255346/05908eb0-ae6a-42b1-991b-ba7c3196428d)

**Comment by realodix** [comment]
Ini popupnya udah gak muncul ya? Kemarin di AdGuard dilaporkan ada popup, dia ganti domain ke sini soalnya.

**Comment by abidjauhar17** [comment]
> Ini popupnya udah gak muncul ya? Kemarin di AdGuard dilaporkan ada popup, dia ganti domain ke sini soalnya.

harusnya udah
soalnya udah ga ada pop up nya
![image](https://github.com/realodix/AdBlockID/assets/37255346/9e207a79-c4f5-4f6e-8d04-5ce9dc91bfae)
