### ISSUE TITLE
OppaDrama (185.217.95.48)

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1625]
### Sample URL

http://185.217.95.48/movie-ganjil-genap-2023-webdl/

### Ad Blocker

uBlock Origin

### Keterangan

Untuk ublock origin iklan diatas layar video kok  gagal blokir ya? Kiwi browser 
![Screenshot_2023-11-23-17-40-09-16_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/a82b402b-f25b-4401-876f-d0621564ae61)

**Comment by Jokopentil** [comment]
Untuk Firefox menggunakan ublock origin dan adguard juga gagal
![Screenshot_2023-11-23-18-06-44-15_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/realodix/AdBlockID/assets/114223791/3227e7a8-2dff-43e8-9497-e32f754e4aa6)

**Comment by realodix** [comment]
- Filter untuk uBO baru Saya push, harus ada yang Saya validasi dulu. Force update saja.
- AdGuard nunggu dari server AdGuard, biasanya sekitar 2-3 jam, tergantung kebijakan dari mereka

**Comment by realodix** [comment]
Duplicate of https://github.com/realodix/AdBlockID/issues/1624
