### ISSUE TITLE
kompas.com (amp) 

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1626]
### Sample URL

https://www.google.com/amp/s/amp.kompas.com/internasional/read/2012/10/11/17363830/oasecakrawala

### Ad Blocker

uBlock Origin

### Keterangan

Iklan blank seluas stadion bola 
![Screenshot_2023-11-24-06-55-09-04_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/2aba782b-2820-4af1-86c9-051fb8e52373)
![Screenshot_2023-11-24-06-54-38-31_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/94befb15-2596-40c6-9af3-b77245e8e90f)

**Comment by Jokopentil** [comment]
Scroll ke bawah

**Comment by realodix** [comment]
Ini Google AMP. Sejak Google mengumumkan mobile firts untuk faktor pake rank, banyak situs yang mengoptimalkan tampilan mobilenya daripada menggunakan AMP.

Sejak beberapa bulan yang lalu AdBlockID juga telah menghapus filter untuk AMP.

Saya tidak yakin apakah saat ini harus menambahkannya kembali atau tidak.

Apakah ada banyak situs besar lainnya di Indonesia yang menggunakan AMP? Jika ada, beritahu Saya dan Saya akan senang hati menambahkannya kembali ke AdBlockID.

Saat ini Anda dapat menggunakan filter ini

```adblock
amp-kompas-com.cdn.ampproject.org,amp.kompas.com##.kgnow-amp
amp-kompas-com.cdn.ampproject.org,amp.kompas.com##.wSpec-iframe:has(> amp-iframe)
```

**Comment by Jokopentil** [comment]
Memang benar setelah AMP di aktifkan gambar yg diatas hilang serta masalah
hilang
Tapi AMP di jurnalfaktual.id menyebabkan erorr saat di scroll

Pada Sab, 25 Nov 2023 00.47, Kei ***@***.***> menulis:
