### ISSUE TITLE
IndoDrama21 (5.253.86.213)

### ISSUE THREAD

**Issue by ChowMein47** [realodix/AdBlockID#1627]
### Sample URL

https://5.253.86.213/

### Ad Blocker

uBlock Origin

### Keterangan

-Anti adblock
-Iklan judi
-close teaser
![Screenshot_2023-11-25-19-15-46-88_3aea4af51f236e4932235fdada7d1643](https://github.com/realodix/AdBlockID/assets/98148960/fec1de85-bec5-4dc2-8e3b-17f963e05eef)

**Comment by krystian3w** [comment]
https://github.com/ABPindo/indonesianadblockrules/pull/470#pullrequestreview-1749220201

https://github.com/uBlockOrigin/uAssets/issues/20864
