### ISSUE TITLE
dunia21.cyou

### ISSUE THREAD

**Issue by wibumoe** [realodix/AdBlockID#1630]
### Sample URL

https://dunia21.cyou

### Ad Blocker

Lainnya

### Keterangan

Jenis iklan (hapus yang tidak perlu)

Inpage
Pop-up
Sample URL
https://dunia21.cyou/

Penjelasan Lebih Lanjut
Inpage + Pop-up

**Comment by realodix** [comment]
Pakai ad blocker apa?

**Comment by Jokopentil** [comment]
![Screenshot_2023-11-30-01-50-11-71_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/adc5c961-ac82-43f5-bf1a-fd1c817339ab)
Iklan banner ini yang kadang muncul di adguard
SEDANGKAN PAKAI UBLOCK ORIGIN ITU BUTUH 3KALI KLIK UNTUK MEMUTAR VIDEO, ITU ARTINYA POP UP OVERLAY

**Comment by Jokopentil** [comment]
![Screenshot_2023-11-30-01-50-11-71_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/adc5c961-ac82-43f5-bf1a-fd1c817339ab)
Iklan banner ini yang kadang muncul di adguard
SEDANGKAN PAKAI UBLOCK ORIGIN ITU BUTUH 3KALI KLIK UNTUK MEMUTAR VIDEO, ITU ARTINYA POP UP OVERLAY
![IMG_20231130_015940.jpg](https://github.com/realodix/AdBlockID/assets/114223791/cf22d94f-3129-4fcb-9070-428ae00fd72f)

**Comment by wibumoe** [comment]
Kalo mau full ilang gimana min

**Comment by realodix** [comment]
> Iklan banner ini yang kadang muncul di adguard
> SEDANGKAN PAKAI UBLOCK ORIGIN ITU BUTUH 3KALI KLIK UNTUK MEMUTAR VIDEO, ITU ARTINYA POP UP OVERLAY

@Jokopentil Aktifkan filter easylist. 

AdGuard settingan default + Easylist + AdBlockID, hasilnya aman kok

> Kalo mau full ilang gimana min

@wibumoe Gunakan uBlock Origin atau AdGuard
