### ISSUE TITLE
sibokepjepang.com

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1638]
### Sample URL

https://sibokepjepang.com/ai-sayama-istri-setia-merawat-suaminya-yang-sakit-dan-mulai-selingkuh-dengan-pasien-di-ranjang-rumah-sakit-yang-berdekatan/

### Ad Blocker

AdGuard

### Keterangan

Iklan banner
![Screenshot_2023-12-02-09-54-50-33_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/8bc520e9-acee-4c2f-a647-b7795dca80c3)

**Comment by realodix** [comment]
Iklannya tidak selalu muncul

Tapi Saya lihat, ketika muncul, filter dari AdGuard dapat menanganinya dengan baik. Selain itu filter utama easylist yang ada di AG juga dapat menanganinya dengan baik.
