### ISSUE TITLE
drakorindofilms.tv

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#164]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://drakorindofilms.tv/

**Penjelasan Lebih Lanjut**
Banner judi

**Comment by realodix** [comment]
Dimananya Gan?

<details>
  <summary>Screencapture</summary>
  
  ![screencapture-drakorindofilms-tv-2019-12-30-17_23_47](https://user-images.githubusercontent.com/1314456/71578069-36b97a00-2b29-11ea-8564-4cbf7fe8f3d5.png)
  
</details>

**Comment by WaferNabati** [comment]
@realodix 

![z1](https://user-images.githubusercontent.com/9379770/71581434-c6febb80-2b37-11ea-8479-69647d1d9221.png)

**Comment by realodix** [comment]
Kalau dilihat dari Cosmetic filters yang disarankan oleh uBlock, harusnya sih sudah hilang

Ini log Saya

![cats](https://user-images.githubusercontent.com/1314456/71583216-0af5be80-2b40-11ea-8606-62cf99dbc9ac.jpg)

**Comment by WaferNabati** [comment]
tpi ini pnya gw kok masih muncul

**Comment by realodix** [comment]
> tpi ini pnya gw kok masih muncul

Saya juga kurang tahu deh kenapa masih muncul. Filter untuk menghilangkan iklan yang mengarah ke `qq8778.online` sudah Saya tambahkan di [1e9762d#diff-4c848bd](https://github.com/realodix/AdBlockID/commit/1e9762d4b3dafe75a344cde15d7aaaecb6a5f53d#diff-4c848bd3bcff4f4b9d5c90a6b5a952b6R1721) sejak Dec 24, 2019.

**Comment by realodix** [comment]
Maaf Gan saya tag invalid, karena sebelumnya filternya sudah ada dan seperti di screenshot di Saya juga bersih. Saya coba bantu dengan blokir gambarnya.

Sepertinya ini mirip dengan https://github.com/realodix/AdBlockID/issues/155

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/71607355-3eb9fe00-2bab-11ea-929a-9b076449a4ca.png)

ada bannernya

**Comment by 3xploiton3** [comment]
drakorindofilms.tv##.modal
drakorindofilms.tv##.cm-popup-modal

**Comment by WaferNabati** [comment]
nah skrng udah ga ada. sebenarnya bisa diblock manual tpi ntar klo ada kasus orang lain yg pakai filter ini sama seperti gw biar fix aja.

**Comment by Recehan-Slayer** [comment]
banner judi baru

**Comment by realodix** [comment]
> banner judi baru

Thank you
