### ISSUE TITLE
glints.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1643]
### Sample URL

https://glints.com/id/opportunities/jobs/explore?keyword=frontend&country=ID

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/19517680/59bf6a43-90ec-4592-bf0e-f4571bc0a366)

pop up login

**Comment by realodix** [comment]
```adblock
glints.com##[class^="LoginModalsc__LoginSignUpModalContainer"]
glints.com##body:style(overflow: auto!important;)
```
