### ISSUE TITLE
rebahin (179.43.163.53)

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1645]
### Sample URL

http://179.43.163.53/nonton-film-silent-night-2023-sub-indo/play/?ep=2&sv=1

### Ad Blocker

AdGuard

### Keterangan

1. pengunjung tidak bisa klik kanan mouse
2. ada pop up tiap kali membuka film apapun

![image](https://github.com/realodix/AdBlockID/assets/37255346/2528baac-e3be-42f6-99e0-283e3545acd6)

oh ya rebahin sepertinya baru ganti alamat dari yang sebelumnya 179.43.163.52 menjadi 179.43.163.53

**Comment by realodix** [comment]
Thank you, mohon tunggu update dari AdGuard ya

**Comment by realodix** [comment]
Klik kanan sudah saya tangani

**Comment by abidjauhar17** [comment]
@realodix situsnya pindah dari http://179.43.163.53/ ke http://179.43.163.54/
jadi masalah yang sudah diatasi di alamat sebelumnya, berpindah ke alamat baru

**Comment by realodix** [comment]
> situsnya pindah dari http://179.43.163.53/ ke http://179.43.163.54/ jadi masalah yang sudah diatasi di alamat sebelumnya, berpindah ke alamat baru

Thank you

**Comment by abidjauhar17** [comment]
> > situsnya pindah dari http://179.43.163.53/ ke http://179.43.163.54/ jadi masalah yang sudah diatasi di alamat sebelumnya, berpindah ke alamat baru
> 
> Thank you

klik kanan sih udah bisa, tapi kenapa pop up nya masih ada? kok ga dihilangkan
![image](https://github.com/realodix/AdBlockID/assets/37255346/394874d2-ecb0-4b76-8309-2963c747d0c5)

**Comment by abidjauhar17** [comment]
> > > situsnya pindah dari http://179.43.163.53/ ke http://179.43.163.54/ jadi masalah yang sudah diatasi di alamat sebelumnya, berpindah ke alamat baru
> > 
> > 
> > Thank you
> 
> klik kanan sih udah bisa, tapi kenapa pop up nya masih ada? kok ga dihilangkan ![image](https://private-user-images.githubusercontent.com/37255346/293477790-394874d2-ecb0-4b76-8309-2963c747d0c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODI1NDIsIm5iZiI6MTcwNDA4MjI0MiwicGF0aCI6Ii8zNzI1NTM0Ni8yOTM0Nzc3OTAtMzk0ODc0ZDItZWNiMC00Yjc2LTgzMDktMjk2M2M3NDdkMGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA0MTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTY0OTQ3NzczMTE1NTY5ZjVlMDU3ZGMxNDQ1NzE0N2FlNDY1MmIwYWZmODc3YjI4MjY0Nzc0ODU2OGFkYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DIutt4HQP-F9oPkYufpp0SyDECprYCxPYXgVPjelnyE)

@realodix ?

**Comment by realodix** [comment]
Itu popup instruksi tentang apa yang dapat user lakukan saat videonya error. Berguna bagi user yang tidak mengerti.

Sayangnya AdBlockID tidak memiliki filter annoyance yang bersifat subjektif.
