### ISSUE TITLE
kompas.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1646]
### Sample URL

 https://www.kompas.id/baca/internasional/2023/11/06/labirin-terowongan-penentu-perang-israel-hamas

### Ad Blocker

uBlock Origin

### Keterangan

annoyance

![image](https://github.com/realodix/AdBlockID/assets/19517680/e34e0d0d-f393-44db-a600-d32ceb1e763e)

**Comment by realodix** [comment]
Di Saya gak ada, adanya langsung paywall

![image](https://github.com/realodix/AdBlockID/assets/1314456/c571c0a4-196f-47de-9ef9-807f79c90eae)
