### ISSUE TITLE
AdblockID Plus Developer

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1647]
### Sample URL

chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/asset-viewer.html?url=https%3A%2F%2Fadblockid.pages.dev%2Fadblockid_plus.adfl.txt&title=AdBlockID%20Plus&subscribe=1#subscribed

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/19517680/d7096fa2-6c3f-482f-9270-1763cd0d8761)

AdblockID Plus Developer tidak up to date

**Comment by realodix** [comment]
Link yang ada di depan, semuanya up to date kok

**Comment by realodix** [comment]
Hingga hari ini masih up to date sesuai harapan. Memang jarang diupdate, karena selama masih memungkinkan untuk dimasukkan ke dalam AdBlockID, akan Saya masukkan ke sana.

![image](https://github.com/realodix/AdBlockID/assets/1314456/605e9b07-a70f-42e6-816f-1d350ece7f31)
