### ISSUE TITLE
huntersekai.info

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1648]
### Sample URL

http://huntersekai.info/

### Ad Blocker

uBlock Origin

### Keterangan

Banner judi

**Comment by realodix** [comment]
Saya tidak menemukannya

<details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/realodix/AdBlockID/assets/1314456/15a6eb17-1a2a-4e28-8ad5-186dbadf44f3)
</details>

**Comment by Recehan-Slayer** [comment]
@realodix 
uBlock Origin: 1.54.0
Firefox: 120
filterset (summary):
 network: 105708
 cosmetic: 47548
 scriptlet: 19353
 html: 1128
listset (total-discarded, last-updated):
 added:
  https://adblockid.pages.dev/adblockid.adfl.txt: 4964-0, 1m
  https://adblockid.pages.dev/adblockid_plus.adfl.txt: 88-14, never
 default:
  user-filters: 11-1, never
  ublock-filters: 36731-134, 1m
  ublock-badware: 7603-11, 1m
  ublock-privacy: 923-4, 1m
  ublock-unbreak: 2203-0, 1m
  ublock-quick-fixes: 183-2, 1m
  easylist: 75311-672, 1m
  easyprivacy: 33075-835, 1m
  urlhaus-1: 10690-0, 1m
  plowe-0: 3777-1, 1m
filterset (user): [array of 11 redacted]
trustedset:
 added: [array of 1 redacted]
 removed:
  about-scheme
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 160 ms (selfie)
 maxAssetCacheWait: 100 ms

![Screenshot 2023-12-10 222109](https://github.com/realodix/AdBlockID/assets/9379770/72502578-16b6-44b9-8090-3d6add47a381)
