### ISSUE TITLE
bokepitu.world

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1650]
### Sample URL

https://bokepitu.world/bokep-nella-lepas-jilbab-toketnya-bulat-live/

### Ad Blocker

uBlock Origin

### Keterangan

Annoyances di layar video 
![Screenshot_2023-12-11-11-08-53-88_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/094e9397-8302-4dee-ae83-b210505ac3a6)

**Comment by realodix** [comment]
Saya tidak menemukannya
