### ISSUE TITLE
AVTub (66.29.129.161)

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1657]
### Sample URL

http://66.29.129.161/video/bokep-adik-manis-pulang-sekolah-malah-asyik-ngewe-wot-begini-123308.html

### Ad Blocker

uBlock Origin

### Keterangan

Putar vidio dulu lalu klik tombol kembali android di bawah 
![Screenshot_2023-12-15-15-02-21-08_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/8ccd13c3-14ee-4fe1-990a-ef1fac32e15a)

**Comment by realodix** [comment]
Ini apa ya? Manipulasi history bukan? Tanpa putar video, klik tombol back, harusnya ke halaman sebelumnya, tapi malah ke halaman lainnya

**Comment by Jokopentil** [comment]
Hasilnya sama kakak tanpa di putar itu
Di direct ke
![Screenshot_2023-12-15-18-52-39-97_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/realodix/AdBlockID/assets/114223791/cc151368-d377-4274-939b-e9b6433ff277)

**Comment by Jokopentil** [comment]
Pakai yandex+adguard Beta di putar dulu
Di direc kesini kalo pakai kiwi
Itu dibdirec ke shoppie

**Comment by Jokopentil** [comment]
Itu kasusnya sama seperti link berikut
https://mypornvid.fun/videos/3/fAvXgThDWl4/breastfeeding-baby-with-mom-cute/new-breastfeeding-vlog-2023-124-beautiful-mom-breastfeeding-124-desi-breastfeeding-vlogs-01
Sudah saya laporkan adguard tapi kayaknya GK di tangggepi
Gak di putar atau tidak ketika di klik tombol kembali malah di direct

**Comment by realodix** [comment]
Di Saya ketika tekan back mengarah ke  [https://traumaticpower.com/bk3lV-0.Pn2ohp0...vzwk_4yMzzAAB1-](https://traumaticpower.com/bk3lV-0.Pn2ohp0qY_XsRtiuPvT-ExmycznAJ_pCZDDE0F5-YH2IYJ1KY_2MYN4OZPD-dRjSMTDUY_wWZXjYJZm-MbjcYdweY_TgQhyiNjD-VlmmZnWoI_yqYrjsFtl-ZviwZxyyc_3AJBjCPDW-hFpGcH3IR_vKcLnMlNi-YPWQNRrSJ_nUNVpWZXD-0Z0aNbzck_4eMfzgAh1-Jjnkplvmb_moVppqZrD-0t0uNvzwk_4yMzzAAB1-) lalu ke [https://shopee.co.id/shop/40142086?utm_..._term=acobeq1gs3u2](https://shopee.co.id/shop/40142086?utm_campaign=-&utm_content=27443-c9w8404sow0k0oso-EB8P1GPCJ0&utm_medium=affiliates&utm_source=an_11290750000&utm_term=acobeq1gs3u2)

> Sudah saya laporkan adguard tapi kayaknya GK di tangggepi
> Gak di putar atau tidak ketika di klik tombol kembali malah di direct

Ya sudah, Saya tangani yang Saya temukan dahulu. Sisanya yang masalah video, berhubung itu video di host di server international, biar AdGuard yang menanganinya.
