### ISSUE TITLE
javindo.eu.org

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1658]
### Sample URL

https://javindo.eu.org/babyfe-live-ga-pake-bra/?player=2

### Ad Blocker

AdGuard

### Keterangan

Pop up membuka banyak halaman dan anti adblock saat di klik putar 
![Screenshot_2023-12-19-19-19-35-47_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/db3eb699-244f-4920-85af-35521da31d87)

**Comment by realodix** [comment]
Popupnya terjadi di 2 tempat:
- javindo.eu.org (sudah diatasi)
- video player server 2

Anti-adblock hanya terjadi di
- video player server 2

Saya ragu menambahkan video player server 2 ke AdBlockID, karena pas Saya buka mengarah ke https://www.56.com/, jadi menurut Saya lebih baik langsung ke AdGuard saja.
