### ISSUE TITLE
Oppadrama

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1663]
### Sample URL

http://185.217.95.43/

### Ad Blocker

AdGuard

### Keterangan

banner iklan
![image](https://github.com/realodix/AdBlockID/assets/37255346/f329a5f8-6cc2-4529-a100-86ab871889c5)

**Comment by abidjauhar17** [comment]
min http://185.217.95.43/movie-hugo-2011-bluray/

![image](https://github.com/realodix/AdBlockID/assets/37255346/10d5babd-150a-4caa-aed0-d2df5e42810f)

**Comment by abidjauhar17** [comment]
@realodix  http://185.217.95.43/movie-hugo-2011-bluray/
![image](https://github.com/realodix/AdBlockID/assets/37255346/10d5babd-150a-4caa-aed0-d2df5e42810f)

**Comment by realodix** [comment]
Done
