### ISSUE TITLE
tempo.co

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1666]
### Sample URL

https://tekno.tempo.co/read/1810544/8-gunung-berapi-bawah-laut-di-indonesia

### Ad Blocker

AdGuard

### Keterangan

![Screenshot_2024-01-06-12-48-28-37_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/d93e0a8c-4bb1-4cec-bb73-a5fe88318a03)

**Comment by Jokopentil** [comment]
![Screenshot_2024-01-06-12-53-33-98_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/36b1baa9-be2f-45d0-a6d8-e238a2644e8e)

**Comment by realodix** [comment]
Video auto player ada di AdBlockID Plus
