### ISSUE TITLE
bgibola

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1668]
### Sample URL

https://ww3.bgibola.monster/

### Ad Blocker

AdGuard

### Keterangan

ada pop up seperti ini
![image](https://github.com/realodix/AdBlockID/assets/37255346/9186a9c9-2dea-4f25-b6ee-1240d30336a7)

**Comment by abidjauhar17** [comment]
@realodix tolong ini
https://bgibola.com/
![image](https://github.com/realodix/AdBlockID/assets/37255346/ae43a18e-aa55-41bb-9b79-253ed3d47c06)

**Comment by realodix** [comment]
> @realodix tolong ini https://bgibola.com/ 

OK
