### ISSUE TITLE
nontondrama.click

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1669]
### Sample URL

https://tv10.nontondrama.click/night-has-come-season-1-episode-4-2023/

### Ad Blocker

AdGuard

### Keterangan

blokir elemen pop up iklan ini min
![image](https://github.com/realodix/AdBlockID/assets/37255346/71dabe5d-3c4b-4ce3-8f38-115727ae1866)

kayaknya berlaku juga untuk situs https://tv8.lk21official.wiki/

**Comment by realodix** [comment]
Di https://tv8.lk21official.wiki/ Saya tidak menemukannya.

Saya coba buka https://tv8.lk21official.wiki/nd.php?page=night-has-come-season-1-episode-4-2023, hasilnya mengarah ke https://tv10.nontondrama.click/night-has-come-season-1-episode-4-2023/
