### ISSUE TITLE
id.savefrom.net

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1677]
### Sample URL

https://id.savefrom.net/247/

### Ad Blocker

uBlock Origin

### Keterangan

Ada iklan berbahasa Korea / Jepang di tengah halaman. dan sepertinya NSFW 
![Cuplikan layar 2024-01-25 234731](https://github.com/realodix/AdBlockID/assets/68702583/6ffbce87-f078-4a7b-bb45-c174c3e2b10d)

**Comment by realodix** [comment]
Saya tidak menemukan iklan yang dimaksud.
