### ISSUE TITLE
[problem] lk21id.com

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#168]
>ini jg bro https://www.lk21id.com/supernova-the-knight-the-princess-shooting-star-2014/
tombol downloadnya keblock

_Originally posted by @WaferNabati in https://github.com/realodix/AdBlockID/issues/154#issuecomment-569586816_

Maksudnya keblock gimana Bro?

**Comment by WaferNabati** [comment]
@realodix coba matiin adblocknya ntar tombol downloadnya psti muncul

**Comment by realodix** [comment]
> coba matiin adblocknya ntar tombol downloadnya psti muncul dibawah video player

Di Saya muncul Gan dengan adblocker nyala

<details>
  <summary>Screencapture 1 - Chrome 79, uBlock Origin 1.23.0</summary>
  
  ![screencapture-lk21id-supernova-the-knight-the-princess-shooting-star-2014-2019-12-30-19_17_22](https://user-images.githubusercontent.com/1314456/71581857-f0b8e200-2b39-11ea-8a60-f345d0446f7c.png)

</details>

**Comment by WaferNabati** [comment]
@realodix lah ini gw filter regional indonya cmn AdblockID aja sisanya adguard filter sama nano filter

**Comment by realodix** [comment]
Ya ampun dari tadi nyari-nyari, ternyata gara-gara uBlock filters. Terkadang kalau lagi hunting Saya gak nyalain uBlock filters, makanya bingung juga.

<details>
  <summary>Screencapture 2</summary>
  
  ![cats](https://user-images.githubusercontent.com/1314456/71582241-d2ec7c80-2b3b-11ea-9479-39684bb378fe.jpg)
</details>

Solusinya
`lk21id.com#@#[href^="//producebreed.com/"]`

`producebreed.com` pernah dilaporkan pada https://github.com/uBlockOrigin/uAssets/issues/6322 dan dicommit oleh tim uAssets di https://github.com/uBlockOrigin/uAssets/commit/68159bbf409a878353948aca0c88ea045d04e75b

Pada describe the issue tertulis `Fake download buttons`

**Comment by WaferNabati** [comment]
@realodix oh iya tpi keknya itu fake download button gan coba ente cek link downloadnya asli atau fake menuju ke web iklan

**Comment by realodix** [comment]
Palsu, masa setiap film tombol `Link Download 1` selalu mengarah ke https://producebreed.com/ijn8gZtxI3kaVupHm/6198

Ampe huruf acaknya sama juga.
