### ISSUE TITLE
brainly

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1682]
### Sample URL

https://brainly.co.id/mapel/b_indonesia

### Ad Blocker

AdGuard

### Keterangan

tolong hilangkan saja survey nya
![image](https://github.com/realodix/AdBlockID/assets/37255346/b87a1541-cd49-4dbd-8ea7-1a9014a50f04)

**Comment by realodix** [comment]
Sayangnya AdBlockID tidak memiliki filter Annoyance yang berdasarjan subjektif. Anda bisa langsung melaporkannya ke filter khusus Annoyance seperti AdGuard Annoyances atau EasyList Annoyances
