### ISSUE TITLE
Saran Pembersihan Domain Mati Pada Adblockid (2/2/2024)

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#1687]
### Discussed in https://github.com/realodix/AdBlockID/discussions/1686

<div type='discussions-op-text'>

<sup>Originally posted by **abidjauhar17** February  2, 2024</sup>
berikut beberapa domain mati yang saya temukan pada filter AdBlockID per Jumat, 2 Februari 2024

mediaiklan.biz.id
tpro.co.id
tuntasonline.com
beritanusa.id
khabarberita.com
beritaborneo.id
metrobuananews.com
satset.id
hidupdigital.id
nusagates.com
manuskripmagazine.com
suki48.web.id
daftarhewan.com
zonakristen.com
biodata-artis.com
kerajaannusantara.com
amplaumplu.com
bonekamu.com
yunoya.id
dramabarat.com
wacana.my
seputarnegeri.com
smsucapan.com</div>

**Comment by abidjauhar17** [comment]
> ### Discussed in #1686
> Originally posted by **abidjauhar17** February 2, 2024 berikut beberapa domain mati yang saya temukan pada filter AdBlockID per Jumat, 2 Februari 2024
> 
> mediaiklan.biz.id tpro.co.id tuntasonline.com beritanusa.id khabarberita.com beritaborneo.id metrobuananews.com satset.id hidupdigital.id nusagates.com manuskripmagazine.com suki48.web.id daftarhewan.com zonakristen.com biodata-artis.com kerajaannusantara.com amplaumplu.com bonekamu.com yunoya.id dramabarat.com wacana.my seputarnegeri.com smsucapan.com

metromanado.com juga

**Comment by realodix** [comment]
Terima kasih atas kerja kerasnya

Total ada 61 filter dari 24 domain telah dihapus

**Comment by abidjauhar17** [comment]
> Terima kasih atas kerja kerasnya
> 
> Total ada 61 filter dari 24 domain telah dihapus

domain mati terbaru:
`depokrayanews.com`

**Comment by realodix** [comment]
> > Terima kasih atas kerja kerasnya
> > Total ada 61 filter dari 24 domain telah dihapus
> 
> domain mati terbaru: `depokrayanews.com`

OK https://github.com/realodix/AdBlockID/commit/b9d34f41caa663a009d9f46deec10e7d31c65483

**Comment by abidjauhar17** [comment]
@realodix barusan saya cek berdasarkan versi filter AdBlockID dan menemukan domain domain yang sepertinya sudah mati yang bisa dilihat di list berikut
[domains.txt](https://github.com/realodix/AdBlockID/files/14167100/domains.txt)

**Comment by realodix** [comment]
> @realodix barusan saya cek domain berdasarkan versi filter AdBlockID terbaru dan kayaknya menemukan beberapa domain yang sepertinya sudah mati yang bisa dilihat di list berikut [domains.txt](https://github.com/realodix/AdBlockID/files/14167100/domains.txt)
> 
> coba di cek mana aja yang beneran mati
> 
> tambahan ini yang udah jelas mati
> 
> ```
> celebrities.id
> analytics.s.id
> disquscdn.com
> ```

Ok, lanjut di https://github.com/realodix/AdBlockID/issues/1689
