### ISSUE TITLE
Domain dan filter yang telah usang

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#1689]
barusan saya cek domain berdasarkan versi filter AdBlockID terbaru dan kayaknya menemukan beberapa domain yang sepertinya sudah mati yang bisa dilihat di list berikut
[domains.txt](https://github.com/realodix/AdBlockID/files/14167100/domains.txt)

coba di cek mana aja yang beneran mati

tambahan
ini yang udah jelas mati
```
celebrities.id
analytics.s.id
disquscdn.com
```

_Originally posted by @abidjauhar17 in https://github.com/realodix/AdBlockID/issues/1687#issuecomment-1927158606_
            
---

Total: 194 domain (file) + 3 (tambahan)

**Comment by abidjauhar17** [comment]
@realodix ketemu domain mati terbaru
```
lines.id
herosoftmedia.co.id
```

**Comment by realodix** [comment]
Terima kasih untuk kerja kerasnya dalam memeriksa filter AdBlockID. Total ada 199 domain (194 domain pada file dan 5 domain pada komentar) yang telah saya verifikasi.

Total ada 160 fileter dari 104 domain yang telah dihapus.

Berikut beberapa domain yang terverifikasi masih hidup atau dibutuhkan
- 0.0.realodix, hanya dummy dan secara internal dibutuhkan
- tobasatu.comx, typo, domain tobasatu.com masih hidup

<details>
  <summary>93 domain yang teridentifikasi masih hidup</summary>
  
  ```
  kaltimpost.id               https://imagekp.kaltimpost.id/file/banner/kp-epson-jan2024.jpg 
  anhar.my.id                 https://www.anhar.my.id/ 
  annews.co.id                http://www.annews.co.id/ 
  ayokediri.com               https://www.ayokediri.com/ 
  barungeblog.com             https://www.barungeblog.com/ 
  borneonusantaranews.com     https://www.borneonusantaranews.com/ 
  brotutor.net                https://www.brotutor.net/ 
  ceritatoday.com             https://www.ceritatoday.com/ 
  fokuspekalongan.com         https://www.fokuspekalongan.com/ 
  garudarevolution.id         https://www.garudarevolution.id/ 
  guntur.eu.org               https://www.guntur.eu.org/ 
  haibanjar.com               https://www.haibanjar.com/ 
  ibarat.id                   https://www.ibarat.id/ 
  inonton.com                 https://www.inonton.com/ 
  jambioke.com                https://www.jambioke.com/ 
  kabarmetro.co.id            https://www.kabarmetro.co.id/ 
  kalimantana.id              https://www.kalimantana.id/ 
  kamiwebdevelopment.com      https://www.kamiwebdevelopment.com/tips-cara-membuat-blog-seperti-website-profesional/ 
  kartikaryani.com            http://www.kartikaryani.com/ 
  kilaswarta.com              https://www.kilaswarta.com/ 
  kilaulampung.com            https://www.kilaulampung.com/ 
  lalulintaskriminalitas.com  https://www.lalulintaskriminalitas.com/ 
  mediasembilan.co.id         https://www.mediasembilan.co.id/ 
  menoreh.net                 https://www.menoreh.net/ 
  ngemotor.com                https://www.ngemotor.com/ 
  nisaahani.com               https://www.nisaahani.com/ 
  otosportif.com              https://www.otosportif.com/ 
  perstoday.com               https://www.perstoday.com/ 
  pondok-belajar.com          https://www.pondok-belajar.com/ 
  programanesia.com           https://www.programanesia.com/ 
  rismayani.id                https://www.rismayani.id/ 
  sabogoran.com               https://www.sabogoran.com/ 
  sekalamedia.com             https://www.sekalamedia.com/ 
  tebarberita.id              https://www.tebarberita.id/ 
  timor-media.com             https://www.timor-media.com/ 
  tobasatu.com                https://www.tobasatu.com/ 
  topkata.com                 https://www.topkata.com/ 
  wartasehat.id               https://www.wartasehat.id/ 
  adikinfo.my.id 
  agenfilm21.com 
  akmazona.com 
  altinanews.com 
  andalpost.com 
  bioskopkeren.ink 
  bioskopkeren.lat 
  bioskopkerenaja.com 
  bluecreative.co.id 
  bulenonnews.com 
  cleverads.co.id 
  cnnxxi.info 
  dairi24jam.id 
  demokrasimaluku.com 
  e-tivinews.id 
  ebrita.com 
  fakta7.com 
  gratis-iklan.com 
  harianborneopost.com 
  idlix.fun 
  indahsuaranews.co 
  indojambi.id 
  infoberita.id 
  inhupost.com 
  jambiterkini.com 
  jatim1.com 
  jodanews.com 
  juraganfilm.lat 
  kurawalmedia.com 
  livefaktanews.co.id 
  lk21official.watch 
  lutim-news.com 
  mediabanjarmasin.com 
  medikita.com 
  meetkcm.com 
  metroluwuk.com 
  monitor24.id 
  nontonfilms24.com 
  otostar.id 
  penaberlian.com 
  radarbatam.id 
  rebahin.quest 
  seputarsultra.com 
  sergaplampung.com 
  siginjai.id 
  suarabinjai.co.id 
  suarafaktual.com 
  sumbernusantara.co.id 
  terasnews.id 
  tuntaslampung.com 
  vasadnews.com 
  wandercom.id 
  wartaalam.com 
  ziyata.com 
  zonamaluku.com
  ```
</details>

**Comment by abidjauhar17** [comment]
> Terima kasih untuk kerja kerasnya dalam memeriksa filter AdBlockID. Total ada 199 domain (194 domain pada file dan 5 domain pada komentar) yang telah saya verifikasi.
> 
> Total ada 160 filter dari 104 domain yang telah dihapus.
> 
> Berikut beberapa domain yang terverifikasi masih hidup atau dibutuhkan
> 
> * 0.0.realodix, hanya dummy dan secara internal dibutuhkan
> * tobasatu.comx, typo, domain tobasatu.com masih hidup
> 
> 93 domain yang teridentifikasi masih hidup
> ```
> kaltimpost.id               https://imagekp.kaltimpost.id/file/banner/kp-epson-jan2024.jpg 
> anhar.my.id                 https://www.anhar.my.id/ 
> annews.co.id                http://www.annews.co.id/ 
> ayokediri.com               https://www.ayokediri.com/ 
> barungeblog.com             https://www.barungeblog.com/ 
> borneonusantaranews.com     https://www.borneonusantaranews.com/ 
> brotutor.net                https://www.brotutor.net/ 
> ceritatoday.com             https://www.ceritatoday.com/ 
> fokuspekalongan.com         https://www.fokuspekalongan.com/ 
> garudarevolution.id         https://www.garudarevolution.id/ 
> guntur.eu.org               https://www.guntur.eu.org/ 
> haibanjar.com               https://www.haibanjar.com/ 
> ibarat.id                   https://www.ibarat.id/ 
> inonton.com                 https://www.inonton.com/ 
> jambioke.com                https://www.jambioke.com/ 
> kabarmetro.co.id            https://www.kabarmetro.co.id/ 
> kalimantana.id              https://www.kalimantana.id/ 
> kamiwebdevelopment.com      https://www.kamiwebdevelopment.com/tips-cara-membuat-blog-seperti-website-profesional/ 
> kartikaryani.com            http://www.kartikaryani.com/ 
> kilaswarta.com              https://www.kilaswarta.com/ 
> kilaulampung.com            https://www.kilaulampung.com/ 
> lalulintaskriminalitas.com  https://www.lalulintaskriminalitas.com/ 
> mediasembilan.co.id         https://www.mediasembilan.co.id/ 
> menoreh.net                 https://www.menoreh.net/ 
> ngemotor.com                https://www.ngemotor.com/ 
> nisaahani.com               https://www.nisaahani.com/ 
> otosportif.com              https://www.otosportif.com/ 
> perstoday.com               https://www.perstoday.com/ 
> pondok-belajar.com          https://www.pondok-belajar.com/ 
> programanesia.com           https://www.programanesia.com/ 
> rismayani.id                https://www.rismayani.id/ 
> sabogoran.com               https://www.sabogoran.com/ 
> sekalamedia.com             https://www.sekalamedia.com/ 
> tebarberita.id              https://www.tebarberita.id/ 
> timor-media.com             https://www.timor-media.com/ 
> tobasatu.com                https://www.tobasatu.com/ 
> topkata.com                 https://www.topkata.com/ 
> wartasehat.id               https://www.wartasehat.id/ 
> adikinfo.my.id 
> agenfilm21.com 
> akmazona.com 
> altinanews.com 
> andalpost.com 
> bioskopkeren.ink 
> bioskopkeren.lat 
> bioskopkerenaja.com 
> bluecreative.co.id 
> bulenonnews.com 
> cleverads.co.id 
> cnnxxi.info 
> dairi24jam.id 
> demokrasimaluku.com 
> e-tivinews.id 
> ebrita.com 
> fakta7.com 
> gratis-iklan.com 
> harianborneopost.com 
> idlix.fun 
> indahsuaranews.co 
> indojambi.id 
> infoberita.id 
> inhupost.com 
> jambiterkini.com 
> jatim1.com 
> jodanews.com 
> juraganfilm.lat 
> kurawalmedia.com 
> livefaktanews.co.id 
> lk21official.watch 
> lutim-news.com 
> mediabanjarmasin.com 
> medikita.com 
> meetkcm.com 
> metroluwuk.com 
> monitor24.id 
> nontonfilms24.com 
> otostar.id 
> penaberlian.com 
> radarbatam.id 
> rebahin.quest 
> seputarsultra.com 
> sergaplampung.com 
> siginjai.id 
> suarabinjai.co.id 
> suarafaktual.com 
> sumbernusantara.co.id 
> terasnews.id 
> tuntaslampung.com 
> vasadnews.com 
> wandercom.id 
> wartaalam.com 
> ziyata.com 
> zonamaluku.com
> ```

wah lumayan juga ya yang masih aktif..
soalnya tool yang dipake ga ngasih tau yang udah usang itu modified rule nya atau domainnya yang mati
jadi ya disertai semua yang dianggap bermasalah di result.txt nya

**Comment by realodix** [comment]
Thank you, ada 26 domain baru (termasuk sergaplampung.com). Telah dihapus 21 filter dari 13 domain.

Alatnya cukup bagus kok, setidaknya dari ribuan domain bisa terfilter jadi hanya ratusan saja. Tidak semua domain mati, ada juga yang dihapus karena filternya sudah tidak berfungsi.

Berikut domain yang masih aktif / tidak masuk kriteria penghapusan

```
dualipa.id
ewafebri.com
financialreview.id
gesahkita.com
idntimes.id
itstaff.web.id
nontonsbo.com
pusatiklan.co.id
sergaplampung.com
serieswans.com
steffifauziah.com
sulutexpress.com
terasjambi.id
```

---

Kenapa banyak domain yang ternyata masih aktif? 

Saya rasa karena berdasarkan https://adguard.com/kb/general/ad-filtering/filter-policy/#common-criteria, AG menetapkan trafik minimal 100rb (atau sekitar 3rban perharinya). Jadi kalau ada website yang tidak aktif sehari, kemungkinan besar mati atau trafiknya rendah. Ini penting untuk mereka ketahui, karena AG memiliki lebih dari 75rb filter. 

Di lain sisi, trafik belum jadi masalah untuk AdBlockID, karena jumlah filternya masih di bawah 10rb. Dan memang sudah jadi tugas AdBlockID untuk meng-cover situs yang tidak bisa masuk kriteria AG.

Sebagai contoh https://urlfilter.adtidy.org/v2/checkDomains?domain=dualipa.id terdeteksi `used_last_24_hours: false`, itu karena trafik bulanannya hanya 2.60K atau di bawah 100 perhari.

**Comment by realodix** [comment]
Tapi sekali lagi, yang Anda kerjakan bener-bener membantu kok. Lebih dari 160 filter dari ratusan domain berhasil dihapus. Saya ucapkan terima kasih.

**Comment by abidjauhar17** [comment]
> Tapi sekali lagi, yang Anda kerjakan bener-bener membantu kok. Lebih dari 160 filter dari ratusan domain berhasil dihapus. Saya ucapkan terima kasih.

sama sama
dengan senang hati bisa membantu
setidaknya bisa mengurangi beban load dari filter dan juga ekstensi adblocker yang dipakai pengguna lain juga agar tidak terlalu lambat.

sangat mudah untuk memberikan domain/filter yang sudah tidak terpakai, tapi dikarenakan tool nya masih baru, jadi belum punya fitur yang bisa memfilter mana yang domainnya mati, mana yang cuma filternya saja yang tidak terpakai.
Jadi maaf kalau next time masih ada domain penting yang ikut dihasilkan pada result oleh tool nya
terlalu banyak domain untuk saya bisa lakukan pengecualian manual dan ditambah saya tidak tau apakah domain tersebut masih terpakai atau tidak

**Comment by abidjauhar17** [comment]
@realodix apakah ada yang baru dari list berikut?
[domains.txt](https://github.com/realodix/AdBlockID/files/14203611/domains.txt)

**Comment by realodix** [comment]
> apakah ada yang baru dari list berikut? [domains.txt](https://github.com/realodix/AdBlockID/files/14203611/domains.txt)

Dari 94 domain yang diajukan, ada sekita 33 domain baru yang dicurigai. Saya akan cek lebih lanjut.

**Comment by realodix** [comment]
Perbersihan selesai dilakukan.

**Comment by abidjauhar17** [comment]
> Perbersihan selesai dilakukan.

jadinya dapat berapa domain yang dihapus?

**Comment by realodix** [comment]
> > Perbersihan selesai dilakukan.
> 
> jadinya dapat berapa domain yang dihapus?

Sekitar puluhan filter dari belasan domain. Rincian domain yang dihapus ada di commitnya, paling bawah.

**Comment by realodix** [comment]
> untuk yang dramaqu sebenarnya sudah ganti domain ke dramaqu.wtf dan sudah ditambahkan ke filter AdBlockID cuma apa tidak sebaiknya yang domain .lat itu dihapus saja?

Karena waktu itu `dramaqu.lat` situsnya aktif. Seingat Saya dari bentuk filternya beda situs sama `dramaqu.wtf`, mirip kayak https://dramaqu.video

**Comment by abidjauhar17** [comment]
[domains.txt](https://github.com/realodix/AdBlockID/files/14215842/domains.txt)

**Comment by realodix** [comment]
> [domains.txt](https://github.com/realodix/AdBlockID/files/14215842/domains.txt)

Sudah dibersihkan

**Comment by abidjauhar17** [comment]
@realodix `lintaspenjuru.com` mati

**Comment by realodix** [comment]
> @realodix `lintaspenjuru.com` mati

Sudah dibersihkan

**Comment by abidjauhar17** [comment]
[domains.txt](https://github.com/realodix/AdBlockID/files/14235145/domains.txt)

**Comment by realodix** [comment]
> [domains.txt](https://github.com/realodix/AdBlockID/files/14235145/domains.txt)

Sudah dibersihkan

**Comment by abidjauhar17** [comment]
@realodix `nblindonesia.com` mati

**Comment by realodix** [comment]
> `nblindonesia.com` mati

Aktif

![image](https://github.com/realodix/AdBlockID/assets/1314456/d10710ae-563b-4282-8ea8-ed98bfdcf10b)

**Comment by abidjauhar17** [comment]
> nblindonesia.com

lah jelas mati di saya
![image](https://github.com/realodix/AdBlockID/assets/37255346/bc1c70eb-a6fd-4c21-aba9-d3e0d40386f7)

**Comment by realodix** [comment]
> lah jelas mati di saya

Iya, Anda sudah menyebutkannya sebelumnya di atas.

Saya coba cek kembali, `nblindonesia.com` server masih aktif dan filter yang ada masih relevan.

Namun memang dengan catatan system pengecekan otomatis mendeteksi `nblindonesia.com` juga down, lalu Saya konfirmasi manual di https://who.is/whois/nblindonesia.com hasilnya domain Expires jatuh di tanggal 2024-02-12. Mereka biasanya dikasih kesempatan beberapa minggu untuk memperbaruinya sebelum akhirnya benar-benar dimatikan.

![image](https://github.com/realodix/AdBlockID/assets/1314456/456d2438-1b0b-4223-ae59-7c2c9adc7f72)

**Comment by abidjauhar17** [comment]
> > lah jelas mati di saya
> 
> Iya, Anda sudah menyebutkannya sebelumnya di atas.
> 
> Saya coba cek kembali, `nblindonesia.com` server masih aktif dan filter yang ada masih relevan.
> 
> Namun memang dengan catatan system pengecekan otomatis mendeteksi `nblindonesia.com` juga down, lalu Saya konfirmasi manual di https://who.is/whois/nblindonesia.com hasilnya domain Expires jatuh di tanggal 2024-02-12. Mereka biasanya dikasih kesempatan beberapa minggu untuk memperbaruinya sebelum akhirnya benar-benar dimatikan.
> 
> ![image](https://private-user-images.githubusercontent.com/1314456/304448071-456d2438-1b0b-4223-ae59-7c2c9adc7f72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4Mzc5NzMsIm5iZiI6MTcwNzgzNzY3MywicGF0aCI6Ii8xMzE0NDU2LzMwNDQ0ODA3MS00NTZkMjQzOC0xYjBiLTQyMjMtYWU1OS03YzJjOWFkYzdmNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMTUyMTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmNkMjI0YTkyNTZlNTJkZjkyMTEwMGM1NjM2NTgzOGZmMjAzYTBhMzAzNzAwNzI0NTJhNmI3YjFkNTYyODJiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Wli6tGgNZJKZ07iWom5z6ykUtMk56gwGGkeXnVbKSg0)

kalau domainnya sudah mereka update, lalu kenapa di saya masih tidak muncul apa apa di situsnya, sedangkan di anda bisa

**Comment by abidjauhar17** [comment]
`radarsamarinda.com`

[domains.txt](https://github.com/realodix/AdBlockID/files/14296284/domains.txt)

**Comment by abidjauhar17** [comment]
[domains.txt](https://github.com/realodix/AdBlockID/files/14330997/domains.txt)

**Comment by realodix** [comment]
> [domains.txt](https://github.com/realodix/AdBlockID/files/14330997/domains.txt)

Thank you, sudah ditindaklanjuti

**Comment by realodix** [comment]
> apakah ada yang baru? [domains.txt](https://github.com/realodix/AdBlockID/files/14404541/domains.txt)

Belum ada yang baru, thank you

**Comment by abidjauhar17** [comment]
@realodix `inhupost.com` mati

**Comment by realodix** [comment]
> `inhupost.com` mati

OK thankyou

**Comment by realodix** [comment]
> @realodix
> 
> ```
> kabarviral79.com
> ngemotor.com
> ```

kabarviral79.com aktif

https://www.kabarviral79.com/2024/03/f1-powerboat-2024-danau-toba-berjalan-sukses-formasu-jakarta-good-job-kapolda-sumut.html

**Comment by abidjauhar17** [comment]
> > @realodix
> > ```
> > kabarviral79.com
> > ngemotor.com
> > ```
> 
> kabarviral79.com aktif
> 
> https://www.kabarviral79.com/2024/03/f1-powerboat-2024-danau-toba-berjalan-sukses-formasu-jakarta-good-job-kapolda-sumut.html

kemarin terdeteksi mati
mungkin domainnya sudah diupdate sama ownernya

**Comment by abidjauhar17** [comment]
`metroluwuk.com` kelihatannya mati

**Comment by realodix** [comment]
> `metroluwuk.com` kelihatannya mati

Thank you, sepertinya mereka ganti ke https://metroluwuk.net. Saudah Saya tangani https://github.com/realodix/AdBlockID/commit/af3571b09d52a9f8a6b118b09d60944925332a14

**Comment by abidjauhar17** [comment]
`media-abpedsi.com` coba dicek

**Comment by realodix** [comment]
> `media-abpedsi.com` coba dicek

OK

**Comment by abidjauhar17** [comment]
@realodix coba dicek gan
```
genmedia.co.id
kalimantantoday.com
```

**Comment by abidjauhar17** [comment]
@realodix
```
posciety.com
haibanjar.com
bioskopkeren.pw
```

**Comment by realodix** [comment]
> ```
> posciety.com
> haibanjar.com
> bioskopkeren.pw
> ```

Setelah beberapa hari, haibanjar.com aktif kembali https://www.haibanjar.com/2022/08/rencanakan-kuliah-diluar-negeri-melalui.html. Sisanya sudah dihapus. Thank you.

**Comment by abidjauhar17** [comment]
@realodix boleh dicek
```
berbagiteknologi.com
iklankita.id
agenfilm21.com
```

**Comment by realodix** [comment]
> @realodix boleh dicek
> 
> ```
> berbagiteknologi.com
> iklankita.id
> agenfilm21.com
> ```

Thank you

**Comment by abidjauhar17** [comment]
@realodix cek

```
beritaplano.com
jurnalexpose.com
iklanmania.com
shinobijawi.id
```

**Comment by realodix** [comment]
Ok thank you

**Comment by abidjauhar17** [comment]
@realodix boleh dicek `karyaiklan.co.id`

**Comment by abidjauhar17** [comment]
@realodix
```
nonstopnews.id
anoboy2.one
```

**Comment by abidjauhar17** [comment]
@realodix  `detikbrita.com`

**Comment by realodix** [comment]
Thank you

**Comment by abidjauhar17** [comment]
@realodix coba cek
```
lomboktvnews.com
rakyatkalteng.com
aluswahtuban.or.id
jurnalpolri.com
liputankendalterkini.com
oppadrama.cc
adikinfo.my.id
```

**Comment by realodix** [comment]
Terima kasih, untuk `rakyatkalteng.com` masih bisa diakses https://www.rakyatkalteng.com/kelestarian-sungai-perlu-dijaga-bersama-2/

**Comment by abidjauhar17** [comment]
@realodix 
```
radarbahtera.com
sriwijayadaily.co.id
bagas31.one
kuyhaa-me.net
```

**Comment by realodix** [comment]
Thank you

**Comment by abidjauhar17** [comment]
@realodix bisa dicek
```
0.0.realodix
1detik.info
agtvnews.com
article-dnz.com
balitren.com
beritalutim.com
bgibola.autos
bgibola.boats
bgibola.bond
billboard-indonesia.com
bolasiar.baby
bolasiar.beauty
brayanews.co.id
desentral.news
dewatanetwork.com
ecology.my.id
ekspres.newsm
fajarbanten.com
fordata.id
freedomnews.id
hardrockfm.com
hisbah.net
idntimes.id
ihwal.id
infodairi.id
jambivalen.com
jobskarir.id
kang-ismet.com
konstruksi.co.id
kontenjatim.com
korankalimantan.com
lk21official.pics
mataberita.co.id
mediaaceh.co
melongmovie.site
oduu.news
okestream.bio
on24jam.tv
pentingpedia.com
programanesia.com
riaupublik.com
risinggeeks.com
rkonline.id
samsungstarters.com
siimanga.cyou
slemannews.com
sorotkamera.com
spiritkepri.com
suara-ntt.com
sudahbaca.com
sumselpedia.com
terdekatku.com
thepapuajournal.com
traznews.com
tvbersama.bond
vasadnews.com
wartafavorit.com
warungkomik.com
```

**Comment by realodix** [comment]
Terima kasih sudah mengajukan 58 domain, sebanyak 52 domain telah dihapus.

Sisanya yang tidak dihapus:
- 1 domain `ekspres.newsm` typo, sudah dibenerin (ca5b000b2e95241cb8ea5b88b6db7e70dd589540).
- 4 domain sedang dipantau.
- 1 domain `0.0.realodix` (hasrusnya ada di [/src/extended.adfl#L42](https://github.com/realodix/AdBlockID/blob/37b2309e46ac7c460ce90e88ccc4fd39ebe5c6bd/src/extended.adfl#L42)), ini merupakan dummy untuk memantau kompabilitas filter dengan AdGuard.

**Comment by realodix** [comment]
maenhp.com ganti domain (2e465e02fe9c587726382c469a7a6589d5690885)

Thank you.

**Comment by abidjauhar17** [comment]
@realodix 
```
explorenews.net
kabar.news
protapriau.com
sulselnet.com
tangerangraya.net
tipsgaptek.com
tivipedia.com
```

**Comment by realodix** [comment]
Thank you

**Comment by abidjauhar17** [comment]
@realodix 
```
zonalinenews.com
apakabarnusantara.com
citawanita.com
kendarinesia.com
poros.id
pascol18.live
```

**Comment by abidjauhar17** [comment]
@realodix 
```
asupanme.shop
bantenjurnalisnews.com
bungasbanten.id
celahkotanews.comdayaknews.com
detikindonesia.co.id
faktualmedia.co
indohd.buzz
infobumn.com
jurnaldepok.com
kabarairta.com
kabarnas.com
kenangananggora.com
klikrealita.com
kucinglucu.net
lokadewata.com
maenhp.org
mediapromoter.id
melayuboleh.me
okson.co.id
pakaiatm.com
playvid.cam
sidikkasus.co.id
siikomik.com
sikapindonesia.com
suaraflores.com
sunting.co.id
tepat.id
yongganas.com
```

**Comment by abidjauhar17** [comment]
@realodix dari AdBlockID + AdBlockID Plus

```
ameeralife.com
bettercrack.com
bluevid.cam
bratanews-id.com
cfcdn.apcqwd.com
cinemaindo.dev
cuanbgt.id
d21.im
deteksimalut-news.com
detikfajar.com
ditonton.dev
filmapik.my
gudangmovies21.host
haluanindonesia.co.id
idenesia.co
image.bannermovie.online
kabarselebes.co.id
khazanahgrobogan.com
komik-cast.com
koranmerah.com
lebaknews.com
literasi.net
lulopedia.id
majalahmataborneonews.com
mediacybernews.com
megamanado.com
monitor24.id
movies21.ing
nasionalita.com
nitizen.id
okestreamtv.com
pejuhinxxx.click
sajada.id
sugawa.id
worldforcrack.com
ziapc.org
```

**Comment by realodix** [comment]
Terima kasih, Saya akan memeriksanya.

Untuk sementara, ini daftar ignore yang saya miliki. Sebagai contoh `https://d21.im/` dan `https://cinemaindo.dev/` jika diakses langsung akan terlihat mati, tetapi `https://tv.d21.im/` dan `https://tv1.cinemaindo.dev/` bisa diakses.

```
cinemaindo.dev
ditonton.dev
ganool.app
movies21.ing
filmapik.my
d21.im
gudangmovies21.host
movieon21.mov
ayononton.app
teman21.app
```
