### ISSUE TITLE
Oppadrama (185.217.95.49)

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1690]
### Sample URL

http://185.217.95.49/

### Ad Blocker

AdGuard

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/37255346/7819fa9a-f93c-40c6-b5fc-fd75d31ce17e)

**Comment by abidjauhar17** [comment]
http://185.217.95.49/movie-fantastic-beasts-and-where-to-find-them-2016-bluray/

link banner: https://t.ly/m717ads

![image](https://github.com/realodix/AdBlockID/assets/37255346/6bef6d40-e786-4763-9cb3-1c9cdf829b20)

**Comment by abidjauhar17** [comment]
@realodix belum hilang?
![image](https://github.com/realodix/AdBlockID/assets/37255346/710c9190-def3-4a5b-93d0-e913601b82cc)

**Comment by realodix** [comment]
Sudah saya perkuat filternya

**Comment by abidjauhar17** [comment]
@realodix https://45.11.57.134/
ada iklan banner baru

**Comment by realodix** [comment]
Thank you
