### ISSUE TITLE
akurat.co

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1703]
### Sample URL

https://banten.akurat.co/budaya/1323705258/bahaya-5-jenis-ilmu-pelet-di-indonesia-yang-sangat-sulit-disembuhkan?page=2

### Ad Blocker

---

### Keterangan

![Screenshot_2024-02-18-19-07-25-42_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/c080caea-f204-484e-a2bc-1cdcd5f19dcf)
![Screenshot_2024-02-18-19-07-15-13_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/6399e219-d191-4c1d-b2fa-4569db410023)
Mengapa setelah di update iklan blank GK hilang
Coba tolong di skrol
Itu iklan blank nya lebih dari satu

**Comment by realodix** [comment]
Duplicate of #1701

---

> Mengapa setelah di update iklan blank GK hilang
> Coba tolong di skrol
> Itu iklan blank nya lebih dari satu

Iya belum Saya rilis. Ada filter yang ngaco, jadi terpaksa Saya revert ke versi kemarin. Saat ini sudah dirilis.
