### ISSUE TITLE
transtv.co.id

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1705]
### Sample URL

https://www.transtv.co.id/live/cnn

### Ad Blocker

AdGuard

### Keterangan

- Tidak bisa klik kanan (contextmenu)
- Dan picture in picture juga disabled

mencoba secara manual melalui console di developers tool nya browser chrome.
$("[oncontextmenu]").prop("oncontextmenu", true)
$("[disablepictureinpicture]").removeAttr("disablepictureinpicture")

Tidak berpengaruh 'kecuali' jika inspect element terlebih dahulu.

**Comment by realodix** [comment]
Thank you

- uBlock Origin: Segera lakukan force update, tersedia pada AdBlockID v24.2.107 atau lebih.
- AdGuard: Tunggu update dari AdGuard (kurang lebih 3-4 jam), lalu force update.
