### ISSUE TITLE
bocilov.pro

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1707]
### Sample URL

Pop up halaman 

### Ad Blocker

AdGuard

### Keterangan

Pilih salah satu video lalu putar sebentar
Lalu klik tombol kembali pada Android
Muncul pop up
![Screenshot_2024-02-20-17-17-12-01_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/f0283f02-90b0-412a-9b9b-f7ba6c6b12b7)

**Comment by realodix** [comment]
https://bocilov.pro/category/indonesia/
