### ISSUE TITLE
zonim.xyz (get4links.com) - Fake button

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#171]
**Jenis iklan** (hapus yang tidak perlu)
- Fake button

**Sample URL**
http://zonim.xyz/fsGct6

**Source URL**
https://kazefuri.web.id/spirit-of-the-book-episode-11-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
fake button dan popups sehabis nyelesaiin captcha

**Comment by realodix** [comment]
Thank you
