### ISSUE TITLE
chordtela.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1718]
### Sample URL

https://www.chordtela.com/2016/10/ungu-aku-bukan-pilihan-hatimu.html

### Ad Blocker

AdGuard

### Keterangan

elemen iklan kosong

Adguard ON
![image](https://github.com/realodix/AdBlockID/assets/37255346/dc819ad7-354b-429a-8b28-6a5f50780c91)

Adguard OFF
![image](https://github.com/realodix/AdBlockID/assets/37255346/0bcabf48-5347-424e-8a50-dc5608773b14)

**Comment by abidjauhar17** [comment]
@realodix belum hilang ya elemennya?
![image](https://github.com/realodix/AdBlockID/assets/37255346/83898014-7710-49d9-b32d-46081c90598c)

oh ya, dan saya mengalami halaman yang rusak seperti chord tidak rapih (contohnya pada gambar diatas)
jadi, saya harus memasukkan user rules ini `chordtela.com#@$#* { user-select:text!important; }` yang dikasih sama member Adguard
bagaimana cara agar saya tidak perlu memasukkan user rules itu?

**Comment by realodix** [comment]
> belum hilang ya elemennya?

Kalau dari jamnya, Anda comment sekitar 5 jam yang lalu, sementara AG baru ngebuat updatenya sekitar 1 jam yang lalu. Jadi memang saat itu belum ada update otomatis dari AG.

Saya close issue ketika update sudah tersedia di uBO.

Untuk ketersediaan update AG, hal paling mudah lihat di `https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_120_AdBlockID` aja Bro. Kalau ada commit terbaru, berati updatenya sudah tersedia.

![image](https://github.com/realodix/AdBlockID/assets/1314456/43b60a02-5885-4e27-902b-eb3bfccc227a)
![image](https://github.com/realodix/AdBlockID/assets/1314456/78fa880f-72b7-4420-8334-9816d33afe02)

**Comment by realodix** [comment]
> oh ya, dan saya mengalami halaman yang rusak seperti chord tidak rapih (contohnya pada gambar diatas)
> jadi, saya harus memasukkan user rules ini chordtela.com#@$#* { user-select:text!important; } yang dikasih sama member Adguard

Seperti yang pernah dibahas di `https://github.com/AdguardTeam/AdguardFilters/issues/170244#issuecomment-1883633496`, kemungkinan itu adalah bug pada AG. Issue telah dibuat di `https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2679`, tapi memang halaman hancur ketika log terbuka.

> bagaimana cara agar saya tidak perlu memasukkan user rules itu?

Sedikit rumit, karena harus mencoba satu per satu untuk mencari tahu penyebabnya.
- Anda bisa install ulang plugin AdGuard. Clear cache, lalu lihat apakah masih error atau tidak.
- Anda bisa matikan seluruh plugin yang ada, kucuali AdGuard. Clear cache, lalu lihat apakah masih error atau tidak. Ini untuk memastikan apakah masalahnya pada plugin lainnya.
- Coba di browser lain, ini untuk memastikan apakah masalahya ada pada browser.

**Comment by abidjauhar17** [comment]
> > oh ya, dan saya mengalami halaman yang rusak seperti chord tidak rapih (contohnya pada gambar diatas)
> > jadi, saya harus memasukkan user rules ini chordtela.com#@$#* { user-select:text!important; } yang dikasih sama member Adguard
> 
> Seperti yang pernah dibahas di `https://github.com/AdguardTeam/AdguardFilters/issues/170244#issuecomment-1883633496`, kemungkinan itu adalah bug pada AG. Issue telah dibuat di `https://github.com/AdguardTeam/AdguardBrowserExtension/issues/2679`, tapi memang halaman hancur ketika log terbuka.
> 
> > bagaimana cara agar saya tidak perlu memasukkan user rules itu?
> 
> Sedikit rumit, karena harus mencoba satu per satu untuk mencari tahu penyebabnya.
> 
> * Anda bisa install ulang plugin AdGuard. Clear cache, lalu lihat apakah masih error atau tidak.
> * Anda bisa matikan seluruh plugin yang ada, kucuali AdGuard. Clear cache, lalu lihat apakah masih error atau tidak. Ini untuk memastikan apakah masalahnya pada plugin lainnya.
> * Coba di browser lain, ini untuk memastikan apakah masalahya ada pada browser.

ini aneh karena saya pun tidak lagi membuka filtering log adguard saat mengunjungi web itu.
untuk ekstensi adguard saya sudah 2-3 kali reinstall tetapi masih sama saja.
kalau ekstensi lainnya, saya tidak memiliki ekstensi mencurigakan yang bisa merusak website itu

**Comment by abidjauhar17** [comment]
> Memang pakai browser dan extensinya apa saja? Nanti akan Saya samakan

sejauh ini sudah aman2 saja tanpa user rules
saya pake adguard versi beta terbaru
![image](https://github.com/realodix/AdBlockID/assets/37255346/470a4697-09ac-4be6-ad7e-56859da9921e)

**Comment by realodix** [comment]
Selain AG ada apa lagi?

**Comment by abidjauhar17** [comment]
> Selain AG ada apa lagi?

ekstensi di browser?
ini
![image](https://github.com/realodix/AdBlockID/assets/37255346/fd7a2f70-901c-49fe-875a-5c9e960d18b4)
