### ISSUE TITLE
semawur.com - fake button

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#172]
**Jenis iklan** (hapus yang tidak perlu)
- Fake Button

**Sample URL**
https://semawur.com/9mvKfJBi9mu

**Penjelasan Lebih Lanjut**
<Details>

![z3](https://user-images.githubusercontent.com/9379770/71588228-536aa780-2b53-11ea-8bd2-5a370985130b.png)

**Comment by realodix** [comment]
Thank you

**Comment by realodix** [comment]
[semawur.com - Fake Button #91](https://github.com/realodix/AdBlockID/issues/91)
