### ISSUE TITLE
vidio.com

### ISSUE THREAD

**Issue by 0xh3LL0** [realodix/AdBlockID#1720]
### Sample URL

https://www.vidio.com/watch/8077325-mega-zoo-25-februari-2024

### Ad Blocker

uBlock Origin

### Keterangan

iklan masih tampil tapi hanya audio saja,

misal lihat video, tiba2 video ngepause, lalu ada lagu shopee, tapi tidak bisa di skip, karena iklannya sendiri tidak tampil, tapi hanya audionya saja, setelah lagu habis video ngeplay lagi.

mungkin karena ini
![Untitled](https://github.com/realodix/AdBlockID/assets/23132217/a25fe8c7-4529-41f8-919c-272faaca7e89)

**Comment by 0xh3LL0** [comment]
uBlock Origin: 1.56.0
Firefox: 115
filterset (summary):
 network: 145701
 cosmetic: 76134
 scriptlet: 37192
 html: 1791
listset (total-discarded, last-updated):
 added:
  https://cdn.jsdelivr.net/gh/realodix/AdBlockID@master/dist/adblockid.adfl.txt: 9297-0, 22h.57m
  https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt?_=1: 23263-33, 22h.57m
  CHN-0: 25447-139, 3d.23h.8m
  JPN-1: 14119-24, 3d.23h.8m
 default:
  user-filters: 711-1, never
  ublock-filters: 37425-2190, 1m Δ
  ublock-badware: 7807-14, 1m Δ
  ublock-privacy: 738-0, 1m Δ
  ublock-unbreak: 2297-0, 1m Δ
  ublock-quick-fixes: 159-1, 1m Δ
  easylist: 81990-678, 1m Δ
  easyprivacy: 50343-920, 1m Δ
  urlhaus-1: 7595-0, 22h.57m
  plowe-0: 3782-1, 11d.5h.43m
filterset (user): [array of 711 redacted]
trustedset:
 added: [array of 2 redacted]
switchRuleset:
 added: [array of 1 redacted]
hostRuleset:
 added: [array of 63 redacted]
userSettings:
 advancedUserEnabled: true
hiddenSettings: [none]
supportStats:
 allReadyAfter: 1064 ms (selfie)
 maxAssetCacheWait: 445 ms
 cacheBackend: indexedDB

**Comment by realodix** [comment]
> iklan masih tampil tapi hanya audio saja,

> misal lihat video, tiba2 video ngepause, lalu ada lagu shopee, tapi tidak bisa di skip, karena iklannya sendiri tidak tampil, tapi hanya audionya saja, setelah lagu habis video ngeplay lagi.

![image](https://github.com/realodix/AdBlockID/assets/1314456/f231402c-55cb-4641-81af-609542058480)

Saya menemukan Fuck Fuckadblock penyebabnya, mereka membuka beberapa blokir yang seharusnya terblokir. Hal itu mungkin cukup bagus untuk situs di luar sana, tapi sayangnya di vidio.com malah membuat iklannya jadi muncul.

Solusinya Anda bisa langsung melaporkannya ke https://github.com/bogachenko/fuckfuckadblock dan mematikan Fuck Fuckadblock hingga mereka membuat perbaikannya.

**Comment by 0xh3LL0** [comment]
ok sip,
nanti biar saya masukkan blokir sendiri,
repot juga kalau saya harus matikan fuckfuckadblock.

terima kasih.
