### ISSUE TITLE
telkomsel.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1721]
### Sample URL

https://www.telkomsel.com/shops/checkout/228173

### Ad Blocker

AdGuard

### Keterangan

cookie warning
![image](https://github.com/realodix/AdBlockID/assets/37255346/4b7c8cf2-e704-4200-984c-a4e6c08aa143)

**Comment by realodix** [comment]
Halo, kita tidak menangani cookie, karena cukup ditekan sekali saja, lalu tidak akan muncul kembali. Kecuali cookie yang seperti popup selalu muncul terus menerus, kita bisa bantu tangani.
