### ISSUE TITLE
detik.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1723]
### Sample URL

https://www.detik.com/jatim/berita/d-7234509/ini-awal-ramadan-2024-versi-muhammadiyah-nu-dan-pemerintah

### Ad Blocker

AdGuard

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/37255346/0ccd8984-537a-47c6-98a5-e28896b3c4ad)

**Comment by abidjauhar17** [comment]
@realodix commit terbaru sudah terlihat di filtering log adguard, tapi sepertinya masih ada element nya
![image](https://github.com/realodix/AdBlockID/assets/37255346/93e9176c-ad14-43d7-b33c-c32ddec80a46)

**Comment by abidjauhar17** [comment]
> Thank you sudah memperhatikannya, sudah diperbaiki. Gokil juga ini detik dalam sehari bisa 2x berubah.

awalnya saya kira emang commit nya belum nyampe ke adguard aja..
tapi pas liat filtering log, udah ada kok rules dari commit nya

**Comment by abidjauhar17** [comment]
@realodix tapi kok tetep ada ya, padahal udah update filter ngikutin dari adguardnya
ditambahin manual ke user rules juga ga hilang element nya
![image](https://github.com/realodix/AdBlockID/assets/37255346/78581831-d300-4a6b-bd3c-96e5db75aeb0)
![image](https://github.com/realodix/AdBlockID/assets/37255346/b9c3f9df-20a6-4ca8-9066-c5b60790ff07)

**Comment by realodix** [comment]
> tapi kok tetep ada ya, padahal udah update filter ngikutin dari adguardnya ditambahin manual ke user rules juga ga hilang element nya

Karena dari kemarin main kucing2an terus Bro. Dalam beberapa jam, mereka terus menerus merubah strukturnya.

```diff
- <div style="width: 100%;height: 280px;background-color: #f8f8f8;font-family: Roboto, sans-serif;font-size: 12px;align-content: center;position: relative;">
+ <div style="width:100%;height: 280px;background-color: #f8f8f8;font-family: Roboto, sans-serif;font-size: 12px;align-content: center;position: relative;">
```

Maka filternya harus dirubah jadi
```diff
- detik.com##.detail__body-text div[style^="width: 100%;"]:has(> span + div > [id^="div-gpt-"])
+ detik.com##.detail__body-text div[style^="width:100%;"]:has(> span + div > [id^="div-gpt-"])
```

Dari kemarin hanya masalah ini saja `width:100%;`  jadi `width: 100%;`, terus berubah lagi jadi `width:100%;`

Untuk sementara Saya diamkan dulu. Anda bisa menggunakan filter yang hijau dulu untuk sementara, nanti kalau mereka berubah, tinggal ikutin saja.
