### ISSUE TITLE
firstmedia.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1724]
### Sample URL

https://www.firstmedia.com/article/starlink-penyelamat-atau-petaka-ini-kelebihan--kekurangan

### Ad Blocker

AdGuard

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/37255346/be96996d-60a6-4f0a-bc8e-4981f71b3a13)
![image](https://github.com/realodix/AdBlockID/assets/37255346/85b177e0-487c-4aca-ba20-f458e5cd150e)

**Comment by realodix** [comment]
Halo, kita tidak menangani cookie, karena cukup ditekan sekali saja, lalu tidak akan muncul kembali. Kecuali cookie yang seperti popup selalu muncul terus menerus, kita bisa bantu tangani.

Untuk bannernya, karena yang diiklankan produk mereka sendiri, sama seperti [kebijakan AdGuard](https://adguard.com/kb/general/ad-filtering/filter-policy/#limitations-and-exceptions), kitapun juga tidak menanganinya.

Anda bisa menggunakan filter ini

```adblock
firstmedia.com##.MuiBox-root:has(> a[href*="?promo=behavior&campaign=Personalized"])
```
