### ISSUE TITLE
republika.co.id

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1728]
### Sample URL

https://islamdigest.republika.co.id/berita/qyhl7t366/badan-fatwa-turki-haramkan-beberapa-jenis-boga-bahari

### Ad Blocker

uBlock Origin

### Keterangan

![Screenshot_2024-03-17-17-39-58-35_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/30f6a451-2e3b-452c-ac3b-68486e4500ae)

**Comment by realodix** [comment]
Untuk social, bisa gunakan `AdGuard Social Media filter`

```adblock
republika.co.id##.vuukle-powerbar-x.share-fixed
```
