### ISSUE TITLE
wizardsubs.com - Anti right click, selection & hotkey 

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#173]
**Jenis iklan** (hapus yang tidak perlu)
- Anti selection anti right click

**Sample URL**
https://wizardsubs.com/2019/12/04/kamen-rider-drive-episode-01-48-subtitle-indonesia-batch/

**Penjelasan Lebih Lanjut**
anti copy paste

**Comment by realodix** [comment]
@WaferNabati Ini hanya bisa pakai scriptlet Gan.. 

Untuk uBlock sudah ada di uBlock Annoyances
https://github.com/NanoMeow/QuickReports/issues/2497

AdGuard, ping @zloyden

**Comment by WaferNabati** [comment]
@realodix oh iya lupa tdi filter annoyancenya blom gw idupin setelah gw reset default
iya dlo gw rasa inget pernah submit di quick issue reporter

**Comment by zloyden** [comment]
Added to our filters.
