### ISSUE TITLE
bolasport.com

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1734]
### Sample URL

https://www.bolasport.com/read/314052966/berani-kangkangi-marc-marquez-pedro-acosta-merasa-sudah-seperti-casey-stoner

### Ad Blocker

uBlock Origin

### Keterangan

![Screenshot_2024-03-29-16-53-55-10_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/c637b1f2-32ba-42ac-b889-735d037f2171)

**Comment by Jokopentil** [comment]
Scroll kebawah baru muncul

**Comment by realodix** [comment]
Ok thank you, ada di AdBlockID Plus yaa
