### ISSUE TITLE
 LingBokep (173.255.236.220) #1735 

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1736]
### Sample URL

https://173.255.236.220/sin/47522-toket-besar-lisa-chan-tiktokers

### Ad Blocker

---

### Keterangan

![Screenshot_2024-03-29-21-33-13-22_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/ef3b64ef-7fe9-4489-a73b-2ffdb6493cec)
![Screenshot_2024-03-29-21-34-48-65_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/0d73a5f5-378e-4f77-ab23-9d17e44a8e28)

**Comment by realodix** [comment]
**Related**
- https://github.com/realodix/AdBlockID/issues/1672
- https://github.com/realodix/AdBlockID/issues/1735

---

Pastiin AdBlockID ada di v24.3.83 atau lebih tinggi.
