### ISSUE TITLE
streamxxi.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#174]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Overlay

**Sample URL**
https://streamxxi.com/

**Penjelasan Lebih Lanjut**
Iklan Judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
gan ini trmasuk adverts bkan `https://www.ijiraeitwqpj.com/hui.js` 
`https://streamxxi.com/the-last-thing-he-wanted-2020/`

**Comment by realodix** [comment]
> gan ini trmasuk adverts bkan https://www.ijiraeitwqpj.com/hui.js
> https://streamxxi.com/the-last-thing-he-wanted-2020/

Iya bener, baru aja masuk https://github.com/easylist/easylist/commit/b290e45f8479544a56c33152b6d455d1981afc17
