### ISSUE TITLE
kumapoi.info

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1744]
### Sample URL

https://kumapoi.info/

### Ad Blocker

AdGuard

### Keterangan

- anti adblock
<img src="https://github.com/realodix/AdBlockID/assets/34759917/00b901b3-6f2c-486e-9037-90fc3ab59f51" width=500>

**Comment by realodix** [comment]
**Info Ketersedian Update**
- **uBO**: Sudah tersedia.
- **AG**: Masih menunggu. Bisa lihat di https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_120_AdBlockID, jika ada commit terbaru artinya sudah tersedia.
