### ISSUE TITLE
republika.co.id (mobile)

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1745]
### Sample URL

https://news.republika.co.id/berita/sbtnfg318/kisah-dua-saudara-kandung-jadi-tersangka-di-kasus-timah

### Ad Blocker

AdGuard

### Keterangan

![Screenshot_2024-04-13-19-19-41-96_4d38fce200f96aeac5e860e739312e76](https://github.com/realodix/AdBlockID/assets/114223791/c16f9bb2-9a10-4361-b3a9-99f6fe579b8c)

**Comment by realodix** [comment]
Ternyata struktur mobilenya berubah sedikit. Perbaikan sudah dilakukan

**Terkait**
- https://github.com/realodix/AdBlockID/issues/1743

---

**Info Ketersedian Update**
- **uBO**: Sudah tersedia.
- **AG**: Masih menunggu. Bisa lihat di https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_120_AdBlockID, jika ada commit terbaru artinya sudah tersedia.
