### ISSUE TITLE
acefile.co

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1746]
### Sample URL

https://acefile.co/f/84206172/alqanime_pgtk_bd_03_720p-mp4

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/19517680/6690c10e-be1b-4e7b-9081-5228218ba67a)

**Comment by realodix** [comment]
@Yuki2718

`acefile.co###btmx` is already in AdGuard, please add to uBlock filters

![image](https://github.com/realodix/AdBlockID/assets/1314456/db0a4ecc-7387-42bc-ac04-89edfdcb485e)

![image](https://github.com/realodix/AdBlockID/assets/1314456/63611346-d48e-4dd4-bd2e-a3fafe521011)

**Comment by Yuki2718** [comment]
Hmm, the link is 404. But okay, thank you for telling us.
