### ISSUE TITLE
nontonindrama.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#175]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
https://nontonindrama.com/

**Penjelasan Lebih Lanjut**
Popups

**Comment by realodix** [comment]
Sample url popup yang muncul
- [https://dnkwgzmuxv.com/O.asp?m=64661...Vejo%3D](https://dnkwgzmuxv.com/O.asp?m=6466148&p=114067537&s=1577790107&y=3055436106&j=493&r=%21d%2Fg76MKlZCoxbFHMOtEsEuW0sQ5z%2BZcpfr56M%2F2zv2sEn4a0w8trwqaOuHyNXkfuP4tEskQelNnkPm27i3a4hvgR1KIaAXnBEC%2FmMJOl5X6Y7wIToSk4D%2FD53PBkWEfC9TxOHqB4eTFW9zFcXHaGPVaKn4hNw4T%2BJU43RpwWMIL5AO%2ByXFDRJibHNjBtmIUtzzou2%2BsZRdJyDvvGKPJc3HNAjYvIJmFNC7FZB0Vj%2FrXq1BZiwkKAs0hTozMEfLMDYOutbe5fbRlsZY85TaGPBuY3aQRUrE1PrSNedRH%2BIcNwtjf59CalU6sRSIKK83ZUj7CPTSmFxjXaKek%2Fa%2B7bPNm5IRqUrrrvjvHyNpPVyGHnbatgfItGLGLciFCtl%2BOa7DSPG14veOMTGg7EZdP8ww6dLW12FQ3cqrTLyVn849tlPwj5TfI1nFKfhjSjpmbrWq6UqwbE2Pk1P5JkEoLV%2Bwei0u3o7LEitWaanQFVejo%3D)
- [https://dnkwgzmuxv.com/M.html?o=78309...gvPUaPz](https://dnkwgzmuxv.com/M.html?o=783096&r=667008892&s=1577790123&j=3055436106&x=449&c=%21N68PfCjnjrBKGy6hsJdxMpXYap2pSSzrfrU%2F7lpc6HdZ%2BUEFUVpUoEi0uh2Y5frwWoosGB8nxGWjRx1zjEZmeyr19nzriJj3uIuJFjnBfFTlJ%2F1IzJHGn%2FbJAral9XwOi9RdT5dxHVefLm6ygUtYFywYBc28Czk659r5nKTDtCiymdASt8eakk2aigl0Zu9%2Fcmw6ZXv%2B7SCZto0l9eKTS2w7dJXBbeB6pd6b5ufpq7Mf%2BbTpRS6VHab0AWWJvlNJbJLNiZohj8wFTOdmPtew0tVOcvZqsfWb7cXsCTrsrBNCYNiUCuy4AJpifrsXSv5Y2qDQGu8ez%2BJ5TLguVzF4wDqBpH9ELCO42fVvvg5GHr7cmNpRbpMKP%2FOEoFjXW7hkfez%2BQINLs9v3AHVbPXirfqvZsJx9j3povSDdNBPCI2nje2mFCJPwpaWZkgvPUaPz)

Penyebanya adalah domain `dnkwgzmuxv.com`. Mohon update easylistnya Gan, sudah dimasukkan pada [db36ad5#diff-4903e75](https://github.com/easylist/easylist/commit/db36ad507f48346ff1d24ee2ae7af1f4e6217d20#diff-4903e7590de76df1abe1703921a2c88bR9148). Sory Saya tag `invalid`.

Thank you

**Comment by WaferNabati** [comment]
@realodix klo yg ini ada popupnya jg
https://movie8stream.com/abigail-2019/
