### ISSUE TITLE
teraboxapp.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1762]
### Sample URL

https://teraboxapp.com/s/1mJ4ydNe1VRntdmSHuzRGJQ

### Ad Blocker

uBlock Origin

### Keterangan

banner

**Comment by realodix** [comment]
Ini link Inter, langsung ke sini aja
- https://github.com/uBlockOrigin/uAssets
- https://github.com/AdguardTeam/AdguardFilters
