### ISSUE TITLE
solopos.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1766]
### Sample URL

https://soloraya.solopos.com/5-sosok-yang-dijuluki-crazy-rich-asal-solo-1134107

### Ad Blocker

uBlock Origin

### Keterangan

ada audio otomatis play, ini datangnya tiba2 dan random, tolong dihilangkan,

![image](https://github.com/realodix/AdBlockID/assets/19517680/5c4c7818-7861-437c-a1c5-f3978a01f6ac)

**Comment by realodix** [comment]
Suaranya muncul dari radio ini bukan?

![image](https://github.com/realodix/AdBlockID/assets/1314456/daf6f75f-cdeb-4a51-811c-524575177e07)

**Comment by 3xploiton3** [comment]
iya saya nggak nyentuh websitenya kurang dari 15 menit, saya tinggal nonton youtube, terdengar suara aneh, setelah saya cari ternyata dari website solopos, autoplaynya aja yg di disable bisa?
tanpa menghilangkan bannernya, klo nggak bisa terpaksa hilangkan aja,

**Comment by realodix** [comment]
> autoplaynya aja yg di disable bisa?
> tanpa menghilangkan bannernya, klo nggak bisa terpaksa hilangkan aja,

Saat ini tidak bisa. Sebagai gantinya Saya hard remove, ada di AdBlockID Plus ya
