### ISSUE TITLE
[SafelinkScript] lk21.rest

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#177]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://lk21.rest/joker-2019/
https://layarkaca18.net/avengers-infinity-war-2018/

**Penjelasan Lebih Lanjut**
`https://androidbusiness.us/wp-content/themes/sflink2017/js/safelink.js`

**Comment by WaferNabati** [comment]
@realodix sama yg ini gan
||githack.com/crezenity/digimoclubwp/*$script,third-party
||githack.com/crezenity/imoclub/*$script,third-party
||githack.com/crezenity/online/*$script,third-party

knp ga dibikin langsung 
||githack.com/crezenity/*$script,third-party aja keknya masih bnyk safelink yg mirip seperti ini

**Comment by realodix** [comment]
Thank you, sudah Saya tambahkan.

> ||githack.com/crezenity/digimoclubwp/_$script,third-party
> ||githack.com/crezenity/imoclub/_$script,third-party
> ||githack.com/crezenity/online/*$script,third-party
> 
> knp ga dibikin langsung
> ||githack.com/crezenity/*$script,third-party aja keknya masih bnyk safelink yg mirip seperti ini

Menurut Saya saat ini jangan dulu, takutnya dia nambahin file javascript untuk keperluan lain. Kecuali kedepannya sudah keterlaluan banget, baru kita block semua dengan `||githack.com/crezenity/*$script,third-party`.
