### ISSUE TITLE
doujindesu.tv

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1771]
### Sample URL

https://doujindesu.tv/manga/my-mom-and-sister/

### Ad Blocker

AdGuard

### Keterangan

di website ini ada iklan pop up yang jika mengklik di area mana saja, maka akan ada iklan yang muncul di tab baru.
kira kira seperti ini gambaran link yang berisi iklan itu
https://fmoqabrwef.com/afu.php?zoneid=2015164&var=2013574&abvar=0

**Comment by Jokopentil** [comment]
Maaf ikut komen 
Biasanya link seperti ini ada di pencarian google 
Ini biasanya link jebakan 
Isi artikelnya sesuai yg kita cari tapi ternyata di alihkan 
Biasanya berisi website judi dan game
Cari yg lain saja
Saya coba memang tak bisa di buka
![Screenshot_2024-05-18-21-05-42-87_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/a874bdef-95ed-4f34-bf68-9fecc015ce8a)

![Screenshot_2024-05-18-21-05-02-52_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/c68515b4-5ffa-4fe0-8180-cb7eb740e4ad)

**Comment by Jokopentil** [comment]
Saya gak ada ya pake ublock

**Comment by abidjauhar17** [comment]
> Saya gak ada ya pake ublock

kayaknya emang cuma ada di adguard masalahnya

**Comment by Jokopentil** [comment]
Tadi punya saya GK bisa di buka
Ternyata internet positif
Mungkin filter adguard ads tidak di aktifkan silahkan cek dulu pengaturan
filter lalu update/periksa pembaruan filter terutama filter untuk pop up
seperti fanboy annoyances dan lainnya

Pada Sab, 18 Mei 2024 21.25, abidjauhar17 ***@***.***>
menulis:

**Comment by realodix** [comment]
- uBo tidak ada masalah
- AG menunggu https://github.com/AdguardTeam/AdguardFilters/pull/179486
