### ISSUE TITLE
nontonhentai.top

### ISSUE THREAD

**Issue by Bug-Cache** [realodix/AdBlockID#1775]
### Sample URL

https://nontonhentai.top/anime/tsuma-ni-damatte-sokubaikai-ni-ikun-ja-nakatta/#

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/98657967/54324027-c712-4ee5-bd3c-3c831f67af70)

**Comment by realodix** [comment]
Saya tidak melihatnya, filter untuk nontonhentai.top sudah ada.

Mohon perbarui AdBlockID ke v24.5.18 atau yang lebih baru. Jika tidak bisa, subs ulang saja.

**Comment by Bug-Cache** [comment]
Subs ulang, problem fixed

thanks
