### ISSUE TITLE
haibunda.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1776]
### Sample URL

https://www.haibunda.com/

### Ad Blocker

AdGuard

### Keterangan

push notifikasi

![image](https://github.com/realodix/AdBlockID/assets/37255346/92b8965c-5efe-47a5-ac0e-6975cf1dfffa)

**Comment by abidjauhar17** [comment]
sama elemen kosong ini juga yang ga tau apa isinya
![image](https://github.com/realodix/AdBlockID/assets/37255346/9a08f599-e73c-4cfc-975a-1192b3df84ea)

**Comment by Jokopentil** [comment]
Tolong scroll sampai bawah ada banyak banner blank putih

**Comment by Jokopentil** [comment]
Terjadi sama adguard saja itu sepertinya

**Comment by realodix** [comment]
> push notifikasi
> https://github.com/realodix/AdBlockID/issues/1776#issue-2316741687

Push notification langsung ke AG Annoyance saja

> sama elemen kosong ini juga yang ga tau apa isinya
> https://github.com/realodix/AdBlockID/issues/1776#issuecomment-2130857846

Tempat iklan, tapi karena secara teknis karena sulit dihilangkan, jadi Saya biarkan.

> Tolong scroll sampai bawah ada banyak banner blank putih
> https://github.com/realodix/AdBlockID/issues/1776#issuecomment-2131134980

Ini di halaman yang mana ya?
