### ISSUE TITLE
trenasia.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1779]
### Sample URL

https://www.trenasia.com/menilik-konsep-ptn-bh-yang-disebut-biang-kerok-ukt-mahal

### Ad Blocker

AdGuard

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/37255346/6e7e9c7c-de36-468a-92de-22b1118a6cbd)

**Comment by abidjauhar17** [comment]
@realodix ini yang kosong di bagian atas element apa ya?
apa aman kalo di hapus/hide?
![image](https://github.com/realodix/AdBlockID/assets/37255346/c64cbe43-67bd-4d5f-b09c-aa79a39c3572)

**Comment by realodix** [comment]
> ini yang kosong di bagian atas element apa ya?
> apa aman kalo di hapus/hide?
> https://github.com/realodix/AdBlockID/issues/1779#issuecomment-2133448888

Cukup aman jika dilakukan dengan hati2, karena banyak css utility class. Beberapa area kosong sudah Saya coba hilangkan di update terbaru.
