### ISSUE TITLE
id.ytmp3.mobi

### ISSUE THREAD

**Issue by Bug-Cache** [realodix/AdBlockID#1781]
### Sample URL

https://id.ytmp3.mobi/fn2t/

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/98657967/5f1b84e3-962d-4702-ac75-be4e883e645c)

**Comment by realodix** [comment]
Saya tidak menemukannya

![image](https://github.com/realodix/AdBlockID/assets/1314456/84987d59-9f41-41fb-ac7e-201f7375ea9a)

**Comment by Bug-Cache** [comment]
masukkan link youtube  yang akan di download, klik konverter, iklan akan muncul

![image](https://github.com/realodix/AdBlockID/assets/98657967/8b1772a4-9b3f-4d5e-aa48-eb78fa1279e0)

**Comment by Bug-Cache** [comment]
contoh link https://www.youtube.com/watch?v=LlN8MPS7KQs
