### ISSUE TITLE
id.savefrom.net

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1782]
### Sample URL

https://id.savefrom.net/102-how-to-download-youtube-video-mp3-103.html

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/19517680/befa8bc0-d4bf-4dc5-9f3e-352c1877a14f)

**Comment by realodix** [comment]
Saya tidak menemukannya

![image](https://github.com/realodix/AdBlockID/assets/1314456/360ad818-3fa1-40e7-8294-0a1f665ebc4c)

**Comment by 3xploiton3** [comment]
convert  dulu itu halaman home, 
![image](https://github.com/realodix/AdBlockID/assets/19517680/df59cbe2-31b3-4e10-bce1-8a631f4ff0ba)

**Comment by realodix** [comment]
> convert dulu itu halaman home

Ok. Saya menemukannya
