### ISSUE TITLE
detik.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1787]
### Sample URL

https://www.detik.com/

### Ad Blocker

AdGuard

### Keterangan

pop up live chat itu sangat menggangu
![Screenshot_2024-06-05-09-55-04-26](https://github.com/realodix/AdBlockID/assets/37255346/d0567bf4-bc9b-4da8-b0b9-e6fa98ca1a86)

**Comment by realodix** [comment]
Sorry Bro, sebaiknya ini langsung ke Filter khusus Annoyance saja.

Sementara bisa pakai ini dulu

```adblock
detik.com##.breaking-detikpagi
```

Kita Annoyance hanya tipis-tipis saja
- Anti klik kanan
- Anti copy paste
- Automatic link attribution
- Auto safelink (seperti di #1785)
