### ISSUE TITLE
viva.co.id

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1788]
### Sample URL

https://www.viva.co.id/showbiz/gosip/1720025-ketemu-lagi-setelah-terkenal-dede-sunandar-spill-istri-artis-yang-pernah-merendahkannya

### Ad Blocker

AdGuard

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/37255346/a0a16131-abe2-4102-98d7-47da0c491601)

**Comment by realodix** [comment]
Ini sudah ada di AdBlockID Plus

**Comment by abidjauhar17** [comment]
> Ini sudah ada di AdBlockID Plus

itu ga digabung di adguard ya filternya?
mesti ditambahin manual

**Comment by realodix** [comment]
> itu ga digabung di adguard ya filternya?
> mesti ditambahin manual

Iya, saat ini tidak ada di AdGuard
