### ISSUE TITLE
adikfilm.click

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1790]
### Sample URL

https://adikfilm.click/the-drug-king-2018/

### Ad Blocker

AdGuard

### Keterangan

link downloadnya pake shortlink clicksfly
![image](https://github.com/realodix/AdBlockID/assets/37255346/364e807b-375e-40e5-9d62-17a2a13f7f4b)

**Comment by realodix** [comment]
Waw, cukup jeli ya Anda melihatnya 👍

**Comment by abidjauhar17** [comment]
> Wow, cukup jeli ya Anda melihatnya 👍

wkwkwk
kalo shortlink yang bikin sendiri page landing nya itu apa bisa juga di bypass?
contohnya disini https://193.233.203.165/drug-hunter-2022/
![image](https://github.com/realodix/AdBlockID/assets/37255346/67a1fc8d-43ad-4e0c-9ec5-f069c6053c90)

**Comment by realodix** [comment]
> kalo shortlink yang bikin sendiri page landing nya itu apa bisa juga di bypass?
> contohnya disini https://193.233.203.165/drug-hunter-2022/

Sebenernya sih gak ngaruh ya dengan page landingnya. Pada dasarnya link yang bisa ditangani adalah link yang dimanipulasi dengan javascript, nah tugas AdBlockID adalah menghalangi kode javascript tersebut, maka link akan kembali normal.

Dalam contoh link yang Anda berikan, tidak ada yang dapat Saya lakukan.

**Comment by abidjauhar17** [comment]
> > kalo shortlink yang bikin sendiri page landing nya itu apa bisa juga di bypass?
> > contohnya disini https://193.233.203.165/drug-hunter-2022/
> 
> Sebenernya sih gak ngaruh ya dengan page landingnya. Pada dasarnya link yang bisa ditangani adalah link yang dimanipulasi dengan javascript, nah tugas AdBlockID adalah menghalangi kode javascript tersebut, maka link akan kembali normal.
> 
> Dalam contoh link yang Anda berikan, tidak ada yang dapat Saya lakukan.

hmmm.. berarti cuma yang pake API dari shortlink aja yang bisa di bypass

**Comment by realodix** [comment]
> hmmm.. berarti cuma yang pake API dari shortlink aja yang bisa di bypass

Gak juga sih, ada juga yang tidak bisa.
