### ISSUE TITLE
mamikos.com

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1794]
### Sample URL

https://mamikos.com/info/nonton-film-vina-sebelum-7-hari-full-movie-gnr/

### Ad Blocker

---

### Keterangan

![Uploading Screenshot_2024-06-14-16-38-14-07_4d38fce200f96aeac5e860e739312e76.jpg…]()

**Comment by Jokopentil** [comment]
![Screenshot_2024-06-14-16-38-14-07_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/3db65e76-0286-4296-be2d-dee3d1598eb3)

**Comment by realodix** [comment]
Ini pakai AdBlocker apa?

Saya coba test di AG dan uBO, dengan settingan default + AdBlockID, Saya tidak menemukannya

<details>
  <summary>Screenshot</summary>
  
  ![unnamed](https://github.com/realodix/AdBlockID/assets/1314456/2f23c587-a0e4-4486-95de-2c8b8bf81593)
</details>

**Comment by Jokopentil** [comment]
Ublock

**Comment by Jokopentil** [comment]
![Screenshot_2024-06-15-08-43-25-58_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/realodix/AdBlockID/assets/114223791/f58e8c49-9770-45a0-b8e2-b926ed94b1d8)

![Screenshot_2024-06-15-08-41-46-14_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/realodix/AdBlockID/assets/114223791/66c3b5ce-601c-4215-a0f0-4eb3840c4d9b)

Aku pake Firefox dan kiwi hasilnya sama  iklan ada

**Comment by Jokopentil** [comment]
Mungkin kakak buka di PC hasilnya beda dengan hp

**Comment by Jokopentil** [comment]
Mungkin kakak buka di PC hasilnya beda dengan hp
![Screenshot_2024-06-15-08-48-55-10_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/realodix/AdBlockID/assets/114223791/5d73c91e-5391-4825-a060-74fcb7dbf7df)

Pake adguard juga sama

**Comment by Jokopentil** [comment]
![Screenshot_2024-06-15-09-12-18-40_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/realodix/AdBlockID/assets/114223791/adc70cbc-d5ce-4aed-a24e-d0a60d3adddf)

Firefox

**Comment by realodix** [comment]
Saya bisa melihatnya di uBO. Saya tidak tahu karena alasannya apa, Saya bisa melihatnya hanya jika `uBlock filters – Privacy` diaktifkan.

**Comment by Jokopentil** [comment]
Bisakah di tambahkan filter hapus elemen saja di adblockid?

**Comment by realodix** [comment]
> Bisakah di tambahkan filter hapus elemen saja di adblockid?

Filter hapus elemen? Dalam konteks ini, elemen yang mana?

**Comment by Jokopentil** [comment]
![Screenshot_2024-06-17-16-56-27-60_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/realodix/AdBlockID/assets/114223791/8d534bd2-1aef-41c1-b748-f66b118cce1f)

Memakai fitur ini 
Nanti kan muncul di filter saya dalam pengaturan

**Comment by realodix** [comment]
> Memakai fitur ini
> Nanti kan muncul di filter saya dalam pengaturan
> https://github.com/realodix/AdBlockID/issues/1794#issuecomment-2172935472

> The element zapper can temporarily remove elements on a web page without creating new filters.
> https://github.com/gorhill/ublock/wiki/Element-zapper

Yang gambar petir ya? Di dokumentasinya disebutkan zapper hanya menghapus sementara tanpa membuat filter baru, maka tidak mungkin menambahkannya ke dalam AdBlockID.

> Bisakah di tambahkan filter hapus elemen saja di adblockid?
> https://github.com/realodix/AdBlockID/issues/1794#issuecomment-2171430978

Jika dibutuhkan ada filter yang dapat benar-benar menghapusnya. Namun Saya masih bingung dengan pertanyaan Anda, mengapa element tersebut (kecuali video/audio) harus benar-benar dihapus? Ada ide apa yang mendasarinya?
