### ISSUE TITLE
LayarDrama (103.70.114.35) 

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1796]
### Sample URL

https://103.70.114.35/ganapath-2023/

### Ad Blocker

AdGuard

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/37255346/cbfd086c-8cfd-4ffb-bb1f-42306b3f1da7)

**Comment by realodix** [comment]
Saya tidak menemukannya.

https://103.70.114.35/ sudah ada di AdBlockID sejak seminggu yang lalu (https://github.com/realodix/AdBlockID/commit/f8bae2d86ca2e9ba4b7002e6da7b70ae4710c9f1) dan belum berganti domain. FIlter yang ada saat ini masih dapat diandalkan.

Berikut settingan Saya
<details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/realodix/AdBlockID/assets/1314456/a63359bc-f243-488d-b107-e347a718dd39)
</details>
