### ISSUE TITLE
komikcast.mom

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1804]
### Sample URL

https://komikcast.mom/

### Ad Blocker

uBlock Origin

### Keterangan

- Domain baru dari `komikcast.moe`
- #1797

**Comment by GrennKren** [comment]
Apa memungkinkan jika dijadikan wildcard aja untuk domain nya karena sering gonta ganti domain?
Pengecualian jika nama domain yang benar2 berbeda.

**Comment by realodix** [comment]
> Apa memungkinkan jika dijadikan wildcard aja untuk domain nya karena sering gonta ganti domain? Pengecualian jika nama domain yang benar2 berbeda.

Secara teknis memungkinkan untuk menggunakanan filter ini `komikcast.*`.

https://github.com/realodix/AdBlockID/blob/c5154e0759085f148c9192a163c15adc1535ac65/src/modules/comic.adfl#L26

Namun saat ini komikcast ada 2, komikcast.cafe dan komikcast.mom. Mereka hanya beririsan pada 1 filter saja, sisanya berbeda. Jika disatukan, saya belum tahu apakah filternya saling cocok atau tidak. Dahulu Saya pernah menemukan di situs layarkaca21, ternyata filter yang cocok di situs A malah membuat tampilan hancur di situs B.
