### ISSUE TITLE
rajakomen.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1805]
### Sample URL

https://rajakomen.com/blog/komentar-instagram-bergambar-apa-bisa-ef64686b68.php

### Ad Blocker

uBlock Origin

### Keterangan

cookies
![image](https://github.com/realodix/AdBlockID/assets/19517680/e1c36cd7-9a58-4264-8baf-cc4795fc9c78)

**Comment by Jokopentil** [comment]
Maaf cuma tanya pada admin 
Apakah juga menangani masalah notifikasi cookie seperti kasus ini 
Biasanya seperti ini di tangani pihak 
Easylist
Adguard 
Ublock 
???

**Comment by Jokopentil** [comment]
![Screenshot_2024-07-06-17-15-00-48_4aed3257f278fcf7bfa3abd644e23333.jpg](https://github.com/realodix/AdBlockID/assets/114223791/7473d1a2-5f93-4f25-9299-71b3ba1db950)

**Comment by Jokopentil** [comment]
Muncul setelah beberapa detik

**Comment by realodix** [comment]
@3xploiton3 Maaf kita tidak menangani cookie, AdBlockID tidak memiliki filter khusus annoyance.

Anda bisa gunakan ini

```adblock
rajakomen.com###idpop_cookie

! Atau gunakan ini untuk semua situs web
###idpop_cookie
```

> Apakah juga menangani masalah notifikasi cookie seperti kasus ini
> Biasanya seperti ini di tangani pihak Easylist Adguard Ublock
> https://github.com/realodix/AdBlockID/issues/1805#issuecomment-2211727040 by @Jokopentil 

Kita tidak menangani cookie, karena AdBlockID tidak memiliki filter khusus annoyance dan cookie sendiri biasanya sekali ditekan browser akan mengingatnya.

Penanganan annoyance di AdBlockID hanya yang benar-benar mengganggu saja dan berhubungan dengan iklan seperti:
- Popup iklan (biasanya di situs nonton dan komik, popup mengandung iklan)
- Auto safelink (biasanya link download, halaman safelink mengandung iklan)
- Fake button (biasanya tombol download palsu yang mengarah ke iklan)

Termasuk kategori mengganggu, namun tidak berhubungan dengan iklan:
- Pembatasan klik kanan dan copy text (biasanya di situs berita)
- Auto attribution link saat copy-paste text (biasanya di situs berita)
