### ISSUE TITLE
komikcast.cz

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#1806]
### Sample URL

https://komikcast.cz/

### Ad Blocker

AdGuard

### Keterangan

- Domain baru dari `komikcast.mom`
- #1804

**Comment by GrennKren** [comment]
Rekor tercepat ganti domain kwkwkw

**Comment by realodix** [comment]
iya ini, Saya lihat sudah ada di https://trustpositif.kominfo.go.id/

Saya akan segera mengevaluasi https://komikcast.cz/ dan https://komikcast.cafe/, jika dirasa aman, filter `komikcast.*` akan segera diterapkan.

**Comment by realodix** [comment]
Filter `komikcast.*` sudah diterapkan https://github.com/realodix/AdBlockID/commit/3dd2fac2e1c38b28535914634a6adb7748a04b14

**Comment by GrennKren** [comment]
> Filter `komikcast.*` sudah diterapkan [3dd2fac](https://github.com/realodix/AdBlockID/commit/3dd2fac2e1c38b28535914634a6adb7748a04b14)

Mantab! Tak perlu was2 akan iklan bila domain nya ganti lagi..

**Comment by GrennKren** [comment]
@realodix ada popup mengarah ke treasuresource.com ketika mengklik di web

**Comment by realodix** [comment]
Di Saya filter untuk menangani popup masih berfungsi dengan baik, jadi Saya tidak dapat menemukan popup tersebut

<details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/600e1989-afb8-4d9c-9ca6-bd4615c94cb1)
</details>

**Comment by GrennKren** [comment]
Baiklah.. berarti permasalahannya ada pada Adguard di versi Windows.
