### ISSUE TITLE
samehadaku.email

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1809]
### Sample URL

https://samehadaku.email/one-piece-episode-1107/

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/realodix/AdBlockID/assets/19517680/230ff27d-0cae-4202-915a-ad9d9fe88431)

**Comment by abidjauhar17** [comment]
@realodix mulai ada iklan lagi
https://samehadaku.email/dragon-ball-daima-episode-10/

**Comment by realodix** [comment]
> mulai ada iklan lagi https://samehadaku.email/dragon-ball-daima-episode-10/

Saya tidak menemukannya

<details>
  <summary>Screenshot</summary>
  
  
![image](https://github.com/user-attachments/assets/945ac98f-4e3c-42c4-a0b4-257370ac9254)

</details>

**Comment by abidjauhar17** [comment]
> > mulai ada iklan lagi https://samehadaku.email/dragon-ball-daima-episode-10/
> 
> Saya tidak menemukannya
> 
> Screenshot
> ![image](https://private-user-images.githubusercontent.com/1314456/395750682-945ac98f-4e3c-42c4-a0b4-257370ac9254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNzAzMDEsIm5iZiI6MTczNDE3MDAwMSwicGF0aCI6Ii8xMzE0NDU2LzM5NTc1MDY4Mi05NDVhYzk4Zi00ZTNjLTQyYzQtYTBiNC0yNTczNzBhYzkyNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTRUMDk1MzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWExYTY1MjQ1M2U3ZTJmYWQ2ZTljODFmZGMyMGExOTI5NWU4ODEyOWE5YzU5ODg1MDk4MWMxOWE5YzIxNTlmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.edlnJTEKKRSV3_PIIIss6Ts92umTSnevg-yPHaqbpDI)

pakai adguard versi terbaru (MV3)

**Comment by realodix** [comment]
AdGuard v5 ya, yang tidak ada tombol updatenya?

Untuk AG distribusi filter sepenuhnya ada di AG.

Di AG versi 4, AdBlockID ada di versi 2.0.22.71, semetara di AG v5 masih AdBlockID v2.0.22.69. Solusinya ditunggu aja.

![image](https://github.com/user-attachments/assets/67802ffd-f836-4197-8e60-aad197fff21d)
![image](https://github.com/user-attachments/assets/ff10b6cd-bf8f-47e1-b25c-878bbb17f9f5)

**Comment by abidjauhar17** [comment]
@realodix ganti domain https://samehadaku.click/

**Comment by realodix** [comment]
Thank you
