### ISSUE TITLE
halodoc.com

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1811]
### Sample URL

https://www.halodoc.com/artikel/mengenal-petting-aktivitas-seksual-tanpa-penetrasi

### Ad Blocker

AdGuard

### Keterangan

![Screenshot_2024-07-10-07-40-47-69_3aea4af51f236e4932235fdada7d1643](https://github.com/realodix/AdBlockID/assets/114223791/b3ce8873-f734-4b32-8c4e-15e10890e2d6)
![Screenshot_2024-07-10-07-43-45-63_3aea4af51f236e4932235fdada7d1643](https://github.com/realodix/AdBlockID/assets/114223791/78518c59-421a-4f9e-b0a2-acccb55a0836)

**Comment by Jokopentil** [comment]
![Screenshot_2024-07-10-07-43-45-63_3aea4af51f236e4932235fdada7d1643](https://github.com/realodix/AdBlockID/assets/114223791/7a5f0241-2b66-4597-9eee-e7e064d8e3bf)

**Comment by Jokopentil** [comment]
![Screenshot_2024-07-10-07-44-06-42_3aea4af51f236e4932235fdada7d1643](https://github.com/realodix/AdBlockID/assets/114223791/eb02e8f6-23d2-49ec-9154-907c060d0849)

**Comment by realodix** [comment]
Untuk sisanya, bisa gunakan ini

```adblock
halodoc.com##.article-page__chat-doctor-card.sticky
halodoc.com##.article__content > figure:has(a > img)
```
