### ISSUE TITLE
kuyhaa.me

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1817]
### Sample URL

https://www.kuyhaa.me/ccleaner-pro-full.html

### Ad Blocker

AdGuard

### Keterangan

anti adblock dan fake download button
![image](https://github.com/user-attachments/assets/b33960cd-8188-465e-928e-efbe48ea51da)

**Comment by abidjauhar17** [comment]
@realodix ini mereka ganti domain apa gimana ya?
saya coba masuk ke https://www.kuyhaa-me.com tapi langsung di redirect ke https://www.kuyhaa.me/

**Comment by realodix** [comment]
> ini mereka ganti domain apa gimana ya? 
>saya coba masuk ke https://www.kuyhaa-me.com tapi langsung di redirect ke https://www.kuyhaa.me/

kuyhaa.me
Registered On: 2017-08-23
https://www.whois.com/whois/kuyhaa.me

kuyhaa-me.com
Registered On: 2019-07-05
https://www.whois.com/whois/kuyhaa-me.com

Saya menyimpulkan awalnya mereka menggunakan `kuyhaa.me`, lalu sempat berganti ke `kuyhaa-me.com`, lalu balik lagi ke `kuyhaa.me`.
