### ISSUE TITLE
kshowsubindo.org - popups

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#182]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
http://kshowsubindo.org/

**Penjelasan Lebih Lanjut**
Popups setelah klik close button empty wadah iklan

**Comment by realodix** [comment]
@okiehsch @zloyden
Popup after clicking the close button empty ad container.

```js
document.onclick = function() {
    var openpopunder = document.getElementById("openpopunder");
    
    if( openpopunder.value == "YES" ){
        document.getElementById("openpopunder").value = "NO";
        iframepopupwidow("https://qqvictoryxx.com/");
    }
};
```

**Comment by zloyden** [comment]
Added to our filters.

**Comment by WaferNabati** [comment]
@realodix https://kordramass.com/ 
nih jg kasusnya sama
