### ISSUE TITLE
rumahperjaka.online

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1824]
### Sample URL

https://rumahperjaka.online/incest/jav-sub-indo-gadis-kampung-pengen-tinggal-di-kota-besar/

### Ad Blocker

AdGuard

### Keterangan

banyak pop up iklan dan element sisa dari banner yang terblokir.
sepertinya ini domain lainnya dari https://rumahperjaka.site

**Comment by realodix** [comment]
> sepertinya ini domain lainnya dari https://rumahperjaka.site/

Iya ini mirip banget

**Comment by abidjauhar17** [comment]
@realodix domain baru `rumahperjaka.icu`

**Comment by realodix** [comment]
> domain baru `rumahperjaka.icu`
> https://github.com/realodix/AdBlockID/issues/1824#issuecomment-2664587708

Terima kasih untuk laporannya. Saat ini AdBlockID menggunakan filter `rumahperjaka.*` dan saat ini masih berfungsi dengan baik.
