### ISSUE TITLE
indojavstream.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1825]
### Sample URL

https://indojavstream.com/watch/royd00186.html

### Ad Blocker

AdGuard

### Keterangan

ini pake API shortlink ouo
bisa di bypass gak?
![image](https://github.com/user-attachments/assets/43c8a0b5-5209-4d7a-b20b-37bd8baf21f7)

**Comment by realodix** [comment]
> ini pake API shortlink ouo
> bisa di bypass gak?

Tidak bisa
