### ISSUE TITLE
inet.detik.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1828]
### Sample URL

https://inet.detik.com/indeks

### Ad Blocker

AdGuard

### Keterangan

element iklan
![image](https://github.com/user-attachments/assets/ec6c1fdb-0067-49f1-8137-be4399bf718d)

**Comment by abidjauhar17** [comment]
@realodix https://sport.detik.com/sepakbola/bola-dunia/d-7475267/neves-gabung-psg-kans-ugarte-ke-mu-terbuka-lebar
![image](https://github.com/user-attachments/assets/f5d64407-6aef-4ce4-92a0-fd369236e0e9)

**Comment by realodix** [comment]
Saya rasa yang Anda maksud adalah video, tidak ada filter AdBlockID yang memblokir video tersebut.

<details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/fe3d60f1-7729-4c79-823d-2eeaa72e8864)
</details>

**Comment by abidjauhar17** [comment]
> Saya rasa yang Anda maksud adalah video, tidak ada filter AdBlockID yang memblokir video tersebut.
> 
> Screenshot
> ![image](https://private-user-images.githubusercontent.com/1314456/355279203-fe3d60f1-7729-4c79-823d-2eeaa72e8864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTA3ODksIm5iZiI6MTcyMjkxMDQ4OSwicGF0aCI6Ii8xMzE0NDU2LzM1NTI3OTIwMy1mZTNkNjBmMS03NzI5LTRjNzktODIzZC0yZWVhYTcyZTg4NjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMDIxNDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmVhNjY4MzEwZWZjNDg4M2Y3NTYyOWFhOTExZjA0MzEzZDEwMTRjYTljNzdkMWIwN2UyYTQ2ZTgyN2ZlNmIxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ao_eD0hCgc4EXlHKZlhjBMAyV6RnCGRrZWWo2XHhXqA)

element nya dihapus saja.
mengganggu kalo lagi baca artikel
