### ISSUE TITLE
cooklike.info

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1829]
### Sample URL

https://go.paid4link.com/6wa7i
https://cooklike.info/5-alasan-mengapa-resep-ikan-goreng-kering-ini-akan-menjadi-favorit-keluarga-anda/

### Ad Blocker

uBlock Origin

### Keterangan

Anti adblock

**Comment by Recehan-Slayer** [comment]
sama recaptcha nya kyk ga muncul klo UBO aktif

**Comment by realodix** [comment]
> sama recaptcha nya kyk ga muncul klo UBO aktif

![image](https://github.com/user-attachments/assets/2831106e-7581-4685-bf0a-e9466a5a2631)

Saya menemukannya di https://link.paid4link.com/6wa7i

Untuk sementara bisa menggunakan ini dulu

```adblock
link.paid4link.com#@#+js(set-constant, counter, 10)
```
