### ISSUE TITLE
gosemut.net

### ISSUE THREAD

**Issue by PenghancurRecehan** [realodix/AdBlockID#183]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
http://gosemut.net/

**Penjelasan Lebih Lanjut**
Popups setelah klik disalah satu postan

**Comment by realodix** [comment]
Post yang mana Gan? Saya gak ketemu popup

**Comment by WaferNabati** [comment]
4 hari yg lalu dipost sembarang ada popupnya tp ntah skrng keknya g muncul lg

**Comment by Recehan-Slayer** [comment]
popups mengarah ke `https://slot.onlineindonesia.tech/`
`http://gosemut.net/the-climbers/`

**Comment by realodix** [comment]
> popups mengarah ke https://slot.onlineindonesia.tech/

Saya gak nemuin ada popup ke arah sana
