### ISSUE TITLE
streamsilk.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1833]
### Sample URL

https://streamsilk.com/d/66ba4b50063ea

### Ad Blocker

AdGuard

### Keterangan

jadi pada saat mengklik tombol download, akan ada pop up iklan di tab baru
nah, saya sudah melaporkannya pada pihak AG, tetapi katanya situs ini belum memenuhi kriteria (views visitors) untuk ditambahkan dalam filter
![image](https://github.com/user-attachments/assets/66e98b34-a221-4373-a196-b93e5372195a)

tapi saya yakin situs ini akan ramai tidak membutuhkan waktu yang lama

**Comment by realodix** [comment]
Kemungkinan ini datang dari https://dl.lk21static.buzz/get/twisters-2024 ya

Hmm gimana ya? Sepertinya saya tidak berminat mengerjakannya.

Sejauh ini jumlah trafik tidak menjadi pertimbangan utama di AdBlockID. Satu-satunya pertimbangan utama adalah situsnya situs lokal saja. Walaupun masih bisa saya longgarin atau Saya langgar dengan AdBlockID Plus.

Namun yang terjadi di sini adalah
- Ngerjainnya ternyata cukup sulit, ditambah di issue AG juga Saya tidak melihat adanya rekomendasi filter yang bisa digunakan.
- Daftar situs lokal juga masih banyak yang perlu dikerjakan 😄
