### ISSUE TITLE
kuramanime.biz

### ISSUE THREAD

**Issue by ridwanpratama** [realodix/AdBlockID#1837]
### Sample URL

https://kuramanime.biz/

### Ad Blocker

uBlock Origin

### Keterangan

Iklan banner muncul.

![Screenshot 2024-09-05 023858](https://github.com/user-attachments/assets/a1d874fb-231f-48ee-a58d-c531881d016b)

**Comment by realodix** [comment]
Sepertinya ini sebelumnya kuramanime.boo yang berganti jadi kuramanime.biz

Update sudah dilakukan https://github.com/realodix/AdBlockID/commit/13dd1c3947a54dfd6ab32809e4a3d142bbd00fbc

Terima kasih sudah membantu

**Comment by ridwanpratama** [comment]
@realodix iklan kembali tayang, domainnya ganti jadi https://kuramanime.dad/

**Comment by realodix** [comment]
> iklan kembali tayang, domainnya ganti jadi https://kuramanime.dad/

Thank you

**Comment by ridwanpratama** [comment]
Terimakasih
