### ISSUE TITLE
kazefuri.asia

### ISSUE THREAD

**Issue by T-Baniza** [realodix/AdBlockID#1839]
### Sample URL

`https://kazefuri.asia/`

### Ad Blocker

uBlock Origin

### Keterangan

- domain baru kazefuri
- popup ads
- banner
- #971 

<details><summary>Screenshot</summary>
<p>

![Screenshot_20240915_155337_Fennec](https://github.com/user-attachments/assets/f04f0909-ddd8-4f34-a4f6-0e2a6a148034)

</p>
</details>

**Comment by realodix** [comment]
Thank you

**Comment by T-Baniza** [comment]
Masih ada iklan gan. Saat saya mengklik sembarang tempat, muncul popup yang secara otomatis mengarahkan saya ke tab baru. Tolong dicek apakah hanya device (hape) saya yang mengalami hal ini

**Comment by realodix** [comment]
Untuk iklan dimana ya?

Saya coba di 2 halaman ini, chrome desktop
- https://kazefuri.asia/
- https://kazefuri.asia/banished-disciples-counterattack-episode-79-subtitle-indonesia/

---

Untuk popup, ini Saya baru saja menemukannya, akan saya update kembali
