### ISSUE TITLE
premierexxi.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#184]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://premierexxi.com/movie/ip-man-4-the-finale-2019/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by realodix** [comment]
Thank untuk laporannya.

Saat ini invalid, gak ada iklannya.

![screencapture-premierexxi-movie-lucy-in-the-sky-2019-2020-01-04-06_18_47](https://user-images.githubusercontent.com/1314456/71754758-366b0700-2eba-11ea-9b77-a2703fcf5d4b.png)

**Comment by 3xploiton3** [comment]
Itu ada banner header, slot available

**Comment by realodix** [comment]
> Itu ada banner header, slot available

Gak apa-apa, itu memang sengaja Saya biarkan. Karena mereka mengiklankan produk mereka di situs mereka sendiri.
