### ISSUE TITLE
bokepsin.diy

### ISSUE THREAD

**Issue by Jokopentil** [realodix/AdBlockID#1844]
### Sample URL

https://bokepsin.diy/bokep-terbaru-tante-semok-montok-live-ngentot-wot/

### Ad Blocker

AdGuard

### Keterangan

![Screenshot_2024-09-25-18-03-45-96_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/e201d746-5405-4953-8e62-cae1bc97979e)

**Comment by realodix** [comment]
Saya rasa filter `bokepsin.*##a[target*="blank"]:has(> img)` masih berfungsi dengan baik.

<details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/user-attachments/assets/dce4ed22-8668-4ad2-bb86-ce35bbcb0c84)
</details>
