### ISSUE TITLE
gamingweb.xyz

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1846]
### Sample URL

https://gamingweb.xyz/hot-fuzz-2007-VSl/server1

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/user-attachments/assets/00582204-dc5c-4a5a-bbb9-2556e2a5aa30)

pop up

**Comment by realodix** [comment]
Halo Bro,

Saya dari kemarin bingung apakah ini merupakan masuk ke dalam ruang lingkup AdBlockID atua tidak, karena popup yang Saya temukan ada di video player, dimana video playernya merupakan situs international. Saya coba teruskan ke AG dan ternyata disetujui.

Anda bisa menggunakan filter AG

![image](https://github.com/user-attachments/assets/5fe666ed-320e-4bc8-a070-8e64f83ee63f)

atau

```adblock
||alene.info/cdn/mv/js/newitem.js
||alene.info/cdn/mv/js/protect.js
```

Terima kasih sudah melapor
