### ISSUE TITLE
IndoSitusXXI (194.233.68.230)

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1847]
### Sample URL

https://194.233.68.230/movie/furiosa-a-mad-max-saga-2024-gi4tkoju/play/

### Ad Blocker

uBlock Origin

### Keterangan

reference : https://server1.indositusxxi.id/

random pop up ketika play video

**Comment by realodix** [comment]
Halo Bro, kebetulan saat ini Saya tidak menemukan popup ketika play video. Saya rasa issue ini bisa ditutup.

https://github.com/user-attachments/assets/1e2b5103-d25f-47f7-9696-bfbac4786f26
