### ISSUE TITLE
animekompi.vip

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1853]
### Sample URL

animekompi.vip

### Ad Blocker

uBlock Origin

### Keterangan

popup

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix muncul lg bro

**Comment by realodix** [comment]
Di halaman yang mana ya? Pakai uBO atau AG?

**Comment by Recehan-Slayer** [comment]
UBO halaman depan

**Comment by realodix** [comment]
Saya masih tidak menemukannya dan bingung apa yang muncul. Tolong berikan screenshot 🙏

**Comment by Recehan-Slayer** [comment]
popup ke situs judi `https://wddijamin.com` pas klik home

**Comment by realodix** [comment]
Thank you
