### ISSUE TITLE
infopublik.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1855]
### Sample URL

https://infopublik.id/kategori/sorot-sosial-budaya/426042/kepala-lapan-idealnya-indonesia-punya-sistem-navigasi-satelit-sendiri?video=

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/user-attachments/assets/c963393c-2bd6-4b80-b6d3-412982ba1eea)

banner ads

**Comment by realodix** [comment]
Halo, terima kasih untuk laporannya.

Saya lihat filter `infopublik.id##.float-info` masih berfungsi dengan baik untuk banner tersebut dan filter itu sudah ada sejak Feb 2024 (https://github.com/realodix/AdBlockID/commit/1ae3ee6dc7fdd4fce3f1e70e53ec693c80fb1205).

<details>
  <summary>Screenshot</summary>
  
  
![image](https://github.com/user-attachments/assets/cd5a54ba-2678-4713-a563-545041dd24bd)
</details>
