### ISSUE TITLE
apkmirror.com - adblockid plus blocks `apkmirror` auto-download

### ISSUE THREAD

**Issue by cyberboh** [realodix/AdBlockID#1856]
### Sample URL

https://www.apkmirror.com/apk/the-pokemon-company/pokemon-tcg-pocket/pokemon-tcg-pocket-1-0-5-release/pokemon-tcg-pocket-1-0-5-android-apk-download/

### Keterangan

Download any apps from `apkmirror.com` , wait for minutes. Usually the app will be downloaded without to click `here`, but with adblockid plus enabled, it is broken. We need to click `here` to download the app.

**Comment by realodix** [comment]
Thank you
