### ISSUE TITLE
tigoals130.com

### ISSUE THREAD

**Issue by ridwanpr** [realodix/AdBlockID#1857]
### Sample URL

https://idn121.tigoals130.com/

### Ad Blocker

uBlock Origin

### Keterangan

- Iklan banner di halaman homepage dan halaman streaming
![image](https://github.com/user-attachments/assets/1e437a17-2e60-4b82-909f-cfbac9d37201)

![Screenshot 2024-10-28 002645](https://github.com/user-attachments/assets/83b68768-9f70-4e3a-9329-b32eaf8b07b4)

**Comment by realodix** [comment]
Thank you
