### ISSUE TITLE
otosia.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#1860]
### Sample URL

https://www.otosia.com/berita/read/4744859/10-pelesetan-merek-kendaraan-ini-bikin-nyengir-dan-geli-sendiri

### Ad Blocker

uBlock Origin

### Keterangan

![Uploading Screenshot_20241031-212945_Kiwi Browser.png…]()

Ada

**Comment by realodix** [comment]
Bisa tolong upload ulang SS-nya? Saya tidak bisa membukanya

**Comment by 3xploiton3** [comment]
pakai kiwi browser

klo ini tampilan chrome desktop
![image](https://github.com/user-attachments/assets/5a12bf8f-a123-44d1-b22a-fcdf7fc17ae8)

**Comment by realodix** [comment]
Thank you
