### ISSUE TITLE
Disway.id

### ISSUE THREAD

**Issue by Reno-Sifana** [realodix/AdBlockID#1862]
### Sample URL

https://disway.id

### Ad Blocker

uBlock Origin

### Keterangan

Ada banner bertuliskan "Advertisement" di halaman beranda disway.id 
![Screenshot from 2024-11-11 21-20-48](https://github.com/user-attachments/assets/ad21c2b1-110c-4411-81c9-f394d9e9c293)

**Comment by realodix** [comment]
Thank you
