### ISSUE TITLE
animekompi.pro

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1866]
### Sample URL

https://animekompi.pro/

### Ad Blocker

uBlock Origin

### Keterangan

judi +popup

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix ada banner judi baru

**Comment by Recehan-Slayer** [comment]
@realodix ada banner judi baru

**Comment by realodix** [comment]
Thank you
