### ISSUE TITLE
downloadtanku.org

### ISSUE THREAD

**Issue by ridwanpr** [realodix/AdBlockID#1867]
### Sample URL

https://game.downloadtanku.org/

### Ad Blocker

uBlock Origin

### Keterangan

![image](https://github.com/user-attachments/assets/4d057c1b-e359-413c-b006-559cb48fe01f)

**Comment by realodix** [comment]
Thank you

**Comment by ridwanpr** [comment]
Di homepage sudah hilang, tapi waktu visit single post muncul warning https://game.downloadtanku.org/metaphor-refantazio-full-repack-dodi/

**Comment by realodix** [comment]
> Di homepage sudah hilang, tapi waktu visit single post muncul warning https://game.downloadtanku.org/metaphor-refantazio-full-repack-dodi/

https://github.com/user-attachments/assets/fccb4db7-8b56-4686-afdd-e36017319008

Dengan pengaturan standard, Saya tidak menemukannya. Mungkin Anda bisa memberikan info lebih lanjut?
