### ISSUE TITLE
offenseproject.com

### ISSUE THREAD

**Issue by abidjauhar17** [realodix/AdBlockID#1868]
### Sample URL

https://www.offenseproject.com/2023/02/downhill-domination-ps2-iso-569mb.html

### Ad Blocker

AdGuard

### Keterangan

![image](https://github.com/user-attachments/assets/4200a032-2a00-49e5-a73f-5edf1487849e)

**Comment by realodix** [comment]
Thank you

**Comment by abidjauhar17** [comment]
@realodix bagaaimana dengan pop up cookies?
![image](https://github.com/user-attachments/assets/ee3a85ff-2da0-4a7f-b0ae-c1bd614224c0)

**Comment by realodix** [comment]
> bagaaimana dengan pop up cookies?
> https://github.com/realodix/AdBlockID/issues/1868#issuecomment-2555804739

Kita tidak menangani ini, karena ditekan sekali langsung hilang. Selama cookies di browser Anda tidak dibersihkan, itu itu tidak akan muncul kembali.

Anda dapat menggunakan AG Annoyances

atau bisa juga ini

```adblock
offenseproject.com##+js(set-cookie, CookiePolicy, true)
```
