### ISSUE TITLE
jurnalistekno.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#1871]
### Sample URL

https://sfl.gl/zwUz8qLY

### Ad Blocker

uBlock Origin

### Keterangan

ANTI ADBLOCK
TIMER

**Comment by realodix** [comment]
Kadang timernya bahaya kalau diutak-atik

Tambahkan secara manual aja `jurnalistekno.id##+js(nano-sib)`

Thank you
