### ISSUE TITLE
moviexxi.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#188]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://moviexxi.net/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by realodix** [comment]
Sorry Gan, statusnya saat ini `Site under maintenance`.

**Comment by realodix** [comment]
Sudah masuk hari ke 7 sejak saya berkomentar, pas dibuka statusnya masih `Site under maintenance`. Rasanya bisa ditutup dulu.

Thank you
