### ISSUE TITLE
dwanonton.com

### ISSUE THREAD

**Issue by PenghancurRecehan** [realodix/AdBlockID#192]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://dwanonton.com/

**Penjelasan Lebih Lanjut**
Iklan Judi

**Comment by realodix** [comment]
Terlihat di Chrome (uBlock Origin 1.23.0) iklannya masih ada.
Tapi sebenarnya iklan yang mengarah ke `wismakita.com`, `unikpoker.net`, dan `wymbet338.com` sudah ada filternya.

Pada Firefox (uBlock Origin 1.24.2) dan Chrome (AdGuard 3.3.4), filter berjalan sempurna.

Sepertinya masalah ada pada uBlock Origin 1.23.0.

![cats](https://user-images.githubusercontent.com/1314456/71756115-8947bd00-2ec0-11ea-93de-25b9f698ba3d.jpg)

**Comment by PenghancurRecehan** [comment]
keknya skrng dah rilis versi stable dichrome 1.24.2 apakah tetep sama

**Comment by realodix** [comment]
Sama aja ternyata, di Chrome (uBlock Origin 1.24.2) tetap muncul iklannya. Kalau gitu Saya blockir secara manual.

Terima kasih
