### ISSUE TITLE
Sektekomik.com - Popup

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#196]
**Sample URL**
https://sektekomik.com/tomb-raider-king-chapter-73/

Membaca komik di sini kalau klik kesembarang halaman selalu ada popup yang muncul jadi agak menggangguin.  dan yang keluar itu geethoap.com, keliatannya itu link redirect buat diarahin ke iklan. Dalam kasus ku ke bhinneka.com tujuan akhirnya. Lagian di cookies juga ada geethoap yg nongol disitu.

Jadinya mencoba sendiri custom rule, dan syukur ga ada lagi.
```
||geethoap.com^$domain=sektekomik.com,third-party
||sektekomik.com^$popup
```

Baris pertama dari Filtering Log nya adguard langsung ku coba blokir dari situ karena terlihat mencurigakan geethoap ada disana.
Yang kedua baru maksud sebenarnya, ngeblokir pop-up.

Punya ku cuman ngecoba-coba aja, dan ga terlalu memahami rule2 filtering, jadinya ga tau apa itu support buat adblocker lainnya karena yang kupake cuman adguard.

**Comment by GrennKren** [comment]
Ada lagi jir..
viatepigan.com kali ini yg nongol.
Berarti punya ku gak bisa dipake..

Kalau ada cara yg cerdik tolong gan..

**Comment by realodix** [comment]
Kalau sekarang gimana? Masih gak?

Saya blokir `nouseeth.com`

**Comment by GrennKren** [comment]
Udah ga ada lagi keliatannya, makasih banyak!

**Comment by realodix** [comment]
OK sip, thank you untuk laporannya

**Comment by GrennKren** [comment]
https://sektekomik.com/

**Penjelasan Lebih Lanjut**
Ada popup yang mengarah ke `onemboaran.com` di situs tersebut, dan selainnya juga ada  menggunakan onemboaran untuk memanggil `https://onemboaran.com/apu.php?zoneid=2882049&oo=1 ,https://onemboaran.com/tag.min.js, https://onemboaran.com/fac.php`

**Rules yang disarankan**
`||onemboaran.com^$third-party,popup`

**Comment by realodix** [comment]
Thank you

`onemboaran.com` [easylist/easylist@fb36609#diff-4903e75](https://github.com/easylist/easylist/commit/fb366097f29ca06a68df7d49e1ab18a3f9f6e113#diff-4903e7590de76df1abe1703921a2c88bR3520)

**Comment by GrennKren** [comment]
Kelihatannya sektekomik meng  generate secara otomatis link2 yang dipanggil.
Selain script javascript, juga menghasilkan link source stylesheet dengan format css tentunya.

**Sample Url**
```
https://zaugroaw.net/index.css?aHR0cHM6Ly92aWF0ZXBpZ2FuLmNvbS9hcHUucGhwP3pvbmVpZD0yODgyMDUw
https://naidafak.net/style.css?aHR0cHM6Ly92aWF0ZXBpZ2FuLmNvbS9hcHUucGhwP3pvbmVpZD0yODgyMDUw
https://soalouve.com/styles.css?aHR0cHM6Ly9uYXRpdmUucHJvcGVsbGVyY2xpY2suY29tLzE/ej0zMDY3NTY2
```
di dalamnya ada content yg di encrypt, bisa pakai function atob() nya javascript bila di console browser untuk mengdecrypt

Pernah nyoba rules ini
`sektekomik.com##+js(abort-current-inline-script.js, Math, "zfgloaded")`
ga berhasil karena sektekomik tetap menghasilkan alamat baru tiap hari nya.
Sampe hari ini, link yang berasal dari sektekomik aku coba block
```
||zelrasty.net^$third-party
||neechuce.net^$third-party
||wauthaum.com^$third-party
||soalouve.com^$third-party
||aukrouwy.net^$third-party
||psoaksoo.com^$third-party
||ptauphie.com^$third-party
||joorejou.net^$third-party
||ausagauw.net^$third-party
||zaugroaw.net^$third-party
```

Jadi nya ku coba memblokir link cache javascriptnya yang isinya ya keliatan mencurigakan. 
Syukur berhasil dan di filter logger nya juga tidak nampak link css maupun javascript hasil generate otomatis nongol kembali. Dan segala fungsi web tetap bekerja secara normal di sektekomik.

**Rules yang disarankan**
/wp-content/cache/min/*^$script,domain=sektekomik.com
