### ISSUE TITLE
[SafelinkScript] /wpsafelink.js

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#202]
- https://globalinew.com/wpsafelink.js
- https://www.daizurin.com/wpsafelink.js
- https://ngasih.info/wpsafelink.js
- https://morebitcoin.club/wpsafelink.js (https://github.com/realodix/AdBlockID/issues/190)

**Comment by Recehan-Slayer** [comment]
https://latestweddingdress.info/wpsafelink.js
`https://nontondrakor.co/eps/dracula-season-1-episode-3/`
