### ISSUE TITLE
nontoncinema.org

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#206]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://nontoncinema.org/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix itu msh bnyak refferal togel dll nya gan

**Comment by realodix** [comment]
Hidden iklan hanya diambil dari https://nontoncinema.org/wp-content/uploads/2019/04/daftar.html

**Comment by realodix** [comment]
> itu msh bnyak refferal togel dll nya gan

Masalahnya dia pakai iframe yang dipanggil dari https://nontoncinema.org/wp-content/uploads/2019/04/daftar.html. Generic filter yang Saya tambahkan hanya berlaku untuk halaman itu saja.

Pada kasus ini, iklan pada iframe bisa hilang jika
- Specific blok (`||nontoncinema.org/wp-content/uploads/2019/04/daftar.html`)
- Specific hode (`nontoncinema.org##[href*="rajabalak66"] > img`)

Hanya saja Saya malas banget melakukannya karena menurut https://www.alexa.com/siteinfo/nontoncinema.org#section_traffic, nontoncinema.org makin hari makin jatuh performanya. Di Indo dia berada di urutan ke 23,523, biasanya situs nonton berada di bawah 10k.

**Comment by Recehan-Slayer** [comment]
@realodix langsung gini kan bisa gan 
`nontoncinema.org##div.sidebarborder:nth-of-type(3) > .sidebar-right > .textwidget`

**Comment by realodix** [comment]
> langsung gini kan bisa gan
> `nontoncinema.org##div.sidebarborder:nth-of-type(3) > .sidebar-right > .textwidget`

Bisa juga (belum saya test, tapi saya percaya sama agan). Baik solusi yang agan kasih maupun yang dari gue, sama-sama mencantumkan nontoncinema.org

**Comment by Recehan-Slayer** [comment]
##[href*="nomorkeluar."]

**Comment by realodix** [comment]
> ##[href*="nomorkeluar."]

Thank you
