### ISSUE TITLE
animeindo.to

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#210]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
https://animeindo.to/

**Penjelasan Lebih Lanjut**
Popups

**Comment by realodix** [comment]
Ping @okiehsch @AdamWr

**Comment by AdamWr** [comment]
It seems that it's already fixed in AdGuard Base filter, because I can't reproduce it.
https://github.com/AdguardTeam/AdguardFilters/commit/b5e04675552ee67acfd2bc286ac96321fa182544

**Comment by okiehsch** [comment]
Fixed.
