### ISSUE TITLE
Iklan inject dari provider INDOSAT

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#213]
**Jenis iklan** (hapus yang tidak perlu)
- Inject ads

**Sample URL**
http://114.6.128.4:8004/CAMPAIGN/0008405290/0008401415.jpg
http://ads.indosatooredoo.com:8004/CAMPAIGN/0008405290/0008401415.jpg

**Penjelasan Lebih Lanjut**
http://114.6.128.4
http://ads.indosatooredoo.com

**Comment by realodix** [comment]
Mantap, thank you Gan
