### ISSUE TITLE
Iklan inject dari provider TELKOM saat sedang login wifi id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#214]
**Jenis iklan** (hapus yang tidak perlu)
- iklan inject

**Sample URL**
http://pushads.wifi.id/landing/   *****
<details>

![wifiid](https://user-images.githubusercontent.com/9379770/71832277-31d26880-30dd-11ea-8dc3-cdaa400be273.png)

**Penjelasan Lebih Lanjut**
http://pushads.wifi.id

**Comment by realodix** [comment]
Ini apa yang harus diblockir ya? haha

**Comment by Recehan-Slayer** [comment]
kwkwow lol ya kan itu push ads inject iklan juga
klo untuk nyobanya ya ntahlah

**Comment by realodix** [comment]
Kalau yang Saya baca di [news.linuxsec.org/telkom-i...an-legal](https://news.linuxsec.org/telkom-indonesia-klaim-ads-injection-yang-mereka-lakukan-adalah-tindakan-legal/), sepertinya gak bisa deh Gan, karena ini otomatis ke http://pushads.wifi.id/landing pas mau login di wifi.id.

Kecuali jika telkom numpang iklan yang di inject pada website, baru bisa diblokir.

Mungkin, meurut Saya sih begitu.

**Comment by Recehan-Slayer** [comment]
ok close aja

**Comment by Recehan-Slayer** [comment]
@realodix yg blom gan dr indohomo
```
 ||u-ad.info^$third-party
 ||cfs.u-ad.info^$third-party
 ||cfs2.uadexchange.com^$third-party
 ||uzone.id^$third-party
 ||v3.mercusuar.uzone.id^$third-party
```

**Comment by realodix** [comment]
> @realodix yg blom gan dr indohomo
> 
> ```
>  ||u-ad.info^$third-party
>  ||cfs.u-ad.info^$third-party
>  ||cfs2.uadexchange.com^$third-party
>  ||uzone.id^$third-party
>  ||v3.mercusuar.uzone.id^$third-party
> ```

Thank you Gan, ada sumbernya gak? Sedikit ngeri untuk blockir.

Sebelumnya Saya sudah pernah menambahkan domain dari [sentabi/telkom/internet-positif.md](https://github.com/sentabi/telkom/blob/master/internet-positif.md) di [/src/adservers.adbl](https://github.com/realodix/AdBlockID/blob/master/src/adservers.adbl) (bagian paling bawah)

**Comment by Recehan-Slayer** [comment]
@realodix 
`https://dikertas.com/komputer-elektronik/cara-mudah-menghilangkan-iklan-indihome-di-windows`
`https://www.jusmardi.id/windows/blokir-inject-iklan-telkom-indihome.html`
`https://hilman.web.id/blog/1540/cara-blokir-script-inject-iklan-u-ad-info-telkom-speedy.html`

**Comment by realodix** [comment]
Thank you Gan, walaupun ini sama-sama internet sari Telkom, tapi karena scopenya berbeda, agar gampang tracking nya maka Saya buat issue baru.
