### ISSUE TITLE
Iklan inject dari Provider smartfren

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#215]
**Jenis iklan** (hapus yang tidak perlu)
- Inject ads

**Sample URL**
http://10.17.194.50:88
http://10.24.224.140:8080

**Penjelasan Lebih Lanjut**
`https://github.com/ABPindo/indonesianadblockrules/issues/41`
`https://www.kaskus.co.id/thread/555b3018925233a93a8b456c/proxy-smartfren-inject-script-iklan-yang-sangat-mengganggu/
`
kemungkinan domain adsnya ganti sekarng atau ada yg lainya

**Comment by realodix** [comment]
Thank you
