### ISSUE TITLE
[SafelinkScript] gigapurbalingga.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#220]
**Jenis iklan** (hapus yang tidak perlu)
- script

**Sample URL**
https://gigapurbalingga.net/idm-terbaru-6-21-build-15-final-full-patch/

**Penjelasan Lebih Lanjut**
`https://go.giga74.com/safelink.js`

**Comment by realodix** [comment]
Ternya ada 2, satu lagi http://giga74.com/safelink.js

**Comment by realodix** [comment]
Tank you

**Comment by Recehan-Slayer** [comment]
@realodix langsung pke filter umum bro `/safelink$script,third-party` bnyak tuh ntar yg keblokir
ga mungkin kan namanya safelink dipakai buat yg lain selain safelink

**Comment by realodix** [comment]
> langsung pke filter umum bro `/safelink$script,third-party` bnyak tuh ntar yg keblokir
> ga mungkin kan namanya safelink dipakai buat yg lain selain safelink
> contohnya kek ini `https://github.com/KecoaTerbank/safelink`

`/safelink$script,third-party` Menurut Saya ini terlalu berbahaya, semua file yang berawalan `safelink` bisa terkena dampak,

Saya akan pertimbangkan untuk `/safelink.` sebagai generic block (`/safelink.$script,third-party`) untuk memastikan yang terblokir hanya `safelink.js` atau `safelink.min.js`.

Saya akan buat issue baru agar gampang trackingnya.

**Comment by realodix** [comment]
- http://giga74.com/safelink.js
- https://go.giga74.com/safelink.js
