### ISSUE TITLE
[SafelinkScript] download.ipeenk.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#221]
**Jenis iklan** (hapus yang tidak perlu)
- Script safelink

**Sample URL**
https://download.ipeenk.com/internet-download-manager-terbaru-full-version.html

**Penjelasan Lebih Lanjut**
`https://rawcdn.githack.com/VoreCorporation/Customer-Host/67738f6c4d558b1784a354e7addfccf4bd90036b/js/ipeenk-safelink.min.js
`

**Comment by realodix** [comment]
Tank you, sepertinya di download.ipeenk.com ada anti-adblock. Akan Saya cek lagi nanti malam.
