### ISSUE TITLE
[SafelinkScript] animebatch.site

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#222]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://www.animebatch.site/2020/01/aico-incarnation-batch-subtitle.html

**Penjelasan Lebih Lanjut**
`https://raw.githack.com/sancan25/safe/master/safeblog.js`

**Comment by realodix** [comment]
Thank you
