### ISSUE TITLE
[SafelinkScript] shinciniku.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#223]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://www.shinciniku.com/2020/01/honzuki-no-gekokujou-shisho-ni-naru-tame-ni-wa-shudan-wo-erandeiraremasen.html

**Penjelasan Lebih Lanjut**
https://php.amelin.us/public/assets/js/link-converter.js

**Comment by realodix** [comment]
Thank you, sepertinya di amelin.us ada anti-adblock. Akan Saya cek lagi nanti malam dan buat issue baru jika ada.
