### ISSUE TITLE
[SafelinkScript] github.com/VoreCorporation/Customer-Host

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#227]
Buka https://github.com/VoreCorporation/Customer-Host/tree/master/js, lalu lihat beberap file yang harus diblockir. Convert ke githack.com, karena kemungkinan pakai itu.

**Penjelasan Lebih Lanjut**
Lanjutan dari https://github.com/realodix/AdBlockID/issues/221

**Comment by realodix** [comment]
Blockir semua script dari github.com/VoreCorporation/Customer-Host

**Comment by GrennKren** [comment]
salah satu sumber dari segala masalah kwkwkw

**Comment by Recehan-Slayer** [comment]
@realodix mantab brow
