### ISSUE TITLE
[SafelinkScript] otaku.tekloggers.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#229]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://otaku.tekloggers.com/2020/01/nekopara-ep1-sub-indo.html

**Penjelasan Lebih Lanjut**
`https://raw.githack.com/yuuari/yuuari.com/master/safeplatinum.js`

**Comment by realodix** [comment]
Thank you
