### ISSUE TITLE
lebahmovie.com

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#232]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
- https://lebahmovie.com/
- https://lebahmovie.com/eps/virgin-river-season-1-episode-10/

**Penjelasan Lebih Lanjut**
- Lanjutan dari https://github.com/realodix/AdBlockID/issues/132
- Lebih baik baca dari https://github.com/realodix/AdBlockID/issues/132#issuecomment-571081196

**Comment by Recehan-Slayer** [comment]
`https://ohbayersbur.pro/VFk2UEsve0UnFCErWnJxdjFCJDsnYxl%2FJzE7VzgmOy9fNWU3Nlt%2FOCN3XCNpeHtFPS12Ywd8aSA4UQ8iMHsMcnNnYQNle3Z1FCM%2BNgZfNHl2YxRgfDA8BWh%2FZXQOYX0wdAJpLTJ0D2V8Y3QENXJkOgQ0c2JoAmdpKQ`
||ohbayersbur.pro^$3p

**Comment by realodix** [comment]
> https://ohbayersbur.pro/VFk2UEsve0UnFCErWnJxdjFCJDsnYxl%2FJzE7VzgmOy9fNWU3Nlt%2FOCN3XCNpeHtFPS12Ywd8aSA4UQ8iMHsMcnNnYQNle3Z1FCM%2BNgZfNHl2YxRgfDA8BWh%2FZXQOYX0wdAJpLTJ0D2V8Y3QENXJkOgQ0c2JoAmdpKQ
> `||ohbayersbur.pro^$3p`
>
> sama close button di video playernya
> https://lebahmovie.com/eps/locke-key-season-1-episode-10/

Saya gak ketemu gan sama ohbayersbur.pro dan close buttonnya

**Comment by Recehan-Slayer** [comment]
coba matiin ubo filter yg utama.

**Comment by Recehan-Slayer** [comment]
nevermind dah masuk ke uBO filter gan

**Comment by Recehan-Slayer** [comment]
http://194.67.196.93/eps/tales-loop-season-1-episode-8/
judi baru
