### ISSUE TITLE
oppa.kdramaindo.tv

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#233]
**Jenis iklan** (hapus yang tidak perlu)
- Ads placeholder
**Sample URL**
https://oppa.kdramaindo.tv/running-man-2020-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
tidak bisa klik continue button
https://oppa.kdramaindo.tv/?38971fecb6=MGRLdDNOMWZucncvZ1BCV0l0bzg3YkFxTEZGcFNHU3hJYWplc0NUQjZDYjExd05NRnkwQVVNTllZbitWd1p1UXYyZ1RtMm9NdHlHZkxXQWdBUG82dXZ4a285cHpGVXIvZEE0dkRoaTFKN1U9#bypassClipboard=runningman2020subtitleindonesiaepisode484googledrive

**Comment by realodix** [comment]
Link ujungnya ini bukan?
https://gdrive.drama21.xyz/sedot/mKrCkhCHBbQ0AUK/

**Comment by Recehan-Slayer** [comment]
mksudnya itu kan didalam bnyak contoh linknya ini kasus kek safelinknya pahe in

**Comment by realodix** [comment]
Iya Gan, maksudnya mau mastiin aja. 

> tidak bisa klik continue button

Karena td buka di HP, continue buttonnya pas dipencet ujungnya ke sana. Klo benar, kemungkinan ada yg bentrok. Ntar gue check lg deh

**Comment by 3xploiton3** [comment]
@Recehan-Slayer bro mau tanya, dr sekian link web film, menurutmu mana yg paling lengkap dan gampang downloadnya?
Ga diputar2 ke link2

**Comment by Recehan-Slayer** [comment]
@3xploiton3 `https://pahe.in/`  `https://psarips.one/` 
itu dua"nya ada kualitas HEVC nya jg jdi hemat penyimpanan

**Comment by Recehan-Slayer** [comment]
atau kalo mw yg lebih lengkap/paling lengkap dan ga ribet lewat web" torrent gan dr sumbernya langsung dr kang ngeripnya

**Comment by realodix** [comment]
> **Penjelasan Lebih Lanjut**
> tidak bisa klik continue button
> https://oppa.kdramaindo.tv/?38971fecb6=MGRLdDNOMWZucncvZ1BCV0l0bzg3YkFxTEZGcFNHU3hJYWplc0NUQjZDYjExd05NRnkwQVVNTllZbitWd1p1UXYyZ1RtMm9NdHlHZkxXQWdBUG82dXZ4a285cHpGVXIvZEE0dkRoaTFKN1U9#bypassClipboard=runningman2020subtitleindonesiaepisode484googledrive

Ini maksudnya gimana ya Gan? Tolong filter listnya gan..

**Comment by Recehan-Slayer** [comment]
iya itu double emang safelinknya

**Comment by Recehan-Slayer** [comment]
ngetesnya jgn pke link yg saya post diatas pke yg didalam webnya krn yg diatas itu ada ketambahan bypass clipboard dr universal bypass

**Comment by realodix** [comment]
> iya itu double emang safelinknya
> tidak bisa klik itu mksudnya ketutupan wadah iklan

Oalah yang di bawah ya?

Saya udah commit 
```
ambyar.info###externalinject-gpt-passback-container
ambyar.info###externalinject-gpt-passback-iframe
```

Thank you Gan

**Comment by 3xploiton3** [comment]
@Recehan-Slayer saya suka simpan di gdrive, klo dr torrent agak ribet dikit harus pindah ke gdrive manual,
