### ISSUE TITLE
[SafelinkScript] tokubatch.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#234]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://www.tokubatch.com/kamen-rider-zero-one-2019/

**Penjelasan Lebih Lanjut**
`https://rawcdn.githack.com/marsksatriagotham/wvw/2f0ffa8f809ee9f561434d487ac43247e05b90e8/safelink_utama.js
`
didalam repo nya juga bnyak safelink scriptnya gan
sama anti right click anti selection

**Comment by realodix** [comment]
Repo https://github.com/marsksatriagotham/wvw dan https://github.com/alfirohman/tutorapk.com, isi filenya kurang lebih mirip. Saya akan pertimbangkan untuk blokir 1 repository.

Saya juga akan pertimbangkan untuk membuat filter generic block file `/safelink_utama.js`.
