### ISSUE TITLE
Tracker kompas.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#235]
**Jenis iklan** (hapus yang tidak perlu)
Sejenis Tracker

**Sample URL**
kompas.com

https://scripts.jixie.io/jixietracker.min.js?accountid=9262bf2590d558736cac4fff7978fcb1

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.
![image](https://user-images.githubusercontent.com/19517680/72170428-70c92c80-3403-11ea-9bea-6042ecdee74f.png)

**Comment by GrennKren** [comment]
iya tuh, aku kemarin lusa ada ngeblokir itu juga.. pas ngebuka portal berita kompas ama liputan6.

Jadinya kepikiran buat ngeblokir semua domain yg pake itu
`||scripts.jixie.io^$third-party`

**Comment by realodix** [comment]
Ping @ryanbr @AdamWr

**Comment by AdamWr** [comment]
Added, thank you.
