### ISSUE TITLE
kurosave.com - Anti right click

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#236]
**Jenis iklan** (hapus yang tidak perlu)
- Anti right click

**Sample URL**
https://kurosave.com/owarimonogatari-s1-batch/

**Penjelasan Lebih Lanjut**
Anti klik kanan

**Comment by realodix** [comment]
**uBlock**: https://github.com/NanoMeow/QuickReports/issues/2707 (https://github.com/uBlockOrigin/uAssets/commit/de7d250a544b8e794410ff0bb6cf952bfd224cb6)
**AdGuard**: Ping @AdamWr

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.

Thank you.
