### ISSUE TITLE
dramaserial.org

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#238]
**Jenis iklan** (hapus yang tidak perlu)
mencurigakan

**Sample URL**
block ini
https://bestvideo2019.xyz/script

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by 3xploiton3** [comment]
https://img.nt1.co/jf/adn/tangkas.gif
https://img.nt1.co/ik/luxury.gif
https://img.nt1.co/jf/adn/nagaikan.gif
https://img.nt1.co/jf/live88.gif
https://img.nt1.co/jf/526bet.gif

mungkin bs di buat begini
/*live88*.gif$image

**Comment by Recehan-Slayer** [comment]
https://dramaserial.org/

**Comment by realodix** [comment]
**Sample URL**
Sesuia judul sebelumnya https://dramaserial.org/tv/in-family-we-trust-2018/7/

**Comment by realodix** [comment]
> blm ada filter yg block gambar keyword ini
> 
> https://img.nt1.co/jf/adn/tangkas.gif
> https://img.nt1.co/ik/luxury.gif
> https://img.nt1.co/jf/adn/nagaikan.gif
> https://img.nt1.co/jf/live88.gif
> https://img.nt1.co/jf/526bet.gif
> 
> mungkin bs di buat begini
> `/*live88*.gif$image`

Terima kasih untuk sarannya.

Saya rasa filter `/*live88*.gif$image` terlau umum. Sebagai contoh pada http://player.live885.com/
File /spinner.gif (http://player.live885.com/assets/img/radioplayer/spinner.gif) dan mungkin file gif lainnya terkena dampak.

===

**tangkas.gif, nagaikan.gif, 526bet.gif**
Saya masukkan jadi `/526bet.$image, /nagaikan.gif$image, /tangkas.gif$image`

**live88.gif**
Sedang dipertimbangkan jadi `/live88.gif$image`

**luxury.gif**
Saya rasa ini terlalu umum

**Comment by realodix** [comment]
Ganti domain ke dramaserial.cc #304
