### ISSUE TITLE
oujanime.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#241]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
http://oujanime.com/

**Penjelasan Lebih Lanjut**
Popups

**Comment by realodix** [comment]
**uBlock**: https://github.com/NanoMeow/QuickReports/issues/2713 (https://github.com/uBlockOrigin/uAssets/commit/425ea78d03f6ca1153ebd8c5c24a5e362ad026f6)
**AdGuard**: Ping @AdamWr

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
Thank you.
