### ISSUE TITLE
juraganfilm.site

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#245]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Overlay

**Sample URL**
https://juraganfilm.site/

**Penjelasan Lebih Lanjut**
iklan judi

**Comment by realodix** [comment]
Waduh, ini harus pakai VPN. Karena sudah terblokir

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
https://juraganfilm.mobi/

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
`https://www.juraganfilm.us/`
