### ISSUE TITLE
111.90.142.151 (detikxxi)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#249]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://111.90.142.151/
https://detikxxi.com/anime/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
ada overlay yg transparan gan jdi postnya tidak bisa di klik

**Comment by realodix** [comment]
> ada overlay yg transparan gan jdi postnya tidak bisa di klik

Thank you
