### ISSUE TITLE
[SafelinkScript] maniak21.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#250]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://maniak21.com/the-informer/

**Penjelasan Lebih Lanjut**
`https://panduanrumah.net/wp-content/plugins/soralink/assets/js/sora.php`
saran `/soralink$script,3p`

**Comment by realodix** [comment]
Ini mirip banget seperti di https://github.com/realodix/AdBlockID/commit/e632964ea4177a65da78b9a43c8b7029c9a1728c

**Comment by Recehan-Slayer** [comment]
`https://fixchidie.com/fOjxIuAZYi1/18391`

**Comment by realodix** [comment]
> https://fixchidie.com/fOjxIuAZYi1/18391

Thank you
