### ISSUE TITLE
mangashiro.co

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#251]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://mangashiro.co/

**Penjelasan Lebih Lanjut**
iklan judi sama dibagian footernya bnyak jg gan
`##[href="joker234ok."]` dll

**Comment by realodix** [comment]
Ini lebih ke tombol Gan, Saya gak bisa ngilangin.

Beberapa yang belum ada, sudah Saya tambahkan. Diharapkan bisa kena di banyak web lain dan jika ke depan https://mangashiro.co/ pasang banner, akan kena juga.

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix kan bisa itu pke cosmetic filter 1 per 1 bro. contoh kyk 
`##[href="http://www.ligaovo88.net/"]` 

dan yg ini msh muncul gan `##[href*="duniajodoh."][target="_blank"]`

**Comment by realodix** [comment]
> kan bisa itu pke cosmetic filter 1 per 1 bro. contoh kyk
> `##[href="http://www.ligaovo88.net/"]`

Saya sedang mempertimbangkan untuk merombak filter pada [src/addons/adult-hide.adbl](https://github.com/realodix/AdBlockID/blob/master/src/addons/adult-hide.adbl) agar efektif untuk issue ini.

**Comment by Recehan-Slayer** [comment]
@realodix yg dunia jodoh masi muncul bro dan dilognya ga ada filter nya dunia jodoh yg muncul jg

**Comment by realodix** [comment]
Iklannya sudah Saya hilangkan, termasuk yang di footer.

>yg dunia jodoh masi muncul bro dan dilognya ga ada filter nya dunia jodoh yg muncul jg

Banner yg ini Saya gak ketemu

**Comment by Recehan-Slayer** [comment]
@realodix yg ini bro gw buka lewat hp jg masi muncul
![Screenshot_2020-01-15-12-11-19-17](https://user-images.githubusercontent.com/9379770/72406959-f3305400-3755-11ea-9ec1-2df5a099e688.png)

**Comment by realodix** [comment]
Filternya sudah Saya modif, coba dicheck Bro

**Comment by realodix** [comment]
> pke filter diatas masih muncul bro ntah knp
> `/*350x350*.gif` klo pke itu ate yg lain ga muncul lg

Kok bisa ya? Masalahnya di gue gak muncul Gan, jdi gak bisa bner2 periksa.

`/*350x350*.gif` terlalu berbahaya Gan, terlalu umum, bisa2 semua gif (yg bukan iklan) diluar sana keblokir semua.

**Comment by Recehan-Slayer** [comment]
apa gara" filter ini gana `@@||mangashiro.*^$generichide` dr ublock filter

**Comment by realodix** [comment]
Owh iya nih. Jadinya mati semua filter general.

**Comment by Recehan-Slayer** [comment]
tolong dibikin spesifik filter gan diadblockid+ nya 
`https://mangashiro.co/`

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
di chrome masih muncul gan banner judi yg dr `duniajodoh.net` dan `mainbet88.online`

**Comment by realodix** [comment]
> di chrome masih muncul gan banner judi yg dr `duniajodoh.net` dan `mainbet88.online`

Thank you

**Comment by Recehan-Slayer** [comment]
masi muncul bro yg disebelah kanan ada 2.

**Comment by realodix** [comment]
> masi muncul bro yg disebelah kanan ada 2.

Yang mana ya? Adanya di footer, ada 2 juga

**Comment by Recehan-Slayer** [comment]
![Annotation 2020-02-15 093520](https://user-images.githubusercontent.com/9379770/74580407-97681d80-4fd6-11ea-843c-46d5952b7eb3.png)

**Comment by realodix** [comment]
Ini harusnya gak ada, karena sudah masuk ke database. Minta filterlisnya gan

**Comment by Recehan-Slayer** [comment]
<details>

uBlock filters​​​​​19,026 used out of 19,707​​​​
uBlock filters – Badware risks​​​​​831 used out of 841​​​​
uBlock filters – Privacy​​​​​155 used out of 170​​​​
uBlock filters – Resource abuse​​​​​115 used out of 118​​​​
uBlock filters – Unbreak​​​​​1,306 used out of 1,381​​​​
Ads (3/4)
Adblock Warning Removal​​​​​652 used out of 734​​​​
AdGuard Base​​​​​31,835 used out of 32,335​​​​
EasyList​​​​​80,863 used out of 81,879​​​​
Privacy (2/3)
AdGuard Tracking Protection​​​​​8,522 used out of 8,576​​​​
EasyPrivacy​​​​​13,299 used out of 17,143​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,104 used out of 1,104​​​​
Malware domains​​​​​26,845 used out of 26,860​​​​
Annoyances (3/7)
AdGuard Annoyances​​​​​24,495 used out of 25,635​​​​
Fanboy’s Annoyance​​​​​48,068 used out of 56,661​​​​
uBlock filters – Annoyances​​​​​2,790 used out of 3,005​​​​
Multipurpose (1/4)
Peter Lowe’s Ad and tracking server list​​​​​3,166 used out of 3,299​​​​
Regions, languages (0/35)
Custom (6/8)
AdBlockID​​​​​8,622 used out of 8,628​​​​
AdBlockID Plus​​​​​224 used out of 224​​​​
I don't care about cookies​​​​​18,154 used out of 18,164​​​​
Nano Defender Integration​​​​​2,645 used out of 2,646​​​​
Nano Filters​​​​​352 used out of 352​​​​
Nano Filters - Whitelist​​​​​1 used out of 1​​​

**Comment by realodix** [comment]
Di logger Saya menemukan `@@||mangashiro.*^$generichide` pada uBlock filters.

**Comment by Recehan-Slayer** [comment]
iya udah prnah gw jelasin diatas kan bro 😅

**Comment by realodix** [comment]
> iya udah prnah gw jelasin diatas kan bro 😅

Ini ya ?

> apa gara" filter ini gana @@||mangashiro.*^$generichide dr ublock filter
> _https://github.com/realodix/AdBlockID/issues/251#issuecomment-579579190_

> tolong dibikin spesifik filter gan diadblockid+ nya
> https://mangashiro.co/
> sama dibagian footernya masi ada beberapa situs judi yg blom masuk
>_https://github.com/realodix/AdBlockID/issues/251#issuecomment-581151265_

Tumben banget, biasanya mereka pakai scriptlet.
`@@||$generichide` biasanya digunakan untuk menangani anti-adblock. Setelah Saya cek tanpa menggunakan uBlock filters, tidak ada peringatan anti-adblock di https://mangashiro.co.

Sorry Gan, Saya enggan melakukannya. karena Saya tidak merasa harus menyelesaikan kesalahan mereka. Menambahkan filter specifik (block/hide), tapi sebenarnya sudah bisa ditangani dengan baik oleh filetr generic hide akan membuat AdBlockID+ jadi tidak efisien dan terkesan berat.

**Comment by Recehan-Slayer** [comment]
@realodix bro klo untuk menonaktifkan filter generichide elemenhide pke rules gmn ya bro??

**Comment by Recehan-Slayer** [comment]
@realodix bro klo untuk menonaktifkan filter @@||$generichide pke rules gmn ya bro??

**Comment by realodix** [comment]
> @realodix bro klo untuk menonaktifkan filter @@||$generichide pke rules gmn ya bro??

`$generichide,badfilter`

**Comment by Recehan-Slayer** [comment]
ada yg baru `http://megawin77idn.com/`

**Comment by realodix** [comment]
> ada yg baru http://megawin77idn.com/

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix situs judi baru dibagian bawah gan

**Comment by realodix** [comment]
> situs judi baru dibagian bawah gan

Thank you
