### ISSUE TITLE
[problem] kompasiana.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#253]
**Sample URL**
https://www.kompasiana.com/

**Penjelasan Lebih Lanjut**
Tampilan semua halaman jadi rusak

**Comment by realodix** [comment]
Thank you untuk laporannya Gan.

Masalah ini disebabkan oleh filter `/^https?:\/\/[^\/]+\.[^\/]+\/[a-zA-Z0-9]{32,}$/$script,1p,domain=` pada AdGuard Annoyances.

**Comment by realodix** [comment]
ping @AdamWr

**Comment by AdamWr** [comment]
Fixed, thank you.

**Comment by Recehan-Slayer** [comment]
@realodix ada placeholdernya gan sama masalahnya masih muncul klo adguard annoyancenya hidup

**Comment by Recehan-Slayer** [comment]
![Untitled7](https://user-images.githubusercontent.com/9379770/73493697-d8acda80-43e5-11ea-9339-24a89c3c2ef1.png)

**Comment by realodix** [comment]
> ada placeholdernya gan

@Recehan-Slayer Di screenshot yang banner warna biru itu ya? Kalau iya, Saya sempat melihatnya, gak lama langsung bersih. Sepertinya sedikit lambat.

> masalahnya masih muncul klo adguard annoyancenya hidup

AdGuard Annoyance, ping @AdamWr

**Comment by Recehan-Slayer** [comment]
masi muncul gan coba tunggu agak lama

**Comment by AdamWr** [comment]
>AdGuard Annoyance, ping @AdamWr

What is the problem?
I don't see any issue with AdGuard app/extension.
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/73495118-2dd0f800-43b6-11ea-8c13-a8a858f93f5c.png)

</details>

**Comment by AdamWr** [comment]
Hmmm, I guess that the problem is with ad-reinjection script.
With uBO you can try this rule:
`kompasiana.com##+js(acis, document.addEventListener, iframe-network)`

**Comment by Recehan-Slayer** [comment]
thanks problem solved

**Comment by AdamWr** [comment]
I also modified rule, so it shouldn't break a website.
Update should be available in 1-2 hours.
