### ISSUE TITLE
premierexxi.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#257]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://premierexxi.net/
https://premierexxi.net/movie/kapal-goyang-kapten-2019/

**Penjelasan Lebih Lanjut**
iklan judi sama yg didalam post

**Comment by realodix** [comment]
Thank you

**Comment by realodix** [comment]
https://github.com/realodix/AdBlockID/issues/184
