### ISSUE TITLE
iklan judi + popups

### ISSUE THREAD

**Issue by KagaKouko99** [realodix/AdBlockID#26]
- [x] https://bioskopbos.com/
- [x] http://awnime.net/
- [x] http://www.oujanime.com/
- [x] http://www.cinemaindo21.org/
- [x] http://lk21c.fun/
- [x] https://www.lk21id.com/
- [x] http://idfl.me/forum.php
- [x] https://layarkacaxxi.id/ (https://github.com/realodix/AdBlockID/commit/ecc8d8e98134f2cdaa5768fe0a35b4bbfe1e49c1)
- [x] https://indo168.club/
- [x] https://kawanfilm21.online/
- [x] https://filmbioskop21.cc/
- [x] https://netnot21.com/
- [x] https://www.animebatch.web.id/
- [x] https://filmindo21.tv/
- [x] http://www.senimovie.co/
- [x] https://lewat.club/post/top-android-phone-games?8IT9=1&d=2
- [x] https://kabarviral.blog/post/top-android-phone-games?dy0lli1PZ=1&d=1
- [x] https://tips.atv.pw/post/top-android-phone-games?8IT9=1&d=0

**Comment by realodix** [comment]
Coba tolong dicek lagi deh

**Comment by KagaKouko99** [comment]
http://www.senimovie.co/ yg ini ada popup iklan judi
https://filmbioskop21.cc/ tampilan seperti invisible
![Annotation 2019-08-31 223123](https://user-images.githubusercontent.com/54178411/64066069-e3e5b980-cc3f-11e9-882e-3767981b3ddb.png)

dan yg lain sisanya close image
![Annotation 2019-08-31 222632](https://user-images.githubusercontent.com/54178411/64066087-08da2c80-cc40-11e9-9e94-c8c140c64e78.png)
