### ISSUE TITLE
cafecoli.xyz

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#261]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://cafecoli.xyz/bokepamerika/bokep-barat-tarzan-x-full-movie/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by Recehan-Slayer** [comment]
@realodix sama iklan diweb indo yg banner adult reff macam gini termasuk scopenya jg ga bro
`1.bp.blogspot.com/-1XXz2BOMrl4/XZboXrfyFaI/AAAAAAAAHt0/S-Vvb5nCGWUA6xJGtpwtTEsFdFa3OALugCLcBGAsYHQ/s1600/javhd-18.gif`

`1.bp.blogspot.com/-bsDdT55auiY/XYHpDd6G4FI/AAAAAAAAHrU/kPCJuyoHu6MRiOgcXTErWPdlKjRZHRx9wCEwYBhgL/s1600/banner6.gif`

dll

**Comment by realodix** [comment]
> sama iklan diweb indo yg banner adult reff macam gini termasuk scopenya jg ga bro
> `1.bp.blogspot.com/-1XXz2BOMrl4/XZboXrfyFaI/AAAAAAAAHt0/S-Vvb5nCGWUA6xJGtpwtTEsFdFa3OALugCLcBGAsYHQ/s1600/javhd-18.gif`
> 
> `1.bp.blogspot.com/-bsDdT55auiY/XYHpDd6G4FI/AAAAAAAAHrU/kPCJuyoHu6MRiOgcXTErWPdlKjRZHRx9wCEwYBhgL/s1600/banner6.gif`
> 
> dll

Pada dasarnya gue cuma liat situsnya aja Bro, itu situs apa?

1. **Situs Legal, bisa spesifik**
Contohnya pada file [specific_block.adbl](https://github.com/realodix/AdBlockID/blob/master/src/specific_block.adbl), [specific_hide.adbl](https://github.com/realodix/AdBlockID/blob/master/src/specific_hide.adbl), [news.adbl](https://github.com/realodix/AdBlockID/blob/master/src/addons/news.adbl), [shortlink.adbl](https://github.com/realodix/AdBlockID/blob/master/src/addons/shortlink.adbl)

2. **Situs ilegal**
Sebagian besar hanya filter generik saja.

Gambar pertama gue bisa generic block `/javhd-18.gif`

Gambar kedua gak bisa generic block, tp mungkin bisa generic hide, kalau keduanya gak bisa, Saya biarkan atau ping maintener filter uBlock dan AdGuard (mereka punya sumber daya yg cukup untuk cek satu per satu domainnya).

**Comment by realodix** [comment]
Thank you
