### ISSUE TITLE
inonton.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#264]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
http://www.inonton.com/
http://www.inonton.com/2019/11/you-might-be-the-killer-2018.html

**Penjelasan Lebih Lanjut**
Popups sama yg didalam post bro bnyak link web poker itu psti web yg msh hidup psti ngiklanin banner di tempat laen

**Comment by realodix** [comment]
Filternya sudah Saya modifikasi dan tambah agar compatible dengan inonton.com.

Sebagai catatan (kshusus untuk issue ini saja), untuk iklan yang mengarah ke livesgphariini.com, rajatoto3.net dan togelkami, iklan tidak hilang di AdGuard, setidaknya hingga issue di `https://github.com/AdguardTeam/FiltersRegistry/issues/259` telah diselesaikan.
