### ISSUE TITLE
Kumpulan situs yang ada popups sama iklan judi dll

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#265]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
http://www.inonton.com/2019/11/you-might-be-the-killer-2018.html
https://platinum21movie.com/2018/05/gamennhujin-2018.html

**Penjelasan Lebih Lanjut**
di backlink 2 web diatas bro bnyak web" indo popups+iklan judi capek ane buat issue 1 per 1 
ntar ane bntu ngecek in aja klo dah dimasukin filternya smua
ane mw bntu pull req tp msh blom paham smua syntax filternya

**Comment by realodix** [comment]
> http://www.inonton.com/2019/11/you-might-be-the-killer-2018.html

Duplicate of #264

>https://platinum21movie.com/2018/05/gamennhujin-2018.html

Duplicate of #263

---

> ntar ane bntu ngecek in aja klo dah dimasukin filternya smua
> ane mw bntu pull req tp msh blom paham smua syntax filternya

Terima kasih sudah berniat untuk membantu ngecek dan ingin membuat pull request. Untuk bahan bacaan, bisa banyak baca di https://github.com/realodix/AdBlockID#panduan-untuk-menulis-filter

**Comment by Recehan-Slayer** [comment]
popups mengarah ke `http://172.104.173.114/id-ID/Home`
