### ISSUE TITLE
pepek.fun

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#267]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://pepek.fun/
https://pepek.fun/bokep-indo-viral-gojek-ngentot-sama-konsumen/

**Penjelasan Lebih Lanjut**
Banner judi sama yg didalam post

**Comment by Recehan-Slayer** [comment]
@realodix yg itu belom bro
`##[href^="probet2424."]`

**Comment by realodix** [comment]
> yg itu belom bro
> `##[href^="probet2424."]`

Thank you, sudah ditambahkan

**Comment by Recehan-Slayer** [comment]
`https://pepek.pro/bokep-indo-skandal-smk-negri-1-salam-magelang/`
banner baru bro sama yg didalam video sama di home

**Comment by realodix** [comment]
> 
> 
> `https://pepek.pro/bokep-indo-skandal-smk-negri-1-salam-magelang/`
> banner baru bro sama yg didalam video sama di home

**Comment by Recehan-Slayer** [comment]
Judi baru probet.biz

**Comment by realodix** [comment]
> 
> 
> Judi baru probet.biz

Thank you
