### ISSUE TITLE
bfoni.com  Safelink script

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#268]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://bfoni.com/salah-satu-murid-terbaik/

**Penjelasan Lebih Lanjut**
`https://raw.githack.com/theboncud/aklista/master/safelink.js`

dan di repo githubnya ada safelink script laen brow

sama dilink drivenya ada anti adblock
`https://sharetvr.my.id/dl.php?id=NnRjS2NWWmN3WksxVDdEUkY5MjFROGdqN1YxUjNNcVJGSFZ1VEhtanRCWnpjdEdUWlNXT3laL3dTbXVPUlRRcmJObFhrSVZrVnRiNnd0Q2hSQmFYZ2JPZ3hBZFFMQjZnWlJLVlNoTmUwNnZtSWxwOXVQcEQrZUYvT3FZV3B2QVY=&type=2`

**Comment by realodix** [comment]
Thank you
