### ISSUE TITLE
feev.net

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#269]
https://feev.net/1Tzi

Saya save disini dulu sementara ada pop up sebelum sampai ke link tujuan

**Comment by 3xploiton3** [comment]
Pop up nya ke redirect seperti ini
![](https://i.imgur.com/j9esGiE.jpg)

**Comment by realodix** [comment]
Urutannya bener gak ini?

1. Linknya di oper ke https://newsteez.com/quick-guide-to-use-semrushs-seo-writing-assistant-for-better-rankings/#wpsafegenerate
2. Lalu ke https://shrtfly.net/VPH0x5u dan isi reCAPTCHA
3. Lalu ke https://torrent.chew.rocks/torrentobot/unlock_cloud.php?id=4rjXozWanz
4. Terus muncul tulisan **"Already unlocked! Please process to upload the file to your cloud."**

**Comment by 3xploiton3** [comment]
Ya bener, sayangnya saya pakai universal bypasser jadi sering ga lihat itu 😆

**Comment by 3xploiton3** [comment]
Setelah recaptcha selesai, tunggu sebentar baru muncul pop up

**Comment by 3xploiton3** [comment]
Ini videonya
https://photos.app.goo.gl/hUu63TcEXdp19x8u6

**Comment by realodix** [comment]
> Setelah recaptcha selesai, tunggu sebentar baru muncul pop up

> Ini videonya
> https://photos.app.goo.gl/hUu63TcEXdp19x8u6
> 
> Sekalian dr short url ada beberapa iklan klo bisa dihapus
> 
> Saya pakai kiwi browser android, ekstension adguard

OK dari penjelasan di atas, berarti nomor 3 ya https://shrtfly.net/VPH0x5u

Untuk sudah pernah Saya tangani di https://github.com/realodix/AdBlockID/commit/29f85af6d555b245c40c01f22e0efb3949bec852
Hanya Saja karena bentuknya scriptlet. untuk AdGuard saat ini yg bisa masukin hanya maintener filter AdGuard.

**Comment by 3xploiton3** [comment]
Ping @AdamWr

**Comment by AdamWr** [comment]
Please describe your issue, because I don't understand what the problem is.

**Comment by 3xploiton3** [comment]
@AdamWr showing pop up before reach destination

Source
https://feev.net/1Tzi
 Then after captcha done, showing pop up look my screenshot

**Comment by AdamWr** [comment]
I can't reproduce any popups on my end with AdGuard for Android (Chome) and on Windows with app/Chrome extension.

**Comment by Recehan-Slayer** [comment]
> Saya pakai kiwi browser android, ekstension adguard


> Ya bener, sayangnya saya pakai universal bypasser jadi sering ga lihat itu 😆

@3xploiton3 btw bro skrng UB versi terbaru udah full kompatibel pakai kiwi browser android dan mungkin jg dgn chromium based browser yg lain. semua fitur dan bypassnya work semua dah gw coba.

**Comment by 3xploiton3** [comment]
@Recehan-Slayer sayangnya ga ada tombol report utk menangani ads

Makanya saya pakai adguard

**Comment by Recehan-Slayer** [comment]
@3xploiton3 mksudnya gmn??? kan gw diatas bahas universal bypass. yg sekarang dah kompatibel ama browser based chromium. seperti kiwi di android kan sebelumnya ga kompatibel bnyak fitur dan bypassnya yg ga work.


> @Recehan-Slayer sayangnya ga ada tombol report utk menangani ads
> 
> Makanya saya pakai adguard


oh ada kok tombol reportnya di uBO tpi lewat ekstensi nano defender

**Comment by 3xploiton3** [comment]
Klo nano defender bukannya hanya utk bypass "anti adblock"

**Comment by Recehan-Slayer** [comment]
mksudnya buat fitur auto reportnya bro lewat nano defender. untuk laporan reportnya bkn hanya khusus anti adblock aja. 


> @Recehan-Slayer sayangnya ga ada tombol report utk menangani ads
> 
> Makanya saya pakai adguard

2 2 nya sama" bagus sih tpi menurut pemakaian pribadi gw lebih enteng uBO gandeng nano defender dan jarang banget nemuin situs muncul anti adblock.

**Comment by 3xploiton3** [comment]
@Recehan-Slayer misal kita report pakai nano defender, apakah nanti filternya masuk ke easylist atau filter nano punya sendiri?

Saya juga pakai ubo klo lg males reporting iklan

**Comment by Recehan-Slayer** [comment]
ya filternya masuk uBO dan nano adblocker/defender trgntung filter khusus apa kan mereka" itu seperti 1 tim gtu.

 trkadang jg masuk easylist.kdang jg masuk adguard filter jg. trgntung filter khusus apa. uBO filter jg kdang ambil referensinya dr laporan direpo lain sperti repo adguard dan begitu jg sebaliknya.
