### ISSUE TITLE
[Anti-Adblock] sharetvr.my.id

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#270]
**Sample URL**
https://sharetvr.my.id/dl.php?id=NnRjS2NWWmN3WksxVDdEUkY5MjFROGdqN1YxUjNNcVJGSFZ1VEhtanRCWnpjdEdUWlNXT3laL3dTbXVPUlRRcmJObFhrSVZrVnRiNnd0Q2hSQmFYZ2JPZ3hBZFFMQjZnWlJLVlNoTmUwNnZtSWxwOXVQcEQrZUYvT3FZV3B2QVY=&type=2

**Penjelasan Lebih Lanjut**
- Sumber: https://bfoni.com/salah-satu-murid-terbaik/
- Lanjutan dari https://github.com/realodix/AdBlockID/issues/268

**Comment by Recehan-Slayer** [comment]
@realodix sama timernya 
`sharetvr.my.id##+js(nano-setInterval-booster.js)`
