### ISSUE TITLE
128.199.102.136 (Bokep Mobile Online)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#272]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://128.199.102.136/
http://128.199.102.136/rangking-kelas-konsen-minta-sperma/

**Penjelasan Lebih Lanjut**
Banner judi sama yg didalam post

**Comment by realodix** [comment]
Thank you
