### ISSUE TITLE
oceantech.xyz

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#273]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Fake button

**Sample URL**
http://jasarekber.net/ccbhyALp

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix masih ada bro `##.separator`

**Comment by realodix** [comment]
> masih ada bro `##.separator`

Sudah ditambahkan, jadinya `oceantech.xyz##.banner`. Thank you
