### ISSUE TITLE
Komiku.co

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#274]
**Jenis iklan** 
- Pop-up
- Lainnya

**Sample URL**
di balik nya ada script memanggil iklan.php , isinya javascript
`- https://komiku.co/`

3 link bawah ini sebenarnya cukup 1 aja, hanya sekedar pembuktian kalau tiap chapter komik nya memanggil script dari url `/views/**angka**/` yang berbeda
```
- https://komiku.co/hero-i-quit-a-long-time-ago-chapter-132/
- https://komiku.co/kimetsu-no-yaiba-chapter-1-id/
- https://komiku.co/apotheosis-chapter-381/
```

**Penjelasan Lebih Lanjut**
Tiap chapter komiknya, ini yg dipanggil komiku , isi nya sama persis hanya beda di link assapebat.club 
`https://komiku.co/views/2032925/` dan `https://komiku.co/views/40508/`

**Rules disarankan**
```
/iklan.php$script,domain=komiku.co
||assapebat.club$script,domain=komiku.co
/views/*/$script,domain=komiku.co
```

**Comment by realodix** [comment]
Thank you untuk laporannya.

> 3 link bawah ini sebenarnya cukup 1 aja, hanya sekedar pembuktian kalau tiap chapter komik nya memanggil script dari url `/views/**angka**/` yang berbeda
> 
> ```
> - https://komiku.co/hero-i-quit-a-long-time-ago-chapter-132/
> - https://komiku.co/kimetsu-no-yaiba-chapter-1-id/
> - https://komiku.co/apotheosis-chapter-381/
> ```
> 
> **Penjelasan Lebih Lanjut**
> Tiap chapter komiknya, ini yg dipanggil komiku , isi nya sama persis hanya beda di link assapebat.club
> `https://komiku.co/views/2032925/` dan `https://komiku.co/views/40508/`

Saya rasa ini tidak perlu Gan untuk membuat filter `/views/*/$script,domain=komiku.co`.

Di dalamnya mereka memanggi Ad Server `imported.src = '//assapebat.club/rCOKEIqkjNhtqxr/12407';`.

assapebat.club sudah Saya blokir https://github.com/realodix/AdBlockID/commit/5c0d51bb6fa4e20aa5b5fd2ee9b331311f8d6af2

**Comment by GrennKren** [comment]
oh udah di blokir yg itu ya.. wa kira  harus ampe ke script yg memanggil nya.. closed dlu.
Makasih banyak

**Comment by realodix** [comment]
Untuk kasus ini tidak perlu, karena script nya dipanggil dr luar. Kecuali memang script nya ada di situ.

Sama-sama, terima kasih juga.

**Comment by GrennKren** [comment]
**Sample URL**
`https://komiku.co.id/manga/apotheosis/`

**Penjelasan Lebih Lanjut**
AA

**Comment by realodix** [comment]
Thank you, update tersedia di [AdBlockID+](https://github.com/realodix/AdBlockID#cara-menggunakan)
