### ISSUE TITLE
komikcast.com

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#275]
**Jenis iklan**
- Pop-up
- Lainnya

**Sample URL**
Halaman depannya berisi popup yang mengarahkan ke `http://www.helenajonsson.com/`
- `https://komikcast.com/`

Dan tiap chapter komik nya berisi popup yg mengarah ke `http://agensurga88.com/`
- `https://komikcast.com/chapter/hero-i-quit-a-long-time-ago-chapter-134-bahasa-indonesia/`

**Penjelasan Lebih Lanjut**
Selain popup , halaman chapter komik nya juga ada script yg mengarah ke `https://leoceran.pw/rOGra5gyiUOPW/11983` . aku ga tau apa itu,  ga bisa membuka dari sini. Cuman mendebak bila diblokir ama DNS yg kupakai yg berarti tracker atau semacamnya.

**Rules yang disarankan**
```
||leoceran.pw^$third-party
komikcast.com##+js(abort-current-inline-script.js, $, "popup")
```

**Comment by realodix** [comment]
Thank you

>komikcast.com##+js(abort-current-inline-script.js, $, "popup")
Pop-up ads Saya cegah secara manual dan blokir ad server. Sebisa mungkin Saya menghindari penggunaan scriptlet (kecuali terpaksa), karena hanya compatible di uBlock dan Nano, sedangkan ABP dan AdGuard tidak.

**Comment by realodix** [comment]
Sebagian update tersedia di AdBlockID & [AdBlockID+](https://github.com/realodix/AdBlockID#cara-menggunakan).

**Comment by Recehan-Slayer** [comment]
@realodix badfilter komikcast.com##+js(nobab) 
saaat cek security cloudflare looping

**Comment by GrennKren** [comment]
@realodix 

**Jenis Iklan**
   - Popup
   - lainnya
  
**Sample URL**
`https://komikcast.com/chapter/lord-of-deathbed-chapter-238-bahasa-indonesia/`

**Penjelasan lebih lanjut**
Jika di halaman sudah ke load, apapun yg di klik akan memunculkan popup.

Serta hal lainnya, tag element select untuk memilih chapter tidak berfungsi jika filter tertentu di aktifkan.
Masalahnya itu adalah `Adguard Base Filter`, untuk Ublock Origin entah apakah juga mengalamin hal serupa.

**Comment by realodix** [comment]
Ping @Alex-302

**Comment by GrennKren** [comment]
Yg popup rupanya dah ada sejak lama di `Adguard Base Filter,` jadi gak ada permasalahan popup.

Untuk yg element select tidak berfungsi keliatannya hanya  di Chrome android tapi tidak di pc.

Jadi untuk sekarang menggunakan filter
`komikcast.com#@%#window.open = function() {};`
Untuk mematikan filter yang berasal dari Adguard.

**Comment by AdamWr** [comment]
Fixed, update should be available in 1-2 hours.
