### ISSUE TITLE
haipedia.com (shrinkads.com)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#276]
**Jenis iklan** (hapus yang tidak perlu)
- Fake Button
- Pop-up

**Sample URL**
https://www.shrinkads.com/d5UXgE
https://www.haipedia.com/2ez08GRl

**Penjelasan Lebih Lanjut**
fake button popups dan anti adblock

**Comment by realodix** [comment]
Berhubungan dengan https://github.com/realodix/AdBlockID/issues/96

**Comment by realodix** [comment]
Pop-up

uBlock: https://github.com/NanoMeow/QuickReports/issues/2768 (https://github.com/uBlockOrigin/uAssets/commit/d032b4333aaedbbfad2a901ab1955401710274be) 
AdGuard: ping @AdamWr

**Comment by realodix** [comment]
@Recehan-Slayer Thank you

**Comment by realodix** [comment]
haipedia.com -> sekilastekno.com
