### ISSUE TITLE
[SafelinkScript] naitonime.ga

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#277]
**Jenis iklan** (hapus yang tidak perlu)
- Safelinkscript

**Sample URL**
https://www.naitonime.ga/2020/01/darwins-game.html

**Penjelasan Lebih Lanjut**
`https://cdn.statically.io/gh/riedayme/bloggercode/master/js/autoreplacebyfeednew.js`

**Comment by realodix** [comment]
Thank you
