### ISSUE TITLE
uiz.io

### ISSUE THREAD

**Issue by RaveN0X87** [realodix/AdBlockID#278]
**Sample URL**
https://uiz.io/UBWp1

**Penjelasan Lebih Lanjut**
blocking recaptcha google

**Comment by realodix** [comment]
Domain international, pennguna terbanyaknya ada di luar.
https://www.alexa.com/siteinfo/uiz.io#section_traffic

Ini harusnya sudah selesai di https://github.com/NanoMeow/QuickReports/issues/2782
