### ISSUE TITLE
jagoanfilm.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#280]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://jagoanfilm.com/film/terminator-dark-fate-2019-jf/
https://cafecinema.vip/terminator-dark-fate-2019-jf/

**Penjelasan Lebih Lanjut**
Iklan judi dll

**Comment by realodix** [comment]
Sedikit sulit untuk memasukkan ini, masalahnya bukan adult ads

```
##[href="https://bit.ly/kuis-film-promo"]
##[href="https://bit.ly/kuis-home"]
```
