### ISSUE TITLE
sobatkeren.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#281]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
https://sobatkeren.com/

**Penjelasan Lebih Lanjut**
Popups 1st visit

**Comment by realodix** [comment]
Thank you untuk laporannya

Pop-upnya mengarah ke `www.google.com/search?q=`, Saya bingung juga blockirnya kalau dilakukan manual.

Bisa diakali dengan uBlock scriplet
- `sobatkeren.net##+js(window.open-defuser)`

**Comment by 3xploiton3** [comment]
![](https://i.imgur.com/zS6BpKr.jpg)

Msh ada di video playback

**Comment by realodix** [comment]
**Catatan Pribadi**
Domain telah berubah dari sobatkeren.com ke sobatkeren.net

---

Laporan pada https://github.com/realodix/AdBlockID/issues/281#issuecomment-579588476 membutuhkan spesific block. Karena ini situs ilegal di Indonesia, Saya masukkan ke AdBlockID Plus

**Comment by Recehan-Slayer** [comment]
popups mengarah ke `https://euro-2020.onlineindonesia.tech/`

**Comment by realodix** [comment]
> popups mengarah ke `https://euro-2020.onlineindonesia.tech/`

Thank you
