### ISSUE TITLE
Flying Popup by netkevin -  Empty ads placeholders

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#282]
**Jenis iklan** (hapus yang tidak perlu)
- placeholder

**Sample URL**
https://nontonfilmdrama.net/
https://geraifilm.com/

**Penjelasan Lebih Lanjut**
bro ini bnyak situs yg mirip mungkin bisa dibikin general filternya buat ngilangin

**Comment by Recehan-Slayer** [comment]
https://juraganfilm.tv/

**Comment by Recehan-Slayer** [comment]
###netkevin-overlay$domain=~juraganfilm^|nontonfilmdrama^  dll kayak gini bisa ga bro semisal webnya pindah domain tp asal namanya tetep msh keblock kan???

**Comment by realodix** [comment]
> https://juraganfilm.tv/

Ganti domain ke juraganfilm.life (#414)
