### ISSUE TITLE
nontonan.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#284]
**Jenis iklan** (hapus yang tidak perlu)
- Annoyance

**Sample URL**
https://nontonan.com/

**Penjelasan Lebih Lanjut**
annoying notification selalu muncul

**Comment by realodix** [comment]
Thank you untuk laporannya

Ini bisa diakali dengan uBlock scriptlet
`nontonan.com##+js(aopr, SGPB_POPUP_PARAMS)`

Hanya saja karena harus menambahkan nama domain, jadi gak Saya masukkan.
