### ISSUE TITLE
gudangfilm.club

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#286]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Overlay

**Sample URL**
https://gudangfilm.club/kembalinya-anak-iblis-2019/

**Penjelasan Lebih Lanjut**
iklan judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix masi muncul bro klo ##[href*="rebrand.ly/gudangfilm"]
ga muncul lg

**Comment by realodix** [comment]
Valid di uBlock dengan browser berbasis chrome dengan banyak filter diaktifkan. Thank you
