### ISSUE TITLE
ceklink.co

### ISSUE THREAD

**Issue by KagaKouko99** [realodix/AdBlockID#29]
popups sama fake generate link

http://ptg.ceklink.co/yqQYFv6D
http://g.ceklink.co/9o4vZ

**Comment by realodix** [comment]
Filter untuk ngilangin popups kemungkinan gak compatible dengan Adblock Plus dan semua versi AdGuard.

**Comment by bogachenko** [comment]
>belum ada solusi untuk ngilanginnya pada Adblock Plus dan AdGuard.

false

**Comment by WaferNabati** [comment]
@realodix update dong skrng ganti domainya fake button ads
