### ISSUE TITLE
199.38.245.239 (Rumah Perjaka)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#290]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://199.38.245.239/
http://199.38.245.239/jav-subtitle-indonesia-yang-ditunggu-gan-goyangan-mantan-memang-tak-terlupakan-yua-mikami/

**Penjelasan Lebih Lanjut**
iklan judi

**Comment by realodix** [comment]
Thank you
