### ISSUE TITLE
[SafelinkScript] anisubindo.video

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#298]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://anisubindo.video/2017/01/o3piece-6jy/

**Penjelasan Lebih Lanjut**
https://www.cariskuy.com/assets/js/safelink.js

**Comment by Recehan-Slayer** [comment]
https://github.com/realodix/AdBlockID/issues/237

**Comment by realodix** [comment]
Thank you
