### ISSUE TITLE
Kumpulan situs judi

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#299]
**Jenis iklan** (hapus yang tidak perlu)
- iklan judi

**Sample URL**
https://cinemaqu.com/
http://onetpedia.net/

**Penjelasan Lebih Lanjut**
kumpulan situs judi

**Comment by realodix** [comment]
Thx Gan. Sebagian sudah ditambahkan dari onetpedia, sebagian lagi sudah diblokir jadi tidak saya tambahkan.

**Comment by Recehan-Slayer** [comment]
ada yg blom itu gan promo855.com topdrakor.website https://linktr.ee/nomorqq

**Comment by realodix** [comment]
> ada yg blom itu gan promo855.com topdrakor.website https://linktr.ee/nomorqq

Thank you

**Comment by Recehan-Slayer** [comment]
ada situs judi baru `http://topdrakor.website/`

**Comment by Recehan-Slayer** [comment]
yg topdrakor.website masi muncul

**Comment by realodix** [comment]
> yg topdrakor.website masi muncul

Thank you

**Comment by Recehan-Slayer** [comment]
https://bandariklan.com/
