### ISSUE TITLE
safelink ads/boost timer

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#30]
https://wadooo.com/g/QpvRF095iS
https://liputannubi.net/g/QpvRF095iS
https://pantauterus.me/g/QpvRF095iS
https://gotravelgo.space/g/QpvRF095iS
https://bercara.com/kc8wLuEh51J
http://semawur.com/vHiX
http://in11.site/v7CuUpYM

**Comment by realodix** [comment]
Ini maksudnya diapain ya? Dicepetin waktu tunggunya?

**Comment by WaferNabati** [comment]
@realodix iya boost countdownnya gan

**Comment by realodix** [comment]
Ini cukup?

`bercara.com,gotravelgo.space,
in11.site,liputannubi.net,pantauterus.me,
semawur.com,wadooo.com##+js(nano-sib)`

**Comment by WaferNabati** [comment]
iya cukup sama misal klo ada ads/fake download button nya atau popup kayak di safelink ini
https://lewat.club/post/top-android-phone-games?hOFwITu=1&d=1
https://www.adlink.pw/post/top-android-phone-games?0KMyeycvD=1&d=0
