### ISSUE TITLE
indocin.me

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#303]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Safelink script

**Sample URL**
http://indocin.me/streaming/streaming-bokep-indo-bokep-abg-cantik/

**Penjelasan Lebih Lanjut**
https://rawcdn.githack.com/antonclanazhary/erpsoftware/6f6e7b6d2202a14c5d2e8e824866af5173aa2899/call.js

dan banner iklan

sama direponya ada safelink yg lain

**Comment by realodix** [comment]
Link diblokir, bannernya juga yang biru gak bisa dihilangkan secara generic Gan. Sorry
