### ISSUE TITLE
dramaserial.cc

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#304]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://dramaserial.cc/scoop-2006/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
https://dramaserial.cc/tv/journey-to-the-west-ii-1998/

banner judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
ada banner judi baru

##[href*="rebrand.ly/DramaserialSidebar"]

**Comment by realodix** [comment]
> ada banner judi baru
> 
> ##[href*="rebrand.ly/DramaserialSidebar"]

Thank you
