### ISSUE TITLE
ayononton.info

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#305]
**Jenis iklan** (hapus yang tidak perlu)
- Close button 

**Sample URL**
https://ayononton.info/

**Penjelasan Lebih Lanjut**
close buttonya jg banyak dipakai dibanyak website

**Comment by Recehan-Slayer** [comment]
https://cinema-indo.web.id/

**Comment by realodix** [comment]
Ini bisa dihilangkan secara spesifik Gan

```
123luxury.xyz###tampil

cinema-indo.web.id##.close-banner
```
