### ISSUE TITLE
nobarfilm.pw

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#308]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://nobarfilm.pw/download/file/bf4dff1043d397a6eda429739d2cf8709383f8615b742e47ecaff451b6ec9786e50bd17f9e58a9746da591c6479d1f8cf41524ab4c8adf199c0dddd32718d564ocLMaFpZoVNGay9QcK8WT5Ekr4DKKbuGd9Envc~q5LIdp~GT6SXmPLblU3zFFma1rguxqyxH7_85mB4pQqsIyQ--?dl=2

**Penjelasan Lebih Lanjut**
fake button judi

**Comment by realodix** [comment]
Ini sebenernya sudah ada https://github.com/realodix/AdBlockID/commit/771073d98539ad2f98addf21e509412a2a2128c8#diff-4c848bd3bcff4f4b9d5c90a6b5a952b6R3251

Thank you

**Comment by Recehan-Slayer** [comment]
`https://nobarfilm.co/star-wars-the-rise-of-skywalker-2019-2/`
`https://libanyelm.com/r83bd1wIgMnO4c/15850`

**Comment by realodix** [comment]
> https://nobarfilm.co/star-wars-the-rise-of-skywalker-2019-2/
> https://libanyelm.com/r83bd1wIgMnO4c/15850

Thank you
