### ISSUE TITLE
vimaxdenpasar.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#313]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Safelinkscript

**Sample URL**
http://vimaxdenpasar.com/bokep-barat-ngentot-pegawai-bank-susu-belang/

**Penjelasan Lebih Lanjut**
`https://rawcdn.githack.com/skuy99/seo-smart-safelink/07180b87591c2f0ec2b9cfff31d1ff5bde567cc4/seo-smart-safelink.js`

dan banner dan direponya banyak safelink scriptnya brow

**Comment by realodix** [comment]
Thank you
