### ISSUE TITLE
kazefuri.me

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#316]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://kazefuri.me/
https://kazefuri.me/spirit-sword-sovereign-3-season-3-episode-11-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
sama yg didalam post jg ada iklan judi
##.adstengah
##.adsbawah2

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix masih ada itu yg didalam post
https://kazefuri.me/king-is-not-happy-episode-01-subtitle-indonesia/
mengarah ke http://bit.ly/2Yb1fA3 dan http://216.83.47.102/

**Comment by realodix** [comment]
Sudah ditambahkan

**Comment by Recehan-Slayer** [comment]
@realodix masih ada bro digambar yg ada tanda segita pentungnya ! nya coba ente cek
`https://kazefuri.me/demon-spirit-seed-manual-episode-03-subtitle-indonesia/`


![Annotation 2020-01-26 155951](https://user-images.githubusercontent.com/9379770/73132983-2ecff580-4055-11ea-9555-04165a95b9a6.png)

**Comment by realodix** [comment]
Iya, karena ada filter ini untuk menangani anti adblock
https://github.com/realodix/AdBlockID/blob/15161cd34eb237fc9520fac9e152993181135102/src/addons/movie.adbl#L94

Saya cek dulu, filter di atas masih berguna atau tidak

**Comment by realodix** [comment]
Ternyata sudah tidak berguna. Jika ke depan muncul anti-adblock lagi, kemungkinan akan menghasilkan efek yang sama, tergantung apa yang harus diwhitelist nanti.

**Comment by Recehan-Slayer** [comment]
`https://jootizud.net/pfe/current/tag.min.js?z=2922875`
terdeteksi adware oleh antivirus eset
||jootizud.net^

**Comment by Recehan-Slayer** [comment]
`https://gagpetwet.com/r88z4En1D4I/16915`
`https://kazefuri.me/qiang-shen-ji-ep-10/`

**Comment by realodix** [comment]
> https://gagpetwet.com/r88z4En1D4I/16915
> https://kazefuri.me/qiang-shen-ji-ep-10/

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix 
https://jootizud.net/pfe/current/tag.min.js?z=2922875 
 sama seperti 
https://propu.sh/pfe/current/tag.min.js?z=2881154 
dari web sektekomik yg diblokir di adguard base uAssets dan terdeteksi adware oleh antivirus.
||propu.sh^$3p
||jootizud.net^$3p

**Comment by realodix** [comment]
> https://jootizud.net/pfe/current/tag.min.js?z=2922875
> sama seperti
> https://propu.sh/pfe/current/tag.min.js?z=2881154
> dari web sektekomik yg diblokir di adguard base uAssets dan terdeteksi adware oleh antivirus.
> `||propu.sh^$3p`
> `||jootizud.net^$3p`

Thank you
