### ISSUE TITLE
192.64.115.42 (Rebahin)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#317]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://192.64.115.42/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by realodix** [comment]
Statusnya maintenance

**Comment by realodix** [comment]
Sudah hari ke 7, status masih maintenance.

Cuplikan pesan

> Sorry for the inconvenience but we’re performing some maintenance at the moment. Fell Free to Access Our Partner Site Rebahin.com, otherwise we’ll be back online shortly!

**Comment by rebahinxxi** [comment]
http://198.54.124.245/

REBAHIN.CO / REBAHIN.ORG 

LANGSUNG ADD WA YA BIAR BISA PAHAM LINK ALTERNATIF NYA APA / BISA CARI INFO DI TWITTER @rebahinxxi / Instagram: @claramonica168
