### ISSUE TITLE
bioskop21.at.ua safelink script

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#318]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
http://bioskop21.at.ua/blog/the_wave_2019/2020-01-17-1291

**Penjelasan Lebih Lanjut**
`https://cdn.staticaly.com/gh/seomakassar/safelink/a65b09c8/safelink.js`

**Comment by realodix** [comment]
Berhubungan dengan https://github.com/realodix/AdBlockID/issues/237

**Comment by Recehan-Slayer** [comment]
https://lk-21.info/load/western/bad_boys_for_life_2020/27-1-0-1368#

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix klo buat seperti ini berbahaya ga gan??? ||safelink.js$script,third-party

**Comment by realodix** [comment]
> klo buat seperti ini berbahaya ga gan??? ||safelink.js$script,third-party

Belum ada cukup bukti untuk verifikasi bahaya atau tidak. Untuk sementara dianggap bahaya.

**Comment by Recehan-Slayer** [comment]
@realodix itu gw buat issue baru bnyak bgt safelink.js
blom lg dr gitlab bitbucket dll

**Comment by realodix** [comment]
> itu gw buat issue baru bnyak bgt safelink.js
> blom lg dr gitlab bitbucket dll

Siap thx Gan, nati Saya tambahkan.

Kasusnya mirip seperti
- `##.ads` yang tidak ada di easylist.
- `##.iklan` yang ada di [ABPindo/indonesianadblockrules/src/elementhide/general_hide.txt#L139](https://github.com/ABPindo/indonesianadblockrules/blob/3e670f09d4e011bbcb15694655e4e6fd489d9035/src/elementhide/general_hide.txt#L139), dulu Saya sering banget buat daftar whitelist hingga jadi salah satu alasan Saya untuk buat filter sendiri.

Kalau kata maintener filter AdGuard `tunggu aja dulu hingga numpuk banyak banget, itu lebih baik dari pada salah blokir, sudah terlanjur hilang semua daftar spesifiknya.`
