### ISSUE TITLE
lontegratis.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#319]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://lontegratis.net/2019/07/29/bokep-thailand-ngentot-dengan-pacar-baruku-di-dalam-kamar-kost/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by realodix** [comment]
Canvas pojok kanan bawah, Saya gak bisa ngilangin

thank you

**Comment by Recehan-Slayer** [comment]
@realodix masih ada itu http://duniamalam.org/ sama http://asiaforbet99.com/

**Comment by realodix** [comment]
Sudah ditambahakan, thank you.
