### ISSUE TITLE
jagogoyang.org 

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#321]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://www.jagogoyang.org/gabie-carter-lagi-enak/

**Penjelasan Lebih Lanjut**
iklan judi didalam video

**Comment by realodix** [comment]
Gak ketemu gan, adanya tulisan 99togel

**Comment by realodix** [comment]
Thank you
