### ISSUE TITLE
citpekalongan.com 

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#328]
**Jenis iklan** (hapus yang tidak perlu)
- Overlay
- Pop-up
- Lainnya

**Sample URL**
http://www.citpekalongan.com/
http://www.citpekalongan.com/2020/01/21-22-desember-2020-part-640-gratis.html
https://www.cheatpekalongan.com/
https://www.cheatpekalongan.com/2020/01/code10-link-download-file-cheats-pubg.html

**Penjelasan Lebih Lanjut**
Anti adblock popups overlay etc

**Comment by realodix** [comment]
Thank you
