### ISSUE TITLE
gembelcit.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#329]
**Jenis iklan** (hapus yang tidak perlu)
- Anti right click
- Anti select

**Sample URL**
https://www.gembelcit.net/2020/01/cheat-point-blank-indonesia-23-januari.html
http://www.gembel9.xyz/2020/01/cheat-point-blank-indonesia-23-januari-dD5jd.html

**Penjelasan Lebih Lanjut**
Anti copy paste

**Comment by realodix** [comment]
**uBlock**: https://github.com/NanoMeow/QuickReports/issues/769
**AdGuard**: Ping @AdamWr

**Comment by AdamWr** [comment]
Fixed, thank you.
