### ISSUE TITLE
indcit.com - anti copy paste

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#330]
**Jenis iklan** (hapus yang tidak perlu)
- Anti right click

**Sample URL**
https://www.indcit.com/cheat-pb-zepetto/

**Penjelasan Lebih Lanjut**
anti copy paste

**Comment by realodix** [comment]
**uBlock**: https://github.com/NanoMeow/QuickReports/issues/2830 (https://github.com/uBlockOrigin/uAssets/commit/7a52f4ec67abd382a268342f6f87eb773e80bbe7)
**AdGuard**: Ping @AdamWr

**Comment by AdamWr** [comment]
Fixed, thank you.
