### ISSUE TITLE
anikyojin.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#331]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://anikyojin.net/plundrr-sub-indo/

**Penjelasan Lebih Lanjut**
||g3938452447.com^$3p
||g2281971609.com^$3p
||g2438896021.com^$3p

dll

**Comment by realodix** [comment]
> ||g3938452447.com^$3p
> ||g2281971609.com^$3p
> ||g2438896021.com^$3p

Hingga hari ini Saya gak nemuin Gan

<details>
  <summary>Screenshot</summary>
  
![cats](https://user-images.githubusercontent.com/1314456/73120719-076d2000-3fa4-11ea-9b71-f7ca5b90fd89.jpg)
  
</details>

**Comment by Recehan-Slayer** [comment]
@realodix coba matiin dlu ublock nya soalnya kmaren dah gw laporin ke quick issue reporter jdinya dah ke block ama ublock filter

**Comment by realodix** [comment]
oh i see, sekarang sudah menemukannya.

Mungkin ada alasannya Gan kenapa gak dimasukkan. Yang Saya temukan, saat ini linknya belum pernah didaftarkan dan bisa kita beli.

**g3938452447.com**
- https://id.godaddy.com/domainsearch/find?checkAvail=1&tmskey=&domainToCheck=g3938452447.com
- https://www.domain.com/registration?__token_timestamp__=1579955669&__token_val__=82dffdadeea72878727ecacf73864fb2&flow=domainDFE&flowid=25&search=g3938452447.com#/domainDFE/1
- https://idwebhost.com/cek-domain/g3938452447.com

**g2281971609.com**
- https://id.godaddy.com/domainsearch/find?checkAvail=1&tmskey=&domainToCheck=g2281971609.com
- https://www.domain.com/registration?__token_timestamp__=1579955401&__token_val__=5d442ea9b28b3f7e98a99fb05b522264&flow=domainDFE&flowid=25&search=g2281971609.com#/domainDFE/1
- https://idwebhost.com/cek-domain/g2281971609.com

**g2438896021.com**
- https://id.godaddy.com/domainsearch/find?checkAvail=1&tmskey=&domainToCheck=g2438896021.com
- https://www.domain.com/registration?__token_timestamp__=1579955737&__token_val__=ecb6a6ed67114c3c98cee1316e568271&flow=domainDFE&flowid=25&search=g2438896021.com#/domainDFE/1
- https://idwebhost.com/cek-domain/g2438896021.com


Berbeda dengan yang sudah masuk easylist, contohnya **g1341551423.com** yang memiliki status "Domain Tidak Tersedia"
- https://id.godaddy.com/domainsearch/find?checkAvail=1&tmskey=&domainToCheck=g1341551423.com
- https://www.domain.com/registration?__token_timestamp__=1579955990&__token_val__=3fef3688d0301d98c3f1d642a6403dec&flow=domainDFE&flowid=25&search=g1341551423.com#/domainDFE/1
- https://idwebhost.com/cek-domain/g1341551423.com

**Comment by realodix** [comment]
Dari yang Saya temukan di atas, sorry Saya tag invalid. Saya rasa tak perlu khawatir, nanti juga akan masuk easylist.
