### ISSUE TITLE
samehadakunettv.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#332]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.samehadakunettv.com/2020/01/black-clover-episode-118.html
https://www.meownimecom.net/2020/01/ahiru-no-sora-episode-16.html

**Penjelasan Lebih Lanjut**
bro ini script 3p safelinknya dah keblock tp kok masi muncul ya?
2 2 nnya itu

**Comment by realodix** [comment]
**Note**
Blockir anti adblock untuk samehadakunettv.com https://cdn.jsdelivr.net/gh/Arlina-Design/quasar@master/arlinablock.js

**Comment by realodix** [comment]
Mungkin linknya dibuat secara manual kali, bukan link manipulator. Saya cari-cari, gak ngerti juga domain siherp.samehadakunettv.com dan miawmiaw21.blogspot.com itu datengnya darimana?

**Comment by Recehan-Slayer** [comment]
iya masalahnya di log ada 3p script yg keblokir coba ente liat .mungkin sebagian manual tp ada pos yg pke 3p

**Comment by realodix** [comment]
Iya sebelumnya Saya sudah liat Gan, kemungkina ini server-side. Blokir 3p script hanya bisa untuk client-side, dengan diblokir dia akan berubah jadi bentuk asli yang dikirim server.

Anti klik kanan karena client side, kita bisa akali dengan `meownimecom.net##+js(acis, redirectCU)`
