### ISSUE TITLE
Safelink

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#336]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
```
https://github.com/aalfiann/safelink-jquery/blob/master/src/safelink.js
https://github.com/ZerosDev/ZSE-Safelink-JS/blob/master/ZSE.min.js
https://github.com/CandraBlackz/legitlink/blob/master/jquery.pietimer.js
https://github.com/asto1/javascript-safelink
https://github.com/renigit99
https://github.com/mascholis
https://github.com/comenxnet
https://github.com/raflipedia
https://gist.github.com/cekfolder
https://github.com/asto1
https://github.com/IMHN


```
**Penjelasan Lebih Lanjut**
repo safelink
itu gan banyak sekali contoh untuk bikin general filter safelink.js dan safelink_utama.js 
sama request buatkan button subscribe filter di readme  gan biar gmpang klo orang mau make filternya

**Comment by realodix** [comment]
Thank you untuk laporannya. Tidak semuanya Saya tambah.

> https://github.com/aalfiann/safelink-jquery/blob/master/src/safelink.js

Ini NPM, kemungkinan kecil untuk dipanggil mandiri. Gak bisa diblokir jika dibundle munggunakan Laravel Mix atau semacamnya.

> https://github.com/ZerosDev/ZSE-Safelink-JS/blob/master/ZSE.min.js

Dari readmenya, kemungkina kecil untuk dipanggil mandiri dengan CDN. Gak bisa diblokir jika dibundle munggunakan Laravel Mix atau semacamnya.

> https://gist.github.com/cekfolder

Kemungkinan kecil untuk dipanggil mandiri dengan CDN. Saya coba hanya compatible di githack.com, sisanya tidak.

> https://github.com/IMHN

Saya tidak menemukan. Adanya NihLink-Safelink-Template-Blogger, sebuat template safelink, bukan file mandiri.

> https://github.com/comenxnet

Terlalu banyak banget. Saya hanya blockir yang baru mereka maintain, sisanya sudah terlihat usang.

**Comment by realodix** [comment]
> sama request buatkan button subscribe filter di readme gan biar gmpang klo orang mau make filternya

Coba buat di https://adblockplus.org/en/abp_linkfactory, gak bisa working linknya.

Lalu saya coba copas dari link pada https://filterlists.com/lists/adblockid, gak bisa diklik
<a href="abp:subscribe?location=https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt&amp;title=AdBlockID">
    Subscribe
</a>

```html
<a href="abp:subscribe?location=https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt&amp;title=AdBlockID">
    Subscribe
</a>
```
Mungkin agan bisa bantu

**Comment by Recehan-Slayer** [comment]
@realodix coba itu gan `<a href="https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt&amp;title=AdBlockID" rel="nofollow">Subscribe</a>`

**Comment by realodix** [comment]
Saya coba klik bukannya muncul popup, malah selalu ke halaman ini https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt&title=AdBlockID

**Comment by Recehan-Slayer** [comment]
pdhal sama kyk yg ini `https://github.com/NanoAdblockerLab/NanoContrib` dan filter abpindo
coba ente lihat codenya ane ga begitu paham tentang bhs pemrograman.

**Comment by Recehan-Slayer** [comment]
@realodix keknya masalahnya di ubo aja deh bro coba pke adblocker lain bisa tuh keknya gpp pasang aja.
`https://github.com/uBlockOrigin/uBlock-issues/issues/763`

**Comment by Recehan-Slayer** [comment]
@realodix  ini bisa brow <a href="https://subscribe.adblockplus.org/?location=https://gitcdn.xyz/repo/realodix/AdBlockID/master/output/adblockid.txt&amp;title=AdBlockID" rel="nofollow">Subscribe</a>

**Comment by Recehan-Slayer** [comment]
@realodix atau ini bro???
<a href="https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/realodix/AdBlockID/master/output/adblockid.txt&amp;title=AdBlockID" rel="nofollow">subscribe</a>

**Comment by Recehan-Slayer** [comment]
https://github.com/daimonz01/Aman_DN

**Comment by realodix** [comment]
Thank you
