### ISSUE TITLE
shrink.world

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#339]
**Jenis iklan** (hapus yang tidak perlu)
- Fake button

**Sample URL**
http://www.shrink.world/R3w1r2ah

**Penjelasan Lebih Lanjut**
fake button setelah mengisi captcha pas countdown

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
ini jg ada `https://www.shrinkads.com/VfRfRp`
tpi dah masuk ke ubo filter sih

**Comment by realodix** [comment]
> ini jg ada `https://www.shrinkads.com/VfRfRp`
> tpi dah masuk ke ubo filter sih

Mengarah ke modebaca.com ya?
- Fake button sudah Saya commmit kemarin https://github.com/realodix/AdBlockID/commit/32059b9ec18b6133609e049e6c0fb5b4d8b4d51e
- Anti adblock baru aja dicommit.

Thank you Gan

**Comment by Recehan-Slayer** [comment]
domain baru sportif.id anti adblock popups sama fake button
`https://www.shrink.world/y0nhHW`

**Comment by realodix** [comment]
> domain baru sportif.id anti adblock popups sama fake button
> `https://www.shrink.world/y0nhHW`

Thank you
