### ISSUE TITLE
ouo.io 3d party script

### ISSUE THREAD

**Issue by KagaKouko99** [realodix/AdBlockID#34]
https://yukisubs.com/arifureta-shokugyou-de-sekai-saikyou-episode-09/

https://cdn.ouo.io/js/full-page-script.js

**Comment by realodix** [comment]
Kenapa ini perlu ditambahkan? Saya lihat ini sudah ada di [easylist](https://github.com/easylist/easylist/blob/c44a5fe788da4dd832a4ee33aeb2dd9245e45a4b/easylist/easylist_thirdparty.txt#L1405)

**Comment by KagaKouko99** [comment]
oh ini cuman pelengkap easylist doang tah.

**Comment by realodix** [comment]
> oh ini cuman pelengkap easylist doang tah.

Bener banget, seperti yang Saya tulis di [readme](https://github.com/realodix/AdBlockID/blob/master/README.md#adblockid) 

> AdblockID adalah filter tambahan untuk melengkapi [EasyList](https://github.com/easylist/easylist) dan [AdGuard Base Filter](https://github.com/AdguardTeam/AdguardFilters)

Jika salah satu dari mereka tidak ada, itu perlu untuk ditambahkan. Biasanya di AdGuard yang gak lengkap, tapi tumben terakhir cek di mereka ouo.io ada jg.
