### ISSUE TITLE
ganoolmovie.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#344]
**Jenis iklan** (hapus yang tidak perlu)
- ghide

**Sample URL**
https://ganoolmovie.com/

**Penjelasan Lebih Lanjut**
ada situs judi yg blom masuk filter bro sebagian sudah

sama nnya bro klo ngilangin main popup disitus ini pke filter apa bro
`https://dunialkc21.com/film-semi-nomat21-sachiko/`

**Comment by realodix** [comment]
Thank you

> sama nnya bro klo ngilangin main popup disitus ini pke filter apa bro
> `https://dunialkc21.com/film-semi-nomat21-sachiko/`

Saya gak nemui pop-up, jadi bingung juga kasih contohnya.
Agan bisa coba filter ini `*$popup,domain=dunialkc21.com`

**Comment by Recehan-Slayer** [comment]
@realodix mksudnya empty ads placeholder yg transparan bukan popup open newtab

**Comment by realodix** [comment]
`dunialkc21.com##+js(aopr, $.magnificPopup.open)`
