### ISSUE TITLE
mangareceh.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#346]
**Jenis iklan** (hapus yang tidak perlu)
- Overlay

**Sample URL**
https://mangareceh.id/

**Penjelasan Lebih Lanjut**
overlay join discrot

mw nnya klo paywall trmasuk scope jg ga bro?

**Comment by realodix** [comment]
> mw nnya klo paywall trmasuk scope jg ga bro?

Maksudnya gimana Gan?

**Comment by Recehan-Slayer** [comment]
Paywall kek misalnya kita hrs berlangganan atau bayar klo mw baca lihat suatu halaman file dll. Contoh situs patreon. situs" berita dll

**Comment by realodix** [comment]
> Paywall kek misalnya kita hrs berlangganan atau bayar klo mw baca lihat suatu halaman file dll. Contoh situs patreon. situs" berita dll

Mohon maaf, nggak Gan
