### ISSUE TITLE
premierexxi.org

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#350]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://premierexxi.org/movie/journey-to-the-west-conquering-the-demons-2013/

**Penjelasan Lebih Lanjut**
banner iklan

**Comment by realodix** [comment]
Berhubungan dengan https://github.com/realodix/AdBlockID/issues/184

---

Thank you
