### ISSUE TITLE
wartaekonomi.co.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#354]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://m.wartaekonomi.co.id/berita253124/kurangi-penggunaan-gas-kehadiran-kompor-listrik-digenjot

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Thank you
