### ISSUE TITLE
inidramaku.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#355]
**Jenis iklan** (hapus yang tidak perlu)
- Overlay

**Sample URL**
https://inidramaku.com/download-drama-korea-forest-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
Overlay

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
anime-indo.id,drakorindofilms.tv,inidramaku.com,kingdrakor.com###fixedban

**Comment by realodix** [comment]
> anime-indo.id,drakorindofilms.tv,inidramaku.com,kingdrakor.com###fixedban

Thank you
