### ISSUE TITLE
drakorindo-tv.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#357]
**Jenis iklan** (hapus yang tidak perlu)
- script

**Sample URL**
https://drakorindo-tv.com/extraordinary-you/

**Penjelasan Lebih Lanjut**
https://cemiw.net/safelinks.js

**Comment by realodix** [comment]
**Note**
Berhubungan dengan https://github.com/realodix/AdBlockID/issues/237

---

Thank you
