### ISSUE TITLE
dramakrsubindo.blogspot.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#358]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://dramakrsubindo.blogspot.com/2019/05/drama-korea-0n-pring-nght-subtitle.html

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Saya gak ngerti maksudnya gimana?

**Comment by Recehan-Slayer** [comment]
popup

**Comment by realodix** [comment]
Trigger pop-upnya apa ya? Dari tadi gak ada apa2

**Comment by Recehan-Slayer** [comment]
udah masuk ke ublock tadi

**Comment by Recehan-Slayer** [comment]
triggernya klik sembarang

**Comment by realodix** [comment]
Klik apa ya? Ini logger Saya cuma segini, gak ada apa2.

<details><summary>Configurasi Filter </summary>

- uBlock filters – Badware risks
- uBlock filters – Privacy​​​​​
- uBlock filters – Resource abuse​​​​​
- uBlock filters – Unbreak​​​​​
- EasyList​​​​​
- EasyPrivacy​​​​​
- Malware domains​​​​​
- uBlock filters – Annoyances​​​​​
- AdBlockID
- AdBlockID Plus
</details>

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +1 | .net/s.gif? | -- | dramakrsubindo.blogspot.com | 3 | image | `https://eventping-a.akamaihd.net/s.gif?_&t=dau&channel=1000-1000&subid=&uid=4204c7f1a28b375f682add5ef007e350&_cb=1580421886526` |
| +1 | .net/s.gif? | -- | dramakrsubindo.blogspot.com | 3 | image | `https://eventping-a.akamaihd.net/s.gif?_&t=dau&channel=1000-1000&subid=&uid=4204c7f1a28b375f682add5ef007e350&_cb=1580421886525` |
| +1 | \|\|pagead2.googlesyndication.com^$script | -- | dramakrsubindo.blogspot.com | 3 | script | `https://pagead2.googlesyndication.com/pagead/js/google_top_exp.js` |
</details>

**Comment by Recehan-Slayer** [comment]
![Untitled11](https://user-images.githubusercontent.com/9379770/73494994-3e9a6180-43e8-11ea-88b3-739a0bd27a3c.png)

klik di sembarang tempat tapi kadang walupun ga klik juga muncul coba clear cookies cahce

**Comment by realodix** [comment]
Asli Gan gak ada apa2. Buka di browser yang jarang banget dipake + clear segala macem, gak ada apa2. Coba deh buka di browser yang gak agan pake.

**Comment by Recehan-Slayer** [comment]
`https://github.com/uBlockOrigin/uAssets/commit/e020e75f28c2c25ae8197849e9aaab427417e27f`

**Comment by Recehan-Slayer** [comment]
Ntah knp ko bisa beda" gtu.

**Comment by realodix** [comment]
Gak ngerti juga deh kenapa, tapi masuk uAssets ya. Sorry ya ditutup.
