### ISSUE TITLE
filmdramakorea.my.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#361]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
http://www.filmdramakorea.my.id/drama-korea-pinocchio-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
http://l.forek.info/safelink.js

**Comment by realodix** [comment]
**Note**
Berhubungan dengan https://github.com/realodix/AdBlockID/issues/237

---

Thank you
