### ISSUE TITLE
kompas.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#364]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://www.kompas.com/

**Penjelasan Lebih Lanjut**
Banner iklan gramedia

coba cek di topsitesID alexa gan bnyak yg masi blom masuk

**Comment by realodix** [comment]
Yang ini?

![cats](https://user-images.githubusercontent.com/1314456/73504116-de63e980-4400-11ea-9af9-f0d333ecf667.jpg)

**Comment by Recehan-Slayer** [comment]
Iya itu trmsuk kan??

**Comment by realodix** [comment]
Mengingat mereka 1 group https://www.kompasgramedia.com/brand, harusnya sih masuk iklan produk sendiri di website sendiri.

Sorry Gan Saya tag invalid
