### ISSUE TITLE
grid.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#365]
**Jenis iklan** (hapus yang tidak perlu)
- Ads

**Sample URL**
https://www.grid.id/

**Penjelasan Lebih Lanjut**
kasusnya sama seperti kompasiana

**Comment by realodix** [comment]
AdGuard Annoyances `/^https?:\/\/[^\/]+\.[^\/]+\/[a-zA-Z0-9]{32,}$/$script,1p,domain=`

ping @AdamWr
