### ISSUE TITLE
id.vpnmentor.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#366]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://id.vpnmentor.com/blog/top-10-situs-web-torrent/

**Penjelasan Lebih Lanjut**
ads

**Comment by realodix** [comment]
Sorry dimananya Gan?

**Comment by Recehan-Slayer** [comment]
iklan vpn sebelah kiri

**Comment by realodix** [comment]
Promo VPN Terbaik?

**Comment by Recehan-Slayer** [comment]
iya yg nord vpn dll

**Comment by realodix** [comment]
Ini sebenernya situs international, scopenya Saya kecilkan ke region indo, jadi hanya di id.vpnmentor.com yang Saya hilangkan.

Thank you
