### ISSUE TITLE
kingdrakor.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#367]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://kingdrakor.com/drama-korea-forest-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Thank you
