### ISSUE TITLE
[problem] neonime.org

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#368]
**Sample URL**
https://neonime.org/episode/infinite-dendrogram-1x4/

**Penjelasan Lebih Lanjut**
link download hilang krn filter di adblockid+

**Comment by realodix** [comment]
Owh ya ampun, pencegahan auto safelinknya bikin semuanya jadi kena.

Thank you, sudah Saya benerin.

**Comment by Recehan-Slayer** [comment]
mereka udah gnti kesoralink wordpress plugin bro yg di neonime

**Comment by realodix** [comment]
waduh dari ciri-cirinya mereka pakai hardcode lagi
