### ISSUE TITLE
kazefuri.web.id

### ISSUE THREAD

**Issue by KagaKouko99** [realodix/AdBlockID#37]
Iklan ada yang masih belum terblokir

![Annotation 2019-09-27 101048](https://user-images.githubusercontent.com/54178411/65739590-028c8280-e110-11e9-826a-cdddc8355eae.png)

**Comment by RaveN0X87** [comment]
@realodix masih ada iklan judi yg ketinggalan dibagian atas
update please

**Comment by WaferNabati** [comment]
@realodix update dong masih ada iklannya

**Comment by WaferNabati** [comment]
@realodix https://kazefuri.web.id/wonderland-s3-ep-9/
update iklan judi
