### ISSUE TITLE
mmsubs.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#371]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://mmsubs.com/

**Penjelasan Lebih Lanjut**
Banner ads

**Comment by Recehan-Slayer** [comment]
klo placeholder yg ada tulisan tolong matikan adblock dll bnyak bgt bro disitus" download/streaming anime

**Comment by Recehan-Slayer** [comment]
http://animekompi.web.id/
`animekompi.web.id##.left`

**Comment by realodix** [comment]
Thank you

> klo placeholder yg ada tulisan tolong matikan adblock dll bnyak bgt bro disitus" download/streaming anime

Sudah dihilangkan

**Comment by Recehan-Slayer** [comment]
@realodix klo safelink yg model gini bisa ga di decrypt ama scriplet uBo gan???
`https://www.adtival.network/full/?api=dbbe0df41fefb5869d22614b8ac803a2953a1bbc&url=aHR0cHM6Ly9hY2VmaWxlLmNvL2YvMTc3NTkxMDYvZG9yYW1haW5kby1pZC1rYXJlcmEtd28tbWlyZWJhLXdha2FydS1rb3RvLWVwMDMtMzYwcC1yYXI=&type=2`

**Comment by realodix** [comment]
Minta sumbernya Gan. Saya gak bisa pastiin, harus Saya check dulu.

**Comment by Recehan-Slayer** [comment]
`https://doramaindo.id/karera-wo-mireba-wakaru-koto-subtitle-indonesia.html`

**Comment by Recehan-Slayer** [comment]
biasanya klo pke 3p script bntuknya jg gtu gan dr adtival network safelinku dll
tpi yg itu digenerate secara manual kira" bisa ga itu

**Comment by realodix** [comment]
Mereka tidak menggunakan ini untuk manipulasi URLnya
- https://www.wts.pw/js/full-page-script.js
- https://www.adtival.network/js/full-page-script.js

Kemungkinan besar ini hardcode (generate secara manual), kalau seperti ini tidak bisa.

**Comment by Recehan-Slayer** [comment]
ohh ok tp klo pke UB bisa gan. kirain bisa jg pke scriptlet uBo

**Comment by realodix** [comment]
Setahu Saya beda deh cara kerjanya
- **UB**: Tetap masuk ke safelink, tapi langsung dilewati tahapan yang ada di safelink.
- **uBlock**: Tidak masuk ke safelink sama sekali, langsung ke URL tujuan.

**Comment by Recehan-Slayer** [comment]
ga gan itu langsung ketujuan ga masuk kesafelink kecuali yg bentuknya begini baru masuk safelink dlo
`https://autoratio.com/PeiXXEkF `
yg ada api" nya lngsung di decrypt ke tujuan sma UB

**Comment by realodix** [comment]
Owh gitu, canggih juga ya sekarang bisa auto decrypt. Udah lama gak pakai UB, karena gak kelihatan safelinknya kena anti-adblock atau gak haha

Ada contoh linknya gak gan yang auto decrypt, jadi kepo juga

**Comment by Recehan-Slayer** [comment]
bnyak bro ente kan programmer intip aja codenya kan source code gw g begitu paham tntang bahsa pemrograman.
ni salah satu contoh aja. yg baru ditmbahkan
https://www.bursadrakor.com/protect-link/aHR0cHM6Ly93d3cubWlycm9yZWQudG8vZmlsZXMvR1cxSDRLRVkvW0J1cnNhZHJha29yLmNvbV1fVy5PLjkuOS5CLkVwMzEtMzIuRU5ELig3MjBwKS5ta3ZfbGlua3M=
https://boomx5.com/yualvS
bnyak bgt bro lupa gw 
sebenarnya fitur ini udah lama ada namanya preflight bypass. yg ada dibackground script itu bro
`https://github.com/timmyRS/Universal-Bypass/blob/master/background.js`

**Comment by Recehan-Slayer** [comment]
@realodix coba tes safelink dr `https://psarips.org/` auto ke decrypt semua itu

**Comment by Recehan-Slayer** [comment]
https://safelinkgratis.info/7-Tips-Succes-Forex-Trading-Online?link=aHR0cHMlM0ElMkYlMkZ1cHRvYm94LmNvbSUyRjhwajE3MjJreTMxcQ==
https://netijenshare.com/safeme/?5dbfcf0bd205d=OGFlMDM0M2YwMjUzNTQ2ZDVjMjhjNWM4ZmZlYzRmZmQ=&url=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D1BFdrVmurTxJvB7MVbbGgYIBvTEKmpMW8
https://linepc.site/safeme/?5dbfcf0bd204e=YTI3MjliNzc0NmE3ZjA2OWExZDg3YTIxNDFjZjZhZWU=&url=https%3A%2F%2Fracaty.com%2F94r84r2anvq6
https://nurhamka.com/safeme/?5dc3a41a796dc=MjM4NTg2Nzc2NTMwMTYyMjQzODI0MDliNmEzNmFjYWY=&url=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D1zdkM6g7OdHEwg3eJCjSTbq2MYYyXroJx
http://ryukanime.lompat.in/?go=0OoL1HM6Ly91c2Vyc2Nsb3VkLmNvbS84YnBtOGQ0ZWR3cjk=
http://st.loncat.in/1cgq
dll

**Comment by realodix** [comment]
Thank you Gan untuk contoh linknya, tapi sorry sepertinya ada kesalahpahaman disini.

Seperti yang Saya bilang di atas.
> Setahu Saya beda deh cara kerjanya
> * **UB**: Tetap masuk ke safelink, tapi langsung dilewati tahapan yang ada di safelink.
> * **uBlock**: Tidak masuk ke safelink sama sekali, langsung ke URL tujuan.


Sebagai contoh seperti di #250 https://maniak21.com/the-informer/
- **UB**: Dari https://maniak21.com/the-informer/, Kita tetap akan masuk ke safelink [https://jurnalwibu.com/?r=aHR0cHM...lhmZUEv](https://jurnalwibu.com/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xbGZNOTlLb3JRMUVvN081U0trQWV1b2VHUGdRblhmZUEv), lalu kemudian di-bypass ke [https://drive.google.com/file/d/1lfM99K...gQnXfeA](https://drive.google.com/file/d/1lfM99KorQ1Eo7O5SKkAeuoeGPgQnXfeA/)
- **uBo**: Dari https://maniak21.com/the-informer/, langsung ke [https://drive.google.com/file/d/1lfM99K...gQnXfeA](https://drive.google.com/file/d/1lfM99KorQ1Eo7O5SKkAeuoeGPgQnXfeA/)

**Comment by Recehan-Slayer** [comment]
iya klo uBO kan emg diblock dr website downloadnya jdi yg ditampilin langsung link filehostingnya.
iya gan tp safelinknya kn ga smpe kebuka sama sekali. iya mungkin emg beda cara kerjanya gw ga begitu paham😅 sorry.
yg gw mksud ga masuk safelinknya itu ga ngeload sama sekali langsung didecrypt ketujuan.
lebih gud ya pake smua gan 🤣.
ya ente kan maintainer klo pke UB pas mw ngetes ato hunting yah ga nemu anti adblock adserver dll gan disafelinknya 🤣

**Comment by ikancupang** [comment]
Permisi, ikut nimbrung ya, UB bisa kok blokir 3rd party safelink script seperti Ad Blocker dengan menggunakan `background.js`.
Kalau mau, coba aja alfan request ke Owner UB, cara kerjanya mirip seperti preflight bypass, bedanya kalau preflight bypass yang diblok typenya adalah `main_frame`, tapi kalau blokir 3rd party safelink script yang diblock typenya adalah `script`.

**Comment by Recehan-Slayer** [comment]
Tp itu yg soralink yg /?r= uda masuk bro ke UB. klo semisal block 3p script hrs 1 1 ato bisa general sprti filternya adblocker. weh bisa tau nma gw😅 lihat dr email gw nih.

**Comment by ikancupang** [comment]
bisa general, contohnya `"*://*/js/full-page-script.js"`

**Comment by Recehan-Slayer** [comment]
Coba ente aja bro yg request. Ato lngsung ditmbahkan aja kn ente jg maintainernya jg disitu. Yg pnting yg /js/full-page-script.js wp-content/plugin/soralink ama /wpsafelink.js 3 itu aja gan yg pling pnting soalnya bnyak bgt diwebsite" indo maupun luar yg pke itu bro. Terutama yg js/full-page-script.js

**Comment by realodix** [comment]
Bener banget, perpaduan uBo dan UB bener-bener bikin puas deh. Iklan bersih, safelink nya juga gak puyeng tunggu waktu. Thank you untuk yg buat plugin nya

**Comment by Recehan-Slayer** [comment]
@ikancupang bro sepertinya yg soralink wordpress plugin yg ini
`https://github.com/timmyRS/Universal-Bypass/commit/2846a329754e550dfe6353f8c03e0b76ea4ebcbe`
mereka menggenerate ID linknya tidak langsung. mungkin bisa diatur waktunya ntah brp jam/hari.
jdi percuma klo yg dicontribute ke crowd source ID linknya yg didepan soalnya gw liat barusan link nya gnti dalam beberapa hari mungkin ini cara jg buat mengelabuhi UB yg pke crowd bypass.
sebagai contohnya
`https://github.com/timmyRS/Universal-Bypass/issues/790`
link yg pertama 720p mirror
link yg ke 2 720p drive
trus coba bandingin IDnya sama yg didalam websitenya
`https://www.conan.id/sword-art-online-alicization-war-of-underworld-episode-12-subtitle-indonesia/` udah berubah.

jdi kemungkinan smua soralink plugin yg dr themesia yg versi paling terbaru itu IDnya berubah" entah itu secara langsung saat direfresh atau dalam beberapa jam/hari/minggu.

**Comment by ikancupang** [comment]
@Recehan-Slayer Ya benar, mereka menggenerate ID linknya tidak langsung, pengaturan waktunya tergantung dari si pemilik website, untuk website soralink yang tidak terlalu populer saya lagi tidak tertarik membuat metode bypassClipboard :)
kalau websitenya cukup populer seperti `oploverz.in` mungkin akan saya buatkan metode bypassClipboard.
napa jadi bahas UB disini :D

**Comment by Recehan-Slayer** [comment]
@ikancupang haha ok gan sorry cmn ngasi info aja :) . iya gan yg pnting yg site populer aja sprti pahe oploverz dll
contoh link yg diatas itu website yg ga populer klo bisa tmbahin 1 ini aja gan
`https://drivenime.com/` itu lumayan populer di alexa rank 999 diindo.

**Comment by ikancupang** [comment]
Untuk drivenime sepertinya mereka selalu memantau UB, karena dulu saat saya masih belum mengenal UB saat mencoba download dari drivenime malah muncul pesan `"Mo Bypass? Wooo, Tidak semudah itu fergusso, silahkan dimatikan Universal Bypass nya"`, sehingga jika dibuatkan bypass, mereka akan buru-buru merubah website mereka, seperti saat ChikaRuraSafe terbypass mereka langsung dengan cepat ganti ke SoraLink.

**Comment by Recehan-Slayer** [comment]
haha iya jg sih gan apalagi open source. seperti web jouganime(shirosafe.web.id) mereka pantau terus repo UB. beberapa menit setelah dibuat bypass nya mereka lngsung gnti kode situsnya. repot jg sih main kucing"an hahah 😅
barusan tdi aja ama owner UB udah diperbarui trus skrng udah ga work lg 😅

**Comment by realodix** [comment]
> @Recehan-Slayer sorry mas realodix OOT
> @ikancupang napa jadi bahas UB disini :D

Gak apa-apa Gan. Menurut Saya ketika terjadi OOT, yang dirugikan itu yang membuat issue. Karena pembahasan masalah yg dia mereka ajukan jadi melenceng. Lah ini kan yg bikin jadi OOT yang buat isuee sendiri haha

**Comment by Recehan-Slayer** [comment]
@ikancupang bro itu tlong tmbahin ada 1 situs populer rank 600an di alexa `neonime.org`

**Comment by ikancupang** [comment]
Peringkatnya masih kalah jauh sama oploverz :)

**Comment by Recehan-Slayer** [comment]
ya jelas lah bro oploverz fansub legend dr zaman kapan itu udah lama trkenal krn ngesub wanpis. klo neonime cmn reshare doang dr berbagai fansub dan fastsub.

**Comment by Recehan-Slayer** [comment]
@ikancupang bro yg di neonime mereka gnti kode captcha atau site key mungkin ga paham yg sehabis ? ke `940caec1dc`

**Comment by Recehan-Slayer** [comment]
@ikancupang bro mau nanya. klo di HP android klo pake browser kiwi atau yandex kenapa ada beberapa bypass yg tidak bekerja terutama yg dibackground yg preflight bypass pdhal kan dr chromium. apa harus ada settingan tmbahan atau emg ga kompatibel?

**Comment by ikancupang** [comment]
Browser kiwi menggunakan mesin chromium tapi sudah dimodifikasi, sehingga cara kerjanya sudah tidak sama lagi dengan google chrome, akibatnya UB ga kompatibel dengan kiwi, kalau di android disarankan pakai Firefox, karena Browser yang di support UB adalah Google Chrome (Desktop), Mozilla Firefox, dan Microsoft Edge.

**Comment by Recehan-Slayer** [comment]
@ikancupang bro ini rankingnya tinggi di india `https://katmoviehd.nl/` tpi terserah sih mw ditambahin atau engga

**Comment by ikancupang** [comment]
soralink sampe ke india juga ya?

**Comment by Recehan-Slayer** [comment]
ya makanya diweb docsnya skrng ada pilihan bhs inggrisnya kan bro dlo perasaan ga ada deh pilihan bahasa inggrisnya.  dan dichangelognya diubah ke inggris smua dlo indo.

**Comment by Recehan-Slayer** [comment]
@ikancupang bro ini bdzone.xyz `https://github.com/timmyRS/Universal-Bypass/issues/717` sama kasusnya seperti `https://github.com/timmyRS/Universal-Bypass/issues/935`
sepertinya mereka mendeteksi jika ada orang yang mengarah secara langsung. tpi klo nunggu 10 detik ga terdeteksi.

**Comment by ikancupang** [comment]
Sepertinya berbeda.

**Comment by Recehan-Slayer** [comment]
ohh iya mungkin gan ga begitu paham. tdi malem udah work tpi commitmu direvert ama owner ub gan jdinya ga work lg sekarang kro mengarah ke bdzone. ada muncul popup terdeteksi.

**Comment by Recehan-Slayer** [comment]
ohh iya mungkin gan g begitu paham soalnya kadang muncul popup terdeteksi tpi klo nunggu beberapa detik ga muncul bisa ngelewati bdzone.

**Comment by Recehan-Slayer** [comment]
@ikancupang bro safelink dr situs ini `https://meownime.me/made-in-abyss-movie-3-fukaki-tamashii-no-reimei/` scam atau bukan soalnya ga bisa dilewatin

**Comment by ikancupang** [comment]
Scam, semua postingan isi linknya sama, bisa dicek dengan membandingan link pada setiap postingan, misalnya `https://meownime.me/goblin-slayer-goblins-crown/`.

**Comment by Recehan-Slayer** [comment]
@ikancupang bro di `pahe.in` mereka uda gnti lgi linknya. dan gw coba di device yg berbeda ID nya berubah dan bisa muncul random link nya antara intercelestial dan sweetlantern. tpi klo di refresh di 1 device tetep sama ga berubah.

**Comment by realodix** [comment]
@ikancupang Gak bisa download file, langsung redirect ke home

https://www.filehorse.com/download-malwarebytes-anti-malware/

**Comment by ikancupang** [comment]
@realodix Tolong buat issue pada repo UB, supaya referensi bisa langsung ke issue UB.

**Comment by ikancupang** [comment]
@realodix Bug pada filehorse.com sudah diperbaiki, terima kasih laporannya.

**Comment by Recehan-Slayer** [comment]
@ikancupang bro di oploverz.in mereka gnti skrng yg berubah IDnya travellinginfos

**Comment by ikancupang** [comment]
Sekarang `https://travellinginfos.com/?id=` IDnya berubah-ubah setelah pakai `https://rujit.com/?r=` ?
saat pakai `https://kontenajaib.xyz/?id=` ID dari travellinginfos.com tidak berubah-ubah.

**Comment by Recehan-Slayer** [comment]
iya itu bro perbedaanya yg berubah" ditaroh di safelink yg kedua. yg kmaren kan yg berubah ditaroh di yg prtama. bntar gw SS in

**Comment by Recehan-Slayer** [comment]
@ikancupang iya bro bedanya yg berubah ditaroh disafelink yg ke2 nah masalahnya orang yg g pke adblocker kn yg kliatan rujin duluan nah itu btw bypass clipboard bisa aktif ato ga. klo ga brarti safelink yg prtama hrs diblock pke UB jg.


ini contoh dilink yg sama 720p 10 bit zippyshare
<details>

![oploverz1](https://user-images.githubusercontent.com/9379770/75085794-52f0fa80-555f-11ea-9405-604536f6b42a.png)
</details>
setelah direfresh
<details>

![oploverz2](https://user-images.githubusercontent.com/9379770/75085815-951a3c00-555f-11ea-954b-75767809cf14.png)
</details>

**Comment by ikancupang** [comment]
UB harus blokir `https://rujit.com/?r=` supaya nampilin `https://travellinginfos.com/?id=` ya?
Ok.

**Comment by Recehan-Slayer** [comment]
@ikancupang gan di pahe ada beberapa tipe button download yg bypassclipboard nya ga work.
`https://pahe.in/kung-fu-hustle-2004-bluray/` `https://pahe.me/kung-fu-hustle-2004-bluray/`
`https://pahe.in/riverdale-season-4-nf-dl/` `https://pahe.me/riverdale-season-4-nf-dl/`

**Comment by Recehan-Slayer** [comment]
@ikancupang bro yg di pahe.in/me mereka gnti lgi safelinknya. klo yg di oploverz ntah itu IDnya statik atau dinamik domain yg barunya.

**Comment by ikancupang** [comment]
ok

**Comment by Recehan-Slayer** [comment]
@ikancupang ada 2 versi bro sebagian post yg tnggal 8 maret 2020 kebawah masih pake yg sebelum diupdate 
```
https://pahe.me/the-grudge-2020/
https://pahe.me/sonic-the-hedgehog-2020/
https://pahe.me/ne-zha-2019-bluray-480p-720p-1080p/
```

**Comment by Recehan-Slayer** [comment]
ehh ternyata bisa berubah" bro ga hanya yg postan lama aja.
disetiap postinganya awalnya pke ?id= terus berubah ke ?c4871c3e35= kemudian balik lagi.
mungkin bisa diatur settingan rentang waktu berubahnya.

**Comment by realodix** [comment]
**Update**
Safelink sudah hilang
