### ISSUE TITLE
downloadbatch.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#375]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Lainnya

**Sample URL**
http://www.downloadbatch.com/

**Penjelasan Lebih Lanjut**
situs judi ama placeholder gan

**Comment by realodix** [comment]
**Related** https://github.com/realodix/AdBlockID/issues/25

---

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix ada yg baru lagi bro

**Comment by realodix** [comment]
> ada yg baru lagi bro
> link99
> cangkal

Thank you

**Comment by Recehan-Slayer** [comment]
94.237.68.227
94.237.66.100
ada situs judi yg baru lg

**Comment by realodix** [comment]
> 94.237.68.227
> 94.237.66.100
> ada situs judi yg baru lg

Thank you

**Comment by Recehan-Slayer** [comment]
4 situs judi baru

**Comment by realodix** [comment]
> 4 situs judi baru
> 
> ```
> http://94.237.75.96/
> http://94.237.79.94/
> http://94.237.65.107/
> https://prediksibola88.net/
> ```

Thank you
