### ISSUE TITLE
rekonime.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#376]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://rekonime.com/2019/10/man-with-a-mission-dark-crow-mp3/

**Penjelasan Lebih Lanjut**
`https://st-n.pc3ads.com/js/a.js` 
ntah ini trmasuk 3p ads jg ga kurang yakin gan

**Comment by realodix** [comment]
```js
// https://rekonime.com/2019/10/man-with-a-mission-dark-crow-mp3/

(sc_adv_out = window.sc_adv_out \|\| []).push({
    id : "616211",
    domain : "n.pc3ads.com"
});
```

> https://st-n.pc3ads.com/js/a.js

Dari kodenya sih ada banyak `_adv_`, seperti iklan

**Comment by realodix** [comment]
Thank you
