### ISSUE TITLE
doujindesu.ch

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#379]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://www.doujindesu.ch/

**Penjelasan Lebih Lanjut**
`https://rawcdn.githack.com/KecoaTerbank/safelink/9530efb06c5124104e2bdedb012a90ed4e06782b/full-page-script.js`

**Comment by realodix** [comment]
**Related** https://github.com/realodix/AdBlockID/issues/122

**Comment by realodix** [comment]
Anti-Adblock tidak jadi didukung karena mengandung content dewasa

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
di gw ga ada anti adblocknya gan. mungkin gegara ublock protector.
tpi klo bisa situs yg bnyak pengunjung nya tmbahin ke adblock+ wlupun itu situs dewasa.

**Comment by Recehan-Slayer** [comment]
https://www.doujindesu.cc/

masi belum keblock brow
`https://rawcdn.githack.com/KecoaTerbank/safelink/9530efb06c5124104e2bdedb012a90ed4e06782b/full-page-script.js`

**Comment by realodix** [comment]
> https://www.doujindesu.cc/
> 
> masi belum keblock brow
> https://rawcdn.githack.com/KecoaTerbank/safelink/9530efb06c5124104e2bdedb012a90ed4e06782b/full-page-script.js

Thank you
