### ISSUE TITLE
deku.zonawibu.cc

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#380]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://deku.zonawibu.cc/

**Penjelasan Lebih Lanjut**
`https://zonawibu.me/data/ngentod.js`

**Comment by realodix** [comment]
Ini apa ya?

**Comment by Recehan-Slayer** [comment]
ntah apa keknya anti copas template mungkin tpi difilter indo lain diblock itu

**Comment by realodix** [comment]
> ntah apa keknya anti copas template mungkin tpi difilter indo lain diblock itu

Ini ya? ABPindo latest version 202002020155
- [ABPindo/indonesianadblockrules/src/advert/specific_block.txt#L266](https://github.com/ABPindo/indonesianadblockrules/blob/dfab8e4758db57945b9f2fb5a9aac2801710ac2e/src/advert/specific_block.txt#L266)

Pertama kali ditambahkan pada [ABPindo/indonesianadblockrules@b963087#diff-eb3c376](https://github.com/ABPindo/indonesianadblockrules/commit/b963087592cc8512ad72521cb165505be32efdfb#diff-eb3c376ea5fa41468c9e0cfa9bb71ac6R230)

Dari historynya ABPindo dan bongkar file https://deku.zonawibu.cc/data/ngentod.js, Saya masih gak paham tentang https://deku.zonawibu.cc/data/ngentod.js kenapa harus diblokir? Saya coba blokir gak ada effect apapun.

**Comment by ikancupang** [comment]
Betul, ini ga ada hubungannya dengan iklan, karena setelah decode `https://zonawibu.me/data/ngentod.js` isinya adalah `console.log('%c GOBLOK!!! OTAK DIPAKE LAH NGENTOD GAk USAH NIRU WEB GW ANJING!!!!','color: red; font-size: 30px; font-weight: bold;');` yang berfungsi menampilkan teks besar berwarna merah pada `"Console"`.
