### ISSUE TITLE
loncatin.keneono.site

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#381]
**Sample URL**
https://loncatin.keneono.site/2018/11/why-bitcoin-investors-should-feel.html?url=aHR0cHM6Ly9naXRodWIuY29tL2RlZGk5Ni9zYWZlbGluay9jb21taXQvY2I3ODdkMDRkZTExZjQyMGU3M2ZhZmI1NWJmOTcwNjJhZWU1Mjk4ZQ==

**Penjelasan Lebih Lanjut**
Ditemukan pada https://github.com/dedi96/safelink/commit/cb787d04de11f420e73fafb55bf97062aee5298e

**Comment by Recehan-Slayer** [comment]
sama ini bro `https://cdn.statically.io/gh/johnali099/gmblc-html/80e79ee1/short1j4.6.9.js`
`gembelcit.net`
