### ISSUE TITLE
anime-indo.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#384]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Overlay

**Sample URL**
https://anime-indo.id/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by realodix** [comment]
Thank you

**Comment by realodix** [comment]
https://github.com/realodix/AdBlockID/issues/403

> **Jenis iklan** (hapus yang tidak perlu)
> 
> * Ads
> 
> **Sample URL**
> https://anime-indo.id/
> 
> **Penjelasan Lebih Lanjut**
> ads
> ![Untitled](https://user-images.githubusercontent.com/9379770/73903193-e91ff200-48ca-11ea-8fe2-98c1dca27729.png)
