### ISSUE TITLE
ganool.wtf

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#389]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Lainnya

**Sample URL**
https://ganool.wtf/

**Penjelasan Lebih Lanjut**
Iklan judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
ganti domain .world

**Comment by realodix** [comment]
Thank you
