### ISSUE TITLE
sukamovie.club

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#390]
**Jenis iklan** (hapus yang tidak perlu)
- Fake button

**Sample URL**
http://sukamovie.club/2020/01/download-terminator-dark-fate-2019-web-dl/

**Penjelasan Lebih Lanjut**
Fake download button

**Comment by realodix** [comment]
Thank you

**Comment by realodix** [comment]
**Related**
- #140

**Comment by realodix** [comment]
Duplicate of #140
