### ISSUE TITLE
angelbatch.web.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#394]
**Jenis iklan** (hapus yang tidak perlu)
- Safelink script

**Sample URL**
https://www.angelbatch.web.id/2019/06/sekaiichi-hatsu-indo.html

**Penjelasan Lebih Lanjut**
`https://rawcdn.githack.com/Purnayasagede/ABSAFE/21e4d6aab6dfe376eb79cbff7e8c7e999901c0f0/ABSafelink.js
`

sama di reponya bnyak

**Comment by Recehan-Slayer** [comment]
https://github.com/realodix/AdBlockID/issues/237

**Comment by realodix** [comment]
**Recent project**
- [Purnayasagede/ABSAFE](https://github.com/Purnayasagede/ABSAFE) - general block `/ABSafelink.$script,third-party`
- [Purnayasagede/NewAngelSafe](https://github.com/Purnayasagede/NewAngelSafe) - repo block
- [Purnayasagede/androixsafe](https://github.com/Purnayasagede/androixsafe) - repo block
- [Purnayasagede/Safelink3](https://github.com/Purnayasagede/Safelink3) - repo block
- [Purnayasagede/Safelink2](https://github.com/Purnayasagede/Safelink2) - repo block
- [Purnayasagede/angelsafe](https://github.com/Purnayasagede/angelsafe) - repo block
- [Purnayasagede/androix](https://github.com/Purnayasagede/androix) - repo block
