### ISSUE TITLE
inonton.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#396]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://www.inonton.com/2020/01/the-standoff-at-sparrow-creek-2018.html

**Penjelasan Lebih Lanjut**
Banner judi
sama popup

**Comment by Recehan-Slayer** [comment]
sama ada beberapa situs judi yg blom masuk

**Comment by realodix** [comment]
Duplicate of #264
