### ISSUE TITLE
Kumpulan Adserver

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#400]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://iindoxxi.online/fantasy-island-2020-2/

**Penjelasan Lebih Lanjut**
||magrie.pw^
||riptukri.net^

**Comment by Recehan-Slayer** [comment]
```
https://negumo.com/anime/ishuzoku-reviewers-sub-indo/
||fandmo.com^
```

**Comment by Recehan-Slayer** [comment]
```
https://www.langitmovie.com/
||grooksom.com^
```

**Comment by Recehan-Slayer** [comment]
```
https://jagomovie.net/gretel-hansel-2020/
||albalbant.com^$third-party

```

**Comment by Recehan-Slayer** [comment]
```
https://indoxx1.page/
||d2wpknqle9nuv8.cloudfront.net^
```

**Comment by Recehan-Slayer** [comment]
```
https://zenomovie.net/uncut-gems-2019/
||mirafaren.pw^
```

**Comment by Recehan-Slayer** [comment]
```
https://www.streamingdrama.id/eps/streaming-the-game-towards-zero-episode-9-10/
||combitly.com^
```

**Comment by Recehan-Slayer** [comment]
```
https://nontonbioskop21.org/
||aspaskaim.club^$third-party
```

**Comment by Recehan-Slayer** [comment]
```
https://duniadrakor.com/
||assandart.site^
```

**Comment by Recehan-Slayer** [comment]
```
https://nontonfilmsemi.net/
https://jusifove.pro/jserr?msg=TypeError%3A%20Failed%20to%20register%20a%20ServiceWorker%20for%20scope%20(%27https%3A%2F%2Fnontonfilmsemi.net%2F%27)%20with%20script%20(%27https%3A%2F%2Fnontonfilmsemi.net%2Fpush-notif_swh.js%27)%3A%20A%20bad%20HTTP%20response%20code%20(404)%20was%20received%20when%20fetching%20the%20script.%0AUrl%3A%20https%3A%2F%2Fnontonfilmsemi.net%2F&ua=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F79.0.3945.130%20Safari%2F537.36&tag=push-self-invocation
```

ini apa gan tracker atau bukan???

**Comment by Recehan-Slayer** [comment]
```
https://galaxyxxi.com/
||areapebeg.club^
```

**Comment by realodix** [comment]
**Domain berubah**
- https://iindoxxi.online -> https://iindoxxi.info

**Ads Server**
> https://iindoxxi.info/fantasy-island-2020-2/
- magrie.pw (Sudah ada di https://github.com/realodix/AdBlockID/commit/0e6ee91f9ab7df6b377634b4a63b23939de6c113#diff-58efe50529c4d73853d68b44cbbbe537R63)
- riptukri.net (Tidak ditemukan pada link yang bersangkutan)

> https://www.langitmovie.com/
- grooksom.com (Tidak ditemukan pada link yang bersangkutan)

**Comment by realodix** [comment]
> ```
> https://nontonfilmsemi.net/
> https://jusifove.pro/jserr?msg=TypeError%3A%20Failed%20to%20register%20a%20ServiceWorker%20for%20scope%20(%27https%3A%2F%2Fnontonfilmsemi.net%2F%27)%20with%20script%20(%27https%3A%2F%2Fnontonfilmsemi.net%2Fpush-notif_swh.js%27)%3A%20A%20bad%20HTTP%20response%20code%20(404)%20was%20received%20when%20fetching%20the%20script.%0AUrl%3A%20https%3A%2F%2Fnontonfilmsemi.net%2F&ua=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F79.0.3945.130%20Safari%2F537.36&tag=push-self-invocation
> ```
> 
> ini apa gan tracker atau bukan???

Kalau dari pesannya, sepertinya iya. Gak bisa pastiin.

**Comment by Recehan-Slayer** [comment]
```
https://duniadrakor.com/episode/tell-me-what-you-saw-season-1-episode-12-2/
https://leimardog.com/r9ECZupfoEl/15850
```

**Comment by Recehan-Slayer** [comment]
```
https://www.layarkaca21indo.net/eps/nonton-the-world-of-the-married-episode-1-3-subtitle-indonesia-dan-english/
https://yonashbin.com/r9ECZupfoEl/15850
```

**Comment by realodix** [comment]
>https://www.layarkaca21indo.net/eps/nonton-the-world-of-the-married-episode-1-3-subtitle-indonesia-dan-english/
> `https://yonashbin.com/r9ECZupfoEl/15850`

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix
```
https://www.cinemabioskop21.top/
https://wowjogsot.com/fJMZeKaTxXMhg/18315
```

**Comment by Recehan-Slayer** [comment]
```
https://pusatfilm21.club/tv/money-heist/
https://outtunova.com/rxPB4Ystuybgj/13686
```

**Comment by Recehan-Slayer** [comment]
```
https://pojokmanga.com/manga/martial-master/chapter-375/
https://ribbumuse.com/t9TaBsF8LWqCh0/19948
```

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
```
https://boomxxi.org/bloodshot-2020/
https://dostophog.com/rdZv76mW8uY/16438
```

**Comment by realodix** [comment]
> https://boomxxi.org/bloodshot-2020/
> 
> `https://dostophog.com/rdZv76mW8uY/16438`

Thank you

**Comment by Recehan-Slayer** [comment]
```
https://tatdunsit.com/roShuicd9HaP/18292
https://pakbos21.org/nonton-money-heist-season-3/
```

**Comment by Recehan-Slayer** [comment]
```
https://jetsowilk.com/rxmtSgRYTVGTL4w/18105
https://dramaencode.com/download-drama-korea-born-again-subtitle-indonesia/
```

**Comment by realodix** [comment]
> ```
> https://tatdunsit.com/roShuicd9HaP/18292
> ```
> https://pakbos21.org/nonton-money-heist-season-3/


> ```
> https://jetsowilk.com/rxmtSgRYTVGTL4w/18105
> ```
> https://dramaencode.com/download-drama-korea-born-again-subtitle-indonesia/

Thank you

**Comment by Recehan-Slayer** [comment]
```
https://boajagoar.com/rjQ9TgmbEyUzWOZom/18943
https://dramaqu.info/nonton-365-repeat-the-year-2020-subtitle-indonesia/
```

**Comment by Recehan-Slayer** [comment]
```
https://simrubwan.com/tDtwSAXPt6gUMs2vZ/20063
https://www.timesindonesia.co.id/read/news/263085/pulang-dari-surabaya-warga-desa-kuwolu-kabupaten-malang-diduga-terjangkit-covid19
```

**Comment by realodix** [comment]
> ```
> https://boajagoar.com/rjQ9TgmbEyUzWOZom/18943
> ```
> https://dramaqu.info/nonton-365-repeat-the-year-2020-subtitle-indonesia/

> ```
> https://simrubwan.com/tDtwSAXPt6gUMs2vZ/20063
> ```
> https://www.timesindonesia.co.id/read/news/263085/pulang-dari-surabaya-warga-desa-kuwolu-kabupaten-malang-diduga-terjangkit-covid19

Thank you

**Comment by Recehan-Slayer** [comment]
https://thetarhaw.com/tWhaMKNmtdu/19948
https://pojokmanga.com/manga/metropolitan-system/chapter-202/

**Comment by Recehan-Slayer** [comment]
`https://mangacanblog.com/`

**Comment by realodix** [comment]
> ```
> https://thetarhaw.com/tWhaMKNmtdu/19948
> ```
> https://pojokmanga.com/manga/metropolitan-system/chapter-202/


Thank you

> https://mangacanblog.com/

Ini beda jenis, sebaiknya dipisah issue saja
