### ISSUE TITLE
Miner

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#402]
**Jenis iklan** (hapus yang tidak perlu)
- Cryptojacking

**Sample URL**
https://www.downloadfilmindo21.xyz/
https://www.downloadfilmindonesia21.xyz/
http://www.indofilms21.com/
https://www.indomov2020.xyz/

**Penjelasan Lebih Lanjut**
miner

**Comment by realodix** [comment]
Masalah ini mirip seperti https://github.com/realodix/AdBlockID/issues/392

Saat ini Saya hanya bisa kasih label invalid. Gak yakin ini miner, karena pas dibongkar dalemnya hanya iframe saja.

Sebagai bahan uji coba, kita akan membuat kurang lebih mirip dengan yang mereka lakukan. Buat file `test.html`, lalu paste kode di bawah ini
```html
<iframe src="https://github.com/Recehan-Slayer" height="0px" width="0px"></iframe>
<iframe src="https://www.kaskus.co.id/" height="0px" width="0px"></iframe>
<iframe src="https://www.kompas.com/" height="0px" width="0px"></iframe>
```

Masing2 paste 150x - 200x, jadi total minimal ada 450 baris.

Ketika dibuka akan menampilkan effect yang sama
- Penggunaan CPU di task manager akan meningkat cepat.
- Loading yang cukup lama.

**Comment by Recehan-Slayer** [comment]
gw jg ga paham bro. tpi ini sama owner nano adblocker/defender kok diberi label cryptojacking
`https://github.com/NanoMeow/QuickReports/issues/2946`
