### ISSUE TITLE
nontonfilm.vip

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#406]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://nontonfilm.vip/bioskop/a-shaun-the-sheep-movie-farmageddon-2019/

**Penjelasan Lebih Lanjut**
##.close-banner

**Comment by Recehan-Slayer** [comment]
https://filmindo.vip/

**Comment by realodix** [comment]
Thank you
