### ISSUE TITLE
linkspy.cc

### ISSUE THREAD

**Issue by RaveN0X87** [realodix/AdBlockID#411]
https://linkspy.cc/js/fullPageScript.min.js
https://www.hienzo.com/2020/02/darksiders-ii-deathinitive-edition-free-download.html
http://www.ovagames.com/devil-may-cry-5-codex.html

**Comment by realodix** [comment]
**Related**
- #122

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
`http://www.ovagames.com/steins-gate-my-darlings-embrace-codex.html`

sponsor uploaded premium
