### ISSUE TITLE
kabargames.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#412]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Overlay

**Sample URL**
https://www.kabargames.id/berita-kecanduan-game-online/

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
ada lagi bro OVERLAY 
https://www.kabargames.id/

**Comment by realodix** [comment]
> ada lagi bro OVERLAY
> https://www.kabargames.id/

Thank you

**Comment by Recehan-Slayer** [comment]
ada banner baru

**Comment by realodix** [comment]
> ada banner baru
> `https://www.inagloss.com/?utm_medium=master_banne&utm_source=kabargames&utm_campaign=referral_link`

Thank you
