### ISSUE TITLE
otaku.tekloggers.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#413]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://otaku.tekloggers.com/2020/02/ryuugajou-nanana-no-maizoukin-sub-indo.html

**Penjelasan Lebih Lanjut**
`https://cdn.statically.io/gh/Tekloggers/CDN-Tekloggers/master/master/safeplatinum.js`

**Comment by realodix** [comment]
Thank you

**Comment by realodix** [comment]
**Related**
- #229
