### ISSUE TITLE
dramaserial.biz

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#414]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://dramaserial.biz/
https://juraganfilm.life/

**Penjelasan Lebih Lanjut**
###netkevin-popup

**Comment by Recehan-Slayer** [comment]
https://jfnonton.com/

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
`https://juraganfilm.casa/` ganti domain terus gan mnding yg adblokcid plus pke wilrdcard rules
