### ISSUE TITLE
quadranglefilmfest.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#415]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://www.quadranglefilmfest.com/

**Penjelasan Lebih Lanjut**
`||grensauy.com^`

**Comment by Recehan-Slayer** [comment]
```
https://xxi21.asia/something-borrowed-2011/
||ampburask.site^
```

**Comment by realodix** [comment]
grensauy.com sudah ada di [easylist/easylist@da25133#diff-4903e75](https://github.com/easylist/easylist/commit/da251331d6c53927ad89d3b2c9fd37285ffcbead#diff-4903e7590de76df1abe1703921a2c88bR2447)
