### ISSUE TITLE
pes-id.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#417]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://www.pes-id.com/2017/08/pes-2017-next-season-patch-terbaru.html

**Penjelasan Lebih Lanjut**
`https://cdn.statically.io/gh/apps2portable/apps2portable/cff368c4/safelink.js`

**Comment by Recehan-Slayer** [comment]
https://github.com/realodix/AdBlockID/issues/237

**Comment by realodix** [comment]
Blokir 1 repo, isinya safelink semua
