### ISSUE TITLE
carasetting.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#418]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://www.carasetting.net/2018/12/psiphon-pro-premium-unlimited-terbaru.html

**Penjelasan Lebih Lanjut**
`https://cdn.statically.io/gh/dulbjn/javascript/10b6b23f/safeplatinum.js`
keknya safeplatinum bnyak bro

**Comment by realodix** [comment]
Kayaknya, tapi baru ada 3 sih sama ini

**Comment by realodix** [comment]
File safeplatinum.js sudah masuk ke dalam genaral block
