### ISSUE TITLE
Sektekomik.com

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#419]
Pengen reopen issue sektekomik yang sebelumnya (#196)  tapi ga menemukan tombol reopen disamping tombol comment. jadi bikin baru.

**Jenis iklan** 
- Pop-up
- Lainnya

Kelihatannya sektekomik meng  generate secara otomatis link2 yang dipanggil.
Selain script javascript, juga menghasilkan link source stylesheet dengan format css tentunya.

**Sample Url**
`sektekomik.com`

sample url yang dipanggil sektekomik
```
https://zaugroaw.net/index.css?aHR0cHM6Ly92aWF0ZXBpZ2FuLmNvbS9hcHUucGhwP3pvbmVpZD0yODgyMDUw
https://naidafak.net/style.css?aHR0cHM6Ly92aWF0ZXBpZ2FuLmNvbS9hcHUucGhwP3pvbmVpZD0yODgyMDUw
https://soalouve.com/styles.css?aHR0cHM6Ly9uYXRpdmUucHJvcGVsbGVyY2xpY2suY29tLzE/ej0zMDY3NTY2
```
di dalamnya ada content yg di encrypt, bisa pakai function atob() nya javascript bila di console browser untuk mengdecrypt

Pernah nyoba rules ini
`sektekomik.com##+js(abort-current-inline-script.js, Math, "zfgloaded")`
ga berhasil karena sektekomik tetap menghasilkan alamat baru tiap hari nya.
Sampe hari ini, link yang berasal dari sektekomik aku coba block
```
||zelrasty.net^$third-party
||neechuce.net^$third-party
||wauthaum.com^$third-party
||soalouve.com^$third-party
||aukrouwy.net^$third-party
||psoaksoo.com^$third-party
||ptauphie.com^$third-party
||joorejou.net^$third-party
||ausagauw.net^$third-party
||zaugroaw.net^$third-party
```

Jadi nya ku coba memblokir link cache javascriptnya yang isinya  ya keliatan mencurigakan dibagian akhir. 
Syukur berhasil dan di filter logger nya juga tidak nampak link css maupun javascript hasil generate otomatis nongol kembali. Dan segala fungsi web tetap bekerja secara normal di sektekomik.

**Rules yang disarankan**
`/wp-content/cache/min/*^$script,domain=sektekomik.com`

**Comment by GrennKren** [comment]
aih.. jangan dulu dah. 
Chatango nya ikutan kena, ga ke load disana bila cache javascript di blokir.

**Comment by realodix** [comment]
> ```
> ||zelrasty.net^$third-party
> ||neechuce.net^$third-party
> ||wauthaum.com^$third-party
> ||soalouve.com^$third-party
> ||aukrouwy.net^$third-party
> ||psoaksoo.com^$third-party
> ||ptauphie.com^$third-party
> ||joorejou.net^$third-party
> ||ausagauw.net^$third-party
> ||zaugroaw.net^$third-party
> ```

Ini dapat dari mana? Gak ada yang keluar.

![cats](https://user-images.githubusercontent.com/1314456/74098803-c00f9380-4b4e-11ea-9e7f-504b73536571.jpg)

**Comment by Recehan-Slayer** [comment]
sepertinya yg 3 dibawah propellerclick itu digenerate beda" bro tiap ip mungkin,soalnya di gw beda. tp smuanya dah masuk ke easylist sih

**Comment by GrennKren** [comment]
Ya kan ku bilang di **generate**, tiap hari berbeda.. itu yg `naidafak.com` juga termasuk.. percuma juga bila kita ngeblokir satu satu link nya tiap hari. ada trus yg nongol otomatis.

misalkan `zelrasty.net`. itu udah ada di issue sebelumnya dan dah dikonfirmasi buat di masukin ke filter adblockid. tapi link sample zelrasty ga bisa dibuka lagi.

**Comment by realodix** [comment]
Semua domain sample sudah masuk ke easylist, kemungkinan besar easylist memantau domain yang dihasilkan oleh https://propellerads.com. Baru saja Saya buka https://sektekomik.com, ada domain baru dan sudah masuk easylist juga.

Modelnya mirip seperti https://www.popads.net yang generate domain hampir setiap hari.

**Comment by Recehan-Slayer** [comment]
`https://github.com/NanoMeow/QuickReports/issues/3004`
itu bro udah bersih skrng, udah masuk ke uBo filter klo lo make uBo bro

**Comment by realodix** [comment]
Iya, mereka pakai uBo scriptlet. Saya hillangkan empty ads placeholder saja.

**Comment by GrennKren** [comment]
@realodix 
**Sample URL**
`https://sektekomik.com`

**Keterangan**
popup yang mengarah ke `ofgogoatan.com`

**Comment by realodix** [comment]
> **Sample URL**
> `https://sektekomik.com`
> 
> **Keterangan**
> popup yang mengarah ke `ofgogoatan.com`

Thx untuk laporannya. Saya tidak menemukan ada popup. Domain `ofgogoatan.com` sudah diblokir oleh easylist.
