### ISSUE TITLE
mangadropout.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#422]
**Sample URL**
https://mangadropout.net/generelatelink/href/8512/68
https://mangadropout.net/generelatelink/href/8509/67

**Penjelasan Lebih Lanjut**
AA

**Comment by realodix** [comment]
Link mengarah ke
- https://dawnstation.com/shortlink/76027/d41d8cd98f00b204e9800998ecf8427e
- https://dawnstation.com/shortlink/76000/d41d8cd98f00b204e9800998ecf8427e

**Comment by Recehan-Slayer** [comment]
@realodix sama mau tanya bro klo ngehilangin overlay pemberatuhan 18+ `https://mangadropout.net/collection/200139/sex-lesson` pke filter apa. soalnya klo ga diklik ya diarahkan ke halaman utama. dan walupun di klik ya selalu muncul terus.

**Comment by realodix** [comment]
Saya ragu untuk menghilangkan ini karena memang bagian dari fitur web tersebut, jadi tidak ditambahkan.

`mangadropout.net##+js(aopr, Swal.fire)`

**Comment by Recehan-Slayer** [comment]
iya mksudnya buat saya tambahin di filter saya sndiri gan
