### ISSUE TITLE
dl.nesia.my.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#423]
**Sample URL**
https://dl.nesia.my.id/d/1ntXV&type=1
https://dl.nesia.my.id/d/TpfJe&type=1

**Penjelasan Lebih Lanjut**
AA

**Comment by GrennKren** [comment]
untuk sementara pake scriptlet ini aja di user filter
dl.nesia.my.id##+js(set-constant.js, "tidakAdaPenghalangAds", "true")

aku pake adguard otomatis di convert biar support ama adguardnya ini scriptlet

**Comment by realodix** [comment]
Thank you, tersedia di AdBlockID+
