### ISSUE TITLE
tantesange.club

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#426]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://tantesange.club/

**Penjelasan Lebih Lanjut**
JUdi

**Comment by Recehan-Slayer** [comment]
https://bokep-jepang.icu/

**Comment by realodix** [comment]
Iklannya di bagian mana? Yang mengarah ke 128.199.117.89 bukan?

**Comment by Recehan-Slayer** [comment]
yg atas superhoki.com/128.199.117.89 yg bawah 159.89.207.166

**Comment by realodix** [comment]
Thank you
