### ISSUE TITLE
https://jalantikus.com/gadgets/harga-paket-internet-telkomsel-terbaru

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#431]
![](https://i.imgur.com/ZamgwRk.jpg)

https://jalantikus.com/gadgets/harga-paket-internet-telkomsel-terbaru

**Comment by 3xploiton3** [comment]
https://www.google.com/amp/s/jalantikus.com/amp/gadgets/harga-paket-internet-telkomsel-terbaru/

Dr google amp

**Comment by realodix** [comment]
Itu pakai filter apa aja ya? Saya gak bisa reproduce issue ini, karena di Saya gak seperti di SS yang agan bagikan

![Screenshot_2020-02-17-19-58-51-588_com android chrome](https://user-images.githubusercontent.com/1314456/74656094-11a7c600-51c0-11ea-9515-d76514897a23.jpg)

**Comment by 3xploiton3** [comment]
Adguard saya yg ngelag

Fixed
