### ISSUE TITLE
mugenfiles.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#432]
**Sample URL**
http://www.mugenfiles.com/tw3nmvpcnk07/KWN-06-360p_Negumo.com.mp4
https://www.okedrive.com/qdmoIIY/aibouanime-xyz-phantasy-star-online-2-episode-oracle-19-720p-mp4
https://yuudrive.me/4a47ceaa/kantai-mahouka-koukou-movie-2017-bd-720p-awsubs-mkv
**Penjelasan Lebih Lanjut**
AA

**Comment by realodix** [comment]
mugenfiles.com sepertinya lebih baik masuk list international saja danSaya lihat juga sudah masuk ke uBO filters.

https://www.okedrive.com dan https://yuudrive.me gak ada anti adblock
