### ISSUE TITLE
otakudesu.org

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#434]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://otakudesu.org/bkhk-episode-6-sub-indo/

**Penjelasan Lebih Lanjut**
`https://skylowhat.site/rHMWB8dxLc9mjObl/10157`
sama kek yg di pahe.in
`https://retiremely.com/rn6kq4PLoQ9/5778`

**Comment by realodix** [comment]
Thank you
