### ISSUE TITLE
Inject xl

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#435]
http://rbt.xl.co.id/rbtapp/www/page/result_page.jsp?header=wap.level.0.header.nonsub.3&mcode=16470612&aotype=AOC2&crypt=NjI4NzgyNzM3MTI4MXwyMDIwMDIxODE2MTQ1Mnw2NGU4Yjg5Yzc3MTFiZmY4ODAzZmM0MGYzY2Q3NWM3NzQ1M2IyYjky

Ga sempat nangkap situs sebelumnya krn redirect ke situ

**Comment by realodix** [comment]
Duplicate of #151
