### ISSUE TITLE
pahe.me

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#436]
**Jenis iklan** (hapus yang tidak perlu)
- Overlay 
- Popup

**Sample URL**
https://pahe.me
https://pahe.in

**Penjelasan Lebih Lanjut**
Di hp muncul overlay dan popups

![Screenshot_2020-02-18-18-42-10-86](https://user-images.githubusercontent.com/9379770/74733534-6f7df180-5244-11ea-84a4-8a75c4e39bbe.png)

**Comment by realodix** [comment]
Saya gak bisa reproduce issue ini. Baik simulasi maupun test di HP langsung, Saya tidak ada notifikasi tersebut.

**Comment by Recehan-Slayer** [comment]
setelah gw force update ga muncul lg. mungkin gegara filternya outdated

**Comment by realodix** [comment]
Bisa jadi Gan. Thank you untuk laporannya
