### ISSUE TITLE
dramaserial.pro

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#439]
**Jenis iklan** (hapus yang tidak perlu)
- Overlay

**Sample URL**
https://dramaserial.pro/

**Penjelasan Lebih Lanjut**
Overlay judi sama banner

**Comment by realodix** [comment]
**Pergantian domain**
- dramaserial.biz (#414) -> dramaserial.pro
- dramaserial.cc (#304) -> dramaserial.fun

**Comment by Recehan-Slayer** [comment]
masi ada `https://luxury138.cc//DramaserialPopUp` `https://www.luxury138besi.com/?Id=10368&AdType=0`

**Comment by realodix** [comment]
Kalau sekarang gimana? Masih ada gak? Di Saya gak ada yg muncul, jadi gak bisa periksa.

**Comment by Recehan-Slayer** [comment]
👌dah bersih

**Comment by Recehan-Slayer** [comment]
ada yg baru `https://sbobet.host/luxurydrmtvsidebar`

https://dramaserial.fun/

**Comment by realodix** [comment]
> ada yg baru https://sbobet.host/luxurydrmtvsidebar
> 
> https://dramaserial.fun/

Thank you

**Comment by Recehan-Slayer** [comment]
https://dramaserial.club/

**Comment by realodix** [comment]
> 
> 
> https://dramaserial.club/

Thank you
