### ISSUE TITLE
asuransiku.info

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#440]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://gudangmoviies21.com/love-for-sale-2-2019/
https://gudangmoviies21.com/?13a9748daa=emp3ZEpjd3ZFOW5uUG9hNCt4TVBwOC81VmIzSlhxWmU4OWJVS2tZWkZFNzkzYXlKVDhPMFAvKzNWbmR0WmhQL3ZtaGw1aFNDRm1SZkp5WU1hM0RmQlFkQzBSK1JKWWVRenFpeHJBU0pzQXlLRkhodHJzUmxxRUI0WHhQUXlSZlp2UFdJb010OXIwTFhXYmpLZ0tOaFpxZkp5WVpVa2o5MFdPTlhDN0VEVkdEM29mL1MzQ0tEaG9iMkx4cEwxeFZM

**Penjelasan Lebih Lanjut**
Fake button

**Comment by realodix** [comment]
Thank you
