### ISSUE TITLE
103.194.171.205 (IndoFilm)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#443]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://103.194.171.205/fast-furious-9-2020/

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
Sorry Gan, di saya bersih. Bisa bantu gak URLnya mengarah ke mana?

**Comment by Recehan-Slayer** [comment]
kemaren ada muncul 1 tp skrng bersih mungkin klo ga diremove ya udah tercover ama filter yg baru ditmbahkan diweb lain.

**Comment by realodix** [comment]
Ok deh sip, thank you Gan
