### ISSUE TITLE
206.189.151.55 (INDOXXI)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#444]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
http://206.189.151.55/

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Sepertinya berhubungan dengan #57
