### ISSUE TITLE
shiroyasha.me

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#447]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://anidl.org/boku-no-hero-academia-season-4-720p-english-subbed-x265-tvrip/

**Penjelasan Lebih Lanjut**
`https://shiroyasha.me/public/assets/js/convert-lnks.js`

**Comment by realodix** [comment]
Thank you
