### ISSUE TITLE
AdGuard

### ISSUE THREAD

**Issue by Alex-302** [realodix/AdBlockID#45]
Hello!
Can we add your filter to AdGuard?
Is your filter compatible with  [ABPindo](https://github.com/ABPindo/indonesianadblockrules/)? or only one filter should be enabled?

**Comment by realodix** [comment]
> Can we add your filter to AdGuard?

Yes..

> Is your filter compatible with [ABPindo](https://github.com/ABPindo/indonesianadblockrules/)? or only one filter should be enabled?

AdBlockID is designed to replace ABPindo overall, so I think only one filter should be enabled.

**Comment by Alex-302** [comment]
Ok, thanks)

**Comment by Alex-302** [comment]
done
