### ISSUE TITLE
islamidina.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#454]
**Jenis iklan** (hapus yang tidak perlu)
- Close Button

**Sample URL**
https://www.islamidina.id/2020/02/sabar-dan-syukur-sebagai-bentuk-tawakal.html

**Penjelasan Lebih Lanjut**
Close Button

**Comment by realodix** [comment]
Ini close buttonnya dimana ya?

**Comment by Recehan-Slayer** [comment]
tampilan webnya keknya udah berubah dan close buttonya ga ada lagi
