### ISSUE TITLE
indoflix.xyz

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#459]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://indoflix.xyz/

**Penjelasan Lebih Lanjut**
Banner judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
situs judi di footer

**Comment by realodix** [comment]
> situs judi di footer

Saya gak nemuin Gan. Minta tolong bannernya mengarah kemana gan

**Comment by Recehan-Slayer** [comment]
```
http://domino-qq.live/
http://asetnet.live/

```

**Comment by realodix** [comment]
> ```
> http://domino-qq.live/
> http://asetnet.live/
> ```

Thank you
