### ISSUE TITLE
nontonsub.top

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#463]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
http://nontonsub.top/

**Penjelasan Lebih Lanjut**
popup ke anaktogel.com

**Comment by realodix** [comment]
Saya belum menemukan popup

**Comment by realodix** [comment]
Harusnya sudah gak ada di sini #425

**Comment by Recehan-Slayer** [comment]
Ini kasusnya kek yg kmaren ada beberapa situs yg muncul popups mengarah ke anaktogel.com

**Comment by realodix** [comment]
Duplicate of #425
