### ISSUE TITLE
209.97.146.28 (Bokep Online) [NSFW]

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#465]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://209.97.146.28/ngewe-binor-galau-part-7/

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
Ini di bagian mananya ya?

**Comment by Recehan-Slayer** [comment]
Td pagi saat browsing" pke PC ada keknya tp skrng gw cek pke hp g muncul ntar deh gw coba cek lg pke PC

**Comment by Recehan-Slayer** [comment]
`http://162.212.153.22/`

**Comment by realodix** [comment]
Thank you
