### ISSUE TITLE
[Anti-Adblock] anoboy.video

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#469]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://anoboy.video/2020/01/one-piece-episode-917/

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by 3xploiton3** [comment]
https://imgur.com/4CmvDjo.png

**Comment by realodix** [comment]
**Related**
- https://github.com/realodix/AdBlockID/issues/438

**Comment by realodix** [comment]
Thank you, update tersedia di [AdBlockID+](https://github.com/realodix/AdBlockID#cara-menggunakan)

**Comment by 3xploiton3** [comment]
Masih ada,
![](https://i.imgur.com/PGuLsEE.jpg)

**Comment by realodix** [comment]
Thank you
