### ISSUE TITLE
idcloudhost.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#472]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up

**Sample URL**
https://idcloudhost.com/kenali-apa-itu-cron-jobs/

**Penjelasan Lebih Lanjut**
pop up

**Comment by realodix** [comment]
Ini ya?

![cats](https://user-images.githubusercontent.com/1314456/75639965-b8cb3980-5c65-11ea-8c5b-a2adc5dae4bb.jpg)

**Comment by 3xploiton3** [comment]
Ya

**Comment by realodix** [comment]
Kalau ini gak bisa Gan. Ini banner yang mempromokan product mereka sendiri di situs mereka sendiri.

Bisa buat custom rule `idcloudhost.com##.idch-popup-wrap`

**Comment by 3xploiton3** [comment]
klo di adguard itu masuk annoyance
