### ISSUE TITLE
animecracks.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#473]
**Sample URL**
https://animecracks.com/anime/rikei-ga-koi-ni-ochita-no-de-shoumei-shitemita/

**Penjelasan Lebih Lanjut**
AA

**Comment by Liz-chan** [comment]
Looks like `animecracks.com##+js(abort-on-property-read.js, mdpDeBlocker)` works to disable the anti-adblock 😄

**Comment by realodix** [comment]
Thank you. Sebagian update tersedia di AdBlockID & [AdBlockID+](https://github.com/realodix/AdBlockID#cara-menggunakan).
