### ISSUE TITLE
mangaindo.web.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#477]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://mangaindo.web.id/apotheosis-indonesia-chapter-462/

**Penjelasan Lebih Lanjut**
`https://misdem.pro/cGDb9Q6/bf2G5Fl/S_WpQp9/MizEc_wENyzSI/wSNgSz0nzvNHzFAz3HMyzsUVzq` ini trmasuk 3p adverts bkn bro

**Comment by realodix** [comment]
> https://misdem.pro/cGDb9Q6/bf2G5Fl/S_WpQp9/MizEc_wENyzSI/wSNgSz0nzvNHzFAz3HMyzsUVzq ini trmasuk 3p adverts bkn bro

Iya nih popup. Thank you
