### ISSUE TITLE
bacakomik.co

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#478]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://bacakomik.co/

**Penjelasan Lebih Lanjut**
`https://ahasagicy.site/rbvwGXsoiej/16974`

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
situs judi difooter

**Comment by realodix** [comment]
> situs judi difooter

Thank you
