### ISSUE TITLE
neumanga.tv

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#481]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://neumanga.tv/

**Penjelasan Lebih Lanjut**
Situs judi dibagian bawah

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
masih ada 2 
```
https://199.192.23.38/
https://139.99.88.67/
```

**Comment by realodix** [comment]
> masih ada 2
> 
> ```
> https://199.192.23.38/
> https://139.99.88.67/
> ```

Thank you
