### ISSUE TITLE
66.42.54.200 (bokep-barat.com) [NSFW]

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#487]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://66.42.54.200/148/bokep-barat-abg-nakal-layani-polisi

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
Di bagian mananya?

**Comment by Recehan-Slayer** [comment]
`https://www.lg88.online/?ref=F949E9`

**Comment by realodix** [comment]
Thank you
