### ISSUE TITLE
alodokter.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#492]
![screen](https://user-images.githubusercontent.com/19517680/75803066-5f235600-5db0-11ea-9c32-436b4f287e76.jpg)

https://www.alodokter.com/ternyata-gula-batu-tidak-lebih-sehat-dibanding-gula-pasir

blank space

**Comment by realodix** [comment]
Ini pkai filter apa aja?

**Comment by 3xploiton3** [comment]
Adguard base, annoyance, ubo default, adblockid + plus

**Comment by realodix** [comment]
Konfigurasi sudah Saya samakan, tapi gak ada Gan

Bisa minta saran syntax filter?

**Comment by 3xploiton3** [comment]
> Konfigurasi sudah Saya samakan, tapi gak ada Gan
> 
> Bisa minta saran syntax filter?

klo via UBO bisa tambahkan syntax ini
##.adunit

**Comment by realodix** [comment]
Sry Gan, `##.adunit` sudah ada di easylist :D

**Comment by Recehan-Slayer** [comment]
easylist biasanya kn settingan default.

**Comment by 3xploiton3** [comment]
saya gak pakai easylist banyak salah filter, kata team adguard

baiknya ditambahkan karena masuk kategori web indonesia

**Comment by realodix** [comment]
> saya gak pakai easylist banyak salah filter (redundant), kata team adguard
> 
> baiknya ditambahkan karena masuk kategori web indonesia

Untuk AdGuard memang disarankan untuk tidak mengaktifkan easylist, karena AdGuard Base filter-nya sudah mengandung easylist. Jika easylist diaktifkan akan menyebabkan kondisi redundant / mubazir.

<details>
  <summary>Screenshot</summary>

![cats](https://user-images.githubusercontent.com/1314456/76161819-90fa3b00-6169-11ea-891e-640d05ca38bb.jpg)
 
</details>

Untuk uBO disarankan mengaktifkan easylist, karena AdGuard Base filter yang disediakan versi mandiri (tanpa easylist). Jika tetap ingin hanya menggunakan AdGuard Base filter saja, maka gunakan ini https://filters.adtidy.org/extension/chromium/filters/2_optimized.txt, ini filter AdGuard Base yang sama persis pada AdGuard, sudah mengandung easylist.

**Comment by 3xploiton3** [comment]
> > saya gak pakai easylist banyak salah filter (redundant), kata team adguard
> > baiknya ditambahkan karena masuk kategori web indonesia
> 
> Untuk AdGuard memang disarankan untuk tidak mengaktifkan easylist, karena AdGuard Base filter-nya sudah mengandung easylist. Jika easylist diaktifkan akan menyebabkan kondisi redundant / mubazir.
> 
> Screenshot
> Untuk uBO disarankan mengaktifkan easylist, karena AdGuard Base filter yang disediakan versi mandiri (tanpa easylist). Jika tetap ingin hanya menggunakan AdGuard Base filter saja, maka gunakan ini https://filters.adtidy.org/extension/chromium/filters/2_optimized.txt, ini filter AdGuard Base yang sama persis pada AdGuard, sudah mengandung easylist.

siap makasih sarannya,
saya kira adguard base filter yg di UBO sama dengan yg di adguard

**Comment by 3xploiton3** [comment]
https://filters.adtidy.org/extension/chromium/filters/2_optimized.txt
ini sepertinya utk mobile

ternyata adguard base di settingan bawaan UBO berdiri sendiri tanpa easylist,
sudah saya cek di filterlists.com

kalau ini adguard base filter + easylist
https://filters.adtidy.org/extension/chromium/filters/2.txt
