### ISSUE TITLE
bebasdownloadfilm.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#497]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
http://asdahsdkjajslkfbkaujqsbsdajaeghfwsadqeqyjj76e8637e68723rhbfajkl.bebasdownloadfilm.com/asfjlasdjfawefuafsjasfaladsfpaeoweuasj123729fasj328237123hkfashk32348201jfasda02491jasdfa6123jasfajlkasuqweoiasdfalaewfu0afwejsfljasfjskjasfahhhhrf7asfjasfajhasdfjcasnsdfuasejfasfuewajfas/get/my-teacher-my-obsession-2018/

**Penjelasan Lebih Lanjut**
popups mengarah ke `https://depobos.vip/`

**Comment by realodix** [comment]
Thank you
