### ISSUE TITLE
detik.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#501]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://m.detik.com/oto/catatan-pengendara-motor/d-4924465/mahal-juga-segini-harga-masker-anti-nuklir-yang-dipakai-driver-ojol?tag_from=wpm_cb_lifestyle_1&utm_source=detik.com&utm_medium=referral

**Penjelasan Lebih Lanjut**
Dimode hp dibagian atas ada iklan video auto play

**Comment by realodix** [comment]
Thank you
