### ISSUE TITLE
mikanime.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#503]
**Jenis iklan** (hapus yang tidak perlu)
- 3p safelink

**Sample URL**
https://mikanime.com/piano-no-mori-s2-sub-indo/

**Penjelasan Lebih Lanjut**
`https://rikucan.com/wp-content/themes/mh-magazine-lite/js/looping.js?v3`

**Comment by realodix** [comment]
Thank you
