### ISSUE TITLE
fotokita.grid.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#504]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://fotokita.grid.id/
https://health.grid.id/

**Penjelasan Lebih Lanjut**
`https://atm.sgp1.digitaloceanspaces.com/library/avmLibrary.js`
tracker bukan gan

**Comment by realodix** [comment]
Terlihat seperti untuk file untuk iklan Gan, tapi gak apa-apa ini, karena gak ada yang muncul
