### ISSUE TITLE
anoboy.id

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#51]
https://anoboy.id/beastars-episode-3-sub-indo/

iklan judi

**Comment by realodix** [comment]
Di mananya ya?
Popup ya?

**Comment by WaferNabati** [comment]
@realodix 
![Annotation 2019-10-28 204930](https://user-images.githubusercontent.com/9379770/67683759-84e4bc80-f9c4-11e9-9e7c-d6a98ba293e4.png)

**Comment by realodix** [comment]
Seperti yang bisa Anda lihat di [screenshot yang Saya kasih](https://github.com/realodix/AdBlockID/issues/51#issuecomment-546937785), Saya gak menemukannya.

Kalau boleh tahu, filter apa saja yang Anda gunakan selain Easylist & uBlock filters?

**Comment by WaferNabati** [comment]
uBlock filters​​​​​17,566 used out of 18,283​​​​
uBlock filters – Annoyances​​​​​2,507 used out of 2,694​​​​
uBlock filters – Badware risks​​​​​344 used out of 348​​​​
uBlock filters – Privacy​​​​​149 used out of 163​​​​
uBlock filters – Resource abuse​​​​​93 used out of 112​​​​
uBlock filters – Unbreak​​​​​1,071 used out of 1,139​​​​
Ads (3/4)
Adblock Warning Removal List​​​​​675 used out of 724​​​​
AdGuard Base List​​​​​29,119 used out of 29,813​​​​
EasyList​​​​​88,437 used out of 89,537​​​​
Privacy (2/3)
AdGuard Tracking Protection​​​​​7,853 used out of 7,891​​​​
EasyPrivacy​​​​​12,943 used out of 17,913​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,105 used out of 1,105​​​​
Malware domains​​​​​26,850 used out of 26,866​​​​
Annoyances (2/6)
AdGuard Annoyances​​​​​22,429 used out of 22,542​​​​
Fanboy’s Annoyance List​​​​​53,136 used out of 55,352​​​​
Multipurpose (1/4)
Peter Lowe’s Ad and tracking server list​​​​​2,944 used out of 3,059​​​​
Regions, languages (1/35)
IDN, MYS: ABPindo​​​​​7,153 used out of 7,587​​​​
Custom (4/7)
AdBlockID​​​​​16,629 used out of 16,636​​​​
Nano Defender Integration​​​​​2,645 used out of 2,646​​​​
Nano Filters​​​​​313 used out of 313​​​​
Nano Filters - Whitelist​​​​​1 used out of 1​​​

**Comment by realodix** [comment]
Sepertinya masalah ada di ABPindo (Last modified: 2019 October 28, 19:41:53).
Rule `@@||anoboy.$generichide` pada ABPindo membuat generic rules Kami menjadi tidak jalan.

![cats](https://user-images.githubusercontent.com/1314456/67693292-10197e80-f9d4-11e9-96a5-ec54a3e8b589.jpg)

**Comment by WaferNabati** [comment]
jadi solusinya gmn

**Comment by realodix** [comment]
Solusinya adalah

**1. Untuk hunting iklan yang masih muncul:**
    Saya sarankan hanya mengaktifkan salah satu saja. Dalam beberapa kasus seperti issue ini, dapat saling bentrok.

   AdBlockID dan ABPindo didesain untuk compatible dengan filter utama, seperti EasyList, uBlock filters, Nano Filters dan AdGuard Base filter.

**2. Untuk penggunaan harian:**
Saya sarankan untuk hanya menggunakan ABPindo yang notabene filter region bawaan.

Terima kasih untuk laporannya, Saya rasa issue ini dapat ditutup :D

**Comment by WaferNabati** [comment]
ok thanks
