### ISSUE TITLE
nanonime.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#510]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://www.nanonime.com/demon-slayer-kimetsu-no-yaiba-episode-26-final/

**Penjelasan Lebih Lanjut**
tempat iklan di  streaming server 2

**Comment by realodix** [comment]
> tempat iklan di streaming server 2

Ini gak bisa, mereka pakai iframe

**Comment by GrennKren** [comment]
@realodix  Blockadblock nya gan juga ada disana..
`@@||nanonime.com$generichide`

Mengenai yang issue ini kenapa ga dilakukan melalui source nya langsung.. klo di video di dalam iframe nya kan berasal dari `svr1.cloudplayer.online`
`cloudplayer.online###banner`

**Comment by realodix** [comment]
> Mengenai yang issue ini kenapa ga dilakukan melalui source nya langsung.. klo di video di dalam iframe nya kan berasal dari `svr1.cloudplayer.online`
> `cloudplayer.online###banner`

Karena ini domain inter, lebih baik yang melakukannya uAsset atau AdGuard, jadi semua negara kena
