### ISSUE TITLE
bukalapak.com (web desktop)

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#515]
![image](https://user-images.githubusercontent.com/19517680/76161047-37424280-6162-11ea-8601-f59f70c6a50b.png)

di tampilan  desktop promo iklan ada 2 baris

**Comment by 3xploiton3** [comment]
https://www.bukalapak.com/products?utf8=✓&search[keywords]=pompa+sepeda&search[sort_by]=weekly_sales_ratio%3Adesc

**Comment by realodix** [comment]
Thank you
