### ISSUE TITLE
ryuukoi.web.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#520]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Lainnya

**Sample URL**
https://ryuukoi.web.id/one-piece-stampede-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
Banner judi sama empty space dibagian atas

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix https://ryuukoi.web.id/princess-connect-redive-05-subtitle-indonesia/
banner

**Comment by realodix** [comment]
> 
> 
> @realodix https://ryuukoi.web.id/princess-connect-redive-05-subtitle-indonesia/
> banner judi sama blank space dibagian atas

Di bagian mananya Gan?

**Comment by realodix** [comment]
Oalah karena ada `@@||ryuukoi.web.id^$generichide` di uBlock filters

<details>
  <summary>Screenshot</summary>
  
  ![noname](https://user-images.githubusercontent.com/1314456/81177224-84ab2680-8fd0-11ea-878d-b5cb1f4d0a27.png)
</details>

`$generichide` biasanya untuk mengatasi Anti-adblock, Saya pribadi gak pakai uBlock filters dan gak ada peringatan Anti-adblock. Saya anggap ini filter usang di uBlock filters, jadi Saya hanya menambahkan filter general block untuk mengurangi dampaknya.

Terima kasih

**Comment by Recehan-Slayer** [comment]
okay bro
