### ISSUE TITLE
shrink.world & shrinkads.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#521]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.shrink.world/y0nhHW
https://www.shrinkads.com/3sncky

**Penjelasan Lebih Lanjut**
Fake Button, Popups, AA, out of focus
2 shortlink diatas sering ganti domain gan

**Comment by realodix** [comment]
> https://www.shrink.world/y0nhHW

https://github.com/realodix/AdBlockID/commit/ac28671ea5d388f676b59f97b2d81861fb70c61c

> https://www.shrinkads.com/3sncky

https://github.com/realodix/AdBlockID/commit/92b13ec3a0654084620ef0c0ecea136812c3894b

---

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix close button gan. 


> **Jenis iklan** (hapus yang tidak perlu)
> 
> * Banner
> * Pop-up
> * Lainnya
> 
> **Sample URL**
> https://www.shrink.world/y0nhHW
> https://www.shrinkads.com/3sncky
> https://www.autoratio.com/Ws6nsgDPPB
> 
> **Penjelasan Lebih Lanjut**
> Fake Button,close button, Popups, AA,

**Comment by realodix** [comment]
> 
> 
> close button gan.
> 
> > **Jenis iklan** (hapus yang tidak perlu)
> > 
> > * Banner
> > * Pop-up
> > * Lainnya
> > 
> > **Sample URL**
> > https://www.shrink.world/y0nhHW
> > https://www.shrinkads.com/3sncky
> > https://www.autoratio.com/Ws6nsgDPPB
> > **Penjelasan Lebih Lanjut**
> > Fake Button,close button, Popups, AA,

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix gnti domain bro yg autoratio(sportif.id) skrng close button

**Comment by realodix** [comment]
> 
> 
> gnti domain bro yg autoratio(sportif.id) skrng close button

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix domain baru bro www.onlinecorp.me fake button dll

**Comment by realodix** [comment]
> domain baru bro [www.onlinecorp.me](http://www.onlinecorp.me) fake button dll

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix ada close buttonya bro

**Comment by realodix** [comment]
> ada close buttonya bro

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix bro ganti domain lagi fake button close button dll

**Comment by realodix** [comment]
Thank you
Thank you
