### ISSUE TITLE
nekonime.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#522]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://nekonime.com/somali-to-mori-no-kamisama-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
Fake button

**Comment by realodix** [comment]
Fake buttonnya yang mana ya?

**Comment by Recehan-Slayer** [comment]
skrng sepertinya udah ga ada.
