### ISSUE TITLE
galaxyxxi.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#523]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://galaxyxxi.com/

**Penjelasan Lebih Lanjut**
Judi di bawah

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
jdui baru

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
overlay

**Comment by realodix** [comment]
Overlaynya buka iklan ini Gan. Infonya juga penting tentang COVID19
