### ISSUE TITLE
tokopedia.com (desktop) - AdGuard

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#527]
![image](https://user-images.githubusercontent.com/19517680/76693936-0bade380-669f-11ea-91ee-eda0affdc186.png)

https://www.tokopedia.com/search?st=product&ob=5&pmin=25000&page=2&pmax=30000&q=speaker

saya pakai adguard ads belum hilang,

**Comment by realodix** [comment]
Ini harus lapor ke AdGuard sih, karena pakai syntax yang valid

`tokopedia.com##[label-atm="taProduct"]:-abp-has(img[alt*="topads" i])`

Di https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pseudo-class-has dikatakan
> Supported synonyms for better compatibility: `:-abp-has`

**Comment by 3xploiton3** [comment]
ping @adamWr
