### ISSUE TITLE
mangalist.org [Anti adblock]

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#53]
Blocking continue link

https://mangalist.org/url/go/REpFUVZqamZmSTYrb25mUU55VnNUd3g4RURmdXA3M1lkYUtXR3pkSWc3SGMwYnY5aEdySSs1Z2NjTmg2bHFabjlhUTlHT0RpWHgxdnVVRlR3ZEtNb2pHWGJ0NmdhM2xtWVFJMld3clU1OGc9

**Comment by realodix** [comment]
Thank you @WaferNabati

**Comment by Recehan-Slayer** [comment]
tautan yang menuju ke filehostingnya ga muncul gan

**Comment by realodix** [comment]
Thank you
