### ISSUE TITLE
dramaencode.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#530]
**Jenis iklan** (hapus yang tidak perlu)
- 3p safelink script

**Sample URL**
https://dramaencode.com/download-drama-korea-tell-me-what-you-saw-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
`https://www.safelinkblog.com/js/v2.js`

**Comment by realodix** [comment]
Thank you
