### ISSUE TITLE
njiir.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#533]
**Sample URL**
https://www.njiir.com/p/stress-measurements-using-oriented-core.html?url=IyMlNUJfWSUxRkVSUktMRCUxMEMlMDdFR0slMDZRJTVDSUtJWiUwNyUwNyUxMiU1QlglNUMlNUMlNDAjIw%3D%3D

**Penjelasan Lebih Lanjut**
generate link ga muncul

**Comment by realodix** [comment]
Thank you
