### ISSUE TITLE
sogafime.org

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#536]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://sogafime.org/uka-uka-the-movie-2019/

**Penjelasan Lebih Lanjut**
`https://cdn.jsdelivr.net/gh/kareelproject/klinkz@master/fullpagescript.js`
sama direponya sprtinya ada 1 lgi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix 
```
http://144.217.211.162/
http://fryawlauk.com/rVcXO88j3JfC2/16443
```

**Comment by realodix** [comment]
> ```
> http://144.217.211.162/
> http://fryawlauk.com/rVcXO88j3JfC2/16443
> ```

Thank you
