### ISSUE TITLE
tokubatch.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#540]
**Jenis iklan** (hapus yang tidak perlu)
- 3p safelink

**Sample URL**
https://www.tokubatch.com/ultraman-x-episode-1-22-tamat-sub-indo-batch/
https://www.tokubatch.com/kamen-rider-zi-o-2019/

**Penjelasan Lebih Lanjut**
`https://pastebin.com/raw/Rw38SyHy
`

**Comment by realodix** [comment]
Duplicate of #234
