### ISSUE TITLE
onbatch.my.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#543]
**Sample URL**
https://www.onbatch.my.id/2020/03/91-days-subtitle-indonesia-batch.html
https://safe.onbatch.my.id/2020/03/important-information-about-bipolar-disorder.html#?go=26b45b29c2546ff084a3a96abba9734e72db2bb5d3924808d9824a24a4f192478d1980949e5b6e78dcd84e9a81b290720f89fb18241fbc8040a972b6dec4f1c6353c34ec5d3d5ea536ca5cd2e0b8602c69ffd512d7de339c9d2b57c3064b4e283e01840e79f1c494

**Penjelasan Lebih Lanjut**
dan 3p safelink scripts
`https://cdn.statically.io/gh/abdiusu/project-safelink-viomagz/21321d8c/cryptojs-murni.js`
dan direponya bnyak safelink yg lain gan `https://github.com/abdiusu`

**Comment by Recehan-Slayer** [comment]
@realodix /safelink-$script,3p broken getlinknya jdi keblock

**Comment by realodix** [comment]
> `/safelink-$script,3p` broken getlinknya jdi keblock

Yang ini maksudnya gimana ya?

**Comment by Recehan-Slayer** [comment]
@realodix  get linknya keblock
![adblock](https://user-images.githubusercontent.com/9379770/77842602-7d694f80-71be-11ea-9ab2-af3011f4bc00.png)

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix yg ini blom gan
`https://cdn.statically.io/gh/abdiusu/project-safelink-viomagz/21321d8c/cryptojs-murni.js`

**Comment by realodix** [comment]
> 
> 
> yg ini blom gan
> https://cdn.statically.io/gh/abdiusu/project-safelink-viomagz/21321d8c/cryptojs-murni.js

Thank you
