### ISSUE TITLE
jkoding.xyz

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#544]
**Sample URL**
https://www.jkoding.xyz/2020/03/safelink-linkmagz-3-halaman-3-tombol.html

**Penjelasan Lebih Lanjut**
AA sama ads ditengah post

**Comment by realodix** [comment]
> AA sama ads ditengah post

Adsnya yang mana Gan?

**Comment by Recehan-Slayer** [comment]
@realodix ehh ternyata bukan ads cmn contoh gambar ads pas muncul

**Comment by realodix** [comment]
> ehh ternyata bukan ads cmn contoh gambar ads pas muncul

OK Gan. Kalau gitu Saya close ya. Thank you
