### ISSUE TITLE
cinemaxxi.art

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#549]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://cinemaxxi.art/

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
https://cinemaxxi.art/confession-2014/
judi baru

**Comment by realodix** [comment]
> 
> 
> https://cinemaxxi.art/confession-2014/
> judi baru

Di bagian mananya ya?

**Comment by Recehan-Slayer** [comment]
http://lapak88.pro/ref.php?ref=INDOXXIFUN

**Comment by realodix** [comment]
> 
> 
> http://lapak88.pro/ref.php?ref=INDOXXIFUN

Pantesan. Masalah lama, di Firefox gak keliatan. Thank you
