### ISSUE TITLE
(anti-adblock) pugam.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#553]
https://www.pugam.com/18790/2-cara-membuat-pesan-terjadwal-di-whatsapp-android/

![](https://i.imgur.com/QEz5beP.jpg)

**Comment by realodix** [comment]
Ini sepertinya sudah gak ada ya peringatan anti adblocknya

**Comment by krystian3w** [comment]
`###ai-adb-message, #ai-adb-overlay`

**Comment by realodix** [comment]
Thank you

**Comment by krystian3w** [comment]
Possible allow load WP plugin:

```

**Comment by realodix** [comment]
> 
> 
> Possible allow load WP plugin:
> 
> ```
> @@/wp-content/plugins/ad-inserter/*$~third-party
> ```

Why?
