### ISSUE TITLE
benime.my.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#554]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://www.benime.my.id/2020/04/hello-world-bd-subtitle-indonesia.html

**Penjelasan Lebih Lanjut**
`https://cdn.statically.io/gh/SylicaChan/BeNime/61ae04fa/safelink.js`

**Comment by realodix** [comment]
Thank you
