### ISSUE TITLE
aibouanime.site

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#558]
**Sample URL**
https://www.aibouanime.site/2020/04/bungou-to-alchemist-shinpan-no-haguruma-episode-02-subtitle-indonesia.html

**Penjelasan Lebih Lanjut**
AA

**Comment by realodix** [comment]
Ini Saya gak nemuin Gan ada notif anti adblock.

Di agan masih gak?
Kalau di agan masih, ini ngaruh gak kalai diblock https://cdnjs.cloudflare.com/ajax/libs/fuckadblock/3.2.1/fuckadblock.min.js

**Comment by Recehan-Slayer** [comment]
Uda masuk ke uassets jdinya g muncul AAnya

**Comment by realodix** [comment]
Thank you
