### ISSUE TITLE
www.kompas.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#566]
**Sample URL**
https://www.kompas.com/sports/komentar/2020/04/16/10400098/shin-tae-yong--penanganan-covid-19-di-indonesia-buruk?sort=terbaru

**Penjelasan Lebih Lanjut**
di mode tampilan mobile buka komentar penuh nya tidak muncul

**Comment by realodix** [comment]
Maksudnya full gimana Gan? Bisa kasih SS gak harusnya bagaimana?

**Comment by Recehan-Slayer** [comment]
itu kan ada pilihan lihat komentar terbaru terlama terpopuler klo di desktop muncul komentarnya tpi klo di mobile ntah knp ga muncul saya matikan adblockpun tetap tidak muncul mungkin emg rusak dr situsnya.

**Comment by realodix** [comment]
Di gue seperti ini Bro, harusnya seperti apa ya? 

![Screenshot_2020-04-16-21-12-19-121_com android chrome](https://user-images.githubusercontent.com/1314456/79466629-07227500-8027-11ea-9472-48161df3b424.jpg)

**Comment by Recehan-Slayer** [comment]
pnya gw ga muncul mungkin gegara ekstensi lain atau browsernya atau mungkin hpnya.

**Comment by Recehan-Slayer** [comment]
![Screenshot_2020-04-16-21-43-49-86](https://user-images.githubusercontent.com/9379770/79470349-cf003f80-7ff0-11ea-9ef9-bd1bc732eeae.png)
