### ISSUE TITLE
sonora.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#567]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://www.sonora.id/read/422108941/sebanyak-50-jenazah-korban-covid-19-di-sulsel-dimakamkan-di-gowa

**Penjelasan Lebih Lanjut**
player ivideosmart 
sama seperti kasus kompasiana ama bolasport bro

**Comment by realodix** [comment]
Thank you
