### ISSUE TITLE
genpi.co

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#568]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.genpi.co/internasional/44082/temuan-baru-gejala-covid-19-bisa-terdeteksi-dari-kaki?page=2

**Penjelasan Lebih Lanjut**
Placeholder

**Comment by realodix** [comment]
Thank you
