### ISSUE TITLE
m.cnnindonesia.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#570]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://m.cnnindonesia.com/nasional/20200423154422-12-496606/nasdem-desak-polisi-usut-dugaan-peretasan-whatsapp-ravio

**Penjelasan Lebih Lanjut**
Di mode mobile ada banner iklan sama ads placeholder
<details>

![Screenshot_2020-04-24-07-11-14-85](https://user-images.githubusercontent.com/9379770/80161597-787e9c80-85c0-11ea-821b-724445eefbfb.png)

**Comment by realodix** [comment]
Di Saya gak ada Gan..

Harusnya juga sudah hilang dengan easylist `##div[id^="div-gpt-ad"]`

**Comment by Recehan-Slayer** [comment]
ohh iya gan skrng dah ga ada mungkin pas koneksi lelet kmaren
