### ISSUE TITLE
nekonime.video

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#571]
**Sample URL**
https://nekonime.video/tenki-no-ko-subtitle-indonesia/
https://gilakerja.com/jangan-biarkan-corona-mematikan-brand-kamu/?link=aHR0cHM6Ly9zaGFyZXIucHcvZmlsZS9EV2tTLXRFbVVzOA==

**Penjelasan Lebih Lanjut**
continue linknya tidak muncul sama bisa ga diblock itu gan safelinknya

**Comment by realodix** [comment]
Kalau adblocknya dimatiin muncul gak?

**Comment by Recehan-Slayer** [comment]
`https://github.com/uBlockOrigin/uAssets/commit/04520adff05e250768ecba2ffb6d81e23fd4db8a`
muncul bro klo adblocknya dimatiin kemaren sebelum masuk filter uassets tpi klo adblocknya hidup ga muncul

**Comment by realodix** [comment]
Di Saya kok sama aja ya? Dimatiin dan dinyalain

**Comment by Recehan-Slayer** [comment]
coba link laen yg dr websitenya langsung gan

**Comment by realodix** [comment]
oh i see

**Comment by realodix** [comment]
Thank you
