### ISSUE TITLE
kiryuu.co

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#575]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://kiryuu.co/fff-class-trashero-chapter-25-bahasa-indonesia/

**Penjelasan Lebih Lanjut**
<details>

rightnative.com
![right native](https://user-images.githubusercontent.com/9379770/80547371-356a6200-89e2-11ea-9514-69a50e3af2c5.png)

**Comment by realodix** [comment]
Thank you
