### ISSUE TITLE
ngopibareng.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#579]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.ngopibareng.id/timeline/pasien-positif-corona-di-kabupaten-malang-bertambah-satu-2642464

**Penjelasan Lebih Lanjut**
iklan disebelah kanan bawah saat di schroll

**Comment by realodix** [comment]
Thank you
