### ISSUE TITLE
pucuktranslation.pw [Popups]

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#58]
https://pucuktranslation.pw/_go/sfWoDLfBg0x25Ust4QtFDlIIafHSsytOZHGKgQzVWfs=:Hr2MWnODCgIB19awICnYhA==
https://pucuktranslation.pw/_go/2DBXlJVog8ZirktvjFVPo3aM3MsfBJlD77iQLu2Kukk=:BYPML7g/mGRpLL2OSD/UnQ==

**Comment by realodix** [comment]
Thank you @WaferNabati
