### ISSUE TITLE
malangtimes.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#580]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://www.malangtimes.com/baca/50817/20200402/122100/kabar-baik-pasien-positif-corona-kabupaten-malang-sembuh-semua-tapi

**Penjelasan Lebih Lanjut**
Banner iklan

**Comment by realodix** [comment]
Thank you
