### ISSUE TITLE
suara.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#582]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.suara.com/news/2020/05/04/190127/puas-ml-ogah-bayar-pelanggan-yang-12-kali-tusuk-psk-abg-masih-misterius

**Penjelasan Lebih Lanjut**
ads dibawah artikel berita

**Comment by realodix** [comment]
Yang mana Gan?

**Comment by Recehan-Slayer** [comment]
@realodix 

![SUARA ADS](https://user-images.githubusercontent.com/9379770/81509990-e3f29900-9338-11ea-892b-370d9d89d27a.png)

**Comment by realodix** [comment]
Maaf Gan, ini masuknya `Websites’ own ads`, jadi Saya biarkan.

suara.com dan serbada.com dibawah satu grup http://arkadiacorp.com/
