### ISSUE TITLE
Iklan Detik.com

### ISSUE THREAD

**Issue by e-budianto** [realodix/AdBlockID#583]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
https://cdnstatic.detik.com/live/_type/timesignal/smartfren/200420-smartfren52GB-300x600-after-v1.jpg

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Ada samplenya urlnya gak? Maksudnya ketika buka halaman apa terjadinya popup?

**Comment by realodix** [comment]
Saya gak menemukan popup. Mungkin bisa kasih tahu Saya lebih detail
- Halaman detik yang mana?
- Filter apa saja yang digunakan?
