### ISSUE TITLE
dutafilm.red

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#587]
https://dutafilm.red/film/nonton-bodyguard-2020-avbvxx

![image](https://user-images.githubusercontent.com/19517680/87231058-28082580-c3de-11ea-9064-390fee792bff.png)

iklan pop up ketika play video

**Comment by realodix** [comment]
Thank you, update tersedia di [AdBlockID+](https://github.com/realodix/AdBlockID#cara-menggunakan)
