### ISSUE TITLE
blank frame ganool21.watch

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#588]
![image](https://user-images.githubusercontent.com/19517680/87446374-6b070a80-c623-11ea-8a25-3d40330a8dca.png)

https://ganool21.watch/

**Comment by 3xploiton3** [comment]
ini juga

https://terbit21.cool/

![image](https://user-images.githubusercontent.com/19517680/87446675-cc2ede00-c623-11ea-9335-5d15bba13ae8.png)

**Comment by realodix** [comment]
Di Saya biasa aja Bro, websitenya normal tidak broken. Hanya beberapa banner saja yang masih belum hilang.

<details>
  <summary>terbit21.cool</summary>

![index](https://user-images.githubusercontent.com/1314456/87709970-494a8680-c7cf-11ea-961e-37f5659bacee.png)
</details>

<details>
  <summary>ganool21.watch</summary>

![index2](https://user-images.githubusercontent.com/1314456/87710063-726b1700-c7cf-11ea-9b10-d15f31d1cd36.png)
</details>

**Comment by 3xploiton3** [comment]
aneh saya coba di device lain juga blank space

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/87817220-cab71d00-c892-11ea-9bf1-b7eb2451c52e.png)

masih ada banner ke https://bit.ly/agenbolaterbit

**Comment by realodix** [comment]
> 
> <details>
>  <summary>Screenshot</summary>
>
>  ![image](https://user-images.githubusercontent.com/19517680/87817220-cab71d00-c892-11ea-9bf1-b7eb2451c52e.png)
> </details>
>
> masih ada banner ke https://bit.ly/agenbolaterbit

Thank you
