### ISSUE TITLE
movienear.me [Anti adblock]

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#59]
Anti adblock, Popups, fake button

https://safelinkblog.com/PKms5t5
https://safelinkblog.com/m9yg

**Comment by WaferNabati** [comment]
@realodix diublock origin sudah gw request sih tpi mungkin diadblock atau adblock plus yg blom
`https://github.com/NanoMeow/QuickReports/issues/2150`

**Comment by realodix** [comment]
**Catatan**

> https://safelinkblog.com/PKms5t5
> https://safelinkblog.com/m9yg
_https://github.com/realodix/AdBlockID/issues/59#issue-514697407_

Link mengarah ke modebaca.com
