### ISSUE TITLE
samehadaku.vip

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#591]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://samehadaku.vip/one-piece-episode-935/

**Penjelasan Lebih Lanjut**
Iklan banner didalam video mas saat mau streaming

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/89131122-a450dd00-d534-11ea-8056-fa096f53f14a.png)

https://gomunime.com/one-piece-episode-924-sub-indo-6gpln/

**Comment by 3xploiton3** [comment]
https://samehadaku.vip/one-piece-episode-931/

**Comment by realodix** [comment]
Thank you
