### ISSUE TITLE
neonime.moe

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#593]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://neonime.moe/episode/pokemon-2019-23x31-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Thank you
