### ISSUE TITLE
aksensei.com

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#594]
**Sample URL**
https://www.aksensei.com/2020/08/goblin-slayer-goblins-crown-bd-sub-indo.html

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci.

**Comment by realodix** [comment]
Thank you, update tersedia di [AdBlockID+](https://github.com/realodix/AdBlockID#cara-menggunakan)
