### ISSUE TITLE
animelu.com

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#597]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://animelu.com
https://animelu.com/black-clover-tv-episode-137/

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Thank you
