### ISSUE TITLE
kiminime.com

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#598]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://kiminime.com/fruits-basket-season-2-episode-18

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
**Related**
- #509 

Thank you
