### ISSUE TITLE
korenime.org

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#599]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://korenime.org/kaguya-sama-wa-kokurasetai-episode-12-end-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
safelink

**Comment by realodix** [comment]
Safelinknya kenapa?

Saya temuin anti-adblock di [oploverznews.blogspot.com/2020/02...db66a67](https://oploverznews.blogspot.com/2020/02/one-piece-chapter-972-apakah-oden.html#?o=802b0785fc1c74aeb4bd2acd1590f8c85f20e6fd87709ed65d7fd5561e7db243af9b02504ab5facc2a02cdfadbc04b1bae8fe35ecdfb863faa0a1a2f575d5d1b864e59b99f0c29e693a1db819da9d70ce0e99c014db66a67)

**Comment by SuperMarioMakerII** [comment]
3rd party scripts gan

**Comment by SuperMarioMakerII** [comment]
3rd party safelink gan
https://raw.githack.com/jefcom/jefar/master/jefar.js

**Comment by realodix** [comment]
Thank you
