### ISSUE TITLE
sobatmovie21.fun

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#604]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://sobatmovie21.fun/the-secret-dare-to-dream-2020/

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
ganti domain ke sobatmovie21.pro
