### ISSUE TITLE
juragan-anime.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#61]
banner judi

https://www.juragan-anime.net/series/boruto-naruto-next-generations-sub-indo/

**Comment by realodix** [comment]
Sory gan, di mananya ya? atau ketika klik apa?

![screencapture-juragan-anime-net-series-boruto-naruto-next-generations-sub-indo-2019-11-02-14_45_25](https://user-images.githubusercontent.com/1314456/68067855-ac020c00-fd7f-11e9-9e79-32a84d442c65.png)

**Comment by WaferNabati** [comment]
kayaknya kasusnya seperti kmren.

**Comment by WaferNabati** [comment]
@realodix ngomong" filternya lebih lengkapan mana bro abpindo ama ini.

**Comment by realodix** [comment]
> kayaknya kasusnya seperti kmren.

OK Siap Bro, but thx ya udah lapor

**Comment by Recehan-Slayer** [comment]
banner judi baru

**Comment by realodix** [comment]
> 
> 
> banner judi baru
> `https://www.juragan-anime.net/`

Thank you
