### ISSUE TITLE
mangakita.net

### ISSUE THREAD

**Issue by RidhoAW** [realodix/AdBlockID#610]
**Jenis iklan** (hapus yang tidak perlu)
- Pop-up

**Sample URL**
https://mangakita.net/

**Penjelasan Lebih Lanjut**
Selalu muncul Pop-up setiap menklik layar Situs
![Screenshot_2020-08-24-14-09-02](https://user-images.githubusercontent.com/69678770/91014526-bd205000-e613-11ea-9d25-95c97beec75a.png)

**Comment by realodix** [comment]
Thank you
