### ISSUE TITLE
https://samehadaku.vip/

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#612]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://samehadaku.vip/

**Penjelasan Lebih Lanjut**
iklan di kanan atas

**Comment by gmarcher** [comment]
coba di update dulu, dari sini tidak ada masalah baik pakai ublock atau ABP. atau tlg berikan SS

**Comment by SuperMarioMakerII** [comment]
kemaren ada ikaln dr 3rdparty tp skrng uda masuk ublock filter/easylist kyknya

**Comment by realodix** [comment]
Duplicate of #591
