### ISSUE TITLE
nekopoi.care

### ISSUE THREAD

**Issue by SuperMarioMakerII** [realodix/AdBlockID#613]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
nekopoi.care

**Penjelasan Lebih Lanjut**
baner

**Comment by realodix** [comment]
Duplicate of #83

**Comment by Recehan-Slayer** [comment]
@realodix banner judi gan di versi mobilenya

**Comment by Recehan-Slayer** [comment]
masi ada bro 


![Uploading Screenshot_2021-03-30-22-43-04-634_com.kiwibrowser.browser.jpg…]()

**Comment by realodix** [comment]
> masi ada bro
> 
> Uploading Screenshot_2021-03-30-22-43-04-634_com.kiwibrowser.browser.jpg…

Gak bisa diklik

**Comment by Recehan-Slayer** [comment]
![Screenshot_2021-03-31-14-47-25-809_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/113109322-686e3480-91f5-11eb-824b-88b84520ef24.jpg)
