### ISSUE TITLE
Iklan di goblintvfree.com

### ISSUE THREAD

**Issue by chigarow** [realodix/AdBlockID#614]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://goblintvfree.com/

**Penjelasan Lebih Lanjut**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/19477257/92623712-d2be9680-f2f0-11ea-8fcc-0d97841fbb74.png">

**Comment by realodix** [comment]
Thank you

**Comment by chigarow** [comment]
![WhatsApp Image 2020-09-10 at 1 59 31 PM](https://user-images.githubusercontent.com/19477257/92692329-2fac6200-f36e-11ea-8fdb-945c47ef10bd.jpeg)
halo gan @realodix kalo di mobile masih muncul ya?
saya pake adguard mobile dan adblockid udah saya nyalain
