### ISSUE TITLE
goblintvfree.com (mobile web)

### ISSUE THREAD

**Issue by chigarow** [realodix/AdBlockID#615]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://goblintvfree.com/

**Penjelasan Lebih Lanjut**
<details>
  <summary>Screenshot</summary>
  
  ![image](https://user-images.githubusercontent.com/19477257/92697396-7a7da800-f375-11ea-9a3b-4a93094cc262.png)
</details>

**Comment by realodix** [comment]
Cona update filternya, barusan test di AdGuard mobile sudah bersih

**Comment by chigarow** [comment]
@realodix test nya di browser mana gan? ane coba di firefox dan edge masih muncul hehehe

ane coba di dua device

1. Redmi Note 3 Pro, Android 9 Liquid Remix OS

2. Xiaomi Mi 10, Android 10 MIUI

**Comment by realodix** [comment]
Pas nyoba kemarin, Saya baru nyoba di Chrome + AdGuard Android v4.0 nightly 1.

Hari ini baru nyoba lagi di Android, di beberapa browser berbeda dengan AdGuard Android v4.0 nightly 1 tetap diaktifkan

<details>
  <summary>Firefox Nightly 200909 + uBlock Origin</summary>

![unnamed](https://user-images.githubusercontent.com/1314456/92927597-17b90900-f468-11ea-9130-20dc1ff2fd0c.jpg)
</details>

<details>
  <summary>Edge 45.07.4.5059</summary>

![unnamed](https://user-images.githubusercontent.com/1314456/92927337-a8431980-f467-11ea-80b1-50172b4329bc.jpg)
</details>

<details>
  <summary>Kiwi Browser 77.0.3865.92  + uBlock Origin</summary>

![unnamed](https://user-images.githubusercontent.com/1314456/92927461-d9234e80-f467-11ea-95fe-5726cc396386.jpg)
</details>

---

Saya gak tahu apakah masalah ini ada di filter atau di aplikasi adblocker?

Saya perlu memastikan
- Filter apa saja yang agan gunakan?
- Apakah sudah diupdate filternya? goblintvfree.com sudah dimasukkan kemarin di [AdBlockID v20.253.1199](https://github.com/realodix/AdBlockID/commit/83f6f9da5285e5c08a5468ab9afabb8d87f9c99a#diff-461c718408241479cb8d1743512a73f8R2). Untuk AdGuard, saat ini versi terbaru [AdBlockID v2.0.4.22](https://github.com/AdguardTeam/FiltersRegistry/blob/4d08834058e515b039891659afdac9499fb0a05c/filters/ThirdParty/filter_120_AdBlockID/revision.json#L2)

**Comment by chigarow** [comment]
Nah ane udah cobain juga gan

Pake Firefox Nightly latest update

Ane lampirkan juga buat version dari adguard sama adblockid nya

Tapi ane ga nyalain ublock origin sih emang di Firefox nya

Cuma pake extension dark reader

![Screenshot_2020-09-12-23-53-28-363_com adguard android](https://user-images.githubusercontent.com/19477257/93000549-70190500-f553-11ea-972f-6b04c8531eb0.jpg)
![Screenshot_2020-09-12-23-53-23-562_com adguard android](https://user-images.githubusercontent.com/19477257/93000551-714a3200-f553-11ea-881a-bb252d9e1ed1.jpg)


![Screenshot_2020-09-12-23-53-56-839_org mozilla fenix](https://user-images.githubusercontent.com/19477257/93000548-6bece780-f553-11ea-8d9d-a70a8bf09a73.jpg)

**Comment by chigarow** [comment]
Ane pake ini filter yg aktif di adguard gan

Ad Blocking:
Peter Lowe's Blocklist,
AdGuard Mobile Ads,
AdGuard Base

Privacy:
EasyPrivacy,
AdGuard Tracking Protection,
Fanboy's Enhanced Tracking List

Annoyances:
Web Annoyances Ultralist,
Fanboy's Annoyances,
AdGuard Annoyances,
Adblock Warning Removal List

Security:
NoCoin Filter List,
Spam404,
Online Malicious URL Blocklist

Other:
AdGuard DNS

Language-specific:
AdBlockID,
ABPindo

**Comment by realodix** [comment]
Settingan sudah Saya samakan, di Chrome dan Edge tetap gak ada masalah.

Sepertinya masalah ada pada AdGuard.

**Comment by chigarow** [comment]
Oke okee makasih ya gan @realodix 
Ane coba raise issue di github nya adguard jugaa

**Comment by Alex-302** [comment]
Hi. HTTPS filtering is not working in Kiwi.
