### ISSUE TITLE
radarbogor.id

### ISSUE THREAD

**Issue by chigarow** [realodix/AdBlockID#617]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://www.radarbogor.id/2020/09/14/13-warga-ciawi-dan-cisarua-positif-covid-19-puncak-jadi-zona-merah/

**Penjelasan Lebih Lanjut**
![image](https://user-images.githubusercontent.com/19477257/93067999-1d9c2d80-f6a6-11ea-804f-1b507973eeb4.png)

**Comment by realodix** [comment]
Thank you
