### ISSUE TITLE
shirainime.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#619]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://shirainime.com/ore-wo-suki-nano-wa-omae-dake-ka-yo-oretachi-no-game-set-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
Judiu

**Comment by realodix** [comment]
Harusnya bersih, hanya saja sama uBlock filters `@@||shirainime.com^$generichide`

![Untitled](https://user-images.githubusercontent.com/1314456/93624393-7a7f4700-fa0a-11ea-924b-263bb79dfa6f.png)
