### ISSUE TITLE
layarkeren.site

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#623]
**Jenis iklan** (hapus yang tidak perlu)
- Lainnya

**Sample URL**
https://layarkeren.site/

**Penjelasan Lebih Lanjut**
overlay

**Comment by realodix** [comment]
Sepertinya sudah tidak ada overlay

**Comment by krystian3w** [comment]
`##.cm-popup-modal` / `###ouibounce-modal`

**Comment by realodix** [comment]
> `##.cm-popup-modal` / `###ouibounce-modal`

Terima kasih, sebenarnya ini sudah masuk di Fanboy’s Annoyance dan AdGuard Annoyances, jadi sudah bisa bersih.

Kedepan, Saya sedang mempertimbangkan untuk merampingkan AdBlockID dengan menghapus filter yang sudah ada di Fanboy’s Annoyance dan AdGuard Annoyances.
