### ISSUE TITLE
goblintv.xyz

### ISSUE THREAD

**Issue by chigarow** [realodix/AdBlockID#624]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop up (intermitten)

**Sample URL**

http://www.goblintv.xyz/

**Penjelasan Lebih Lanjut**
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19477257/94329539-020a1e80-ffe6-11ea-87f5-d1e0311623bd.png)

</details>

Panah merah: Banner

Kotak kuning: Kadang pop up membuka tab baru ketika list tersebut diklik.

**Comment by realodix** [comment]
Thank you

Dari kemarin coba klak klik klak klik kotak kuning, gak muncul popup Gan, jadi Saya gak bisa analisa.

**Comment by chigarow** [comment]
thanks gan @realodix
