### ISSUE TITLE
pikiran-rakyat.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#628]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.pikiran-rakyat.com/nasional/pr-01797813/bupati-bangka-tengah-ibnu-saleh-meninggal-dunia-usai-positif-covid-19

**Penjelasan Lebih Lanjut**

ads dibawah artikel gan

**Comment by realodix** [comment]
Ini dimananya ya? Di Saya gak ada, bisa SS gak?

**Comment by Recehan-Slayer** [comment]
@realodix itu gan dibawahnya artikel pilihan
![Opera Snapshot_2020-10-05_063511_www pikiran-rakyat com](https://user-images.githubusercontent.com/9379770/95029818-314f1880-06d5-11eb-9cf0-ef66c8392282.png)

**Comment by realodix** [comment]
Thank you
