### ISSUE TITLE
clampschoolholic.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#629]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.clampschoolholic.com/higurashi-no-naku-koro-ni-2020-sub-indo-eps-1/

**Penjelasan Lebih Lanjut**
popup sama close button

**Comment by realodix** [comment]
Thank you
