### ISSUE TITLE
disafelink.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#631]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://disafelink.com/m/POCoMDm

**Penjelasan Lebih Lanjut**
fake button

**Comment by realodix** [comment]
**Note:**
Terkadang mengarah ke https://link.kangapip.com

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix mengarah ke `https://s.kamerafoto.net/benefits-of-buying-car-insurance-online/` juga gan

**Comment by realodix** [comment]
> mengarah ke `https://s.kamerafoto.net/benefits-of-buying-car-insurance-online/` juga gan dan ada anti adblocknya

Thank you

**Comment by r3gamerz** [comment]
sekarang (7 des) mengarah ke https://litpets.website/benefits-of-annuities/ dan mengarah lagi ke https://m.nstnews.net/do-you-understand-how-annuities-work/

**Comment by realodix** [comment]
> sekarang (7 des) mengarah ke https://litpets.website/benefits-of-annuities/ dan mengarah lagi ke https://m.nstnews.net/do-you-understand-how-annuities-work/

@r3gamerz
Thanks untuk laporannya. Ini Fake button atau anti-adblock? Saya gak menemukan salah satunya.
