### ISSUE TITLE
sukacrot.site [NSFW]

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#634]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://sukacrot.site/bokep-indo-ferdian-paleka/

**Penjelasan Lebih Lanjut**
judi

**Comment by realodix** [comment]
Dimananya gan?

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2020-10-19 Bokep Indo Ferdian Paleka](https://user-images.githubusercontent.com/1314456/96420489-c7c82180-121f-11eb-8738-2ac01a23ffd3.jpg)
  ```
  
</details>

**Comment by Recehan-Slayer** [comment]
@realodix dibawah player
<details>

![Untitled](https://user-images.githubusercontent.com/9379770/96451324-99f3d480-1241-11eb-8ca7-f960d4e52137.png)

**Comment by realodix** [comment]
Thank you
