### ISSUE TITLE
Dutafilm.us

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#638]
![](https://i.imgur.com/yWDPpYB.jpg) 

https://dutafilm.us/seri/nonton-the-walking-dead-season-1-2010-doxt-1

**Comment by realodix** [comment]
Sorry, I'm on holiday

**Comment by realodix** [comment]
Thank you

**Comment by 3xploiton3** [comment]
Error malah gak bs diplay
![](https://i.imgur.com/sLGnkMh.jpg)

**Comment by realodix** [comment]
Sudah Saya benerin, barusan test video bisa diputar. 
Thank you

**Comment by 3xploiton3** [comment]
> Sudah Saya benerin, barusan test video bisa diputar.
> Thank you

masih error

coba cek link ini
https://dutafilm.us/seri/nonton-the-walking-dead-season-3-2012-doxt-3

episode ke 2 gak bisa di play

**Comment by realodix** [comment]
Di Saya gak ada masalah. Coba diupdate, AdBlockID seharusnya versi 20.303.806 atau di atas itu.

<details>
  <summary>Screenshot</summary>
  
![cats](https://user-images.githubusercontent.com/1314456/97625532-38aadd00-1a5b-11eb-894e-7568ff7e7892.jpg)

</details>
