### ISSUE TITLE
firefaucet.win

### ISSUE THREAD

**Issue by Alex-302** [realodix/AdBlockID#643]
### Issue URL (Anti Adblock Script)
 [https://firefaucet.win/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffirefaucet.win%2F)
### Comment

This is caused by `/blockadblock.$script`. Frequently used in anti-adblock checks.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/QbofUCo.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.12
Browser: | Firefox
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese, <br/>EasyList Czech and Slovak, <br/>AdBlockID, <br/>List-KR

**Comment by realodix** [comment]
Not reproduced. this 51ae56f  work?

**Comment by Alex-302** [comment]
Yes.
