### ISSUE TITLE
downloadbatch.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#646]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.downloadbatch.net/

**Penjelasan Lebih Lanjut**
banner ama situs judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix masih ada gan `https://formasibola.com/`

**Comment by realodix** [comment]
> masih ada gan `https://formasibola.com/`

Thank you
