### ISSUE TITLE
dutafilm.us

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#648]
![image](https://user-images.githubusercontent.com/19517680/97938837-10054900-1db5-11eb-8ce9-f91d6b138da7.png)

https://dutafilm.us/genre/musical

gambar thumnail hilang

mungkin rule ini yg harus dihilangkan
kotakputih.casa^$image,third-party

**Comment by realodix** [comment]
**Related**
- #638

---

Thank you
