### ISSUE TITLE
anoboy.stream

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#649]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://anoboy.stream/2020/11/high-school-fleet-movie/

**Penjelasan Lebih Lanjut**
judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix ada yg baru gan `https://bit.ly/anoboypw`

**Comment by realodix** [comment]
> ada yg baru gan `https://bit.ly/anoboypw`

Thank you
