### ISSUE TITLE
icutlink.com - popup dan notif yang mengganggu

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#65]
notif nya gan ganggu banget trus klo di klik ok muncul popups

https://icutlink.com/stmauX8nnp

**Comment by realodix** [comment]
Sepertinya penyebabnya ini

```
<script>
alert('Click OK to continue..');
if (window.confirm('Skip this site? '))
{
   window.open('
       https://zy16eoat1w.com/dqcmnz649a?key=74813d901412a08501e5879438504ad5', 
       '_blank'
   );
};
</script>
```

Saya lihat di https://github.com/uBlockOrigin/uAssets/issues/3979 pernah ditangani oleh mereka dengan berbagai scriptlet.

Solusi sementara, Saya cegah popup zy16eoat1w.com, agar bisa working di uBlock, AdGuard dan ABP.

**Comment by RaveN0X87** [comment]
notifnya emg ga bisa diblock ya gan kok kadang pas mau download movie akses ke shortlink itu masih ada notifnya

**Comment by realodix** [comment]
Barusan saya cek kembali, sudah tidak ada notif yang mengganggu. Untuk sementara Saya tutup dulu issue ini. Jangan ragu untuk comment jika ada yang perlu untuk ditangani.

**Comment by WaferNabati** [comment]
@realodix https://icutlink.com/etxQ4MWywp
masih ada popup dan notifnya brow

**Comment by realodix** [comment]
> https://icutlink.com/etxQ4MWywp
> masih ada popup dan notifnya brow

Thank you, akan Saya pisahkan pada issue baru
