### ISSUE TITLE
rebahin.me | 85.114.138.56

### ISSUE THREAD

**Issue by chigarow** [realodix/AdBlockID#650]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
http://85.114.138.56/
http://rebahin.me/

**Penjelasan Lebih Lanjut**
Screenshot
![image](https://user-images.githubusercontent.com/19477257/97990829-175b3f80-1e13-11eb-800a-ae4685b953b4.png)

**Comment by realodix** [comment]
Di Saya sudah ilang ini, karena sudah masuk filter semua. Mungkin bisa dijelaskan pakai filter apa saja?

<details>
  <summary>Screenshot</summary>
  
![cats](https://user-images.githubusercontent.com/1314456/98020639-d7598400-1e35-11eb-9d94-5c49ed62c0ad.jpg)
</details>

**Comment by chigarow** [comment]
Ini filter yang saya pakai ya

Ad Blocking:
AdGuard Base,
EasyList,
Peter Lowe's Blocklist

Privacy:
AdGuard Tracking Protection,
EasyPrivacy,
Fanboy's Enhanced Tracking List

Annoyances:
AdGuard Annoyances,
Fanboy's Annoyances,
Web Annoyances Ultralist,
Adblock Warning Removal List

Security:
Online Malicious URL Blocklist,
Spam404,
NoCoin Filter List

Other:
AdGuard DNS

Language-specific:
AdGuard Chinese,
ABPindo,
AdBlockID

**Comment by realodix** [comment]
Saya test di dengan ext AdGuard dan konfigurasi filter yang sama, hasilnya tetap sama, bersih dari iklan

<details>
  <summary>Screenshot</summary>
  
  ![cats](https://user-images.githubusercontent.com/1314456/98079830-107e0c80-1ea7-11eb-8390-cb2486b25eda.jpg)
</details>

**Comment by chigarow** [comment]
Nah... Di saya masih ada kenapa yak
Apa karena pake Adguard app yg for Mac, bukan extension sih
Dia tetep pake adblocker syntax kan?

**Comment by realodix** [comment]
Menurut Saya seharusnya sih sama saja antara AdGuard Browser extension dan AdGuard for Mac.

Saya coba memanggil tim dari AdGuard. Ping @Alex-302 @AdamWr

**Comment by Alex-302** [comment]
Also not reproduced on http://85.114.138.56/. Cannot open http://rebahin.me/
@chigarow Do you have antivirus? Which macos version?

**Comment by chigarow** [comment]
I just use Bitdefender Virus Scan, on demand virus scanner, but i dont think it has impact to the system, bcs it doesnt hv any realtime detection.
And my version of Mac OS is Catalina 10.15.7 (19H2)
@Alex-302

**Comment by Alex-302** [comment]
@chigarow In macos one app only can filter network. Could you please to remove Bitdefender just for test?

**Comment by chigarow** [comment]
I remove/uninstalled the Bitdefender and restart my mac
Then i re-check on this http://85.114.138.56/ but just realize the adguard assistant isnt there

![image](https://user-images.githubusercontent.com/19477257/98325279-01bb6500-2021-11eb-9d63-66b7c345fa14.png)

But for others website it works well
@Alex-302

**Comment by Alex-302** [comment]
Weird. Could you please check in another browser?

**Comment by chigarow** [comment]
Wow, somehow it fixed now, the url is redirect me directly to the site i want, thanks a lot @Alex-302 @realodix 
Can close this issue~
