### ISSUE TITLE
jefriapriyandi.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#652]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
http://jefriapriyandi.com/ghCkE
http://jefriapriyandi.com/lFS353Mt

**Penjelasan Lebih Lanjut**
fake button
popup

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix ini jg sama gan 
`http://womenhaircolors.review/3YMRd`
`http://fotodovana.com/3ni84Rro`

**Comment by realodix** [comment]
> @realodix ini jg sama gan
> `http://womenhaircolors.review/3YMRd`
> `http://fotodovana.com/3ni84Rro`

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix ini lg gan
http://luangusaha.com/PfD5Wo9

**Comment by realodix** [comment]
> ini lg gan
> http://luangusaha.com/PfD5Wo9

Thank you
