### ISSUE TITLE
clickyfly.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#656]
**Sample URL**
http://clickyfly.com/mBZhvB

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci.

**Comment by realodix** [comment]
Mengarah ke https://absolutesmmpanel.com/land/?at=https://myhiddentech.com/mBZhvB

**Comment by realodix** [comment]
Masih mengarah ke `https://absolutesmmpanel.com`
