### ISSUE TITLE
misayukiusagi.blogspot.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#657]
**Sample URL**
https://misayukiusagi.blogspot.com/2020/11/bocah-2014.html#?o=c90b99994454398551eb605d8bbcc52bcb7d186845e975f232c8f6e9c2ad79e3bbadf63574e5a3dd751d1d4864a652341464af79b47a03b5
https://misayukiusagi.blogspot.com/2020/10/like-dan-ikuti.html#?o=0b1b09611fff5760ab4ed46dca6041262600b8d3158e580a213a3dabc9f924f809aa35a5cba083119b0862b9a3a128faf7683821386ea2197558b44130f812edf4800320b29d740e

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci.

**Comment by realodix** [comment]
Thank you
