### ISSUE TITLE
Tidak bisa mem-bypass safelink di situs melongfilm.cc

### ISSUE THREAD

**Issue by mbakmanis** [realodix/AdBlockID#658]
**Sample URL**
https://www.melongfilm.cc/bring-me-home-2019/

**Penjelasan Lebih Lanjut**
Filter saat ini tidak bisa mem-bypass safelink situs tersebut.
Alamat safelink: maukredit.online

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2020-11-11-13-39-19](https://user-images.githubusercontent.com/58507846/98777655-0c8f4480-23e9-11eb-8be2-b8860b3cbda6.png)
</details>

<details>
  <summary>Screenshot 2</summary>
  
  ![Screenshot_2020-11-11-13-40-14](https://user-images.githubusercontent.com/58507846/98777772-3ba5b600-23e9-11eb-9c59-23155e7c055d.png)
</details>

**Comment by realodix** [comment]
> Filter saat ini tidak bisa mem-bypass safelink situs tersebut.
> Alamat safelink: maukredit.online

Kondisi tidak bisa mem-bypass, pakai plugin apa? Universal Bypass?

**Comment by mbakmanis** [comment]
Saya memakai uBlock Origin mas, di Kiwi Browser (Android)

**Comment by mbakmanis** [comment]
Filter yang saya pakai

![Screenshot_2020-11-11-14-40-27](https://user-images.githubusercontent.com/58507846/98783373-5d0aa000-23f1-11eb-9cf6-8aeb3b4de57e.png)

**Comment by realodix** [comment]
> Filter saat ini tidak bisa mem-bypass safelink situs tersebut.

Sepertinya Saya mulai paham. Saya pikir terjadi bug, gara-gara AdBlockID, situsnya tidak bisa di-bypass, makanya tadi Saya coba test dengan mematikan AdBlockID sepenuhnya.

Saat ini uBlock Origin hanya bisa digunakan untuk menggagalkan script pembuatan safelink secara otomatis.

**Comment by realodix** [comment]
Safelink ditulis manual, atau dibuat secara otomatis, lalu disimpan ke dalam database. Saya test dengan mematikan javascript sepenuhnya, link tetap ada.
