### ISSUE TITLE
lewat.club

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#66]
https://autoratio.com/UjFY

fake button

**Comment by realodix** [comment]
@WaferNabati Thank you :D

**Comment by WaferNabati** [comment]
@realodix https://autoratio.com/4CUnwU3Fph 
fake button setelah mengisi captcha

**Comment by realodix** [comment]
> @realodix https://autoratio.com/4CUnwU3Fph
> fake button setelah mengisi captcha

Thank you Bro

**Comment by WaferNabati** [comment]
@realodix update lg gan setelah captcha pada saat countdown 10 detik ada ads miyabi
