### ISSUE TITLE
maxnime.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#663]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.maxnime.com/

**Penjelasan Lebih Lanjut**
banner ads

**Comment by realodix** [comment]
Ini di bagian mananya Bro?

**Comment by Recehan-Slayer** [comment]
![Opera Snapshot_2020-11-18_171049_www maxnime com](https://user-images.githubusercontent.com/9379770/99516689-0f79ce80-29c1-11eb-9e75-2cb2ad3c1b13.png)

**Comment by realodix** [comment]
Thank you
