### ISSUE TITLE
bukalapak.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#667]
ads

**Sample URL**
https://www.bukalapak.com/products/s/alat-untuk-membuat

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.
![image](https://user-images.githubusercontent.com/19517680/100311082-790d6480-2fe1-11eb-8796-93118894e517.png)

```
<div tabindex="-1" class="bl-product-card__description"><div class="bl-product-card__description-name"><p class="bl-text bl-text--body-small bl-text--ellipsis__2"><a href="https://www.bukalapak.com/p/perawatan-kecantikan/makeup/mata/2vqjr0o-jual-alat-untuk-pasang-bulu-mata-511981?from=list-product&amp;keyword=alat%20untuk%20membuat&amp;funnel=omnisearch&amp;product_owner=normal_seller&amp;pos=0&amp;cf=1&amp;ssa=1&amp;sort_origin=relevansi&amp;search_sort_default=true&amp;promoted=1" class="bl-link">
            Alat Untuk Pasang Bulu Mata - 511981
          </a></p> <img src="https://s0.bukalapak.com/ast/bazaar-dweb/base/images/pc-ico-ads.png" alt="ico-promoted" width="16" height="16" title="Barang iklan" class="ml-4" style="flex-shrink: 0;"></div> <!----> <div class="bl-product-card__description-price"><p class="bl-text bl-text--subheading-2 bl-text--semi-bold bl-text--ellipsis__1">
          Rp11.400
        </p> <div class="bl-product-card__description-price-discount"><span class="mr-4 bl-text bl-text--body-small bl-text--subdued" style="text-decoration: line-through;">
            Rp12.000
          </span> <span class="bl-text bl-text--caption bl-text--error">
            -5%
          </span></div></div> <div class="bl-product-card__description-rating-and-sold"><!----> <!----> <!----></div> <div class="bl-product-card__description-store"><span class="mr-4 bl-product-card__location bl-text bl-text--body-small bl-text--subdued bl-text--ellipsis__1">
          Jakarta Barat
        </span> <span class="bl-product-card__store bl-text bl-text--body-small bl-text--subdued bl-text--ellipsis__1" wfd-invisible="true"><a href="https://www.bukalapak.com/u/ayralapak" class="bl-link">
            AYRALAPAK
          </a></span> <div title="superseller" class="ml-4 bl-emblem bl-emblem--superseller_icon te-superseller_icon" style="flex-shrink: 0;"></div></div> <div class="bl-product-card__description-feedback"><span class="bl-text bl-text--body-small bl-text--subdued bl-text--ellipsis__1" wfd-invisible="true"><a href="https://www.bukalapak.com/u/ayralapak/feedback?feedback_as=as_seller&amp;filter_by=all" class="bl-link">
            563 Feedback Positif
          </a></span></div> <!----></div>
```

**Comment by realodix** [comment]
Saya tidak menemukannya, hasil pencariannya berbeda seperti di SS dan Kita sudah memiliki filter `bukalapak.com###product-explorer-container .bl-product-card:-abp-has(img[src*="pc-ico-ads." i])` ([ca01e73#diff-3f27ac8](https://github.com/realodix/AdBlockID/commit/ca01e73f6d23a17f84fc64e70332ec35f016ada0#diff-3f27ac85795a54da9258ffd97c67a3c54a289c01f15648cacbda62b7cf8ef5eaR2191))

Apakah ini butuh login?

**Comment by realodix** [comment]
**Related**
- #515
- #608

---

Saya sudah coba login beberapa kali di waktu yang berbeda, hasilnya masih tetap sama.

**Comment by 3xploiton3** [comment]
saya tidak login, memang acak ads, tp ada simbol seperti toa kecil di gambar produk sblah kanan

**Comment by 3xploiton3** [comment]
ini ada lagi
https://www.bukalapak.com/products?search%5Bkeywords%5D=cukur
![image](https://user-images.githubusercontent.com/19517680/100458591-9d0e9a00-30f6-11eb-9699-fe8400ab8104.png)

**Comment by 3xploiton3** [comment]
> ads
> 
> **Sample URL**
> https://www.bukalapak.com/products/s/alat-untuk-membuat
> 
> **Penjelasan Lebih Lanjut**
> Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.
> ![image](https://user-images.githubusercontent.com/19517680/100311082-790d6480-2fe1-11eb-8796-93118894e517.png)

yg ini sudah gak muncul

**Comment by realodix** [comment]
Ini menggunakan AdGuard ya?

**Comment by 3xploiton3** [comment]
> Ini menggunakan AdGuard ya?

iya, sudah update terbaru versi beta

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/100587507-3de19d00-3323-11eb-95ed-8f4f73a6cbfa.png)

di log blm filter blm terbaca

**Comment by realodix** [comment]
> <details>
>   <summary>Screenshot</summary>
>   
>   ![image](https://user-images.githubusercontent.com/19517680/100587507-3de19d00-3323-11eb-95ed-8f4f73a6cbfa.png)
> </details>
>
> di log blm filter blm terbaca

Sudah Saya coba perbaiki
