### ISSUE TITLE
conan.id [Ads]

### ISSUE THREAD

**Issue by KagaKouko99** [realodix/AdBlockID#67]
https://www.conan.id/

iklan judi

**Comment by realodix** [comment]
@KagaKouko99 Thank you :D

**Comment by Arsindy** [comment]
@realodix iklan judi gan dibagian atas

**Comment by realodix** [comment]
> @realodix iklan judi gan dibagian atas
> sma disini atas video player
> `https://www.conan.id/shinchou-yuusha-episode-08-subtitle-indonesia/`

Sepertinya sudah tidak ada iklannya

![screencapture-conan-id-shinchou-yuusha-episode-08-subtitle-indonesia-2019-11-28-17_01_02](https://user-images.githubusercontent.com/1314456/69796513-c1dce280-1200-11ea-992a-a8aca5a6845b.png)

**Comment by 3xploiton3** [comment]
@realodix 

![](https://i.imgur.com/ecOhgFW.jpg)

Di tampilan hp msh ada banner

**Comment by realodix** [comment]
@Arsindy @3xploiton3 

Owh Saya ngerti sekarang. AdGuard ya?

Saat ini ada bug pada AdGuard yang menyebabkan rule pada file [/src/addons/adult-hide.adbl](https://github.com/realodix/AdBlockID/blob/master/src/addons/adult-hide.adbl) dianggap tidak valid semua.

Beberapa hari yang lalu Saya sudah melaporkannya
`https://github.com/AdguardTeam/FiltersRegistry/issues/259`

Untuk saat ini Saya sedang mengakalinya di https://github.com/realodix/AdBlockID/pull/85
