### ISSUE TITLE
drakorindo.work

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#671]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://drakorindo.work/

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
**Related**
- #672
- #673
- #674
- #675

---

Thank you

**Comment by realodix** [comment]
**Related**
- #672
- #673
- #674
- #675

---

Thank you

**Comment by Recehan-Slayer** [comment]
masi ada gan
![Opera Snapshot_2020-11-27_175918_drakorindo work](https://user-images.githubusercontent.com/9379770/100442281-4f843400-30da-11eb-817a-8d538aa8e400.png)

**Comment by realodix** [comment]
Thank you
