### ISSUE TITLE
inidramaku.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#674]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Lainnya

**Sample URL**
https://inidramaku.net/

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
**Related**
- #672
- #673
- #675

---

Thank you

**Comment by Recehan-Slayer** [comment]
masi ada gan

![Opera Snapshot_2020-11-27_180152_inidramaku net](https://user-images.githubusercontent.com/9379770/100442482-b0ac0780-30da-11eb-9e38-8a857de0ca90.png)
