### ISSUE TITLE
kingdrakor.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#675]
**Jenis iklan** (hapus yang tidak perlu)
- Banner

**Sample URL**
https://kingdrakor.net/

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
**Related**
- #672
- #673
- #674

---

Thank you

**Comment by Recehan-Slayer** [comment]
judi baru gan

**Comment by realodix** [comment]
> 
> 
> judi baru gan

Thank you
