### ISSUE TITLE
jatim.suara.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#676]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://jatim.suara.com/read/2020/11/24/085629/waduh-warga-sedusun-di-kota-batu-terpapar-covid-19-usai-melayat-tetangga

**Penjelasan Lebih Lanjut**
![Opera Snapshot_2020-12-06_200005_jatim suara com](https://user-images.githubusercontent.com/9379770/101280810-c669ad00-37fd-11eb-88cd-6e81276b2ea1.png)

**Comment by realodix** [comment]
Thank you
