### ISSUE TITLE
doktersehat.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#679]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://doktersehat.com/susu-kental-manis-bikin-diabetes/

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Thank you
