### ISSUE TITLE
sukakesehattan.com

### ISSUE THREAD

**Issue by KagaKouko99** [realodix/AdBlockID#68]
https://sukakesehattan.com/full/?api=a43e9781fc804e34814e29bf4c2bb518989da6ad&url=https%3A%2F%2Fdrive.google.com%2Fuc%3Fexport%3Ddownload%26id%3D1q0FtUOb1kTehSW_BbBolU1g5mbut1O63&type=2

Fake button

**Comment by realodix** [comment]
@KagaKouko99 Thank you

**Comment by realodix** [comment]
Ganti jadi semawur.com (#91)
