### ISSUE TITLE
anime.tohaboy.web.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#680]
**Sample URL**
https://anime.tohaboy.web.id/

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci.

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix di safelinknya ada anti adblocknya gan

**Comment by realodix** [comment]
> di safelinknya ada anti adblocknya gan

Alamat safelinknya tohaboy.web.id juga kan? Harusnya sudah deh, nanti Saya cek lagi deh

**Comment by realodix** [comment]
Fixed, thank you
