### ISSUE TITLE
disafelink.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#681]
**Sample URL**
https://disafelink.com/m/99Ba

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci.

**Comment by realodix** [comment]
Ini domainnya memang mengarah ke leafpro.website ya atau sebelumnya disafelink.com?

**Comment by Recehan-Slayer** [comment]
ganti" bro

**Comment by realodix** [comment]
OK thanks

**Comment by Recehan-Slayer** [comment]
@realodix antin adblock

**Comment by realodix** [comment]
Domain:
- plantqo.website

---

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix anti adblock

**Comment by realodix** [comment]
> 
> 
> anti adblock

Thank you
