### ISSUE TITLE
zxcfiles.com

### ISSUE THREAD

**Issue by febrianbs** [realodix/AdBlockID#683]
**Sample URL**
https://zxcfiles.com/

**Penjelasan Lebih Lanjut**
Saat membuka situs ini masih terdeteksi.
![Screenshot_2020-12-28-11-10-59-032_mark via gp](https://user-images.githubusercontent.com/16359705/103189070-9a71b100-48fd-11eb-95e7-b7b7bbe534a7.jpg)

**Comment by realodix** [comment]
Sepertinya ini shortlink ya? Di Saya gak terdeteksi ada peringatan anti-adblock. Bisa minta link full nya gak atau ini link dapatnya dari mana?

**Comment by febrianbs** [comment]
Coba dengan link ini
http://zxcfiles.com/3aud28hp94i0

**Comment by realodix** [comment]
Saya masih belum melihat peringatan anti-adblock

**Comment by febrianbs** [comment]
Barusaja Update List.
Easylist tak matikan terus tersisa Adblok id ini saja. Hasilnya masih sama terdeteksi
![Uploading Screenshot_2020-12-29-18-10-07-618_mark.via.gp.jpg…]()

**Comment by realodix** [comment]
Baru muncul nih peringatannya. Thank you

**Comment by febrianbs** [comment]
Mantappu... 😁👍🏻👍🏻👍🏻
