### ISSUE TITLE
oploverz.in

### ISSUE THREAD

**Issue by febrianbs** [realodix/AdBlockID#684]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://oploverz.in

**Penjelasan Lebih Lanjut**
Masih ada iklan klik, popup, dan banner.

![Screenshot_2020-12-28-11-13-54-740_mark via gp](https://user-images.githubusercontent.com/16359705/103189148-e3296a00-48fd-11eb-8d35-8d25268fad04.jpg)

**Comment by realodix** [comment]
**Related**
- #507
- #606
- #659

---

Thank you

**Comment by febrianbs** [comment]
Terima Kasih Kembali. 🙏🏻😁

**Comment by febrianbs** [comment]
Case Closed ini berati gimana ? Tidak bisa di bersihkan iklannya ya ?

**Comment by realodix** [comment]
> Case Closed ini berati gimana ? Tidak bisa di bersihkan iklannya ya ?

> https://github.com/realodix/AdBlockID/issues/659#issuecomment-752282548 Belum sembuh ya ini berati... Iklannya masih ada.🤔

Iklannya yang mana ya Bro?

**Comment by febrianbs** [comment]
Iklan ini...
![Screenshot_2020-12-30-09-37-41-295_mark via gp](https://user-images.githubusercontent.com/16359705/103326398-b488cc00-4a82-11eb-8376-2d52ff2d84cd.jpg)

**Comment by realodix** [comment]
Di HP pakai AdBlocker apa dan filternya apa saja? Akan Saya samakan untuk diteliti lebih lanjut

**Comment by febrianbs** [comment]
> Di HP pakai AdBlocker apa dan filternya apa saja? Akan Saya samakan untuk diteliti lebih lanjut

Biasanya easylist, tapi AdblockId lebih manteb, bisa tanpa detect (menurut saya paling penting ini). @realodix bener bener keren 👍🏻😁.

Jadi sekarang yang saya on kan hanya AdblockId saja.
Browser pakai Via karena bisa link ke ADM juga. Adakah rekomendasi browser kesukaan mimin ?

![IMG_20201230_094819](https://user-images.githubusercontent.com/16359705/103326786-860bf080-4a84-11eb-9bb3-4aeab1156ecf.jpg)

**Comment by realodix** [comment]
Terima kasih sudah menggunakan AdBlockID sebagai filter default. Btw ADM itu Advanced Download Manager atau apa ya? Saya kurang paham di sini.

<details>
  <summary>Screenshot</summary>
  
  ![cats](https://user-images.githubusercontent.com/1314456/103327543-88237e80-4a87-11eb-87ac-0e67e5edea4e.jpg)
</details>

Saya mulai paham sekarang kena iklannya tetap muncul.

Via Browser kalau Saya baca helpnya, mereka menggunakan [AdBlock Plus](https://adblockplus.org/) sebagai software AdBlock bawaan. Sekitar 20% hingga 30% fitur tambahan AdBlockID tidak dapat berjalan di AdBlock Plus. Cukup banyak web menggunakan teknik yang cukup rumit untuk menampilkan iklan dan memblokir software AdBlock, jadi fitur tambahan ini cukup penting.

> Adakah rekomendasi browser kesukaan mimin ?

Ada beberapa opsi untuk dapat menikmati fitur tambahan AdBlockID
1. Gunakan [AdGuard](https://adguard.com), Saya pribadi menggunakan ini di HP, karena bisa menggunakan browser apa saja yang Saya suka, tanpa terpatok apakah di browser tersebut ada software AdBlock bawaan atau tidak.
2. Gunakan [Firefox](https://www.mozilla.org/id/firefox/mobile/) atau bisa juga [Kiwi Browser](https://kiwibrowser.com/) (mirip banget sama Chrome ini), lalu install extensi uBlock Origin.

**Comment by febrianbs** [comment]
> Terima kasih sudah menggunakan AdBlockID sebagai filter default. Btw ADM itu Advanced Download Manager atau apa ya? Saya kurang paham di sini.
> 
> Screenshot
> Saya mulai paham sekarang kena iklannya tetap muncul.
> 
> Via Browser kalau Saya baca helpnya, mereka menggunakan [AdBlock Plus](https://adblockplus.org/) sebagai software AdBlock bawaan. Sekitar 20% hingga 30% fitur tambahan AdBlockID tidak dapat berjalan di AdBlock Plus. Cukup banyak web menggunakan teknik yang cukup rumit untuk menampilkan iklan dan memblokir software AdBlock, jadi fitur tambahan ini cukup penting.
> 
> > Adakah rekomendasi browser kesukaan mimin ?
> 
> Ada beberapa opsi untuk dapat menikmati fitur tambahan AdBlockID
> 
> 1. Gunakan [AdGuard](https://adguard.com), Saya pribadi menggunakan ini di HP, karena bisa menggunakan browser apa saja yang Saya suka, tanpa terpatok apakah di browser tersebut ada software AdBlock bawaan atau tidak.
> 2. Gunakan [Firefox](https://www.mozilla.org/id/firefox/mobile/) atau bisa juga [Kiwi Browser](https://kiwibrowser.com/) (mirip banget sama Chrome ini), lalu install extensi uBlock Origin.

Muantappppp... Penjelasannya sangat memuaskan...
Sepertinya saya harus stop pakai VIA. Meluncur ke Kiwi... 😁. Terima Kuasih Buanyak... Adguard bagi saya akan jadi opsi terakhir... 😁😁😁

**Comment by febrianbs** [comment]
Mohon Maaf.
Tanya di luar topik.

Jadi sebenarnya di gabung dengan filter lain tidak masalah ya.. yang masalah adalah browsernya.

**Comment by realodix** [comment]
> Jadi sebenarnya di gabung dengan filter lain tidak masalah ya.. yang masalah adalah browsernya.

Gak masalah, karena setiap filter kan punya kelebihan di bidangnya masing2. Yang terpenting jangan kebanyakan saja, berpotensi jadi berat. Disarankan untuk menggunakan [EasyList](https://filterlists.com/lists/easylist) atau [AdGuard Base Filter](https://filterlists.com/lists/adguard-base-filter-ublock-origin) sebagai filter pokok juga, karena AdBlockID dan filter regional lainnya didesain untuk melengkapi kedua filter tersebut. Biasanya kalau kita install software adblock, salah satu dari kedua filter tersebut sudah ada sih.

> Mohon Maaf.
> Tanya di luar topik.

Iya gak apa-apa. Tapi menurut Saya jika ada pertanyaan, akan lebih baik buat issue baru atau buat diskusi di [AdBlockID/discussions](https://github.com/realodix/AdBlockID/discussions). DIharapkan jika orang lain yang membutuhkan informasi yang sama jadi bisa tahu juga.

**Comment by febrianbs** [comment]
Terima Kasih @realodix ... Sarannya sangat bagus dan membantu... Sekarang bisa browsing bebas iklan...
😁😁😁
