### ISSUE TITLE
timesindonesia.co.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#685]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.timesindonesia.co.id/read/news/318350/pemkab-malang-siapkan-rapid-test-antigen-untuk-pendatang

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Thank you
