### ISSUE TITLE
jatimtimes.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#686]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://jatimtimes.com/baca/232188/20201228/174300/bupati-malang-sanusi-mengaku-siap-disuntik-vaksin-covid-19-pertama-di-kabupaten-malang

**Penjelasan Lebih Lanjut**
Jika diperlukan, Anda dapat menjelaskannya secara rinci atau memberikan gambar screenshot.

**Comment by realodix** [comment]
Thank you
