### ISSUE TITLE
Terdeteksi Adblock

### ISSUE THREAD

**Issue by febrianbs** [realodix/AdBlockID#687]
**Sample URL**
https://www.dramazon.id/2020/11/nonton-film-the-swordsman.html

**Penjelasan Lebih Lanjut**
Terdeteksi Adblock

**Senjata***
Google Chrome + Ublock Origin + AdBlockID filter, Ublock, Easylist

**ScreenShoot**
![2021-01-02_085700](https://user-images.githubusercontent.com/16359705/103449374-04ad9b80-4cda-11eb-8ec1-ffa3e32cae27.png)

**Comment by febrianbs** [comment]
My Bad... Sorry 😅😁

**Comment by febrianbs** [comment]
Nunggu sekitar 10 detik, baru muncul Deteksi Adblock. 
@realodix

**Comment by realodix** [comment]
Thank you
