### ISSUE TITLE
movienear.me 

### ISSUE THREAD

**Issue by RaveN0X87** [realodix/AdBlockID#69]
https://www.shrinkads.com/full/?api=d1f51d5bad4cd73415c25c2863c05189942a3b35&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MVZsc21QR0YzR1NsS19pc3hVTGY2anNhcjdhV2tMOHRT&type=2

https://www.safelinkblog.com/PKms5t5

bokep button

**Comment by realodix** [comment]
@RaveN0X87 Thank you
