### ISSUE TITLE
mangaku.pro

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#696]
**Jenis iklan**
- Pop-up
- Lainnya

**Sample URL**
https://mangaku.pro/jagaaaaaan-chapter-109/

**Penjelasan Lebih Lanjut**
kadang klo pas klik kiri muncul popup ke situs judi sama anti klik kanan dll

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix popupnya masi ada gan setiap di clear cookies dan chache situsnya mengarah ke `http://172.105.216.174/`

**Comment by realodix** [comment]
> popupnya masi ada gan setiap di clear cookies dan chache situsnya mengarah ke `http://172.105.216.174/`

Di Saya gak muncul Gan. Coba ini deh `mangaku.pro##+js(acis, popup)` atau `mangaku.pro##+js(window.open-defuser)`

**Comment by Recehan-Slayer** [comment]
@realodix masi muncul gan popupnya tp setelah pakai filter yg diatas uda ga

**Comment by realodix** [comment]
Yang mana tuh Gan? `mangaku.pro##+js(acis, popup)` atau `mangaku.pro##+js(window.open-defuser)`?

**Comment by Recehan-Slayer** [comment]
yg ke 2

**Comment by Recehan-Slayer** [comment]
@realodix di hp/mobile mode juga muncul popupnya bro pke rule yg ke 2 uda fix jg dan blank space dibagian atas dibawah judul chapter
https://mangaku.pro/tensei-shitara-slime-datta-ken-chapter-56/

**Comment by realodix** [comment]
> di hp/mobile mode juga muncul popupnya bro pke rule yg ke 2 uda fix jg dan blank space dibagian atas dibawah judul chapter
> https://mangaku.pro/tensei-shitara-slime-datta-ken-chapter-56/

Ok Thankn you Gan. Saya bener-bener gak bisa reproduce issue ini mulai dari popup hingga blank space nya

**Comment by Recehan-Slayer** [comment]
@realodix https://mangaku.pro/solo-leveling-chapter-152/
Banner judi di mobile bro

**Comment by realodix** [comment]
> 
> 
> @realodix https://mangaku.pro/solo-leveling-chapter-152/
> Banner judi di mobile bro

Thank you
