### ISSUE TITLE
doujindes.blogspot.com

### ISSUE THREAD

**Issue by chigarow** [realodix/AdBlockID#698]
**Jenis iklan**
- Pop-up
- Something blocking for click

**Sample URL**
https://doujindes.blogspot.com/

**Penjelasan Lebih Lanjut**

Try to open the site, then wait until it fully loaded, then try to click. Any image and label cannot be clicked.

---

**Software:**
AdGuard for Mac v2.5.1.928 release

**Filters:**
Ad Blocking:
AdGuard Base,
EasyList,
Peter Lowe's Blocklist

**Privacy:**
AdGuard Tracking Protection,
EasyPrivacy,
Fanboy's Enhanced Tracking List

**Annoyances:**
AdGuard Annoyances,
Fanboy's Annoyances,
Adblock Warning Removal List

**Security:**
Online Malicious URL Blocklist,
Spam404,
NoCoin Filter List

**Other:**
AdGuard DNS

**Language-specific:**
ABPindo,
AdBlockID

**Custom:**
https://block.energized.pro/spark/formats/filter

**Comment by realodix** [comment]
Thank you
