### ISSUE TITLE
detik.com

### ISSUE THREAD

**Issue by chigarow** [realodix/AdBlockID#702]
**Jenis iklan**

**Sample URL**
https://detik.com/

**Penjelasan Lebih Lanjut**
Screenshot:
<details>

![image](https://user-images.githubusercontent.com/19477257/106255318-7979e400-624c-11eb-8dfc-e7d07c848c1e.png)

</details>

**Comment by realodix** [comment]
Sry ini masuknya masih gak masalah Gan.

**Comment by chigarow** [comment]
oh gituu, oke okee gan thankyouu juga

**Comment by realodix** [comment]
Kalau ketemu situs koran lokal, mungkin bisa bantu lapor Gan. Mereka biasanya suka pasang banyak banner.

<details>
  <summary>Screenshot</summary>
  
  ![cats](https://user-images.githubusercontent.com/1314456/106258478-73860200-6250-11eb-8ecc-5cae4a24218a.jpg)
</details>

**Comment by chigarow** [comment]
ini ada sih gan ane karena tinggal di Bogor, jadi sering buka https://radarbogor.id
<details>

![image](https://user-images.githubusercontent.com/19477257/106258726-cd86c780-6250-11eb-99ce-ef198b83af4d.png)


</details>

Mau dibuat ticket issue nya?

**Comment by realodix** [comment]
> ini ada sih gan ane karena tinggal di Bogor, jadi sering buka https://radarbogor.id
> 
> Mau dibuat ticket issue nya?

Mantap!
Gak usah, gpp Gan, sudah langsung Saya tangani.

**Comment by chigarow** [comment]
wokeee gan thankyouu yaap!

**Comment by 3xploiton3** [comment]
> Sry ini masuknya masih gak masalah Gan.
> 
> Terima kasih sudah melapor

kalau menurut saya termasuk mengganggu, klo pakai adguard filter annoyance, video sudah hilang

**Comment by realodix** [comment]
Prinsip dasarnya AdBlockID didesain untuk menghilangkan iklan, bukan untuk menghilangkan komponen yg mengganggu (popup, banner cookie, dll).

Berhubung komponen Annoyance suka digunakan untuk menampilkan iklan, makanya suka Saya block juga dalam beberapa situs, seperti situs nonton. 

Dalam kasus ini, Saya lihat popup videonya digunakan bukan digunakan untuk menampilkan iklan, makanya Saya tag Invalid.

**Comment by 3xploiton3** [comment]
@realodix misal dibuat lagi filter utk annoyance gmn bro?

Cookie banner
Video autoplay
Pop up
Dll
