### ISSUE TITLE
carisinyal.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#703]
**Jenis iklan**
Overlay

**Sample URL**
https://carisinyal.com/aplikasi-lirik-lagu-untuk-pc/

**Penjelasan Lebih Lanjut**
<details>

![Opera Snapshot_2021-01-30_225542_carisinyal com](https://user-images.githubusercontent.com/9379770/106361055-6ea77800-634e-11eb-912c-5635132b71c3.png)

**Comment by realodix** [comment]
Ini di Saya bersih gan? Kondisinya pas sedang apa ya?

**Comment by Recehan-Slayer** [comment]
ntah skrng kyknya g muncul lg kmaren tiba" muncul pas prtama buka

**Comment by realodix** [comment]
OK deh, thank you Gan sudah lapor
