### ISSUE TITLE
komikmoe.my.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#707]
**Sample URL**
https://komikmoe.my.id/sweet-guy-chapter-6/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
**Related**
- https://github.com/realodix/AdBlockID/issues/705

===

komikmoe.my.id masih Gan? Di Saya sudah nggak ada peringatan anti-adblock

**Comment by Recehan-Slayer** [comment]
oh iya lupa gw update bro
