### ISSUE TITLE
didrakorindo.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#715]
**Jenis iklan**
- Banner

**Sample URL**
https://didrakorindo.com/

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
judi baru gan

**Comment by realodix** [comment]
> 
> 
> judi baru gan

Thank you

**Comment by Recehan-Slayer** [comment]
judi baru bre

**Comment by realodix** [comment]
> judi baru bre

Thank you Bre

**Comment by Recehan-Slayer** [comment]
judi baru gan

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
banner judi bro

**Comment by realodix** [comment]
> 
> 
> banner judi bro

Thank you
