### ISSUE TITLE
drakorasia.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#717]
**Jenis iklan**
- Banner

**Sample URL**
https://drakorasia.net/

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
judi baru gan

**Comment by realodix** [comment]
> judi baru gan

Thank you

**Comment by Recehan-Slayer** [comment]
judi baru bro

**Comment by realodix** [comment]
> 
> 
> judi baru bro

Thank you
