### ISSUE TITLE
multiup.org

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#72]
https://multiup.org/ddee0948bf683fa1c967ce28923926f2
https://multiup.org/0a0c8199029c5c67a3cf4e8b2ec2e023

tidak bisa masuk ke filehosting nya gan klo adblocknya hidup selalu diarahkan ke ads

**Comment by realodix** [comment]
Thank you

**Comment by WaferNabati** [comment]
@realodix masalahnya masih ada gan coba masuk terus pilih salah satu filehostingnya. 
kebanyakan diarahkan ke ads seperti amazon dll tidak diarahkan ke link tujuan

**Comment by realodix** [comment]
@WaferNabati Ternyata lebih rumit dari yang dibayangkan Bro.

Beberapa referensi yang Saya baca, ternyata tim uBlock Filters juga sedang menangani ini sejak lama. 
- https://github.com/NanoMeow/QuickReports/issues/2096
- https://github.com/uBlockOrigin/uAssets/issues/5435

Saat ini hasilnya masih tetap suka redirect ke iklan

**Comment by WaferNabati** [comment]
@realodix ini skrng klo pke UB link iklan didalam tombolnya bisa diblock klo pke adblocker ga bisa ya???
