### ISSUE TITLE
melongmovie.com

### ISSUE THREAD

**Issue by mbakmanis** [realodix/AdBlockID#736]
**Jenis iklan**
- Iklan Banner

**Sample URL**
https://melongmovie.com/the-peanuts-movie-2015/

**Penjelasan Lebih Lanjut**
<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2021-02-09-13-38-28](https://user-images.githubusercontent.com/58507846/107326181-97add280-6add-11eb-9193-7193766bc3a8.png)
</details>

**Comment by realodix** [comment]
Thank you
