### ISSUE TITLE
anoboy.tube

### ISSUE THREAD

**Issue by mbakmanis** [realodix/AdBlockID#737]
**Jenis iklan**
- Iklan Banner

**Sample URL**
https://anoboy.tube/2021/01/wonder-egg-priority/

**Penjelasan Lebih Lanjut**

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2021-02-09-13-37-36](https://user-images.githubusercontent.com/58507846/107326647-6550a500-6ade-11eb-9cf4-d9bd119e0140.png)
</details>

**Comment by realodix** [comment]
**Related**
- #662

---

Sorry, ini pakai filter apa aja ya? Di Saya sudah bersih

**Comment by mbakmanis** [comment]
Saya make filter ini mas

![Screenshot_2021-02-09-19-16-53](https://user-images.githubusercontent.com/58507846/107362842-e1151680-6b0b-11eb-8111-ea79db4412ae.png)

**Comment by realodix** [comment]
Di halaman Filterlist, ada tulisan `Ignore generic cosmetic filters`, sudah dipastikan itu tidak tercentang?

**Comment by mbakmanis** [comment]
Tercentang mas (settingan default ublock origin)
Harus dinonaktifkan kah?

![Screenshot_2021-02-09-20-07-38](https://user-images.githubusercontent.com/58507846/107368064-a793d980-6b12-11eb-93d3-ea2bb36dbdef.png)

**Comment by mbakmanis** [comment]
Makasih mas. Setelah menonaktifkan ignore generic cosmetic filters, issue #737 #738 #739 sudah solved 👍

**Comment by realodix** [comment]
Terima kasih sudah melapor
