### ISSUE TITLE
otakudesu.tv

### ISSUE THREAD

**Issue by mbakmanis** [realodix/AdBlockID#738]
**Jenis iklan**
- Iklan Pop-up

**Sample URL**
https://otakudesu.tv

**Penjelasan Lebih Lanjut**
<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2021-02-09-14-14-44](https://user-images.githubusercontent.com/58507846/107328729-c037cb80-6ae1-11eb-82f5-b5cb74150fbc.png)
</details>

**Comment by realodix** [comment]
Sorry, Saya gak bisa reproduce issue ini. BUtuh info filter apa saja yang aktif, pakai adblock apa?

**Comment by realodix** [comment]
Masalah selesai di #737

Terima kasih sudah melapor
