### ISSUE TITLE
neonime.vip

### ISSUE THREAD

**Issue by mbakmanis** [realodix/AdBlockID#739]
**Jenis iklan**
- Iklan Pop-up
- Iklan Banner

**Sample URL**
https://neonime.vip

**Penjelasan Lebih Lanjut**
<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2021-02-09-14-37-34](https://user-images.githubusercontent.com/58507846/107331942-1a3a9000-6ae6-11eb-8451-295a6c21184e.png)
</details>

<details>
  <summary>Screenshot 2</summary>
  
  ![Screenshot_2021-02-09-14-37-53](https://user-images.githubusercontent.com/58507846/107332090-46eea780-6ae6-11eb-845b-a3e6e821da8e.png)
</details>

**Comment by realodix** [comment]
Sorry, Saya gak bisa reproduce issue ini. BUtuh info filter apa saja yang aktif, pakai adblock apa?

**Comment by realodix** [comment]
Masalah selesai di #737

Terima kasih sudah melapor
