### ISSUE TITLE
soranime.top

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#747]
**Jenis iklan**
safelink

**Sample URL**
https://www.soranime.top/yuru-camp△-season-2-episode-5/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Iklannya dimananya ya Gan?

**Comment by Recehan-Slayer** [comment]
cmn anti adblock sma safelink doang kyknya

**Comment by realodix** [comment]
Ok sip, thank you Bro
