### ISSUE TITLE
gomunime.com [Anti adblock]

### ISSUE THREAD

**Issue by RaveN0X87** [realodix/AdBlockID#75]
https://gomunime.com/

**Comment by realodix** [comment]
@RaveN0X87 Tolong ditest lagi Bro..

**Comment by realodix** [comment]
Sudah beberapa hari, terakhir cek tidak ada masalah. Saya akan anggap ini selesai dan tutup masalah ini. Jika ke depannya ada masalah, mohon laporkan kembali.
