### ISSUE TITLE
kurosave.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#752]
**Jenis iklan**
- Safelink script

**Sample URL**
https://kurosave.com/naruto-shippuuden-batch-eps-1-500-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
https://duit.cc/safelink.js?id=43566

**Comment by realodix** [comment]
Related
- https://github.com/realodix/AdBlockID/issues/236

---

Thank you
