### ISSUE TITLE
awnime.net

### ISSUE THREAD

**Issue by RaveN0X87** [realodix/AdBlockID#76]
https://awnime.net/

popups

**Comment by realodix** [comment]
Sadis banget ini popupnya, buka halaman `https://awnime.net/popup.htm` semua.

Tolong ditest lagi Bro..

**Comment by RaveN0X87** [comment]
udah fix ini

**Comment by realodix** [comment]
Thanks untuk laporan dan konfirmasinya

Saya akan tutup issue ini

**Comment by Recehan-Slayer** [comment]
`https://awnime.net/pokemon-movie-22-mewtwo-no-gyakushuu-evolution-bd-subtitle-indonesia/`

situs judi di footer

**Comment by realodix** [comment]
> https://awnime.net/pokemon-movie-22-mewtwo-no-gyakushuu-evolution-bd-subtitle-indonesia/
> situs judi di footer

Thank you
