### ISSUE TITLE
Cinemakeren (185.145.131.204)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#765]
**Jenis iklan**
- Banner

**Sample URL**
http://185.145.131.204/silk-road-2021/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix ada pre roll ads jg gan

**Comment by realodix** [comment]
> ada pre roll ads jg gan

Pre roll ads itu maksudnya gimana ya Gan?

**Comment by Recehan-Slayer** [comment]
yg iklan diawal video gan

**Comment by Recehan-Slayer** [comment]
![Opera Snapshot_2021-02-21_182201_185 145 131 204](https://user-images.githubusercontent.com/9379770/108623496-f6763300-7471-11eb-902a-b508cbccc021.png)
