### ISSUE TITLE
manhwaindo.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#770]
**Jenis iklan**
- Pop-up

**Sample URL**
https://manhwaindo.com/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Sorry ini apa ya Gan?

**Comment by Recehan-Slayer** [comment]
popup pas pertama kali klik

**Comment by realodix** [comment]
Ok Sip, thank you Gan
