### ISSUE TITLE
manhwaid.co

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#773]
**Sample URL**
https://manhwaid.co/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
https://manhwaid.me/ 
domain satunya bro sama anti adblock

**Comment by realodix** [comment]
> manhwaid.me/
> domain satunya bro sama anti adblock

Thank you
