### ISSUE TITLE
woiden.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#779]
**Sample URL**
https://woiden.com/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
anti adblock

**Comment by realodix** [comment]
> 
> 
> anti adblock

Sorry Gan, agan pakai extensi apa ya? uBlock atau AdGuard? Saya test pakai uBlock dan sudah tidak ada masalah, sementara AdGuard tidak Saya test, karena selama ini mereka pakai alat automatic converter agar compatible di AdGuard.

**Comment by Recehan-Slayer** [comment]
pke ublock origin di opera versi terbaru
![Opera Snapshot_2021-03-02_070241_woiden com](https://user-images.githubusercontent.com/9379770/109575951-6bf29b00-7b25-11eb-8d4d-ca8af10d0bdb.png)

**Comment by realodix** [comment]
Thank you Gan untuk feedbacknya.
