### ISSUE TITLE
yusepjaelani.blogspot.com 

### ISSUE THREAD

**Issue by RaveN0X87** [realodix/AdBlockID#78]
https://yusepjaelani.blogspot.com/?kareeI=aHR0cHM6Ly93d3cubWlycm9yZWQudG8vZmlsZXMvWVVDVElTMDcvQW5vdGhlcl9Xb3JsZF9bNzIwcF0ucmFyX2xpbmtzfHxHbyBUbyBMaW5rfHx8fF9zZWxmfHx0cnVlfHx0cnVlfHx0cnVlfHx0cnVlfHxmYWxzZXx8

https://yusepjaelani.blogspot.com/?kareeI=aHR0cHM6Ly9rdWxpYWhtYXRlbWF0aWthLm15LmlkL2RyaXZlLz9pZD1TbkF2VlZweVNWVlpRMk5xTWpBeVVHZG1OWGhIV0VKdVRXcEtOMVZHV1hGWFpVTjFVbXB6UWpCVGNucG5aMVZZVG5OQmIzQXhXbmRYTUVKelFYWkJXQT09fHxHbyBUbyBMaW5rfHx8fF9zZWxmfHx0cnVlfHx0cnVlfHx0cnVlfHx0cnVlfHxmYWxzZXx8

ANTI ADBLOCK

**Comment by realodix** [comment]
Thank you
