### ISSUE TITLE
107.152.39.187

### ISSUE THREAD

**Issue by Taufiq-HxH** [realodix/AdBlockID#781]
**Jenis iklan**
- Safelink

**Sample URL**
https://107.152.39.187/forgotten-2017-sub-indo/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Sorry friend, Saya mencoba untuk mematikan javascript browser, hasilnya tetap dalam mode shortlink. Kemungkinan ini [hard code](https://en.wikipedia.org/wiki/Hard_coding), jadi tidak bisa ditangani.

**Comment by Taufiq-HxH** [comment]
Oke mas, ga papa
