### ISSUE TITLE
drivenime.com

### ISSUE THREAD

**Issue by Taufiq-HxH** [realodix/AdBlockID#782]
**Jenis iklan**
- Safelink

**Sample URL**
https://drivenime.com/hinamatsuri-subtitle-indonesia-batch1/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Sorry friend, Saya mencoba untuk mematikan javascript browser, hasilnya tetap dalam mode shortlink. Kemungkinan ini [hard code](https://en.wikipedia.org/wiki/Hard_coding), jadi tidak bisa ditangani.
