### ISSUE TITLE
sektekomik.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#786]
**Sample URL**
https://sektekomik.com/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Sorry ini Saya gak nemuin peringatan anti adblock. Di halaman yang mana ya?

**Comment by Recehan-Slayer** [comment]
kemaren ada semacam overlay transparan di halaman depan jd g bisa klik apa" nutupi smua layar 
tp ntah skrng uda ga ada
