### ISSUE TITLE
joglosemarnews.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#796]
**Jenis iklan**

**Sample URL**
https://joglosemarnews.com/2021/02/10-000-guru-di-sragen-masuk-daftar-disuntik-vaksin-covid-19-dinas-pendidikan-tak-sabar-berharap-segera-diterapkan-pembelajaran-tatap-muka/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you
