### ISSUE TITLE
neonime.site

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#802]
**Jenis iklan**
- Banner

**Sample URL**
https://neonime.site

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
Sorry ini dibagian mananya ya?

**Comment by Recehan-Slayer** [comment]
@realodix 

![Screenshot_2021-03-07-17-33-33-225_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/110236907-b4002c00-7f30-11eb-9375-36b7c1e1ca7c.jpg)

**Comment by realodix** [comment]
**uBlock Origin**
- Di halaman Filterlist, apakah "Ignore generic cosmetic filters" sudah dipastikan tidak tercentang?
- Jika sudah dipastikan, Saya butuh info daftar filter apa saja yang digunakan.

**Selain uBlock Origin**
- Saya butuh info daftar filter apa saja yang digunakan dan extensi apa yang digunakan.

**Comment by Recehan-Slayer** [comment]
@realodix oh iya bro abaikan filter generiknya auto centang pas baru install ubo di browser hp

**Comment by realodix** [comment]
> oh iya bro abaikan filter generiknya auto centang pas baru install ubo di browser hp

Ok Gan, thank you sudah melapor
