### ISSUE TITLE
inidramaku.tv

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#803]
**Jenis iklan**
- Banner

**Sample URL**
https://inidramaku.tv

**Penjelasan Lebih Lanjut**
Judi

**Comment by realodix** [comment]
Sorry ini dibagian mananya ya?

**Comment by Recehan-Slayer** [comment]
![Screenshot_2021-03-07-17-35-10-889_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/110236928-db56f900-7f30-11eb-891e-75338757d706.jpg)

**Comment by realodix** [comment]
**uBlock Origin**
- Di halaman Filterlist, apakah "Ignore generic cosmetic filters" sudah dipastikan tidak tercentang?
- Jika sudah dipastikan, Saya butuh info daftar filter apa saja yang digunakan.

**Selain uBlock Origin**
- Saya butuh info daftar filter apa saja yang digunakan dan extensi apa yang digunakan.

**Comment by realodix** [comment]
Thank you
