### ISSUE TITLE
sektekomik.com

### ISSUE THREAD

**Issue by wout-codes** [realodix/AdBlockID#804]
Hello @realodix. I do not understand Indonesian as I am not from there. 

Please check this site: `https://sektekomik.com/`
Third party adservers and popups.

**Comment by wout-codes** [comment]
Nice bot you have got. I like it.

**Comment by wout-codes** [comment]
Btw, you gotta add some scriptlets.
I will write here those. Add these scriptlet rules and some adservers from your discovery.

1. `sektekomik.com##+js(acis, String.fromCharCode, delete window)`
2. `sektekomik.com##+js(acis, String.fromCharCode, break;case)`

**Comment by realodix** [comment]
> `sektekomik.com##+js(acis, String.fromCharCode, break;case)` 

filter for what?

**Comment by realodix** [comment]
Thank you

**Comment by wout-codes** [comment]
@realodix Add the scriptlet too. Otherwise some platforms like AdGuard for Windows, will still have some popups.
