### ISSUE TITLE
melongmovie.net

### ISSUE THREAD

**Issue by Taufiq-HxH** [realodix/AdBlockID#807]
**Sample URL**
https://melongmovie.net/

**Penjelasan Lebih Lanjut**
Ada ruang kosong
![Screenshot_2021-03-08-21-17-38](https://user-images.githubusercontent.com/58507846/110334806-c0ca7000-8055-11eb-8e60-762693498a17.png)

**Comment by realodix** [comment]
Pakai filter apa aja Gan? Saya hanya menemukan tombol close yg belum hilang, ruang kosong yang agan maksud gak ada

**Comment by realodix** [comment]
Tombol close sudah Saya hilangkan.

Jika pakai uBlock, pastikan "**Ignore generic cosmetic filters**" yang ada di halaman Filter list tidak tercentang.

Thank you untuk laporannya.
