### ISSUE TITLE
melongmovie.org

### ISSUE THREAD

**Issue by Taufiq-HxH** [realodix/AdBlockID#813]
**Jenis iklan**
- Overlay

**Sample URL**
https://melongmovie.org/
https://melongmovie.org/godzilla-vs-kong-2021/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Popup di bagian mananya ya Gan?

**Comment by Taufiq-HxH** [comment]
Tombol close mas

**Comment by realodix** [comment]
> 
> 
> Tombol close mas

Tombol close sudah saya hilangkan, apakah masih ada?

**Comment by Taufiq-HxH** [comment]
Kemaren sudah hilang, sekarang ada lagi

**Comment by realodix** [comment]
> Kemaren sudah hilang, sekarang ada lagi

Sorry maksudnya gimana ya? Agan bilang ada popup di tombol close, lalu Saya sudah menghilangkan tombol closenya di https://github.com/realodix/AdBlockID/commit/71a42311a774ed68e7868c049505b7e46999b637 , jadi popupnya harusnya sudah tidak ada.

Sekarang apakah masih ada popup yang terlewat?

**Comment by Taufiq-HxH** [comment]
Udah ga ada mas

**Comment by realodix** [comment]
OK, thank you untuk laporannya
