### ISSUE TITLE
razorlink.us

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#82]
https://www.razorlink.us/2019/01/is-catering-good-business.html?url=IyNERSU1QyU0MCUwNk1EQU4lMDd%2BJTE4YSU3QmZDeEElMDclNUUlMDdFR0slMDZNWkklNDAlNUJRWFhBUiUwNiUxRCUxRV9fXyUwNyUwNyUxMiU1QlglNUMlNUMlNDAjIw%3D%3D

ads

**Comment by realodix** [comment]
Iklan apa? Pop-up?

![screencapture-razorlink-us-2019-01-is-catering-good-business-html-2019-11-27-03_33_35](https://user-images.githubusercontent.com/1314456/69670650-f0ef3900-10c6-11ea-8051-0d2a7d50e50b.png)

**Comment by WaferNabati** [comment]
kemaren kyknya bnyak iklanya mungkin pas gw matiin ublocknya

**Comment by realodix** [comment]
OK sip Gan.. Kmrn pas gue buka ada iklan pop-up.
Kalau gitu Saya tutup ya

Thank you
