### ISSUE TITLE
adik.my.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#826]
**Sample URL**
http://m.adik.my.id/p/?id=eU1MSm9oN1RaY0hzQnQxZzB3U0FlOGhhMzZFRC9oQVlkU3JjeGhTNUxiRDAzeUVCTmE2MjlLT1pxblVuWGwzNUtmR1VxdnJrL1N1VG1SczVTNUlualhwQkU3dzdRYjhZaXc0blBwVG9uaDVmUHoxRjlEUnpYRlhNdUVGbGpTOEo2NkRuV0lEWVFWaE85RmRZL29aQm9RPT0=

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
[m.adik.my.id/p/?id=eU1MSm9...m9RPT0=](http://m.adik.my.id/p/?id=eU1MSm9oN1RaY0hzQnQxZzB3U0FlOGhhMzZFRC9oQVlkU3JjeGhTNUxiRDAzeUVCTmE2MjlLT1pxblVuWGwzNUtmR1VxdnJrL1N1VG1SczVTNUlualhwQkU3dzdRYjhZaXc0blBwVG9uaDVmUHoxRjlEUnpYRlhNdUVGbGpTOEo2NkRuV0lEWVFWaE85RmRZL29aQm9RPT0=) -> mangindo.xyz

**Comment by realodix** [comment]
Thank you
