### ISSUE TITLE
nekopoi.care

### ISSUE THREAD

**Issue by arsindyfm** [realodix/AdBlockID#83]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://nekopoi.care/

**Penjelasan Lebih Lanjut**
iklan judi belum terblokir

**Comment by realodix** [comment]
@Arsindy Thank you

**Comment by WaferNabati** [comment]
@realodix masi ada gan iklan bannernya tolong diupdate

**Comment by realodix** [comment]
Ganti domain ke nekopoi.web.id

**Comment by Recehan-Slayer** [comment]
beda web itu bro yg asli ttep .care

**Comment by realodix** [comment]
> beda web itu bro yg asli ttep .care

Siap Gan, sudah Saya ganti penjelasannya. Thank you

**Comment by realodix** [comment]
> ada banner iklan judi baru

Thank you, update tersedia di AdBlockID+

**Comment by Recehan-Slayer** [comment]
##[href*="bit.ly/2Tywrsi"]
link bannernya dimasukin bit.ly

**Comment by realodix** [comment]
> ##[href*="bit.ly/2Tywrsi"]
> link bannernya dimasukin bit.ly

Thank you

**Comment by Recehan-Slayer** [comment]
ganti lagi linknya `http://1001win.net/id-ID/Home`

**Comment by realodix** [comment]
> ganti lagi linknya `http://1001win.net/id-ID/Home`
> ##[href*="1001win.net"]

Thank you

**Comment by Recehan-Slayer** [comment]
banner judi baru https://bit.ly/2LkQffc

**Comment by realodix** [comment]
> banner judi baru `https://bit.ly/2LkQffc`

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix masi ada placeholder dibagian atas

**Comment by realodix** [comment]
> masi ada placeholder dibagian atas

Iya sengaja. Situs nekopoi.care masuknya AV Hentai, Saya gak dukung filter spesifik

**Comment by Recehan-Slayer** [comment]
Judi baru

**Comment by Recehan-Slayer** [comment]
Banner judi baru

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix dirubah lagi link bannernya gan

**Comment by realodix** [comment]
> 
> 
> dirubah lagi link bannernya gan

Thank you

**Comment by Recehan-Slayer** [comment]
```
https://bit.ly/2Kv5eRU
https://bit.ly/3cOegpA
```
dirubah lg gan linknya

**Comment by realodix** [comment]
> 
> 
> ```
> https://bit.ly/2Kv5eRU
> https://bit.ly/3cOegpA
> ```
> 
> dirubah lg gan linknya

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix update lg bro

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix banner judi gnti domain bro 1001win.site

**Comment by realodix** [comment]
> 
> 
> @realodix banner judi gnti domain bro 1001win.site

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix doamain baru gan `1001win.loan`

**Comment by Recehan-Slayer** [comment]
@realodix gnti lg gan `1001win1.loan`

**Comment by realodix** [comment]
> gnti lg gan `1001win1.loan`

**Comment by Recehan-Slayer** [comment]
@realodix judi baru gan

**Comment by realodix** [comment]
> judi baru gan

Tarengkiu

**Comment by Recehan-Slayer** [comment]
@realodix judi baru bro

**Comment by Recehan-Slayer** [comment]
@realodix update banner baru gan

**Comment by Recehan-Slayer** [comment]
close button gan
![Screenshot_2022-07-22-22-07-29-854_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/180468756-6a91c5fa-be9d-41ce-bc27-f97154ece38a.jpg)

**Comment by Bug-Cache** [comment]
![image](https://user-images.githubusercontent.com/98657967/180628424-2007adf9-974f-4af9-968b-d88954c0de31.png)
https://nekopoi.care/uncensored-raiden-shogun-baal-genshin-impact-animation/

**Comment by realodix** [comment]
@Recehan-Slayer [#83 (comment)-1192670361](https://github.com/realodix/AdBlockID/issues/83#issuecomment-1192670361)

@Bug-Cache [#83 (comment)-1193224106](https://github.com/realodix/AdBlockID/issues/83#issuecomment-1193224106)

Test di PC dengan tampilan mobile, Saya tidak dapat menemukannya.

Mungkin ada yang bisa bantu?

Saat ini issue Saya tutup dahulu.

**Comment by Recehan-Slayer** [comment]
udah ga ada skrng

**Comment by Recehan-Slayer** [comment]
@realodix banner judi di dalam video streaming bro
![Screenshot_2022-07-30-21-35-30-133_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/181919202-64d871f0-ff8d-4a93-ba0c-4ed93efec057.jpg)

**Comment by realodix** [comment]
> banner judi di dalam video streaming bro ![Screenshot_2022-07-30-21-35-30-133_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/181919202-64d871f0-ff8d-4a93-ba0c-4ed93efec057.jpg)

Ini berasal dari dood.pm (domain internasional) dan sulit juga karena tagnya `vjs-logobrand-image`.

Bisa tambahkan ini `dood.pm###vjs-logobrand-image` atau `dood.*###vjs-logobrand-image` (karena dood suka bergonta-ganti domain)

<details>
  <summary>Screenshot</summary>
  
  ![Image 003](https://user-images.githubusercontent.com/1314456/181995864-85e20d49-ec86-472f-80f6-cb5b7538a1ea.png)
</details>
