### ISSUE TITLE
otakudere.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#832]
**Jenis iklan**

- Banner
- Pop-up

**Sample URL**
https://otakudere.net/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix https://otakudere.net/anime/wotaku-ni-koi-wa-muzukashii-youth/
judi baru bro

**Comment by realodix** [comment]
>  judi baru bro

Thank you
