### ISSUE TITLE
gamebrott.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#833]
**Jenis iklan**

- Banner
- Lainnya

**Sample URL**
https://gamebrott.com/walau-rugi-ratusan-juta-dollar-bos-epic-games-dinobatkan-jadi-orang-terkaya-di-north-carolina

**Penjelasan Lebih Lanjut**

![Opera Snapshot_2021-04-18_151658_gamebrott com](https://user-images.githubusercontent.com/9379770/115138906-2e0bf080-a059-11eb-84d2-fea2c71af350.png)

**Comment by realodix** [comment]
Thank you
