### ISSUE TITLE
nontondrama.site

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#835]
**Jenis iklan**

- Banner

**Sample URL**
http://nontondrama.site/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Sry di bagian mananya ya?

**Comment by Recehan-Slayer** [comment]
![Opera Snapshot_2021-04-20_134410_nontondrama site](https://user-images.githubusercontent.com/9379770/115349832-891b2000-a1de-11eb-9d3d-b497a12f64de.png)

**Comment by realodix** [comment]
Thank you
