### ISSUE TITLE
klikmanga.com

### ISSUE THREAD

**Issue by valkyraa** [realodix/AdBlockID#837]
**Jenis iklan**

Banner & pop-up
**Sample URL**
https://klikmanga.com

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Saya butuh info lebih lanjut atau SS. Popup ketika klik apa dan bannernya ada dimana?

**Comment by valkyraa** [comment]
> Saya butuh info lebih lanjut atau SS. Popup ketika klik apa dan bannernya ada dimana?

![Screenshot_2021-04-22-21-14-12-697_com android chrome](https://user-images.githubusercontent.com/46155943/115729857-f92cd000-a3af-11eb-846f-feb69b577d5c.png)
![Screenshot_2021-04-22-21-15-49-571_com android chrome](https://user-images.githubusercontent.com/46155943/115729890-00ec7480-a3b0-11eb-8310-a30e49e8c8f4.png)

Pop up muncul ketika saya mencoba meng-close announcement milik web tersebut

**Comment by realodix** [comment]
Thank you
