### ISSUE TITLE
oploverz.bz

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#838]
**Jenis iklan**
- Pop-up
- Lainnya

**Sample URL**
https://oploverz.bz/

**Penjelasan Lebih Lanjut**
`whouledu.com`
<details>

![Opera Snapshot_2021-04-24_092246_oploverz bz](https://user-images.githubusercontent.com/9379770/115944305-2cba4800-a4df-11eb-9f7a-ada3e7ccc35d.png)

**Comment by realodix** [comment]
Di Saya bersih Gan, domain `whouledu.com` juga tidak ditemukan. Saya butuh info lebih lanjut

<details>
  <summary>Screenshot</summary>
  
  ![cats](https://user-images.githubusercontent.com/1314456/115955132-0d430f80-a51f-11eb-8c88-440ceb24de82.jpg)
</details>

Untuk popup sudah pernah ditangani di https://github.com/realodix/AdBlockID/commit/c6fb8e7765e195b08a078219466e1ea5825a3ada

**Comment by Recehan-Slayer** [comment]
@realodix  <details> 
itu bro masi ada

![image_2021-04-24_175940](https://user-images.githubusercontent.com/9379770/115956439-da9d1500-a526-11eb-9495-d314dbfa0d45.png)

**Comment by realodix** [comment]
Nah lo bisa beda gt ya.. Tapi kalau `whouledu.com` kamu ta block, popup hilang?

**Comment by Recehan-Slayer** [comment]
popupnya ga ada sih itu yg di pojok kanan bawah hilang

**Comment by realodix** [comment]
Thank you
