### ISSUE TITLE
koenime.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#839]
**Sample URL**
https://www.koenime.com/rohan-sub-indo/

**Penjelasan Lebih Lanjut**

**Comment by Recehan-Slayer** [comment]
sama di safelinknya jg anti adblock gan
https://apasih.pw/?id=MXFnZERwbmw0OU91S1luQmRrWXMzcFhWSi9iUG5Mcm9PZXg3M0Z0MmMwZGdtaWpGbC82ZDB2Q2d3KzRHR0l2NDU1azk0Njcvd1FEUzdBYVhnM0tCTUlvTFRBSzdRZUVHVVdJWTRyYy81RFFBWFhQb04wUzdBZExRLzZRTU9WenNBM1NCcys5MG5mVHhJYjBCMVNQc1RjZXg0TGhtSVh1dDlrNlFWRW5aQjhZPQ==

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
kok masi muncul ya bro, apa gara" di opera ubo nya masi versi 1.33.2 ya?

**Comment by realodix** [comment]
Gimana Gan, masih gak? Metodenya sudah Saya ganti

**Comment by Recehan-Slayer** [comment]
iya skrng uda bisa
