### ISSUE TITLE
kazefuri.me

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#84]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://kazefuri.me/?id=UWNaOVFWaFBkRUo3czVqczFESFlxaXVySjlsZXZqa3N2R0piejY1cktHRT0=
https://kazefuri.me/?id=UWNaOVFWaFBkRUo3czVqczFESFlxc25KeHZVUDc4QkNXR3p6ZXhJSzNyRT0=

**Penjelasan Lebih Lanjut**
popups ads dll

**Comment by WaferNabati** [comment]
smua yg dr domain cewaugaz.net block gan

**Comment by realodix** [comment]
> smua yg dr domain cewaugaz.net block gan

https://imgur.com/uKANSxm

**Comment by WaferNabati** [comment]
apa itu yg di SS masa SS history komenan ini

**Comment by WaferNabati** [comment]
ada kok di bawah sndiri iklanya banyak bgt

**Comment by WaferNabati** [comment]
![Annotation 2019-11-28 184446](https://user-images.githubusercontent.com/9379770/69803675-59e1c880-120f-11ea-9d7f-cf1b4cbca5d6.png)
![Annotation 2019-11-28 184518](https://user-images.githubusercontent.com/9379770/69803677-5b12f580-120f-11ea-88b6-5845bd679519.png)

**Comment by WaferNabati** [comment]
@realodix coba lihat di lognya bro

**Comment by realodix** [comment]
@WaferNabati  Gak ada Bro, di Gue gak ada domain `cewaugaz.net`. Adanya malah `peefeehu.com`.

Berita baiknya, `cewaugaz.net` sudah ada di [easylist/easylist@ad1c2b0#diff-4903e75](https://github.com/easylist/easylist/commit/ad1c2b0ea6683f2b0b8152962ae74fee23ee3607#diff-4903e7590de76df1abe1703921a2c88bR1532)

![cats](https://user-images.githubusercontent.com/1314456/69830670-781fe680-1258-11ea-89e4-18fd908bedd6.jpg)

**Comment by WaferNabati** [comment]
kok aneh bro kok bisa beda" gitu

**Comment by realodix** [comment]
Nggak tau tuh, emang rada ajaib dia.

Semalem udah dicoba klik2 beberapa halaman yang ada di sana, karena penasaran juga dengan `cewaugaz.net`. Saat ini masih `peefeehu.com`, gak tahu juga deh kalau beberapa hari lagi atau beberapa minggu lagi. Tapi rasanya sudah masuk ke dalam pengawasan easylist.

**Comment by WaferNabati** [comment]
ok kemaren blom gw update filternya jdi msih muncul iklanya bejibun
