### ISSUE TITLE
anoboy.media

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#850]
**Jenis iklan**
- Pop-up

**Sample URL**
https://anoboy.media/2021/04/isekai-maou-to-shoukan-shoujo-no-dorei-majutsu-season-2-episode-4/

**Penjelasan Lebih Lanjut**
popup ke situs judi saat pertama klik

**Comment by realodix** [comment]
Ketika kliknya, klik bagian yang mana ya? Mengarah ke situ apa?

**Comment by Recehan-Slayer** [comment]
oh ternyata ngeklik banner bro invisible di sebelah kanan

**Comment by realodix** [comment]
OK Gan, thank you

**Comment by Recehan-Slayer** [comment]
mnasi ada gan dibagian atas video player `https://bit.ly/QQ39anoboy`

**Comment by realodix** [comment]
> mnasi ada gan dibagian atas video player `https://bit.ly/QQ39anoboy`

Thank you

**Comment by Recehan-Slayer** [comment]
masi ada gan `https://kliksaya.info/mcdanoboy`

**Comment by realodix** [comment]
> 
> 
> masi ada gan `https://kliksaya.info/mcdanoboy`

Thank you

**Comment by Recehan-Slayer** [comment]
ada lgi gan `https://bit.ly/SG88anoboy`

**Comment by realodix** [comment]
> ada lgi gan https://bit.ly/SG88anoboy

Thank you

**Comment by Recehan-Slayer** [comment]
judi baru bre

**Comment by realodix** [comment]
> 
> 
> judi baru bre

Thank you
