### ISSUE TITLE
sportif.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#880]
**Jenis iklan**
- Banner
- Lainnya

**Sample URL**
https://www.shrinkads.com/P2wnFYw
https://www.shrinkads.com/brdj

**Penjelasan Lebih Lanjut**
fake button

**Comment by realodix** [comment]
**Related**
- https://github.com/realodix/AdBlockID/issues/521#issuecomment-626121112
- https://github.com/realodix/AdBlockID/issues/339#issuecomment-585596350

---

Thank you
