### ISSUE TITLE
duit.cc

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#884]
**Sample URL**
https://duit.cc/w5lyf
https://duit.cc/l4J6H

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Saya gak nemuin peringatan anti-adblock Gan

**Comment by Recehan-Slayer** [comment]
di opera ama chrome muncul gan klo di firefox emg ngga 
<details>
 <summary>SS</summary>

![Opera Snapshot_2021-05-06_190537_duit cc](https://user-images.githubusercontent.com/9379770/117296275-12994600-ae9f-11eb-865d-d37cd7cb9222.png)

</details>

**Comment by realodix** [comment]
Waduh kok bisa beda ya?

Saya coba https://duit.cc/w5lyf di
- Firefox (uBo 1.35.2)
- Edge (uBo 1.35.2)
- Chrome (uBo 1.34.0)

Semuanya normal gan, bisa mengarah ke https://hxfile.co/060jeqj7z345 tanpa ada peringatan.

**Comment by realodix** [comment]
Ternyata hanya Opera (uBo 1.33.2) yang muncul notif anti-adblock

**Comment by realodix** [comment]
Tolong ditest kembali Gan

**Comment by Recehan-Slayer** [comment]
> Tolong ditest kembali Gan
uda hilang .
eh iya id opera ama kiwi browser android aja yg muncul anti adblocknya di chrome dekstop ngga

**Comment by realodix** [comment]
OK, thank you
