### ISSUE TITLE
drakorindoo.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#888]
**Jenis iklan**
- Banner
- Pop-up

**Sample URL**
https://drakorindoo.net/download-drama-korea-taxi-driver-subtitle-indonesia/

**Penjelasan Lebih Lanjut**

**Comment by Recehan-Slayer** [comment]
judi bru gan

**Comment by realodix** [comment]
> 
> 
> judi bru gan

Thank you
