### ISSUE TITLE
sheamanga.my.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#889]
**Jenis iklan**
- Pop-up

**Sample URL**
https://sheamanga.my.id/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Popupnya di saat apa gan?

**Comment by Recehan-Slayer** [comment]
pas klik di salah satu pilihan manga td muncul popup tp ntah skrng ga muncul lg

**Comment by Recehan-Slayer** [comment]
@realodix  ada gan popupnya 
<details>

![Untitled](https://user-images.githubusercontent.com/9379770/119226905-a91f6580-bb35-11eb-940d-215575c66ae1.jpg)

**Comment by realodix** [comment]
Saya masih bingung ini masukin ke NSFW atau bukan. Halamn depannya nunjukin banget dan ada listnya juga https://sheamanga.my.id/blog/list-terlarang/. Tapi kebanyakan komiknya sih sepertinya bukan.

Thank you

**Comment by Recehan-Slayer** [comment]
Sebagian besar emg bukan
