### ISSUE TITLE
Block indoxbet.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#89]
Pop up dari aplikasi xx1lite

block website ini
https://indoxbet.com/mobile/home

**Comment by realodix** [comment]
Wah popup di aplikasi ya? Bisa kasih link apk nya gak?

**Comment by 3xploiton3** [comment]
@realodix 
is.gd/R52H2j

**Comment by realodix** [comment]
Bisa jelasin lebih gak Bro? Saya sudah install, tapi dari tadi gak ada tanda-tanda pop-up.

**Comment by 3xploiton3** [comment]
Play salah 1 video disitu ada juga banner, coba klik random dibagian video player nanti muncul pop up

**Comment by realodix** [comment]
> Pop up dari aplikasi xx1lite
> 
> block website ini
> https://indoxbet.com/mobile/home

Saya sudah coba buat rule `||indoxbet.com/mobile/home^` di AdGuard mobile, banner indoxbet masih tetap muncul Bro di aplikasinya.

Versi webnya (http://103.194.171.75/) bersih, karena udah Saya block di [5338175#diff-58efe50](https://github.com/realodix/AdBlockID/commit/5338175394868cf4fc0380d8cd8a5a7e9f6f9d0d#diff-58efe50529c4d73853d68b44cbbbe537R124).

Saya rasa harus lapor ke AdGuard Gan untuk blockir banner di aplikasi Android.

ping @Alex-302

**Comment by Alex-302** [comment]
This ad is loaded from the main domain, cannot be blocked.
