### ISSUE TITLE
niihen-subs.blogspot.com [NSFW]

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#893]
**Jenis iklan**
- Pop-up
- Safelink

**Sample URL**
https://niihen-subs.blogspot.com/2021/02/haitoku-no-kyoukai.html

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Sry Gan ini harus spesifik. 

NSFW, Jika isi berkonten dewasa hanya sebagian saja Saya masih bisa. Tapi karena ini full, jadi gak bisa.
