### ISSUE TITLE
lner.co.uk

### ISSUE THREAD

**Issue by Alex-302** [realodix/AdBlockID#897]
### Issue URL (Incorrect Blocking)
 [https://www.lner.co.uk/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.lner.co.uk%2F)

Caused by `~doxadigital.com##.banner-top`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/U7jUf2X.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Nd66ajV.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v3.5.34
Browser: | Chrome
Stealth mode: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdBlockID

**Comment by realodix** [comment]
Thank you
