### ISSUE TITLE
Block analytics dari telegraph

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#90]
![](https://i.imgur.com/W9XsXxh.jpg)

analytics.metrix.ir

**Comment by realodix** [comment]
Thank you untuk laporannya. Sorry Gan, Graph Messenger aplikasi internasional. Menurut Saya sebaiknya langsung dilaporkan ke [AdGuard](https://github.com/AdguardTeam/AdguardFilters/issues).

Ping @Alex-302

**Comment by Alex-302** [comment]
Done.
