### ISSUE TITLE
bokephub.icu [NSFW]

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#901]
**Jenis iklan**
- Banner

**Sample URL**
https://bokephub.icu/bokep-indo/nonton-film-bokep-indo-ngewe-ayam-kampus-cantik/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Bannernya di bagian mana ya?

**Comment by realodix** [comment]
Duplicate of #861

**Comment by Recehan-Slayer** [comment]
iya yg itu
