### ISSUE TITLE
Memeksiana (198.252.110.95) [NSFW]

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#902]
**Jenis iklan**
- Banner

**Sample URL**
http://198.252.110.95/cewek-kacamata-suka-vulgar-bugil-depan-kamera/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
masi ada bro

**Comment by realodix** [comment]
> 
> 
> masi ada bro

Thank you
