### ISSUE TITLE
sektekomik.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#905]
**Jenis iklan**
- Banner

**Sample URL**
https://sektekomik.com/manga/rebirth-of-the-urban-immortal-cultivator/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Duplicate of #419, #786, #804

---

Thank you

**Comment by Recehan-Slayer** [comment]
@realodix gan gmbarnya kok tidak keluar ya
https://sektekomik.com/cultivation-return-on-campus-chapter-222-bahasa-indonesia/

**Comment by Recehan-Slayer** [comment]
@realodix  gan punya gw kok thumbnailnya ga muncul ya.  klo gambarnya uda fix
<details>

![Untitled](https://user-images.githubusercontent.com/9379770/121298199-ac7c6480-c91d-11eb-9cbd-8469fbdbb477.jpg)

**Comment by realodix** [comment]
Kurang tahu deh. Di Saya muncul, gak ada masalah.

<details>
  <summary>Screenshot</summary>
  
  ![noname](https://user-images.githubusercontent.com/1314456/131340050-2737e0f8-b3f4-42a7-ae8f-304a6031e004.png)
</details>
