### ISSUE TITLE
semawur.com

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#91]
https://semawur.com/GlLjChS
https://semawur.com/vmiPFDlk6SR

Fake button
![Annotation 2019-11-30 134235](https://user-images.githubusercontent.com/9379770/69896947-8d3f6700-1377-11ea-8105-c31da906190b.png)

**Comment by realodix** [comment]
Thank you

**Comment by WaferNabati** [comment]
@realodix masih ada gan fake button yg warna biru kadang muncul

**Comment by realodix** [comment]
> @realodix masih ada gan fake button yg warna biru kadang muncul

Dari kemarin gak ketemu Bro sama fake button nya. Tolong dibantu pas muncul fake buttonnya

**Comment by WaferNabati** [comment]
@realodix iya kadang muncul tp jarang ini lg cari" lgi ga muncul warna biru bentuknya sama kayak SS yg atas itu tpi warnanya biru.
ntar klo ada aku SS beserta element picker Ublock

**Comment by WaferNabati** [comment]
@realodix itu gan  
![Untitled](https://user-images.githubusercontent.com/9379770/70360398-f0b62100-18b0-11ea-9a68-42c7a3756bfd.png)

**Comment by realodix** [comment]
> @realodix itu gan
> ![Untitled](https://user-images.githubusercontent.com/9379770/70360398-f0b62100-18b0-11ea-9a68-42c7a3756bfd.png)

Thank you Gan, sudah Saya tambahkan..

**Comment by Recehan-Slayer** [comment]
close button `https://semawur.com/Mxo2`

**Comment by realodix** [comment]
> close button `https://semawur.com/Mxo2`

Thank you
