### ISSUE TITLE
shorten-link.com (ciustekno.me)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#92]
https://kuygan.com/FExDwU0
https://kuygan.com/Jq2c

bro shortlink ini kok sering bgt diarahin keweb ads bukan ke link tujuan emg dr sananya apa gara" pke adblock

**Comment by realodix** [comment]
> https://kuygan.com/FExDwU0
> https://kuygan.com/Jq2c
> 
> bro shortlink ini kok sering bgt diarahin keweb ads bukan ke link tujuan emg dr sananya apa gara" pke adblock


Tiitle Saya edit, karena pas diklik ngarah ke ciustekno.me.

Cara paling gampang, matiin AdBlock di situs tersebut. 

Saya rasa emang dari sananya. Pakai AdBlock, abis ngisi captcha dia ngarahin ke tujuan yang benar, ke `mirrorace.com`. Mungkin pas Bro buka, dia ganti ad server dan kebeneran belum masuk di easylist.

**Comment by WaferNabati** [comment]
bukan itu selalu diarahin ke sini
https://loading.mntzr-january2019.com/?utm_medium=cc511fb7b1835e5e9e9dc772d19397787ba45251&utm_campaign=mainstream&1=1&2=2&3=3&4=4&5=5&cid=90affC1575294093affe504718b63262a819a468
itu knp ya dipunyamu diarahin ke ciustekno apa kesitu

**Comment by realodix** [comment]
Waduh, bisa beda begitu.

Setiap buka
- https://kuygan.com/FExDwU0
- https://kuygan.com/Jq2c

Selalu dapat pola yang sama
1. Klik `Click here to go to the destination link` pada `ciustekno.me`
2. Isi `CAPTCHA SECURITY`
3. Tunggu 15 detik
4. Klik `Get Link`
  Disini akan dapet popup yang langsung ditutup oleh easylist
![cats](https://user-images.githubusercontent.com/1314456/70035354-43f44f00-15e5-11ea-841e-eb163ba0b231.jpg)
5. Langsung di-redirect ke `mirrorace.com`

**Comment by WaferNabati** [comment]
iya klo pke vpn/ssh selalu diarahin ke situs ads bukan ciustekno ini pke opsel XL/AXIS bisa ga diarahin ke situs ads
klo itu tau gw pke UB ga prlu isi captcha lngsung auto ke tujuan klo msk real linknya

**Comment by Recehan-Slayer** [comment]
bro knp disafelink ini klo pke vpn negara luar dialihkanya keweb iklan.
coba pke vpn luar. https://ciustekno.me/Jq2c

**Comment by realodix** [comment]
> bro knp disafelink ini klo pke vpn negara luar dialihkanya keweb iklan.
> coba pke vpn luar. https://ciustekno.me/Jq2c

Gak ngerti juga deh alasannya kenapa
