### ISSUE TITLE
sektekomik.com - Gambar tidak keluar

### ISSUE THREAD

**Issue by realodix** [realodix/AdBlockID#922]
gan gmbarnya kok tidak keluar ya
https://sektekomik.com/cultivation-return-on-campus-chapter-222-bahasa-indonesia/

_Originally posted by @Recehan-Slayer in https://github.com/realodix/AdBlockID/issues/905#issuecomment-856121356_

**Comment by realodix** [comment]
@Recehan-Slayer Saya coba disable AdBlockID, tapi gambar masih tidak keluar juga. Belum tahu apa penyebabnya.

**Comment by realodix** [comment]
@Recehan-Slayer Ternyata ini penyebabnya, di uBlock filters terdapat filter `*$script,3p,denyallow=[domain_list],domain=sektekomik.com` yang belum menyelesaikan masalah.

<details>
  <summary>Screenshot</summary>
  
  ![cats](https://user-images.githubusercontent.com/1314456/121064918-5eb70d80-c7f2-11eb-8f43-c4be07f2f1c1.jpg)
</details>

---

Ping @uBlock-user, image does not appear

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/b9c98ffe3ec9d49fbe05f402dbb7a6c4f011601b

**Comment by realodix** [comment]
gan punya gw kok thumbnailnya ga muncul ya.  klo gambarnya uda fix

<details>
  <summary>Screenshot</summary>
  
  ![Untitled](https://user-images.githubusercontent.com/9379770/121298199-ac7c6480-c91d-11eb-9cbd-8469fbdbb477.jpg)
</details>

_Originally posted by @Recehan-Slayer in https://github.com/realodix/AdBlockID/issues/905#issuecomment-857385612_

---

Sample https://sektekomik.com/manga/rebirth-of-the-urban-immortal-cultivator/

Ping @uBlock-user

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/50db47cb795a4f6aade4cc8ae30d8bc6cae9c3ae
https://github.com/uBlockOrigin/uAssets/commit/94c8ffad203389d61c063ee0d071eaea7ecd1461
