### ISSUE TITLE
oploverz.bz

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#923]
**Sample URL**
https://oploverz.bz/boruto-naruto-next-generations-202-subtitle-indonesia/

**Penjelasan Lebih Lanjut**
komentarnya ga muncul

**Comment by realodix** [comment]
Saya lihat ini karena uBlock filters.

Ping @uBlock-user

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4a591c5baf595b7f039d982fbf202b523261e98a
