### ISSUE TITLE
cinema.botam.xyz

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#924]
**Jenis iklan**
- Safelink

**Sample URL**
https://cinema.botam.xyz/the-conjuring-the-devil-made-me-do-it/

**Penjelasan Lebih Lanjut**
`https://raw.githack.com/botamspawn/safelink/master/auto.js`

**Comment by realodix** [comment]
Thank you

**Comment by Recehan-Slayer** [comment]
@realodix banner refferal bro

**Comment by realodix** [comment]
> banner refferal bro

Di bagian mananya Bro?

**Comment by Recehan-Slayer** [comment]
uda masuk ke filternya keknya uda ga ada
