### ISSUE TITLE
huntersekai.download

### ISSUE THREAD

**Issue by Taufiq-HxH** [realodix/AdBlockID#928]
**Jenis iklan**
- Safelink

**Sample URL**
http://www.huntersekai.download/2021/06/KNY-movie-BD.html

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Saya lihat sepertinya hardcode Gan, atau mereka paste manual linknya. Saya coba matiin javascript di browser, namun gak ada perubahan.
