### ISSUE TITLE
dramaencode.co

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#930]
**Sample URL**
https://dramaencode.co/love-ft-marriage-divorce-season-2-subtitle-indonesia/

**Penjelasan Lebih Lanjut**

**Comment by Recehan-Slayer** [comment]
masi ada bro

![Screenshot 2021-06-29 at 18-26-03 DRAMAENCODE - Download Drama Korea dan Variety Show Subtitle Indonesia](https://user-images.githubusercontent.com/9379770/123789617-90aa2400-d907-11eb-83ae-0b6a8c9c9e97.png)

**Comment by realodix** [comment]
Thank you
