### ISSUE TITLE
idfl.info

### ISSUE THREAD

**Issue by Uranite** [realodix/AdBlockID#935]
**Sample URL**
http://idfl.info/forum.php

**Jenis Gangguan**
Pop-up

**Penjelasan Lebih Lanjut**
![image](https://user-images.githubusercontent.com/62639703/124276677-50001400-db6e-11eb-825a-c99389148659.png)

**Comment by realodix** [comment]
Pakai filter apa aja Gan, biar Saya samain? Popup terjadi ketika klik apa?

**Comment by Uranite** [comment]
popupnya terjadi walaupun ga klik apa-apa
adguard extension
adguard base, adguard tracking, adguard annoyances

**Comment by Uranite** [comment]
kayaknya popupnya terjadi karena extension decentraleyes

**Comment by Uranite** [comment]
![image](https://user-images.githubusercontent.com/62639703/124285410-159b7480-db78-11eb-8e68-2026b5b04452.png)
popupnya harusnya diblokir oleh chrome tapi ke unblock karena extension decentraleyes

**Comment by Uranite** [comment]
idfl.*##+js(window.open-defuser)

**Comment by realodix** [comment]
Filter sudah Saya samakan dan install Decentraleyes 2.0.15 (firefox)

Sudah Saya update dengan mencoba untuk mematikan ini di halaman mereka

```js
window.open(page2, "", windowprops1);
window.open(page1, "", windowprops2);
```

Pakai AdGuard, tungga beberapa saat ya Gan hingga keluar updatenya di AdGuard. Kira-kira masih keluar gak tuh popupnya

**Comment by Uranite** [comment]
work, thanks
