### ISSUE TITLE
kompas.com

### ISSUE THREAD

**Issue by Gyputra** [realodix/AdBlockID#936]
**Jenis iklan**
- Lainnya

**Sample URL**
https://kompas.com/

**Penjelasan Lebih Lanjut**
Banyak ruang kosong di setiap kategori.
Saya pakai browser Vivaldi Android

<details>
  <summary>Screenshot 1</summary>
  
  ![2021-07-06 14 16 45 www kompas com 79630a64-bd0a-42e1-96cf-e9f960ec0dd9](https://user-images.githubusercontent.com/87004316/124560371-eda55d00-de66-11eb-94c4-312b1170ed66.jpg)
</details>

<details>
  <summary>Screenshot 1</summary>
  
  ![2021-07-06 14 15 34 tekno kompas com 1c167d25-0b15-40ac-b0ec-cdedb1d6674a](https://user-images.githubusercontent.com/87004316/124561105-b5eae500-de67-11eb-82d0-b134761183b0.jpg)
</details>

**Comment by realodix** [comment]
Saya berasumsi Agan pakai Vivaldi Mobile dengan AdBlocker bawaannya Vivaldi ya?

Saya sudah coba cek di HP Saya dengan membuka halaman https://www.kompas.com/global , hasilnya bersih gan

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2021-07-06-15-59-27-863_com android chrome](https://user-images.githubusercontent.com/1314456/124572882-36fba980-de73-11eb-8dc9-79b4fadb30bf.jpg)
</details>

**Comment by Gyputra** [comment]
Iya, pakai AdBlock bawaannya.
Saya custom filter ini : Adguard Base, Tracking, Annoyance, EasyPrivacy (optimized), AdBlockID, 1Host (Lite)

**Comment by realodix** [comment]
Sepertinya tidak compatible Gan dengan AdBlockernya Vivaldi Mobile, atau mungkin kemampuannya dibatasi untuk custom filter (mungkin ?), karena AdGuard juga membatasi kemampuan custom filter.

Di sini (https://github.com/realodix/AdBlockID/commit/a07cbfbe439efb33d14359e90d82cfc5839ad84b dan https://github.com/realodix/AdBlockID/commit/1d62933d570d14d20f09a8b0136fc9ec02cb99cc) Saya coba eksperiment dengan menghilangkan semua gambar, hasilnya gak ada reaksi.

Untuk mobile, Saya sarankan pakai aplikasi AdGuard sih Gan, hasilnya sperti SS yang kasih di atas jadi bersih.
Bisa juga pakai Kiwi Broser atau Firefox agar bisa install ext uBlock Origin.

Kompas sendiri termasuk hebat Gan, dimana Saya perlu syntax khusus yang hanya berlaku di uBlock Origin dan AdGuard.

Terima kasih untuk laporannya Gan, sementara issue ini Saya tutup karena alasan external.
