### ISSUE TITLE
mnfrips.me

### ISSUE THREAD

**Issue by Taufiq-HxH** [realodix/AdBlockID#937]
**Jenis iklan**
- Safelink

**Sample URL**
https://mnfrips.me/movie/99-names-of-love-2019/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Ini link yang http://megaurl.in itu ya?

**Comment by Taufiq-HxH** [comment]
Iya gan

**Comment by realodix** [comment]
Sayangnya gak bisa Gan..

Kemarin dan beberapa menit yg lalu, Saya coba untuk mematikan javascript untuk melihat apakah ada efek atau tidak? Ternyata tidak ada efeknya. 

Singkatnya saat ini scripct pada uBlock dan AdGuard hanya bisa mengakali javascriptnya.

Terima kasih untuk laporannya
