### ISSUE TITLE
kumparan.com [ads leftover]

### ISSUE THREAD

**Issue by What-Zit-Tooya** [realodix/AdBlockID#938]
**Jenis iklan**
Banner leftover

**Sample URL**
`https://kumparan.com/kumparantech/cuma-2-hari-telkomsel-umbar-paket-internet-50-gb-harga-rp-100-000-1w6ab2zr675`

**Penjelasan Lebih Lanjut**
[Screenshot](https://i.imgur.com/XFp36GW.png)

Using uBO default settings + AdBlockID + uBO annoyance + Fanboy annoyance

**Comment by realodix** [comment]
Thank you
