### ISSUE TITLE
kompas.com & kompas.tv

### ISSUE THREAD

**Issue by What-Zit-Tooya** [realodix/AdBlockID#939]
**Jenis iklan**
Banner leftover
Video popup

**Sample URL**
`https://www.kompas.com/sains/read/2021/07/10/160300623/direstui-bpom-kalbe-farma-segera-mulai-uji-klinis-vaksin-gx-19n`

&

`https://www.kompas.tv/article/191487/besok-ada-program-seribu-vaksin-di-gbk-dan-jiexpo-berikut-cara-daftarnya`

**Penjelasan Lebih Lanjut**
Screenshot from FF Desktop:
[Screenshoot 1](https://imgur.com/m7FiPvI)
[Screenshoot 2](https://imgur.com/KwNyM1D)

Screenshot from google discover (using adguard):
[Screenshoot 1](https://imgur.com/6YonQll)
[Screenshoot 2](https://imgur.com/EOJhnEZ)
[Screenshoot 3](https://imgur.com/A5bFwAW)

**Comment by realodix** [comment]
Thank you

**Comment by What-Zit-Tooya** [comment]
@realodix Today, i get ads on site
[screenshoot](https://i.imgur.com/ULBp4hx.jpg)

**Comment by realodix** [comment]
https://github.com/realodix/AdBlockID/commit/1d140b5a15d94e7e5396e351597b74552a49a60c
