### ISSUE TITLE
Block bdubkeg.com

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#94]
![](https://i.imgur.com/p8wzJf1.jpg)

 Block website itu gak jelas asal usulnya

**Comment by realodix** [comment]
Nama aplikasiya apa yang request ke `bdubkeg.com`? Saya bingung ini termasuk ad server, tracking server, atau apa?

**Comment by 3xploiton3** [comment]
![](https://i.imgur.com/ZXHtxC6.jpg) 
![](https://i.imgur.com/AnrbGZz.jpg)

Maksudnya seperti itu?

**Comment by realodix** [comment]
Dari kemarin Saya gak bisa reproduces issue ini, dns gak ketahuan itu request dari aplikasi apa? Takutnya kalau kita block, malah jadi kena yang lain dan nimbulin masalah baru.

**Comment by realodix** [comment]
@Alex-302 Please check this, does `bdubkeg.com` need to be blocked?

**Comment by Alex-302** [comment]
I don't know how this domain is used.
