### ISSUE TITLE
idxx1.cam (kotaksilver.casa) - Warning Install FixPlay/VidPlay Sebelum Download Video

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#95]
https://g.kotaksilver.casa/gsharer/?gsharer=53128-1&gshareruri=https%3A%2F%2Fidxx1.cam%2Ffilm-seri%2Fhormones-2013-14zss1%2Fplaytv%23&gsharertitle=[idxx1.cam]-Hormones-(2013)|1

![](https://i.imgur.com/JMoxubt.jpg)

**Comment by realodix** [comment]
![cats](https://user-images.githubusercontent.com/1314456/70420915-4f3ef300-1a9b-11ea-9b7b-0618699a8a15.jpg)

Saya lihat ini merupakan bagian dari fiturnya, sumber video (berlogo G) yang saat menonton menggunakan FixPlay/VidPlay, downloadnya pun juga sama harus terinstall extension tersebut. 

Lalu Saya ambil sample lagi dari https://idxx1.cam/movie/fast-and-furious-presents-hobbs-and-shaw-2019-88b6
Video yang dapat langsung diputar tanpa FixPlay/VidPlay, pas download tidak memunculkan notif untuk install FixPlay/VidPlay.

Saya gak paham kenapa mereka mengharuskan install FixPlay/VidPlay untuk sumber video tertentu.

Adapun notifnya dihasilkan oleh function `alternateLinks()`. Mungkin ini bisa diakali dengan userscript seperti https://greasyfork.org untuk memanipulasi halamannya lebih dalam.
![cats2](https://user-images.githubusercontent.com/1314456/70420998-7bf30a80-1a9b-11ea-8031-4b7ef3d7556d.jpg)

**Comment by 3xploiton3** [comment]
Web sudah mati
