### ISSUE TITLE
mangaku.cc

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#951]
**Jenis iklan**
- Pop-up

**Sample URL**
https://mangaku.cc/dr-stone-chapter-204/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Di Saya popupnya gak muncul Gan.. Pas lagi klik apa ya?

**Comment by Recehan-Slayer** [comment]
ga langsung muncul agak lama pas klik schroll baca manganya
kasusnya sama seperti ini gnti domain 
https://github.com/realodix/AdBlockID/issues/696

**Comment by realodix** [comment]
Ok dicoba dulu Gan, kira2 manjur gak

**Comment by Recehan-Slayer** [comment]
iya uda ga muncul lg sepertinya

**Comment by realodix** [comment]
Ok Gan, kalau beitu Saya tutup dulu

Thank you

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/125311959-0e394f80-e35e-11eb-8ae5-d524c932725a.png)

pop up muncul mungkin itu yg dimaksud @Recehan-Slayer , saya pakai ekstensi [anti popup adguard](https://popupblocker.adguard.com)

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/125312444-75ef9a80-e35e-11eb-92dd-0b417f2266ba.png)

ads
