### ISSUE TITLE
darts-ads.telkom.co.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#953]
domain ads

darts-ads.telkom.co.id
![image](https://user-images.githubusercontent.com/19517680/125223647-53c23200-e2f6-11eb-9d3a-441874fb4b9a.png)

saya pakai indihome

**Comment by realodix** [comment]
Ini aman Gan di block? Ada contoh urlnya gak yg inject iklan dari darts-ads.telkom.co.id?

**Comment by 3xploiton3** [comment]
itu dari landing page ketika awal masuk wifi.id atau wms venue
sementara saya block tidak merusak website landing page


ini juga perlu di block iklan di landing page wifi.id
lp.wifi.id###skinnerleft
lp.wifi.id###skinnerright
lp.wifi.id###showcasesatu
lp.wifi.id##.col-md-9, .col-sm-12, .col-xs-12, .feed-news, .row

**Comment by realodix** [comment]
> `lp.wifi.id##.col-md-9, .col-sm-12, .col-xs-12, .feed-news, .row`

Yang ini `##.col-md-9, .col-sm-12, .col-xs-12` cukup riskan Gan, karena cukup umum penamaan HTML class attribute-nya. Mungkin bisa dipastekan disini Gan alamat landingnya untuk Saya lihat apa yg bisa bisa diakalin.
