### ISSUE TITLE
VideoLendir (164.68.105.199)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#959]
**Jenis iklan**
- Banner

**Sample URL**
http://164.68.105.199/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Ini banner dimananya Gan?

**Comment by Recehan-Slayer** [comment]
mobile gan

**Comment by realodix** [comment]
Thank you

Ada satu banner yang gak Saya hilangkan `164.68.105.199##[href="https://jali.me/daftar"]` butuh filter spesifik.
