### ISSUE TITLE
shrinkads.com (movienear.me) - Fake Button

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#96]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
http://shrinkads.com/H53ppUYR

**Penjelasan Lebih Lanjut**
FAKE BUTTON

**Comment by realodix** [comment]
Thank you

**Comment by WaferNabati** [comment]
@realodix masih ada fake buttonya dibawah timer
https://www.shrinkads.com/TcO4c

**Comment by realodix** [comment]
Owh di sini kemarin sempat Saya hapus. Kirain sudah usang [`b2fd2c9`#diff-03d0d32](https://github.com/realodix/AdBlockID/commit/b2fd2c90f1d3ff42d56ea57663a543a619565735#diff-03d0d329604da316778711d6c080a1b0L125).

Saya coba kembalikan `movienear.me##img[width="200"][height="60"]`.

**Comment by realodix** [comment]
Sepertinya ini sudah aman, barusan saya cek kembali sudah gak ada fake button. Jangan sungkan untuk comment disini jika muncul kembali.
