### ISSUE TITLE
BokepFb (96.43.139.237)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#960]
**Jenis iklan**
- Banner

**Sample URL**
http://96.43.139.237/video-viral-nurul-diperkosa-rame-rame/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Ini gak ada Banner baru Gan

**Comment by Recehan-Slayer** [comment]
mobile gan

**Comment by realodix** [comment]
Thank you
