### ISSUE TITLE
[NSFW] semprot.com & 93.115.24.210

### ISSUE THREAD

**Issue by What-Zit-Tooya** [realodix/AdBlockID#961]
**Sample URL**
`https://www.semprot.com/threads/toket-temen.1397891/`
need account

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Saya gak ada akun. Bisa tolong di save (complete) gak halamannya, lalu dizip dan upload ke sini

**Comment by realodix** [comment]
Ini sulit, karena Saya gak punya akunnya. Have another page?

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Ini sulit, karena Saya gak punya akunnya. Have another page?

Akun untuk test `https://snippet.host/twtk`
Semua link di situ kalau mau lihat harus pake akun, btw

**Comment by realodix** [comment]
Saya gak menemukan adanya peringatan anti-adblock Gan? Di halaman yang mana ya?

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Saya gak menemukan adanya peringatan anti-adblock Gan? Di halaman yang mana ya?

Sudah fix gan karena baru saja saya update, tadi pagi masih tidak dapat memunculkan thumbnail foto di forumnya.

Btw, apakah tulisan di blok hitam itu bisa dihide juga? 
![1](https://user-images.githubusercontent.com/9832875/131340311-2cd32653-4bf3-4846-8085-3ce94a5e21ab.png)

**Comment by realodix** [comment]
Agan bisa tambahin ini `semprot.com##.semprot_wizard:has-text(adblocker)`.

Karena ini termasuk NSFW, jadi Saya hanya bisa menambahkan filter generic saja, tidak filter specific

**Comment by realodix** [comment]
Kalau gambar masih gak muncul, bisa tambahkan filter di bawah, Ini untuk mencegah jebakan gambar yang dibuat seolah-olah adalah iklan.

`semprot.com#@#img[width="500"][height="70"]`
`semprot.com#@#img[width="550"][height="70"]`
`semprot.com#@#.adVertical`

Sejauh ini, baru itu yang Saya temukan

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Kalau gambar masih gak muncul, bisa tambahkan filter di bawah, Ini untuk mencegah jebakan gambar yang dibuat seolah-olah adalah iklan.
> 
> `semprot.com#@#img[width="500"][height="70"]`
> `semprot.com#@#img[width="550"][height="70"]`
> `semprot.com#@#.adVertical`
> 
> karena semprot punya banyak domain, bisa ditulis seperti ini
> `example1.com,example2.com#@#.adVertical`
> 
> Sejauh ini, baru itu yang Saya temukan

Nah ini maksud saya gan, kadang gambar tidak muncul karena (mungkin) terdeteksi anti-adblock.
Filter di atas bisa dimasukkan ke AdBlockID nggak gan?

**Comment by What-Zit-Tooya** [comment]
Saya apply ini ke UBO filter works gan

`semprot.com,93.115.24.210##.semprot_wizard:has-text(adblocker)
semprot.com,93.115.24.210#@#img[width="500"][height="70"]
semprot.com,93.115.24.210#@#img[width="550"][height="70"]
semprot.com,93.115.24.210#@#.adVertical`

**Comment by realodix** [comment]
Untuk NSFW bisa pakai ini Gan, [AdBlockID+ (Adult)](https://github.com/realodix/AdBlockID-Adult).

Berbeda dengan AdBlockID, saat ini keadaanya membuat AdBlockID+ (Adult) memiliki konsekonsi tambahan (setidaknya hingga ada yang bantu untuk maintain)

1. Tidak dimaintain secara aktif. Artinya Saya hanya menambahkan saja, tapi tidak mengecek apakah filter yang sudah ada masih terpakai atau tidak.
2. Filter akan jadi gemuk dengan banyak sampah filter (filter tidak terpakai).
3. Hanya optimal di uBlock Origin.

**Comment by What-Zit-Tooya** [comment]
> 
> 
> Untuk NSFW bisa pakai ini Gan, [AdBlockID+ (Adult)](https://github.com/realodix/AdBlockID-Adult).
> 
> Berbeda dengan AdBlockID, saat ini keadaanya membuat AdBlockID+ (Adult) memiliki konsekonsi tambahan (setidaknya hingga ada yang bantu untuk maintain)
> 
>     1. Tidak dimaintain secara aktif. Artinya Saya hanya menambahkan saja, tapi tidak mengecek apakah filter yang sudah ada masih terpakai atau tidak.
> 
>     2. Filter akan jadi gemuk dengan banyak sampah filter (filter tidak terpakai).
> 
>     3. Hanya optimal di uBlock Origin.

Udah ku subs gan, tp beberapa filter u/ `semprot` udah usang, perlu diupdate
