### ISSUE TITLE
idws.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#962]
**Jenis iklan**

**Sample URL**
https://idws.id/

**Penjelasan Lebih Lanjut**

![image](https://user-images.githubusercontent.com/19517680/131324549-8953cf75-3598-43aa-8fb4-0a7b24c3c693.png)

**Comment by realodix** [comment]
Saya sudah coba mematikan Ad Blocker, gak ada tanda-tanda ini digunakan untuk menampilkan iklan. Gak bisa Saya blokir, takutnya untuk mereka gunakan untuk selain iklan.
