### ISSUE TITLE
kaskus.co.id

### ISSUE THREAD

**Issue by 3xploiton3** [realodix/AdBlockID#963]
**Sample URL**
https://www.kaskus.co.id/thread/61316f8ea0236313e836d354/yuk-rasakan-bagaimana-windows-11-bekerja-melalui-web-gak-butuh-spek-tinggi-kok/

**Jenis Gangguan**
auto play annoying banget setiap buka tab muncul suara video tv

**Penjelasan Lebih Lanjut**

![image](https://user-images.githubusercontent.com/19517680/132005599-f4a693b4-6a17-41d3-89fe-a909a34bf620.png)

**Comment by realodix** [comment]
Belum bisa Gan..

Untuk video autoplay, normalnya harusnya seperti ini
<details>
  <summary>Screenshot 1</summary>
  
![1](https://user-images.githubusercontent.com/1314456/132031602-db5a3e0b-056b-470b-b744-aff0d1e5108d.png)
</details>

Lalu ketika diklik, bisa diputar
<details>
  <summary>Screenshot 2</summary>
  
![2](https://user-images.githubusercontent.com/1314456/132031695-02644023-548d-446b-be30-39a53104c680.png)
</details>

Tapi yang terjadi di Kaskus, terjadi bug
<details>
  <summary>Screenshot 3</summary>
  
![3](https://user-images.githubusercontent.com/1314456/132031816-869e21ce-ddf3-4bb1-861c-a298504a3461.png)
</details>

Pas diklik pun, tidak bisa diputar

<details>
  <summary>Screenshot 4</summary>
  
![4](https://user-images.githubusercontent.com/1314456/132031908-751c602d-ed2b-4244-9abb-42f18d57a497.png)
</details>

Agan, bisa tambahkan ini (hanya uBlock)
`||tv.kaskus.co.id/api/embed/widget/?autoplayInViewPort=true$frame,redirect=click2load.html,domain=kaskus.co.id`

atau ini
`||tv.kaskus.co.id/api/embed/widget/?autoplayInViewPort=true$domain=kaskus.co.id`

**Comment by 3xploiton3** [comment]
saya pakainya adguard

**Comment by realodix** [comment]
> saya pakainya adguard

Berarti bisa pakai filter yang ke 2 gan, untuk blokir sepenuhnya.
`||tv.kaskus.co.id/api/embed/widget/?autoplayInViewPort=true$subdocument,domain=kaskus.co.id` 

AdBlockID sendiri memang tidak mendukung Annoyance Gan, kecuali Annoyance yang mengandung iklan, salah satunya seperti short url. Kebeneran di uBlock ada fitur Click2Load, jadi Saya masukkan juga beberapa video Annoyance, sisanya Saya masukkan ke filter pribadi.

Alternatifnya Agan bisa
- Langsung lapor ke filter khusus Annoyance yang Agan gunakan([AdGuard Annoyances](https://github.com/AdguardTeam/AdguardFilters/tree/master/AnnoyancesFilter/sections), [Fanboy’s Annoyance](https://github.com/easylist/easylist/tree/master/fanboy-addon))
- Atau lapor ke sini untuk Saya bantu buatkan filternya, lalu Agan tambahkan sendiri ke filter pribadi.

**Comment by 3xploiton3** [comment]
sip makasih penjelasannya

**Comment by realodix** [comment]
Video Kaskus sudah Saya block 😃 

Thank you
