### ISSUE TITLE
mnfrips.me

### ISSUE THREAD

**Issue by Taufiq-HxH** [realodix/AdBlockID#965]
**Jenis iklan**
- Safelink

**Sample URL**
https://mnfrips.me/movie/yowis-ben-2018/

**Penjelasan Lebih Lanjut**
Safelinknya ada 2

**Comment by realodix** [comment]
Sorry Gan, ini gak bisa.

Alsannya sama seperti di [ mnfrips.me #937  (comment)](https://github.com/realodix/AdBlockID/issues/937#issuecomment-877826153)
