### ISSUE TITLE
Samehadaku (194.163.183.129)

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#967]
**Jenis iklan**
- Pop-up

**Sample URL**
https://194.163.183.129/tensei-shitara-slime-datta-ken-season-2-part-2-episode-10/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Saya gak nemuin popup Gan..

Pas lagi klik apa ya?

**Comment by realodix** [comment]
Thank you
