### ISSUE TITLE
gomunime.red

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#974]
**Jenis iklan**
- Pop-up

**Sample URL**
https://gomunime.red/shinigami-bocchan-to-kuro-maid-episode-11-sub-indo/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Ini pop-up pas lagi keadaan apa ya?

**Comment by Recehan-Slayer** [comment]
yang tutup iklan ada detikanya itu bro

**Comment by realodix** [comment]
Thank you
