### ISSUE TITLE
mangaku.club

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#977]
**Jenis iklan**
- Pop-up

**Sample URL**
https://mangaku.club/enen-no-shouboutai-chapter-280/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Ini popup pas sedang apa Gan?

**Comment by realodix** [comment]
**Related**
- mangaku.pro #601 
- mangaku.cc #951 

---

Thank you
