### ISSUE TITLE
huntersekai.website

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#98]
**Jenis iklan** (hapus yang tidak perlu)
- Banner
- Pop-up
- Lainnya

**Sample URL**
https://www.huntersekai.website/

**Penjelasan Lebih Lanjut**
Reff ads + banner

**Comment by realodix** [comment]
Bannernya hanya di halaman depan saja ya?

![cats](https://user-images.githubusercontent.com/1314456/70622705-147dbc00-1c4f-11ea-9e25-102c811604fe.jpg)

**Comment by WaferNabati** [comment]
sepertinya iya

**Comment by realodix** [comment]
Sip, udh Saya tambahin.
Tolong dicek Bro, takutnya masih ada yg muncul.

**Comment by WaferNabati** [comment]
ok fix untuk saat ini

**Comment by realodix** [comment]
Sip, kalau gitu Saya tutup dulu. Thank you untuk laporannya.

**Comment by WaferNabati** [comment]
bannernya muncul lg

**Comment by Recehan-Slayer** [comment]
dibagian bawah

**Comment by realodix** [comment]
Banner ini ya? [2.bp.blogspot.com/-fpL2GTTcEnU/XSnTKxf...CLcBGAs/s1600/leaderboard.jpg](https://2.bp.blogspot.com/-fpL2GTTcEnU/XSnTKxfdH3I/AAAAAAAAAaY/A13MBfZwrwMXtZBHRGZ6hWLkMSk3vzNEgCLcBGAs/s1600/leaderboard.jpg)

Harusnya sih ini gak apa2

**Comment by Recehan-Slayer** [comment]
ada promosi channel youtube diwebnya.

**Comment by realodix** [comment]
> ada promosi channel youtube diwebnya.

Thank you

**Comment by Recehan-Slayer** [comment]
masi ada yg disebelah kanan bawah

**Comment by realodix** [comment]
Mereka pakai iframe, Saya gak bisa hilangin. Bisa pakai `##.widget-content [src^="https://www.youtube.com/embed/"]`, tapi ngeri banget karena terlalu umum

<details>
  <summary>Screenshot</summary>
  
![cats](https://user-images.githubusercontent.com/1314456/76306030-c7b28b80-62f8-11ea-81f3-5c3d33f721ac.jpg)
</details>
