### ISSUE TITLE
sinopsisdrama.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#982]
**Sample URL**
https://cloud.sinopsisdrama.id/?id=d2liM1NsY0VHeUxLdVNsR1pPbVREUE5xak95UFpMZHN3THk0cWdxOFBzU1ZscVNQK0FQbEp1T1QwakRDMnRZOWxzbS9ZVWRSSnhhZiticThYT3Z1WDFjUUZ4dmF4dVFIWnlHanMrTmJOVktvaFNCWXNJaXdFM3Q4Vjhydnc5VkMzUHVOdG01TmovdnF3Y1FJb3hPUGNrcGU1dUwzcjZwc0lUT1VqUDJJbVNSK1Z0WmVhSHlwWjRUdUNFYXZxUlZ2bXhTMFJBNGpPbEdJMFpkamw4L3FlOWZKU0Zoc1Zublc3S1VlNnVVVVhjV0RscVFHMzdyb3o5UXFRdGU0ZlNiRA==

**Penjelasan Lebih Lanjut**
https://drakorfilm.me/drama-korea-hometown-cha-cha-cha-subtitle-indonesia/

**Comment by realodix** [comment]
Thank you
