### ISSUE TITLE
apk.miuiku.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [realodix/AdBlockID#987]
**Jenis iklan**
- overlay

**Sample URL**
https://apk.miuiku.com/dNgG7OWT
https://apk.sekilastekno.com/lkET7m

**Penjelasan Lebih Lanjut**

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot_2021-09-19-09-45-09-695_com kiwibrowser browser](https://user-images.githubusercontent.com/9379770/133913733-0b57e2c1-dc35-4740-914b-b9f34110f0b3.jpg)
</details>

**Comment by realodix** [comment]
Thank you
