### ISSUE TITLE
[Anti-Adblock] files.cx

### ISSUE THREAD

**Issue by WaferNabati** [realodix/AdBlockID#99]
**Sample URL**
https://files.cx/id/krqjh7

**Penjelasan Lebih Lanjut**
AA

**Comment by realodix** [comment]
Thank you Bro, sudah ditambahkan ke database. Butuh sedikit konfirmasi nih, tadi issue ini hampir Saya tandai `invalid`. Gak tau apa yg mereka lakukan, beberapa kali buka https://files.cx/id/krqjh7 dan refresh2, gak terjadi apa2

**Comment by WaferNabati** [comment]
mksudnya gmn ga bisa dibuka gitu sitenya???

**Comment by realodix** [comment]
Maksudnya biasanya kan ada peringatan "Tolong matikan ad blocker Anda" atau peringatan sejenisnya. Nah kemarin pas Saya buka beberapa kali, normal2 aja, gak ada peringatan apa2.

Barusan Saya cek kembali, sepertinya sudah gak ada masalah. Thank you untuk laporannya.
