### ISSUE TITLE
pahe.ph

### ISSUE THREAD

**Issue by Taufik-Rahman** [realodix/AdBlockID#993]
**Jenis iklan**
- Safelink

**Sample URL**
https://pahe.ph/squid-game-season-1-complete-nf-web-dl-480p-720p/

**Penjelasan Lebih Lanjut**

**Comment by realodix** [comment]
Ini belum bisa Gan, barusan Saya bongkar kodenya, sepertinya saat ini teknologi uBlock Origin belum memungkinkan.

Thank you
