### ISSUE TITLE
Ngomik.net

### ISSUE THREAD

**Issue by GrennKren** [realodix/AdBlockID#994]
**Sample URL**
https://ngomik.net

**Jenis Gangguan**
- Popup

**Penjelasan Lebih Lanjut**
Saat halamannya ke load, apapun yg diklik akan ada popup muncul sekali. Dan itu agak mengganggu.. mencoba jenis filter rule apapun mulai dari memblokir url yg bersangkutan, $popup, $script,dll nihil hasilnya..

Tapi berakhir dengan 
`ngomik.net##+js(acis, document.createElement)`
Baru bisa

**Comment by realodix** [comment]
Sip mantap Gan, thank you

**Comment by GrennKren** [comment]
Mantab banget gan!  
Dah gak muncul lagi popup2 misterius..

Thanks!

**Comment by GrennKren** [comment]
**Jenis Gangguan**
- Float Banner

![Untitled](https://user-images.githubusercontent.com/34759917/142977385-6a3eec28-35e4-44ec-ab31-0a22cd93e44e.jpg)

**Comment by realodix** [comment]
Thank you

**Comment by GrennKren** [comment]
Sayang nya masih muncul gan..  menambahin important belakangnya baru bisa
`##.adfoxly-wrapper,important`

Keliatannya salah satu filter default ada yg meng whitelist kan rule nya. Atau memang cara baru iklan membypass adblocker

**Comment by realodix** [comment]
Pakai filter apa aja Gan, biar Saya samain dan check

**Comment by GrennKren** [comment]
Semua filter ku aktifkan untuk Adguard, kecuali yg Region cuman Adblockid sama ABPIndo.

Tapi buat ngetes, aku matikan semua filter nya termasuk User rule .. dan hanya menyisakan Adblockid. Rupanya masih sama saja.

Di Adguard Android soalnya.. lum nyoba di extension Chrome browser kompi

**Comment by realodix** [comment]
Saya ngerti sekarang, dari tadi ngetest pakai semua filter haha

Untuk AdGuard, Agan bisa cek di [AdguardTeam/FiltersRegistry/filters/ThirdParty/filter_120_AdBlockID](https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_120_AdBlockID)
Mereka akan memvalidasi dan konversi secara otomatis, biasanya terjadi sekitar 4 jam sekali setelah mereka melakukan automatic update sebelumnya. 

Jika waktunya ada di bawah dari Saya update, artinya belum masuk. Saat ini harusnya sudah masuk dan Agan bisa force update, karena waktunya sudah di atas setelah Saya update.

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot 2021-11-23 at 20-25-46 FiltersRegistry filters ThirdParty filter_120_AdBlockID at master · AdguardTeam FiltersRe](https://user-images.githubusercontent.com/1314456/143032275-c4890102-690e-4a56-9775-8c0db0c21f1d.png)
</details>

Jika Agan pakai uBlock Origin di browser kompi, Agan bisa langsung force update setelah Saya update.

**Comment by GrennKren** [comment]
Lah iya jir.. bener udah gak muncul lagi banner nya.
Mantab gan..  baru tau juga klo sistem di adguard nya begitu
